### ISSUE TITLE
Alert when the set of people who can access cloud.gov IaaS resources is in an unexpected state

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#10]
In order to minimize the risk of cloud.gov infrastructure being tampered with at the AWS level, only members of the cloud.gov team should be able to access cloud.gov AWS resources.

Acceptance Criteria
- [ ] Only people in the cloud.gov ops team are able to access cloud.gov resources in AWS

(This refers to the fact that other people at 18F outside the team retain some access as we've never detangled cloud.gov from non-cloud.gov. That access needs to be restricted, whether via negative IAM, or totally separate AWS accounts.)

**Comment by suprenant** [comment]
@brittag we're going through the Navigator icebox and thought this seemed like more of a HighBar fit.

**Comment by brittag** [comment]
Ah thanks! Yeah, this is an Atlas/Highbar issue, but it's obsolete now, so I'll close it.
