### ISSUE TITLE
Resolve record-leaking bug in the custom domain broker

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#1000]
Mike said:
> There is an unknown bug in the custom domain service broker. While troubleshooting [#1508](https://cloud-gov.zendesk.com/agent/tickets/1508) I found several stale records with deployed ALBs but no associated deployed services. There's likely a bug here, but I'm not sure what it is without spending an extensive amount of time on this.
> 
> Because the custom domain service broker deploys AWS resources which cost money, we need to ensure that stale resources are cleaned up.
> 
> It also needs extensive overhauling to be updated.

**Comment by bengerman13** [comment]
obsoleted by new broker
