### ISSUE TITLE
Resolve maintainability problem with CDN broker code

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#1001]
The CDN broker code is severely outdated and needs to be updated to the latest versions of Let's Encrypt and Broker API.

Acceptance Criteria
- [ ] WHEN the CDN broker is using the latest interfaces, IT builds and passes the tests correctly.

**Comment by mogul** [comment]
@mxplusb last said in April:
> So the core code base is updated to use the latest and greatest LE libraries, but the Broker API library it's using is v1.0.0, and the current version is v4.2.x, so it drastically needs updating.

**Comment by RonWilliams** [comment]
@mxplusb Is this something the contractors should work on since work has been potentially started on this?

**Comment by mxplusb** [comment]
No, I will finish it up as time permits.

**Comment by karareinsel** [comment]
@mxplusb We want to start work on this and @ChrisMcGowan @soutenniza @spgreenberg are available so they'll get the background work underway.

**Comment by karareinsel** [comment]
closing out - deprecating the old brokers.
