### ISSUE TITLE
[Discussion Item] PostGIS extensions

### ISSUE THREAD

**Issue by eddietejeda** [18F/cg-product#1005]
We don't offer PostGIS and not think we will anytime soon. But I am interested in learning more about how we handle Postgres extensions in general.

**Comment by mogul** [comment]
We could add support for PostGIS pretty easily, we just don't have the bandwidth to take that on right now. See [the discussion yesterday in Slack on this very topic](https://gsa-tts.slack.com/archives/C17Q2LC9W/p1562692226023400). The [page with the directions for adding the PostGIS extension to RDS instances](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.html#Appendix.PostgreSQL.CommonDBATasks.PostGIS) also includes directions for other common extensions. What it comes down to is that we would need to modify our broker (or the AWS Labs broker, after we switch to it), to expose a parameter like `enablePostGIS`, and use that to automate setup of the extension according to the directions immediately after creating the DB instance. The same pattern holds for other extensions.

**Comment by mogul** [comment]
If we have a customer dying for it, this makes a great candidate for a micropurchase.

**Comment by mogul** [comment]
Oh hey, it turns out we don't have to do anything... Customers **are** able to enable PostGIS without any operator intervention or modifications to our existing broker!
https://github.com/18F/cg-site/issues/569

**Comment by eddietejeda** [comment]
perfect!

**Comment by HotHotBig** [comment]
我在pgadmin4中添加postgis扩展失败，错误提示：未在安装目录下找到rtpostgis.dll文件，可是我的目录下是存在这个文件的，请问是什么原因呢，如何解决。我安装的postgresql v11,postgis v2.5.1. Thank you
