### ISSUE TITLE
Test CDN broker end-to-end on a schedule

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#1014]
Currently, we test the CDN broker only when deploying it. We should run end-to-end tests more frequently (weekly?) since it involves two external APIs. This should not be daily or more often, though, so we don't start hitting rate limits on either LetsEncrypt or CloudFront

**Comment by bengerman13** [comment]
I'm closing this, as the broker it talks about will cease to exist soon, but @mxplusb FYI - might be worth considering this when working on the pipeline for the new broker
