### ISSUE TITLE
decouple LetsEncrypt custom-domain broker and cdn broker provisioning

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#1018]
The cdn broker and custom domain broker share a lot of code, but the code is managed separately. The way the brokers are written mashes the AWS interactions and LetsEncrypt interactions into the same functions, objects, and tables. By separating the LetsEncrypt logic from the AWS logic, we can make this more maintainable, and maybe make it easier to bring HTTP-01 challenges back

**Comment by bengerman13** [comment]
obsoleted by new broker
