### ISSUE TITLE
Update incident response exercise template

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#1025]
https://ift.tt/30noTcu

**Comment by alexcsmith23** [comment]
Link to Template: [https://docs.google.com/spreadsheets/d/1zgTRR9NsVix226gQnU0hld7GNrr3IrzsyDJZ1M-DZoQ/edit?usp=drive_web&ouid=108934138382699099578](url)

**Comment by eddietejeda** [comment]
Is that link working? I don’t see anything.

**Comment by alexcsmith23** [comment]
Yes, it loads for me. It's the same link that Bret used, I just put context
next to it. We need to check your access rights.

**Comment by bengerman13** [comment]
clicking the link doesn't work for me, but copy-paste does

**Comment by hillaryj** [comment]
The hyperlink was using link markdown as `[https://docs.google.com/...](url)` so wasn't taking you to the actual link. I've fixed the markdown formatting so the link should work now.

**Comment by alexcsmith23** [comment]
Thanks Hillary!
