### ISSUE TITLE
Propagate secret changes from CredHub to Concourse

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#1036]
As operators, we want secrets that change in CredHub to be propagated to Concourse automatically as-needed. 

#### Acceptance Criteria 

- [ ] WHEN a secret changes in CredHub THEN the secrets in use by Concourse are updated without manual intervention
- [ ] GIVEN I'm an operator and I need to get ahold of a secret WHEN I look at our runbook pages on cg-site THEN I find a documented procedure for extracting secrets

#### Implementation sketch
- [ ] Add a Concourse task that can dip into the related environment to talk to CredHub for the needed properties, export them to a file, and pass the file on to future tasks.

**Comment by hillaryj** [comment]
Part of #945

**Comment by mxplusb** [comment]
This has been superseded by https://github.com/18F/cg-private/issues/95.
