### ISSUE TITLE
Document etcd troubleshooting steps

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#105]
Etcd is required to be up and running for both CloudFoundry and Kubernetes.  Occasionally during upgrades Etcd will lose consensus across the cluster.  In order to restore service in a timely fashion, we should document how to efficiently restore the cluster. 

**Acceptance Criteria:**

As a operations team member, we can refer to documentation which describes:

- [ ] Restore etcd from a specific node with a known good version
- [ ] Join other nodes to the node with known good data
- [x] Initialize entire cluster

**Comment by cnelson** [comment]
To reset an entire cluster to a known good state you can do the following:

Run `monit stop etcd` on all cluster members.

Then run `export DIR=/var/vcap/store/etcd && rm -fr  $DIR && mkdir $DIR && chown vcap:vcap $DIR && chmod 755 $DIR && monit start etcd` on each cluster member (one at a time, in order).

**Comment by mogul** [comment]
So is that all we need, or does this need to be captured somewhere else/account for other scenarios?

**Comment by cnelson** [comment]
That's how to reset etcd to a blank state, if we need to restore data you'd follow the upstream documentation: https://coreos.com/etcd/docs/latest/admin_guide.html#disaster-recovery (which I've verified works in the etcd bosh deployment).  If we want to update our docs somewhere to link to those etcd docs, I'm happy to do so.

**Comment by mogul** [comment]
It sounds like that's all we'd have to do to mark this one complete... Is that right?
