### ISSUE TITLE
can't access page tree for some widths on cloud.gov

### ISSUE THREAD

**Issue by bengerman13** [18F/cg-product#1053]
The page tree sidebar disappears at a different width than the page tree menu appears, so there are widths at which users cannot access the page tree![out.gif](https://images.zenhubusercontent.com/5d23723654489141ee75f9ef/b70a453c-4edc-442c-94ba-7149af4d45ef)

**Comment by karareinsel** [comment]
This issue will be handled through a staffing micro-request with 18F. Keeping the issue open so that the 18F engineer can refer to it. Staffing issue https://github.com/18F/staffing/issues/668

**Comment by karareinsel** [comment]
Closing for now until an 18F front end dev is available to work on this as a micro-request.
