### ISSUE TITLE
Team consensus on a confident direction for deploy methodology

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#1057]
In order to improve reliability of deployment processes and security of deployment processes (including by reducing confusion among the team) when deploying software, we want to have strong team consensus on a confident direction for deploy methodology. 

This ideally gets us in better alignment with industry standards and enables us to work more efficiently with our future contractors.

Implementation sketch:
- [ ] Design document with a proposal for standardizing on deploy methodology [~3 hours]
- [ ] Discussion with team to come to consensus on a direction forward
- [ ] Determination of next steps to put that into practice (might be documentation updates, or other work)

Acceptance criteria:
- [ ] The team agrees on a pipeline design pattern

**Comment by RonWilliams** [comment]
Pipeline consensus presentation material is now available at https://drive.google.com/drive/folders/1LgI6Yo82GEIjo06Uef_jRYeU269FhcKR.

**Comment by mxplusb** [comment]
I'll get time on the calendar for this later this week.

**Comment by karareinsel** [comment]
Each pipeline should be addressed individually. Closing this so it can be captured as separate issues for each pipeline.
