### ISSUE TITLE
Raise alerts on RDS CPU contention 

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#106]
* [x] Send RDS CloudWatch metrics to Riemann
* [x] Alert to PagerDuty on CPU spikes

**Comment by jmcarp** [comment]
Options:
* https://github.com/riemann/riemann-tools/blob/master/tools/riemann-aws/bin/riemann-aws-rds-status
* CloudWatch alert -> SNS -> PagerDuty

**Comment by jmcarp** [comment]
<img width="924" alt="screen shot 2016-07-21 at 6 58 11 pm" src="https://cloud.githubusercontent.com/assets/1633460/17061509/d9c6d65e-4ffc-11e6-8143-568611f1f7b2.png">
<img width="1257" alt="screen shot 2016-07-21 at 6 57 50 pm" src="https://cloud.githubusercontent.com/assets/1633460/17061516/e044fdee-4ffc-11e6-9b2e-ccca5756a0d1.png">

**Comment by sharms** [comment]
Verified
