### ISSUE TITLE
Add cf-cli to GEARS

### ISSUE THREAD

**Issue by mxplusb** [18F/cg-product#1063]
## Requirements

In order to let GSA users install the CF CLI properly, the CF CLI must be added to GEARS.

## Acceptance Criteria

*GIVEN* a GSA employee wants to install the CF CLI on their machine,
*WHEN* they look in the GEARS list of approved software,
*THEN* the CF CLI appears.
*ALSO* CF CLI is in Service Catalog Software Request Ticket.

**Comment by Bryanthales** [comment]
Technology Request Form Submitted. This is your Request Tracker (RT) ticket number: 2019-92785
https://gsa.my.salesforce.com/a1Zt0000000AxOMEA0

**Comment by Bryanthales** [comment]
Security Review is approved. 508 Review is approved. Legal and TSC Reviews are still outstanding.

![image](https://user-images.githubusercontent.com/42779803/64191434-5798e980-ce2d-11e9-9ff7-f7ffc72cc829.png)

**Comment by Bryanthales** [comment]
TSC = "it's just the final step of the software request process. It gets reviewed by the CTO / Leadership team for approval" - Brian Kim on CTO's team.

**Comment by Bryanthales** [comment]
Update (but not really): Hi Bryant! Apologies for the delay haha there's just been some internal changes to our process so there's just been a delay on all ticket reviews. But you should hear back soon (latest by monday) about the final status (9/11)

**Comment by karareinsel** [comment]
Ready to close out- but confirm with @Bryanthales that all is set with this issue.

**Comment by Bryanthales** [comment]
@karareinsel Yes, lets close it! It is now in GEAR so any GSA user can get it installed on their machine. Based on the challenges with maintaining the most recent version in ServiceNow, I am cancelling the ticket to get it added to the service catalog -- so users will just have to make a generic request instead of selecting it from a dropdown.

**Comment by mxplusb** [comment]
Reopening because the cf cli does not appear in the list of software which can be installed in service now, so this is not done yet.
