### ISSUE TITLE
Pipelines need refactoring to use `in_parallel` instead of `aggregate`

### ISSUE THREAD

**Issue by mxplusb** [18F/cg-product#1064]
## Requirements

In order to continue having our pipelines be current and supported, the `aggregate` keyword must be replaced with the `in_parallel` keyword.

## Acceptance Criteria

*GIVEN* an operator runs `fly get-pipeline -p <pipeline>`
*WHEN* they search for the `aggregate` key
*THEN* no results are YAML keys.

**Comment by hillaryj** [comment]
I'm using this sheet to track the work 🔒[Pipeline refactoring aggregate -> in_parallel](https://docs.google.com/spreadsheets/d/1XKfVlck0Hb6dEdq700NtfHwznFphs6sUumIVwOFGx7Q/edit?usp=sharing).

**Comment by mxplusb** [comment]
@ChrisMcGowan here is the core issue of what I suggested would be good to work on as a starter task while you don't have your hardware. Definitely coordinate with @hillaryj on the best way to go about it. :)

**Comment by karareinsel** [comment]
Now that @ChrisMcGowan @spgreenberg have their laptops, should this issue be wrapped up so that other stories that were waiting on HW can be tackled? @hillaryj @mxplusb
