### ISSUE TITLE
Onboard Steve Greenberg

### ISSUE THREAD

**Issue by eddietejeda** [18F/cg-product#1065]
## Getting to know cloud.gov

* [x] Bookmark the [pertinent links listed here](https://github.com/18F/cg-product/blob/master/PertinentLinks.md).
* [x] Read our [service disruption guide](https://cloud.gov/docs/ops/service-disruption-guide/) to learn how we handle customer-facing service disruptions.
* [x] Join [the cloud.gov team Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov) so you can participate in team-wide internal communication.
* [x] Make sure they're in [the list of people working on the project](https://docs.google.com/spreadsheets/d/1mW3tphZ98ExmMxLHPogSpTq8DzYr5Oh8_SHnOTvjRWM/edit#gid=0).
* [x] Add them to the `@cg-team` [in Slack’s Team Directory](https://get.slack.help/hc/en-us/articles/212906697-User-Groups#edit-a-user-group).
* [x] Add them to the recurring cloud.gov meetings that are relevant for them in [the team calendar](https://calendar.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks@group.calendar.google.com&amp;ctz=America/Los_Angeles).

## Required items for all team members

These items help us fulfill security and compliance requirements (including for FedRAMP).
* [x] Complete [GSA OLU](https://gsaolu.gsa.gov/) GSA Mandatory Cyber Security and Privacy Training, including accepting the GSA IT Rules of Behavior, which is required before we can give you access to any cloud.gov systems. If you joined GSA more than two months ago, you've already completed this task and can just check the box.
* [x] Add their name, whether they're Cloud Ops (Platform), and the date they joined the team to the [training tracker](https://docs.google.com/spreadsheets/d/1hqU6cNeEB293OT0j3OvbdAFRkrf2zDOrPVxGfnr4sSw/edit#gid=0). Copy the formulas for the due dates from an existing row (grab the "corner" of the cells and pull down).
* [x] As they complete training, fill out their completion dates in the [training tracker](https://docs.google.com/spreadsheets/d/1hqU6cNeEB293OT0j3OvbdAFRkrf2zDOrPVxGfnr4sSw/edit#gid=0).

## Platform-specific required items

The person must complete OLU security training before being added to privileged access on any system.

* [x] Ask the System Owner to have them added to the [@18F/cloud-gov-ops](https://github.com/orgs/18F/teams/cloud-gov-ops) team on GitHub. *(For contractors: Confirm they have cleared GSA security review before doing this one!)*
* [x] If the new person is a contractor, ask the System Owner (Eddie) to have them added to the [@18F/cloud-gov-partners](https://github.com/orgs/18F/teams/cloud-gov-partners) team on GitHub.
* [x] Add them to @cg-operators [in Slack’s User Groups](https://get.slack.help/hc/en-us/articles/212906697-User-Groups#edit-a-user-group).
### Grant them access to the following:
* [x] [AWS Accounts](https://cloud.gov/docs/ops/aws-onboarding/) via the AWS web console (not Terraform) and provide one-time credentials.
* [x] AWS GovCloud
* [x] AWS East tied to GovCloud

Note: AWS user names should be identical across accounts so that permissions can be correctly managed by terraform

* [ ] Nessus Manager GUI
* [x] Opsgenie
* [ ] StatusPage
* [x] Make sure that PagerDuty will alert you through at least one of these ways:
* [x] [Make them an admin](https://cloud.gov/docs/ops/managing-users/#managing-admins) of the platform.
* [x] Add them to the *cloud-gov-operators* organization in cloud.gov.

### Platform-specific items

* [x] Review the System Security Plan (the latest version lives on [Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0); look for "cloud.gov System Security Plan (SSP)" as a *.docx* file). Of particular note for onboarding: Section 9 (System Description) and Section 10 (System Environment)
* [x] Join the *#cg-platform* channel on Slack.
* [x] Join the *#cg-support* channel on Slack.
* [x] Join the *#cg-services* channel on Slack.
* [x] Join the *#cg-compliance* channel on Slack.
* [x] Join the *#cg-program* channel on Slack.

###  Get familiar with our AWS setup
* [x] Read about [AWS onboarding](https://cloud.gov/docs/ops/aws-onboarding/)
* [x] Read about the [AWS CLI](https://aws.amazon.com/cli/)
* [x] Review the [daily maintenance tasks](https://cloud.gov/docs/ops/maintenance-list/) for when you're on support duty

### Learn our policies and procedures:

* [x] Coordinate with your onboarding buddy to go through [Incident Response Training](https://docs.google.com/presentation/d/1AZjQE8zBzMRWZIFUuJPkJLted1ykGtALrLPoPRx5Vls/edit#slide=id.p) within 60 days of joining the team (and annually after that). This will cover the following document, which you should also review before or after training:
* [x] Read the [Incident Response Guide](https://cloud.gov/docs/ops/security-ir/).
* [x] Coordinate with your onboarding buddy to go through [nonpublic information training](https://docs.google.com/presentation/d/1uB4MlGCu8ZYUxjKVZKwicQ95MvLxaT4Mh93y6w79GPw/edit#slide=id.p) within 60 days of joining the team (and annually after that). This will cover the following documents, which you should also review before or after training:
* [x] Review the [18F open source policy guidance about protecting sensitive information](https://github.com/18F/open-source-policy/blob/master/practice.md#protecting-sensitive-information).
  * [x] Read our [sharing secret keys](https://cloud.gov/docs/ops/secrets/#sharing-secret-keys) policy.
  * [x] Review the [18F requirements for password management](https://handbook.18f.gov/password-requirements/).
* [x] If you're Cloud Ops or Business Unit: Coordinate with your onboarding buddy to go through Contingency Planning training within 10 days (and annually after that). This will cover the following document, which you should also review before or after training:
* [x] Read the [Contingency Plan](https://docs.cloud.gov/ops/contingency-plan/).

Read the following documents as well, which explain our practices in a formal written way. Reach out to your buddy or the team if anything is unexpected or confusing.
* [x] Read the [Continuous Monitoring Strategy](https://cloud.gov/docs/ops/continuous-monitoring/), particularly the [cloud.gov team responsibilities](https://cloud.gov/docs/ops/continuous-monitoring/#cloud-gov-team).
* [x] Read the [Configuration Management Plan](https://cloud.gov/docs/ops/configuration-management/).
* [x] Read the [18F Security Policies and Procedures](https://github.com/18F/compliance-docs). These documents explain the high-level policies and procedures we must comply with while running cloud.gov, sorted into security control "families" They explain that we follow GSA IT security policy, and they provide a summary of the procedures in our System Security Plan.

### Services-specific items

* [x] Join the *#cg-services* channel on Slack.
* [x] Take a look at [our existing brokers](https://github.com/18F?utf8=%E2%9C%93&amp;query=broker).
* [x] Check out our [staging](https://ci.fr-stage.cloud.gov/) and [production](https://ci.fr.cloud.gov) Concourse instances, and take a look at some of [our pipelines](https://github.com/search?q=org%3A18F+cg-deploy).

## Ensure you know what's happening on the team:
* [x] Subscribe to [the cloud.gov team calendar](https://calendar.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks@group.calendar.google.com&amp;ctz=America/Los_Angeles) (click the + in the bottom right) so you know when assorted team meetings are happening in the various squads. Tip: When you plan Out of Office time, make a calendar event for that on the cloud.gov calendar so that your teammates know you'll be away.
* [x] Subscribe (through the GitHub watch function) to the [cg-site](https://github.com/18F/cg-site) GitHub repository notifications.
* [x] Ask Program Manager or Director for access to the cg-supportstream Slack channel.

## Install a development environment for cloud.gov

- [x] Install `brew`
  - If this is a new GSA-provided laptop, it likely does not come with `brew` installed. Install `brew` and other tools via the 18F platform scripts from the [18F laptop repo](https://github.com/18F/laptop) (or manually if you have strong preferences about the laptop script)
  - `bash <(curl -s https://raw.githubusercontent.com/18F/laptop/master/laptop)`
- [x] Install [CloudFoundry for mac per their docs](https://docs.cloudfoundry.org/cf-cli/install-go-cli.html#pkg-mac):
  - `brew tap cloudfoundry/tap`
  - `brew install cf-cli`
  - `brew install cloudfoundry/tap/bosh-cli`
  - `brew install openssl`
- [x] Verify CloudFoundry Installation via the CLI (once an existing cloud.gov teammate has [made your cloud.gov admin account](https://cloud.gov/docs/ops/managing-users/#creating-admins))
  - `cf login -a api.fr.cloud.gov --sso`
  - `cf orgs`
    - As a cloud.gov team member, you should have a very giant list of organizations
    - If you have none or one (e.g. sandbox) org, contact your facilitator
- [x] Install the [Bosh CLI using their instructions for MacOS](https://bosh.io/docs/cli-v2-install/#using-homebrew-on-macos)
  - `brew install cloudfoundry/tap/bosh-cli`
  - [x] Verify the installation using
    - `bosh -v`
- [x] Install Terraform and other tools per [cg-provision](https://github.com/18F/cg-provision)
  - `brew install terraform`
  - `brew install awscli`
  - `brew install jq`
  - [x] Verify Terraform installed and is in your path
    - Run `terraform` and helper text should display
  - [x] Verify AWS CLI installed and is in your path
    - Run `aws` and helper text should display
- [x] Install the Concourse `fly` CLI
  - Download the `fly` binary zip for MacOS from https://concourse-ci.org/
  - Extract the binary and move it to `/usr/local/bin/fly` so it's in your path
    - `cd ~/Downloads`
    - `mv fly /usr/local/bin/fly`
  - [x] Verify using `fly -h`
- [x] Install cloud.gov dev tools by cloning the [`cg-scripts` repo](https://github.com/18F/cg-scripts/)
  - `git clone https://github.com/18F/cg-scripts.git`

**Comment by spgreenberg** [comment]
The Incident Response Guide references a slack channel not in the above list of slack adds: #incident-response. The channel name does not seem to follow the naming convention. Is this a channel that should be added to the list above?

**Comment by bengerman13** [comment]
#incident-response is not a channel we normally want to monitor - it's a channel that all of 18F uses for incident response, so I think it should be left off of list of adds.
#cloud-gov probably _should_ be on the list of channels.

**Comment by spgreenberg** [comment]
@bengerman13 as a contractor, I can't add myself to channels. So if I don't need to ever be in #incident-response then it would be fine to leave off. But if I might need access perhaps I should be added but then mute notifications. What do you think?

**Comment by mxplusb** [comment]
@spgreenberg don't forget to set up MFA.

**Comment by mxplusb** [comment]
@eddietejeda or @RonWilliams I cannot add @spgreenberg to the Statuspage board because there are not enough seats.

**Comment by mxplusb** [comment]
> Add them to @cg-operators

Don't have permissions. @RonWilliams can you track this down?

> Add them to the @cg-team

Don't have permissions. @RonWilliams can you track this down?

> Nessus Manager GUI

Skipping for now as they don't need Nessus access.

> StatusPage

Not enough seats. @RonWilliams can you please follow up on this?

> Make sure that PagerDuty will alert you through at least one of these ways

Not using pagerduty anymore.

> Review the System Security Plan

@spgreenberg to finish.

> Coordinate with your onboarding buddy to go through Incident Response Training within 60 days of joining the team (and annually after that). 

Will wait for more contractors and do several at once.
