### ISSUE TITLE
Update Docker away from 1.12

### ISSUE THREAD

**Issue by hillaryj** [18F/cg-product#1069]
# What we're after

Upgrade away from Docker 1.12 to latest quarterly release (2019 Q3 or later).

## Hypothesized benefit(s)
* Increase stability of k8s cluster
* More compliant 
* Fewer security problems

## Potential metrics
* Current version

### Notes for implementers

- Relates to #976 
- When Docker changed from numeric versions to time-based versioning, they also changed the way that packages get delivered so this may be difficult and require a manual compilation
  - If manual compilation is required, more discussion should happen before doing so

**Comment by karareinsel** [comment]
I'll coordinate with @hillaryj to discuss further and prioritize.

**Comment by bengerman13** [comment]
this is a sub-task of #976. I think if we're calling that dead, we should do the same here

**Comment by karareinsel** [comment]
Let's find a few minutes to discuss.

**Comment by karareinsel** [comment]
Closing this issue based on intent to replace with broker elasticsearch and redis services. May re-open if required by FedRAMP.
