### ISSUE TITLE
Raise alerts on Concourse worker failures

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#107]

**Comment by s-matyukevich** [comment]
@sharms  can you, please, provide more details how you are going to achieve this?

From what I was able to figure out we can:
1. Setup some job, that will be responsible for forwarding all concourse logs  to influxdb, and then  write a config file for Riemann that will raise an alert, in case if it will see a record, saying that some job fails.
2. Do concourse log filtering on concourse VM and use riemannc to send alert in case of job failure.
3. modify each concourse pipeline and add on_fail step that will sent alert to riemann.

Neither of this seems a good solution to me.
