### ISSUE TITLE
Clean up quotas from smoke tests during testing

### ISSUE THREAD

**Issue by hillaryj** [18F/cg-product#1070]
# What we're after

Smoke tests need to clean up cf quotas that they create during testing.

## Hypothesized benefit(s)/
* Unused quotas will not languish
* The `cf quotas` command will take <30 seconds to run
* Tidier and less confusing

### Acceptance Criteria

- [ ] Determine if this is still a bug or if there’s just leftover detritus from a fixed bug
- [ ] Clean up obsolete quotas from smoke tests

**Comment by karareinsel** [comment]
Low priority, minor annoyance/nuisance.
