### ISSUE TITLE
Overhaul k8s deployment manifest generation process

### ISSUE THREAD

**Issue by bengerman13** [18F/cg-product#1072]
# What we're after
Clearer deployment manifest generation

## Hypothesized benefit(s)/why:**
* easier to understand
* less error-prone to modify
* more aligned with current processes = easier to get assistance from community

## Potential metrics
* not using spruce anymore (use ops files)
* instance types are defined in only one place
* adding new instances doesn't require manually messing with static IPs

**Comment by karareinsel** [comment]
As long as we keep moving towards removing k8s then this story will no longer be needed. If we can't get rid of k8s, then we will need to revisit this.
