### ISSUE TITLE
Research: Improve k8s cluster balancing

### ISSUE THREAD

**Issue by hillaryj** [18F/cg-product#1073]
# What we're after

Research options for rescheduling to load-balance the cluster. Two possibilities are to use a descheduler or chaos engineering to more-proactively load-balance the cluster.

## Hypothesized benefit(s)
* Improve stability of k8s cluster
* Customer loads become true-HA (high availability)
* Use cloud.gov resources more effectively

## Potential metrics
* [ ] Path forward for active load-balancing on k8s cluster is determined

---
### Further context for those unfamiliar with what we're doing

Our loads are extra-susceptible to scheduling issues because they don't recycle often.

Current approach means that the last minion will have no pods scheduled to it, which means we'd be paying for a bunch of unused CPU as well as having less overhead on other minions.

### Security considerations

- [note any potential changes to security boundaries, practices, documentation, risk]

### Notes for implementers

- There is a descheduler as part of the k8s community project which may get integrated - if so, this task becomes obsolete with a k8s update
- Implementation will be blocked by #1068

**Comment by karareinsel** [comment]
Closing out this issue - if we end up not being able to replace K8s then we will re-evaluate the plan.
