### ISSUE TITLE
Improve customer communication during incidents

### ISSUE THREAD

**Issue by hillaryj** [18F/cg-product#1074]
# What we're after

Standardize and document how we communicate with customers during incidents and outages.

**Goal:** Provide degradation information to customers more proactively via StatusPage

- [x] Create a template for note-taking during incidents similar to the k8s upgrade outage
- [ ] Update cloud.gov docs (e.g. [ops support](https://cloud.gov/docs/ops/maintenance-list/)) on when to declare an incident
- [x] Update cloud.gov operator/developer docs to recommend a StatusPage/customer update frequency during incidents (e.g. 2 hours)

**Comment by karareinsel** [comment]
Issue needs further fleshing out first before an estimate can be provided. @hillaryj will refine.

**Comment by hillaryj** [comment]
I updated this issue and created a template for a maintenance or ops event in the Templates folder in the cloud.gov drive: https://docs.google.com/document/d/1ip0Ey3R7USsTLLWvnlLg8YMUUznVrtJSIQ24UEIZPFA/edit#heading=h.o8p2msgaqnv5

**Comment by karareinsel** [comment]
Closing out. When to declare an incident will be addressed by TTS' guidance updates.
