### ISSUE TITLE
Verify AWS Quota bot is checking correct services

### ISSUE THREAD

**Issue by hillaryj** [18F/cg-product#1075]
# What we're after

Verify that everything quota bot is using is correct - currently tracks static IPs, databases, etc - and we want to make sure it represents everything we're using.

## Hypothesized benefit(s)/why:**
* By having regular postings, we're ensuring we have a head's up on where we are with capacity.

## Potential metrics
* Instance types
* IPs
* S3 Buckets
* Databases

### Notes

- Would be cool if it checked quota on everything we're using at least one of
- We ran into an issue when trying to provision a new instance type during the k8s troubleshooting in August 2019

**Comment by karareinsel** [comment]
The value of this will be seen once the Slack webhooks are in place.

**Comment by mxplusb** [comment]
Still waiting on webhooks to get the base functionality working again, but the script itself should work, I can look into it.
