### ISSUE TITLE
Put in an automated test for TLS for RDS from Java

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#1079]
In order to make sure that TLS works in RDS as we expect it for apps using the Java buildpack, we need to have a routine process of automated testing for it.

Acceptance Criteria:

- [ ] We have a test within our system that successfully connects via TLS to RDS instances, and that test runs automatically

**Comment by bengerman13** [comment]
waiting on 18F/cg-laboratory#1

**Comment by karareinsel** [comment]
Test has been written but integration has not. De-prioritize out of the current sprint.
