### ISSUE TITLE
CDN broker gets hopelessly stuck if minor issues occur

### ISSUE THREAD

**Issue by bengerman13** [18F/cg-product#1083]
If the CDN broker gets a certificate, but then fails to update the cloudfront distribution, it continues trying to get a certificate.
This means that after 4 more tries, it gets rate-limited by Lets Encrypt, and the user can't fix the problem for a week. 

Given the CDN broker has gotten a certificate from Lets Encrypt for a domain
when it fails to update the cloudfront distribution
then it should stop attempting to get new certificates

**Comment by karareinsel** [comment]
Address within the next 1-3 sprints.

**Comment by karareinsel** [comment]
Van is working on #1001 which takes care of this issue so we can close this issue out.
