### ISSUE TITLE
Resolve DMARC/DKIM issues with ZenDesk setup

### ISSUE THREAD

**Issue by hillaryj** [18F/cg-product#1084]
# What we're after

Ability to send emails via ZenDesk re-enabled without causing DMARC/DKIM issues (as experienced by the EPA, especially).

## Hypothesized benefit(s)/why:
* Simplifies support/inquiry process
* Allows emails to be received by customers

## Acceptance Criteria
- [ ] EPA successfully receives email through ZenDesk without DMARC warnings
- [ ] DMARC/DKIM settings are set in accordance for ZenDesk

---
### Further context for those unfamiliar with what we're doing

There's some history with this in the 🔒 [Support Processes doc](https://docs.google.com/drawings/d/1x12SuZsyqhRutuhRpl8CN3jmIQ0bPy_IMJxsft55hZw/edit).

EPA customers sometimes receive emails with “[WARNING: DMARC validation failed]” in the subject of the email.

GSA Service Desk INC2781800 - Email failures for Cloud.gov Emails

### Security considerations
- Some question re: whether we can make the necessary changes with the current cloud-gov-support@gsa.gov email address or if we'll need to move to a @cloud.gov address
  - Will discuss with GSA IT

**Comment by hillaryj** [comment]
> If the messages are being generated and sent by a system outside of GSA's network, they cannot use @gsa.gov in the from field because of anti-spoofing protections we have in place. We have had a couple of groups use a subdomain, like @zendesk.gsa.gov , but if you can change the address to @cloud.gov that would probably be the path of least resistance, as there's a bunch of additional setup for rolling out a new subdomain.

Sounds like moving to support@cloud.gov would be our path of least resistance, and we can set the google group to autoforward from the Support group to that new address.

Tasks for this would be:

- Work with GSA IT to get CNAME records set for the cloud.gov domain
- Set up ZenDesk with new support address
- Verify with customers (EPA) that they receive new emails from ZenDesk
- Update documentation to use new cloud.gov support address
- Set Support google group to autoforward to cloud.gov support address
- Disable emails from Support google group (or possibly remove individuals)

**Comment by karareinsel** [comment]
@eddietejeda and @hillaryj is this story still a priority for this sprint (sprint 19.10.30)? Is this addressing a client request? Just trying to figure out if this story is high enough priority that it should be wrapped up this sprint or de-prioritized and addressed in a future sprint?
