### ISSUE TITLE
Plan for Federalist S3 bucket requests and AWS 1000 S3 bucket hard limit

### ISSUE THREAD

**Issue by hillaryj** [18F/cg-product#1086]
In order to support our Federalist partners, we want to determine a path for how to accommodate their bucket creation request while staying within the 1000 bucket hard limit from AWS.

## Acceptance Criteria
* [ ] GIVEN that Federalist wants to create hundreds of S3 buckets \
  AND AWS has a hard limit of 1000 S3 buckets per AWS account \
  AND cloud.gov has ~430 buckets provisioned \
  WHEN Federalist goes to create its buckets \
  THEN cloud.gov AWS account preserves future space for additional buckets

--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch
From 🔓 [Slack](https://gsa-tts.slack.com/archives/GAZ7T1BNV/p1568307135009800):
>We might have a slight problem soon with our s3-broker. [Federalist] wants to create ~490 buckets, and we already have ~430 buckets provisioned for cloud.gov. There is a hard limit of 1000 s3 buckets per AWS account, so if we create all those buckets, we'll be very close to the account limit with no way to increase.
>We can get around this by leveraging our other AWS accounts, but that would mean deploying a new broker and giving it separate credentials.

Per AWS support:
> The limit has been set to 1000, which is the maximum amount of buckets per account. This is a hard limit and can't be increased further.

* [ ] Determine technical path for accommodating 1000+ S3 buckets, e.g. a new broker and separate credentials for Federalist buckets

**Comment by hillaryj** [comment]
Current plan is to ask infrastructure for a new AWS account specific to federalist, and then deploy an s3-broker dedicated to that account, only for use for them.

**Comment by mxplusb** [comment]
Touched base with @afeld and @melanienleopold about this yesterday, waiting on provisioning to be filed.

**Comment by mxplusb** [comment]
Issue moved to [18F/cg-private #92](https://github.com/18F/cg-private/issues/92) via [**ZenHub**](https://www.zenhub.com/)
