### ISSUE TITLE
Pipeline tasks should declare parameters

### ISSUE THREAD

**Issue by spgreenberg** [18F/cg-product#1088]
## Requirements

Concourse pipeline tasks should declare required parameters using the `params:` key. 

## Why?

Concourse will thereby ensure the required parameters are set as parameters (environment variables) in the pipeline.yml. This check occurs during job/task execution before attempting to run the task script. 

## Example

An example of where this is not happening is here: 
- task config: https://github.com/18F/cg-bosh-dependencies/blob/master/ci/create-issue.yml
- task script: https://github.com/18F/cg-bosh-dependencies/blob/master/ci/create-issue.sh

## Acceptance

Task config files will list all environment variables used in the task script(s).

Scope: [repos listed in this spreadsheet](https://docs.google.com/spreadsheets/d/1XKfVlck0Hb6dEdq700NtfHwznFphs6sUumIVwOFGx7Q/edit#gid=0). (As part of this work, update the spreadsheet.)

Note: To check this for accepting, review the spreadsheet!

**Comment by karareinsel** [comment]
This is a nice to have for now.
