### ISSUE TITLE
Deal with outdated insecure Docker containers

### ISSUE THREAD

**Issue by karareinsel** [18F/cg-product#1094]
@mogul commented on [Wed Jul 10 2019](https://github.com/18F/cg-private/issues/18)

In order to fulfill our obligations to the open source community, we need to make sure we're not distributing insecure Docker containers.

## Acceptance Criteria
- [x] 18fgsa/bosh-deployment-resource
- [x] 18fgsa/cg-common-resource
- [x] 18fgsa/s3-resource
- [ ] 18fgsa/s3-resource-simple [our team is not actively using this one]
- [ ] `18fgsa/docker-elasticsearch-kubernetes-auth` no longer appears in the list
- [ ] We have a second card representing implementation of a longer-term plan for maintaining these container (or passing them off to others)
---
This is brought up by https://vulnerablecontainers.org - they probably do a daily refresh.

We are probably just on the list because Concourse polls frequently, which Docker Hub counts as a "download".

**Comment by ChrisMcGowan** [comment]
Per Jerry Gamblin - for 18fgsa/s3-resource - a score of `0` and a report status of `null` the scan was clean/no issues found

**Comment by ChrisMcGowan** [comment]
Created PR for s3-resource simple: https://github.com/18F/s3-resource-simple/pull/29

**Comment by ChrisMcGowan** [comment]
`latest` pushed to dockerhub with CVE fix: https://hub.docker.com/r/18fgsa/s3-resource-simple/tags

**Comment by ChrisMcGowan** [comment]
18fgsa/docker-elasticsearch-kubernetes-auth is in testing with @jontours at the moment.

**Comment by ChrisMcGowan** [comment]
As of 10/3/19 the s3-resource-simple image is now clean - https://vulnerablecontainers.org/reports/18fgsas3-resource-simple.json

**Comment by ChrisMcGowan** [comment]
As of 10/8 s3-resource-simple is back on the list with new CVEs - looking at fix

**Comment by ChrisMcGowan** [comment]
10/9 update - s3-resource-simple is back to being clean - contacted the website admin - there was an issue with the scan tool DB and yesterday's report was false positive.

**Comment by karareinsel** [comment]
@ChrisMcGowan is this being actively worked on? Or has it slowed down/is blocked?

**Comment by ChrisMcGowan** [comment]
18fgsa/docker-elasticsearch-kubernetes-auth is still in testing.  Need to test in k8s staging to make sure fixes don't effect ES operations.  Task is being back logged for now to make way for other higher priority issues.  The test image is located at cmcgowan279/docker-elasticsearch-kubernetes-auth:2.4.1-8u222-edge

**Comment by spgreenberg** [comment]
I recommend we re-scope this to refactor how docker images are being built. Pipelines can monitor base images and installed resources and update themselves.

**Comment by karareinsel** [comment]
Once testing is complete, let's re-evaluate and possibly re-scope.
