### ISSUE TITLE
[3d] Research how to schedule recurring tasks

### ISSUE THREAD

**Issue by sushiandbeer** [18F/cg-product#110]
As an SRE, I need to research how end-users can schedule recurring tasks

**Comment by jmcarp** [comment]
Same as https://github.com/18F/cg-docs/issues/234. Looks like we already have https://github.com/18F/cg-cron and https://github.com/18F/cf-go-cron, as well as a bunch of examples from the 18F dev team.

**Comment by sushiandbeer** [comment]
It appears we have a solution in with cg-cron and cf-go-cron and are closing this in favor of #154
