### ISSUE TITLE
As a cloud.gov stakeholder, I want a document specifying the organization suspension rules and timeline

### ISSUE THREAD

**Issue by spgreenberg** [18F/cg-product#1103]
Proposed levels of suspension:

1. Read only mode (all users are reassigned to an auditor role). Apps will continue to run
2. App shutdown: All apps will be shutdown. No data will be lost (routes, service instances, etc are unaffected).
3. Org removal. All apps, routes, service instances and associated data are destroyed. This is irrecoverable.

## Acceptance Criteria

- [ ] A public document outlining the suspension process and timelines

**Comment by karareinsel** [comment]
Government shutdowns are outside the scope of this issue.

**Comment by karareinsel** [comment]
Closing out because this is not a priority. If it becomes a priority at a later time, it will be revisited.
