### ISSUE TITLE
As a platform operator, I want a concourse pipeline that allows me to progressively revoke access to an organization and restore all access and functionality.

### ISSUE THREAD

**Issue by spgreenberg** [18F/cg-product#1104]
A pipeline instance will be created for each required org. The pipeline will represent the lockout lifecycle from the first level of lockout through restoration as defined by 18F/cg-product#1103.

## Acceptance Criteria 

- [ ] A parameterized pipeline definition which implements the progressive lockout tasks as defined by: 18F/cg-product#1103. 
- [ ] Given contract execution is not automated/integration, jobs should be triggered manually to prevent accidental action
- [ ] Slack notifications to warn of upcoming suspension deadlines 
- [ ] A `set-pipeline.sh` script which takes the org name as an input and creates a pipeline instance for the lockout lifecycle of that org
- [ ] A README specifying how to utilize these pipelines: creation through destruction.
- [ ] Limit pipeline trigger access using teams
- [ ] Audit log of pipeline actions taken

**Comment by karareinsel** [comment]
Closing per discussion in business unit sprint planning to also close #1103 .
