### ISSUE TITLE
As a cloud.gov stakeholder, I want a description of initial tech talks applicable to cg customers, platform operators and other TTS/18f team members.

### ISSUE THREAD

**Issue by spgreenberg** [18F/cg-product#1106]
## Acceptance Criteria

- [ ] A document outlining proposed tech talks and perspective audiences

**Comment by karareinsel** [comment]
@spgreenberg can you add the link to the list of tech talks you had originally proposed?

**Comment by spgreenberg** [comment]
https://docs.google.com/document/d/1qlFy0ZWvel8zQNOzPXQ-EzERgJAFDG33xYSX7bGo8Dc/edit?usp=sharing
