### ISSUE TITLE
Migrate Admin UI to Credhub

### ISSUE THREAD

**Issue by mxplusb** [18F/cg-product#1112]
Migrate Admin UI to Credhub

In order to get Admin UI credentials into Credhub, we need to import Admin UI's variables into Credhub.

## Acceptance Criteria

- [x] Staging Admin UI manifest should be identical to existing manifest, but with variables pulled from Credhub.
- [x] Production Admin UI manifest should be identical to existing manifest, but with variables pulled from Credhub.

**Comment by karareinsel** [comment]
@mxplusb is this just waiting on a PR?

**Comment by mxplusb** [comment]
Ya. It'll autoclose once the PR closes.
