### ISSUE TITLE
Migrate Concourse to Credhub

### ISSUE THREAD

**Issue by mxplusb** [18F/cg-product#1114]
In order to get Concourse credentials into Credhub, we need to import Concourse's variables into Credhub.

## Acceptance Criteria

- [x] Staging Concourse manifest should be identical to existing manifest, but with variables pulled from Credhub.
- [x] Production Concourse manifest should be identical to existing manifest, but with variables pulled from Credhub.

**Comment by karareinsel** [comment]
Currently blocked by an upstream PR.
https://github.com/concourse/concourse-bosh-deployment/pull/186

**Comment by mxplusb** [comment]
Staging is done, no longer blocked.

**Comment by mxplusb** [comment]
Done, just waiting on work to close this out.

**Comment by karareinsel** [comment]
Just waiting on PR and then it can be closed out.
