### ISSUE TITLE
Add a ‘plan k8s deployment` step to pipeline, like in cg-deploy-cf

### ISSUE THREAD

**Issue by mxplusb** [18F/cg-product#1115]
Copy the plan deployment process from cf-production and implement it in deploy-kubernetes pipeline.

**Comment by karareinsel** [comment]
This will be great to have for Tuesday's (10/22) K8s scale out so address this early in the sprint. Time box to 3 hours. If it can't be done in 3 hours, then add notes to the comments explaining why it couldn't be completed in 3 hours.
