### ISSUE TITLE
ENHANCEMENT: The aws-rds broker reports "created" for incomplete provisioning requests

### ISSUE THREAD

**Issue by spgreenberg** [18F/cg-product#1126]
The aws-rds broker uses asynchronous provisioning and incorrectly reports service instance status after creation.

Steps to reproduce:

1. Create an instance of medium-psql: `cf cs aws-rds medium-psql psql-test`
2. Note status shows as `created`: `cf service psql-test`
3. Attempt to use the service instance by creating a service key and note failure: `cf create-service-key psql-test key-test`

You will see a message that contains: `Error: Instance not available yet. Please wait and try again.`

**Comment by spgreenberg** [comment]
Closing. This is expected behavior as per the docs: https://cloud.gov/docs/services/relational-database/#instance-creation-time.

**Comment by bengerman13** [comment]
I would be in favor of keeping this around as an improvement rather than a bug. That behavior certainly seems weird to me, and having to have two paragraphs on our docs about what "created" hints at this not being ideal

**Comment by spgreenberg** [comment]
Sounds good. Will re-phrase and re-open.

**Comment by karareinsel** [comment]
This might be replaced by the new AWS broker.
