### ISSUE TITLE
Migrate ZenDesk support to a cloud.gov email address

### ISSUE THREAD

**Issue by hillaryj** [18F/cg-product#1127]
Follow-on to #948  and #1084:

Sounds like moving to support@cloud.gov is the way forward to resolve DMARC/DKIM issues with sending email from ZenDesk.

Tasks include:

- [ ] Set up CNAME records for the cloud.gov domain (possibly via Terraform)
- [ ] Set up ZenDesk with new support address
- [ ] Verify with customers (e.g. EPA) that they receive new emails from ZenDesk
- [ ] Update documentation to use new cloud.gov support address
- [ ] Set Support google group to autoforward to cloud.gov support address
- [ ] Disable emails from Support google group (or possibly remove individuals)

**Comment by eddietejeda** [comment]
FYI: In our meeting with FDIC, they asked if they can get ticket numbers to keep track of their requests.

**Comment by hillaryj** [comment]
I looked into ZenDesk and there was an inactive trigger to auto-reply to a requestor. I've re-enabled it and updated the body of the email, so customers who don't have DMARC issues with us (e.g. EPA) will be able to receive an auto-reply.

**Comment by eddietejeda** [comment]
Our current approach to handling customer emails is not sustainable. Let's keep this issue alive.

**Comment by pburkholder** [comment]
Seems we have to leave ZenDesk entirely since our support system by definition needs to store customer (federal) information, and it's not FedRAMP authorized.

**Comment by karareinsel** [comment]
@eddietejeda spoke with Aiden and needs to go through GSA IT

**Comment by eddietejeda** [comment]
Investing using gsuite as our email backend. We won't have user accounts, just be able to use @cloud.gov domain to route our emails and will be the frontend to zendesk.

**Comment by karareinsel** [comment]
Ask OPM to send test emails.

**Comment by hillaryj** [comment]
As of this morning, Eddie reports this is complete and to use ZenDesk to send support emails.

https://gsa-tts.slack.com/archives/C3RJX3N8P/p1581523396118300

**Comment by pburkholder** [comment]
Resetting DMARC back to 100% in https://github.com/18F/cg-provision/pull/695
