### ISSUE TITLE
As a cg operator, I want the redis and elastic search provisioning tested.

### ISSUE THREAD

**Issue by spgreenberg** [18F/cg-product#1130]
In order to update the redis and elasticsearch offerings to AWS, we want to verify the provisioning behavior of the AWS broker.

Depends on: #1129

## Acceptance Criteria
* [ ] GIVEN the AWS broker deployed via concourse
  WHEN the pipeline runs
  THEN the provisioning of redis and elasticsearch instances is tested.

--- 

## Implementation sketch
* [ ] Provision a redis instance
* [ ] Bind a redis instance
* [ ] Verify redis credentials "look" correct
* [ ] Delete the redis instance

* [ ] Provision a elasticsearch instance
* [ ] Bind a elasticsearch instance
* [ ] Verify elasticsearch credentials "look" correct
* [ ] Delete the elasticsearch instance

**Comment by karareinsel** [comment]
@spgreenberg do you think this will be tackled this sprint?

**Comment by karareinsel** [comment]
Closing this out in favor of newer, more granular stories that reflect the latest information about broker migrations.
