### ISSUE TITLE
As a cloud.gov user, I want to know how to migrate from elasticsearch 2.4 to the new AWS elastic search

### ISSUE THREAD

**Issue by spgreenberg** [18F/cg-product#1132]
In order to support our customers, we need to provide guidance and possibly tools to ease migration off of the kubernetes versions of elasticsearch to AWS.

## Acceptance Criteria
* [ ] GIVEN a customer using elasticsearch 2.4 hosted on kubernetes
  WHEN they are ready to migrate to the new AWS service
  THEN they know what to do.

--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
* [ ] [first thing to do]
* [ ] [another thing to do]

**Comment by karareinsel** [comment]
Closing this out in favor of newer stories that reflect the latest information about broker migrations.
