### ISSUE TITLE
As a cloud.gov user, I want to know how to migrate from elasticsearch 5.6 to the new AWS elastic search

### ISSUE THREAD

**Issue by spgreenberg** [18F/cg-product#1133]
In order to support our customers, we need to provide guidance and possibly tools to ease migration off of the kubernetes versions of elasticsearch to AWS.

## Acceptance Criteria
* [ ] GIVEN a customer using elasticsearch 5.6 hosted on kubernetes
  WHEN they are ready to migrate to the new AWS service
  THEN they know what to do.

--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
* [ ] [first thing to do]
* [ ] [another thing to do]

**Comment by soutenniza** [comment]
Documented here: https://github.com/18F/cg-deploy-aws-servicebroker/pull/1
