### ISSUE TITLE
As a cloud.gov user, I want to know how to migrate from redis 2.8 to the new AWS elastic cache

### ISSUE THREAD

**Issue by spgreenberg** [18F/cg-product#1134]
In order to support our customers, we need to provide guidance and possibly tools to ease migration off of the kubernetes versions of redis to AWS.

## Acceptance Criteria
* [ ] GIVEN a customer using redis 2.8 hosted on kubernetes
  WHEN they are ready to migrate to the new AWS service
  THEN they know what to do.

--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
* [ ] [first thing to do]
* [ ] [another thing to do]

**Comment by karareinsel** [comment]
@ChrisMcGowan and @soutenniza  should this be closed out in favor of new cards that reflect the latest information since AWS is no longer being pursued as the broker option?
