### ISSUE TITLE
As a cloud.gov user, I want to know how to migrate from redis 3.2 to the new AWS elastic cache

### ISSUE THREAD

**Issue by spgreenberg** [18F/cg-product#1135]
In order to support our customers, we need to provide guidance and possibly tools to ease migration off of the kubernetes versions of redis to AWS.

## Acceptance Criteria
* [ ] GIVEN a customer using redis 3.2 hosted on kubernetes
  WHEN they are ready to migrate to the new AWS service
  THEN they know what to do.
--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
* [ ] [first thing to do]
* [ ] [another thing to do]

**Comment by RonWilliams** [comment]
Currently blocked by AWS broker missing elasticache (redis) integration for CF. Pending follow-up response from AWS. Issue open with AWS open-source repository by community.

**Comment by karareinsel** [comment]
@ChrisMcGowan @soutenniza should this be closed out in favor of new cards that reflect the latest information since AWS is no longer being pursued as the broker option?
