### ISSUE TITLE
clamav defs are current does not exist

### ISSUE THREAD

**Issue by bengerman13** [18F/cg-product#1136]
on most or all bosh hosts, monit reports 'clamav_defs_are_current' as 'does not exist', which indicates a problem with clamav.

There are two problems here:
- clamav isn't working
- we're not getting alerts about it

**Comment by karareinsel** [comment]
Deprioritize for now - revisit in the next sprint.

**Comment by karareinsel** [comment]
@bengerman13 confirming that it's fixed. Close if resolved.

**Comment by bengerman13** [comment]
fixed by 18F/cg-clamav-boshrelease#31
