### ISSUE TITLE
Rename aws-broker

### ISSUE THREAD

**Issue by bengerman13** [18F/cg-product#1139]
We maintain a broker named `aws-broker` that really only does RDS.
We're also now adding the awslabs broker. Having both of these called something like `aws-broker` will certainly cause confusion. We should rename `aws-broker` to something more like `rds-broker`to reduce confusion

**Comment by karareinsel** [comment]
Closing out the issue because the catalog value will be different and the broker name is mostly administrative. The broker name isn't customer facing.
