### ISSUE TITLE
Static Egress

### ISSUE THREAD

**Issue by mxplusb** [18F/cg-product#1140]
Since we aren't going to support private egress, we can support static egress. The EPA is asking for it, and it's a reasonable request to explore since it would benefit all customers.

**Comment by mxplusb** [comment]
Feedback from a customer:

> We want to send emails and transfer logs and other files from our cloud.gov application. It’s unlikely that we’ll be able to use something like Amazon SES (although we’re still pursuing it). Our best bet with our network staff is to present a small list of IPs that they can whitelist: private egress would have been perfect for that (based on my understanding of it). Static egress sounds OK, too, but our concern was that anyone else using cloud.gov would be coming from the same IPs. We understand that we would have to authenticate the request first. The transferring files might be easily solvable, so it’s not a big priority. For email, we’re looking into using smtp.outlook365.com, as well, but it’s been harder than we anticipated.

**Comment by karareinsel** [comment]
This feature request is being tracked in the cloud.gov business feature request tracker and so far EPA is the only customer to request this feature. Additional technical investigation is required to assess the level of effort to implement. For these reasons, we're going to close the issue and @RonWilliams will update EPA.
