### ISSUE TITLE
Webhooks or Apps?

### ISSUE THREAD

**Issue by mxplusb** [18F/cg-product#1144]
We need to get webhooks up and working again, but we can't just provision our own and Slack is deprecating webhooks in favour of "apps".

**Comment by hillaryj** [comment]
This is probably part of #1155 to determine the future strategy for getting Slack alerts.

**Comment by hillaryj** [comment]
This is more of a strategy/research/feasibility question than an outright task.

**Comment by mxplusb** [comment]
Ya, strategy and research, not a task.

**Comment by karareinsel** [comment]
Timebox for 2 hours and identify next steps.

**Comment by karareinsel** [comment]
@hillaryj do you want to tackle this in conjunction with #1155 ?

**Comment by hillaryj** [comment]
This can be closed - preference by Infrastructure and TTS is for webhooks because it's only incoming data and not interfacing with another system that could extract data.
