### ISSUE TITLE
Finish updating k8s

### ISSUE THREAD

**Issue by mxplusb** [18F/cg-product#1145]
There are a couple broken things which need to be addressed in Kubernetes, like the staging pipeline is broken, etc.

- [ ] Bring staging and dev inline with the same version as production. 
- [ ] Update staging pipeline
- [ ] Deploy K8s exporter broker to production (pipeline should be green upon completion)
- [ ] ??? @mxplusb, anything else.

**Comment by RonWilliams** [comment]
@mxplusb Please add any additional items when you have a chance. Thanks!

**Comment by mxplusb** [comment]
@bengerman13 last worked on this, he would know the status of things.

**Comment by karareinsel** [comment]
@bengerman13 Can you share a status update for the team?

**Comment by bengerman13** [comment]
@mxplusb the question, I think, was if you had anything for
> ??? @mxplusb, anything else.

I'm working right now on getting the pipeline green.
