### ISSUE TITLE
fix uaa in staging and dev environments

### ISSUE THREAD

**Issue by bengerman13** [18F/cg-product#1148]
Currently, attempting to log in to any services in dev or stage gives the error `Response doesn't have any valid assertion which would pass subject validation`
This makes troubleshooting and testing in environments other than production slow and painful. Fix it.

**Comment by hillaryj** [comment]
Right now, this error means that operators cannot log into any of the dev/staging environments. It's unclear whether this is an issue with UAA itself or if it's due to using the dev SecureAuth. There will need to be some investigation but this is a high-priority fix for maintainability.

**Comment by karareinsel** [comment]
@mxplusb working on this as part of the regular maintenance.

**Comment by tammersaleh** [comment]
@mxplusb The [`push-cf-cdn-service-broker-staging`](https://ci.fr.cloud.gov/teams/main/pipelines/deploy-cdn-broker/jobs/push-cf-cdn-service-broker-staging/builds/181) stage of the `deploy-cdn-broker` pipeline is currently failing due to bad staging credentials.  Is that likely caused by this staging UAA authentication issue? /cc @spgreenberg

**Comment by mxplusb** [comment]
@tammersaleh the two are unrelated as the issue you are referring to is related to OIDC/SAML authentication. The broker likely just had it's credentials rotated - it uses standard UAA user constructs.

**Comment by karareinsel** [comment]
@mxplusb submitted a ticket to GSA IT. Waiting to hear back.

**Comment by mxplusb** [comment]
Okay, I have the SAML metadata, just waiting [to figure out the EntityID value](https://gsa-tts.slack.com/archives/C0ENP71UG/p1579203439153500).

**Comment by mxplusb** [comment]
This is done!
