### ISSUE TITLE
Refactor CF pipeline to be linear

### ISSUE THREAD

**Issue by bengerman13** [18F/cg-product#1152]
the CP pipeline currently deploys Dev and Staging in parallel. We should refactor this pipeline to be linear.

**Comment by hillaryj** [comment]
This is a minor effort change and would align us with best-practices. Prioritize in the next few sprints.

The only trick is to make sure that dev is working when we make this change so it gets propagated - currently, we're blocked by a Bosh CLI change to blobstore configuration validation.
