### ISSUE TITLE
incorporate cloud.gov IT troubleshooting guidance

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#1168]
Probably makes sense for the Equipment page, or being split out to a more general one.

https://docs.google.com/document/d/195V9ss3yRheU2j5x3_N5kCt4YNQCW7LsJd-ZJTAEQkI/edit

**Comment by JJediny** [comment]
@eddietejeda this is more of cloud.gov docs team call on next steps.

**Comment by karareinsel** [comment]
The documentation has been archived and practice is in place for reaching out to #infrastructure so closing this issue.
