### ISSUE TITLE
Snort alerts are still going to pagerduty

### ISSUE THREAD

**Issue by bengerman13** [18F/cg-product#1169]
We have alerts set up in CloudWatch for Snort events, and they're currently going to PagerDuty.
We need to switch these to email or something until we have a monitoring system in place

**Comment by karareinsel** [comment]
Address within the next 1-3 sprints. Hopefully is a small lift to implement.

**Comment by bengerman13** [comment]
This is fixed. I'm creating a couple lower-priority issues I've discovered since then, though.
