### ISSUE TITLE
Update Ongoing platform maintenance page on cloud.gov

### ISSUE THREAD

**Issue by karareinsel** [18F/cg-product#1170]
In order to best support the cloud.gov operations team, the information on https://cloud.gov/docs/ops/maintenance-list/ should be updated to reflect the latest team practices.

- [x] Team make edits to the content https://docs.google.com/document/d/11DuNX2SXgWsa8C9X9QRwIto0HxnXVCAuQX3jrlX4e3g/edit#
- [x] Apply changes to https://cloud.gov/docs/ops/maintenance-list/

**Comment by hillaryj** [comment]
Here's the source file for this page: https://github.com/18F/cg-site/blob/master/content/docs/ops/maintenance-list.md - you can edit it live using the GitHub editor plus preview and create a "patch" branch plus PR like we did before.
