### ISSUE TITLE
As a federalist operator, I want to be able to migrate S3 origins in Cloud Front while the cdn broker is unavailable.

### ISSUE THREAD

**Issue by spgreenberg** [18F/cg-product#1171]
The Federalist team has a backlog of sites awaiting S3 origin migration. 

## Acceptance Criteria
* [ ] GIVEN an existing federalist site \
  AND the need to update the origin of the site \
  WHEN the federalist team invokes a migration via `cf task` \
  THEN the origin is updated \
  AND certification regeneration is NOT triggered.

--- 

## Implementation sketch

The federalist team executes migrations in tasks in Cloud Foundry. The task is defined here https://github.com/18F/federalist/tree/apburnes/bucket-migration/scripts/migrate-site-bucket. The task handles the bucket creation and replication. 

The `update-service` call is here: https://github.com/18F/federalist/blob/6feb3c48147e7ea35d7a157a03a7e841bf393f83/scripts/migrate-site-bucket/migrate-site-bucket.sh#L364. This call in unavailable when the broker is unavailable.

The existing CDN broker is still running as it is processing renewals. The plan is to invoke the update-service endpoint via a POST. However, we must be sure the update call does not trigger a certificate regeneration. Therefore we need to filter requests to ONLY s3 origin migrations. 

* [ ] Verify calls to update-service to change the origin will not trigger a certificate regeneration
* [ ] Implement a proxy filter to the update-service call to ensure only s3 origin migration updates are permitted
* [ ] Inform the federalist team to replace the `update-service` call in their task with a curl to the proxy filter

## Security considerations

The proxy application will require basic authentication at a minimum. The federalist team will need these credentials.

The proxy application will ensure we do not need to disclose broker credentials to the federalist team. Only the proxy will need these credentials.

**Comment by eddietejeda** [comment]
is this still relevant?

**Comment by spgreenberg** [comment]
No. Will close it out.
