### ISSUE TITLE
SSO for OMB

### ISSUE THREAD

**Issue by karareinsel** [18F/cg-product#1197]
Configure cloud.gov authentication to work with OMB ADFS (https://adfs.omb.gov.

**Comment by mxplusb** [comment]
This is on-hold pending the resolution of our dev and staging strangeness.

**Comment by mxplusb** [comment]
This is currently deployed in staging.

**Comment by karareinsel** [comment]
@eddietejeda this is ready for OMB to test in staging.

**Comment by karareinsel** [comment]
@jessykacastillo will email OMB.

**Comment by mxplusb** [comment]
This is done as of [build #184](https://ci.fr.cloud.gov/teams/main/pipelines/deploy-cf-deployment/jobs/deploy-cf-production/builds/184). OMB was notified.
