### ISSUE TITLE
Existing users are invited to subscribe to statuspage.io for outage updates

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#120]
In order for existing users to promptly get notified about cloud.gov outages, we should explicitly invite them to subscribe to https://cloudgov.statuspage.io/ updates (if they aren't already subscribers).

We already have an issue for auto-subscribing new users to statuspage.io (https://github.com/18F/cg-product/issues/74), but we should make sure our existing users know about this too.

**Comment by nikzei** [comment]
PI8 75% assessment:

SHOULD: This is important for our customer experience + potentially important for prospective customers. Seems like a light lift.
