### ISSUE TITLE
Research & track reasons for customers not converting

### ISSUE THREAD

**Issue by berndverst** [18F/cg-product#128]
In order to obtain actionable data for improving our documentation, process, and product roadmap we need to determine why customers are failing to convert.

We will obtain this information through #131 and possibly our website analytics. We will device a mechanism for tracking this data over time.

**Comment by nikzei** [comment]
PI8 75% assessment:

WON'T: we do not have enough cases of potential customers entering the pipeline but not converting to prioritize this research during PI8. I think this would make more sense to take on when we have more business.
