### ISSUE TITLE
Allow customers and users to opt into technical & business newsletters

### ISSUE THREAD

**Issue by berndverst** [18F/cg-product#129]
We will likely have two distinct newsletters, one focussed on business / acquisition / compliance / major features at a high level (target is the customer / CIO) and one focussed on technical items ( best practices, new features announcements and how to use / implement them, breaking change announcements).

We want to allow any person to opt into either of these newsletters.

**Comment by nikzei** [comment]
(leaving this in icebox during this grooming session).

**Comment by nikzei** [comment]
PI8 75% assessment:

COULD: definitely should be done eventually; we have not received requests for this by anyone (I don't think) so this is not of high priority. Seems like it could be a light lift.
