### ISSUE TITLE
Explain Interagency Agreement Process in Docs

### ISSUE THREAD

**Issue by berndverst** [18F/cg-product#130]
We believe [to be confirmed] that lack of clarity and transparency of the IAA process is reducing the number of potential conversions.

We will create better documentation to ensure the IAA process with respect to Cloud.gov is clear.

**Comment by berndverst** [comment]
Perhaps we can eventually consider tracking the IAA process somehow and send email notifications for the next steps. Think our _checklistomania_ app combined with a traditional email marketing funnel.

**Comment by nikzei** [comment]
In response to 8/19 [thread in #skyporter](https://18f.slack.com/archives/cloud-gov-skyporter/p1471617531000501) - perhaps we can create an "How to run a cloud.gov IAA" doc.

**Comment by afeld** [comment]
> Think our checklistomania app combined with a traditional email marketing funnel.

That's more [C2](https://cap.18f.gov/)-like, actually.

**Comment by nikzei** [comment]
I see this as a subissue within #226. First, map out the process, then identify ways to streamline it.

**Comment by berndverst** [comment]
@nikzei so perhaps this shouldn't be in the Ready column after all since it depends on #226 , what do you think?

**Comment by berndverst** [comment]
Clarification on this issue:

This is for a customer user (agency trying to understand the IAA process from their perspective, things they need to do, wait times, etc).

**Comment by nikzei** [comment]
Our processes for IAAs will (hopefully) change in the near future so not worth creating new customer-facing guides for this.

I say that we can offer the 18Fwide IAA guide from Ops to our customers for now, until we have our own process in place.

**Comment by nikzei** [comment]
@mogul @dlapiduz ☝️

**Comment by dlapiduz** [comment]
sure, but we can create a page in the docs site that says "How to buy cloud.gov" and it does some intro and then links there.

**Comment by nikzei** [comment]
I'm going to create an issue for that @dlapiduz

**Comment by nikzei** [comment]
done.
