### ISSUE TITLE
Reach out to existing leads

### ISSUE THREAD

**Issue by berndverst** [18F/cg-product#131]
See https://github.com/18F/cg-skyporter/issues/2 for details.

We have a big list of potential leads who completed our contact form. We should reach out to them.

**Comment by berndverst** [comment]
Depends on 18F/cg-product#346

**Comment by nikzei** [comment]
PI8 75% assessment:

SHOULD: Re #346, we should feel ready to do outreach once we've merged homepage updates (this week).
