### ISSUE TITLE
Improve our contact forms / help info pages to be more informative

### ISSUE THREAD

**Issue by berndverst** [18F/cg-product#134]
Our help pages and contact forms are not very clear about how to contact us, or whom to contact for what type of inquiry.

This is to ensure customers and users can easily contact us for help or questions.

**Comment by berndverst** [comment]
@brittag can you update the description if I am missing something?

**Comment by brittag** [comment]
Here's an existing issue with more detail: https://github.com/18F/cg-landing/issues/66

**Comment by nikzei** [comment]
closing this, keeping open [18F/cg-landing#66](18F/cg-landing#66).
