### ISSUE TITLE
Require MFA for idp.cloud.gov

### ISSUE THREAD

**Issue by LinuxBozo** [18F/cg-product#138]
In order to ensure all cloud.gov logins make use of MFA, we want any accounts provisioned through our fallback IDP to require MFA to be setup and validated before login

**Acceptance Criteria:**
- [x] Scenario: Invitations for unknown domains are prompted to set up MFA  
  GIVEN an invite link is issued for an "unknown" domain  
  WHEN the invite link is clicked  
  AND the user sets their password  
  THEN the user is redirected to the MFA setup form on idp.cloud.gov  
  AND [ the MFA setup form verifies that the user is authenticated on UAA | a single-user token is validated ]  
  AND the user is prompted to set up MFA  
  AND the user is logged in

**Implementation sketch:**

Normally, when you send an invitation, these things happen:
- The invite app sends a request to UAA with the target e-mail address
- UAA creates the account in an "inactive" state
- UAA returns the single-use token for use in confirming the invitation
- The invite app creates a confirmation URL with the token
- The invite app sends the e-mail with the URL to the user

Normally, when you accept an invitation these things happen:
- You click a link to UAA
- UAA verifies the code
- UAA prompts for credential setup (password only; username is in the invite)
- User fills in the form; form checks the requirements
- User submits the form; UAA also checks the requirements
- User is logged in

We _think_ we can use the redirect_uri and client_id when generating the invitation to ensure that users are redirected to the MFA setup form after setting up their password.
- [x] handle allowing the user setting appropriate seed so we can use TOTP for MFA. Configure/use https://github.com/korteke/Shibboleth-IdP3-TOTP-Auth. This plugin does need some work around the edges as well for storing seed somewhere other than LDAP.

**Comment by rogeruiz** [comment]
This needs to be done _after_ the #401

**Comment by jbarnicle** [comment]
In addition to modifying `SQLSeedFetcher`, I believe we will need to make similar changes to `RegisterNewToken` in the `impl`.  It currently is set to store the token in a LDAP server.  It might make sense to refactor `SQLSeedFetcher` to handle both the setting/getting of the shared secret from a SQL resource.

**Comment by jbarnicle** [comment]
Disable `Register New Token` button for returning users.

https://github.com/18F/Shibboleth-IdP3-TOTP-Auth/pull/10

**Comment by jbarnicle** [comment]
We also need to make the name of the seed configurable.  Right now, it shows up as `TOTP` in Google Authenticator.

**Comment by rogeruiz** [comment]
We're going to split out the work in this issue in order to be able to demo the `Shibboleth MFA` portion of this at today's sprint review. The bits we're grooming out of this story are at the end of the first comment.

> handle allowing the user setting appropriate seed so we can use TOTP for MFA. Configure/use https://github.com/korteke/Shibboleth-IdP3-TOTP-Auth. This plugin does need some work around the edges as well for storing seed somewhere other than LDAP.

The _need some work around the edges_ turned out to be **a bit more involved**.

**Comment by rogeruiz** [comment]
We also need to ensure the Shibboleth configuration complies with [FedRamp requirement AC-7](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=AC-7)

**Comment by rogeruiz** [comment]
In response to the ☝️ above, It looks like Shibboleth Account Lockout is [coming in a later version](https://wiki.shibboleth.net/confluence/display/IDP30/PasswordAuthnConfiguration#PasswordAuthnConfiguration-AccountLockout3.3). So we'll need to be building it ourselves and [borrowing](http://svn.shibboleth.net/view/java-identity-provider/trunk/) [as](http://svn.shibboleth.net/view/java-identity-provider/trunk/idp-conf/src/main/resources/flows/authn/conditions/conditions-flow.xml?view=markup) [much](http://svn.shibboleth.net/view/java-identity-provider/trunk/idp-conf/src/main/resources/flows/authn/conditions/account-locked/account-locked-flow.xml?view=markup) [as](http://svn.shibboleth.net/view/java-identity-provider/trunk/idp-conf/src/main/resources/system/flows/authn/password-authn-beans.xml?view=markup) possible from them as well.


## Pertinent `src` links from Shibboleth's SVN repository.

> Linking these here as well...

- http://svn.shibboleth.net/view/java-identity-provider/trunk/
- http://svn.shibboleth.net/view/java-identity-provider/trunk/idp-conf/src/main/resources/flows/authn/conditions/conditions-flow.xml?view=markup
- http://svn.shibboleth.net/view/java-identity-provider/trunk/idp-conf/src/main/resources/flows/authn/conditions/account-locked/account-locked-flow.xml?view=markup
- http://svn.shibboleth.net/view/java-identity-provider/trunk/idp-conf/src/main/resources/system/flows/authn/password-authn-beans.xml?view=markup
- https://wiki.shibboleth.net/confluence/display/IDP30/PasswordAuthnConfiguration#PasswordAuthnConfiguration-AccountLockout3.3

**Comment by jbarnicle** [comment]
How invites are handled in UAA

https://github.com/cloudfoundry/uaa/blob/5cbf9c1b65598892e6f72966a1288e11f72e793a/server/src/main/java/org/cloudfoundry/identity/uaa/invitations/InvitationsController.java

**Comment by rogeruiz** [comment]
Still trying to work around not building the invitation flow ourselves.

**Comment by rogeruiz** [comment]
Progress on this made in 18F/shibboleth-boshrelease#30 around password expiration. Next steps are to fulfill the AC-7 requirement.

**Comment by mogul** [comment]
Looking close per @LinuxBozo... AC-7 sorted now, just working on content of messages.

**Comment by jbarnicle** [comment]
Finalizing documentation for cg-site / deployment / and email.

**Comment by jbarnicle** [comment]
Documentation has been updated in the respective repos.
