### ISSUE TITLE
[5h] Spike to investigate feasibility of a BOSH broker

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#14]
In order to determine the feasibility of using BOSH to dynamically provision managed services via a broker, we want to spend up to 5 hours prototyping to learn more.

**Acceptance criteria**

* [ ] We attempt to create a broker that presents service plans corresponding to a configured set of BOSH manifests and manages instance lifecycles for them, and talk about how far we got.
* [ ] We're able to make a decision about whether this is a viable path forward, and we can write stories for what would need to be done to do it properly

**Comment by mogul** [comment]
@sushiandbeer Can you involve the person who's working on this from the Altoros side in this issue for visibility?

**Comment by dlapiduz** [comment]
@mogul is this still "in progress"?

**Comment by mogul** [comment]
Yes, I asked @s-matyukevich to post info on what he's done here.

**Comment by mogul** [comment]
(He said in today's standup that he's got it working!)

**Comment by mogul** [comment]
@s-matyukevich, in case you didn't see it, please also check out 18F/cg-product#13 for additional context about what we're after here... Wasn't sure if you've seen the Brooklyn stuff or the CF Summit talk.

**Comment by s-matyukevich** [comment]
@mogul  You can find the broker here https://github.com/s-matyukevich/bosh-broker

**Comment by mogul** [comment]
Tagging @jmcarp to review and give feedback/PRs.

**Comment by jmcarp** [comment]
Update: I read the code a week or so ago and thought the overall approach made sense. If we're going to continue with this, the next step would be https://github.com/18F/cg-product/issues/52.

**Comment by dlapiduz** [comment]
@jmcarp should we close this out then?

**Comment by jmcarp** [comment]
Sounds good to me--closing.
