### ISSUE TITLE
Ensure services don't lapse due to expired credentials

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#15]
In order to be aware when someone has established foothold on a host, we want common signs of rootkits or other malware on a host to result in alerts.

Acceptance Criteria
- [ ] Local host-IDS (HIDS) is deployed on all hosts
- [ ] The HIDS signatures used to detect attacks are updated regularly, with trivial team effort
- [ ] When attacks are detected, alerts are sent via Riemann and PagerDuty

**Comment by dlapiduz** [comment]
I think we need a service that creates and tracks deployer credentials

**Comment by afeld** [comment]
--> https://github.com/18F/cg-product/issues/32

**Comment by mogul** [comment]
We have a Slack reminder covering this for now... Going to Icebox this until it's more of a hassle.
