### ISSUE TITLE
Research garden vs runc for Diego

### ISSUE THREAD

**Issue by sushiandbeer** [18F/cg-product#164]

**Comment by s-matyukevich** [comment]
@sushiandbeer  

The only restriction that I can found is that runc and guardian requires kernel version 3.19+ (but seems like Ubuntu trusty was already updated to 4.2, so this should not be a problem)

Another interesting thing, is that PCF still use garden. https://docs.pivotal.io/pivotalcf/1-7/pcf-release-notes/p1-v1.7/runtime_rn_1_7.html

So what we can do is to wait until runc will be adopted in PCF, this way we can be sure that it is production ready.

**Comment by dlapiduz** [comment]
@s-matyukevich @sushiandbeer so basically we are ready to upgrade whenever we want? Can garden droplets run in runc or does it have to be restaged?

**Comment by sushiandbeer** [comment]
Garden-runC is not quite ready for production use according to  https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/PQGMSHFBPDSKEFBI233JX3OETDILYJMS/

I agree with @s-matyukevich and advise we transition to it when Pivotal does so in PCF.

**Comment by sushiandbeer** [comment]
Also note the garden-linux default max_containers of 250.  https://github.com/18F/cg-atlas/issues/101

**Comment by jbarnicle** [comment]
@dlapiduz Can we close this research story?
