### ISSUE TITLE
Define interesting monitoring metrics for Diego

### ISSUE THREAD

**Issue by sushiandbeer** [18F/cg-product#175]

**Comment by s-matyukevich** [comment]
@sushiandbeer  all diego metrics have exactly the same structure as CF metrics. What I suggest to do is to create a common dashboard, that will be able to display all metrics from all cf and diego components. 

https://github.com/18F/cg-product/issues/220

**Comment by sushiandbeer** [comment]
Blocked on waiting for merge of https://github.com/18F/cg-product/issues/220

/cc @dlapiduz @mogul

**Comment by sushiandbeer** [comment]
See the descriptions for various Diego metrics here: https://github.com/cloudfoundry/diego-release/blob/develop/docs/metrics.md

**Comment by sharms** [comment]
![screen shot 2016-10-05 at 1 01 54 pm](https://cloud.githubusercontent.com/assets/95657/19123260/edc42e6a-8afb-11e6-846a-857badfb3a02.png)
