### ISSUE TITLE
[2d] Research existing CF deployment migration options

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#177]
In order to understand how much responsibility must be put on cloud.gov users for the migration to GovCloud, we want to spend up to 2 days researching existing tools that could make things easier

**Acceptance Criteria:**

- [ ] We know what's required to backup/restore the platform itself (for both this migration, and for contingency planning) See [Pivotal's docs on how they do it](https://docs.pivotal.io/pivotalcf/1-7/customizing/backup-restore/backup-pcf.html)
- [x] Research [S&W Shield](https://github.com/starkandwayne/shield) to see if it can help migrate stateful services
- [ ] Determine feasibility of mirroring changes in quotas orgs, spaces, users, and roles between environments

**Comment by frsfx** [comment]
After researching SHIELD, it is definitely a viable solution as a self service for end users in backing up their stateful services from AWS East Region to AWS GovCloud.  End users will need to use an appropriate plugin to backup/restore their services.  As an example, end users download SHIELD CLI to connect to the backend SHIELD server and update their deployment manifest to perform a backup.  SHIELD can also backup BOSH if we needed to.

**Comment by mogul** [comment]
Given we've spent way more than 2 days researching this, have a ticking clock to get our GovCloud migration going, and little confidence that we're going to have this in a production-worthy and supportable mode for our tenants in a short amount of time, we're going to move forward on the GovCloud migration **without** Shield in the picture. (We'll consider Shield for future use in keeping a warm-standby of our production environment for contingency-planning purposes.)
