### ISSUE TITLE
Alert on Riemann failures

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#18]
In order to ensure we're aware when alerting is not functional, we want to be notified when Riemann enters or leaves a non-functional state.

**Comment by rogeruiz** [comment]
_Proposed AC_
- [ ]  Alert when Riemann is not receiving collectd messages
- [ ] Alert when Riemann is not receiving `cf-firehouse` messages

**Comment by mogul** [comment]
Please elaborate on the story here sooner (to help with prioritization) or later (once this reaches `Grooming`) to ensure everyone has enough context to be able to move it forward.
