### ISSUE TITLE
Aggregate all logs, generated by bosh jobs and send them to ELK

### ISSUE THREAD

**Issue by s-matyukevich** [18F/cg-product#185]
For Cloud Foundry components, all logs are aggregated and available through firehouse. But for other bosh jobs (concourse, snort, riemann, etc. ) seems like the only way to access their logs is to ssh to bosh VM, where particular component is installed. 
What we can do is to create special bosh job, that will be responsible for aggregating logs from all other components and send them to ELK.

is that something that we are going to look at?

**Comment by mogul** [comment]
I think @LinuxBozo had concerns about sending those to the same ELK instance, but I'm not sure if those were security, stability, or scalability concerns! Maybe something to look at once we have hammered on our ELK cluster (both volume and chaos-monkey) and know it can take the punishment?

**Comment by dlapiduz** [comment]
@mogul I think since @sharms fixed the heap memory thing ES is running on very low revs... I'd love to see all the logs aggregated in ELK!

**Comment by s-matyukevich** [comment]
I have created a BOSH release that can do this task https://github.com/s-matyukevich/bosh-log-forwarder-boshrelease

**Comment by s-matyukevich** [comment]
I've completed this task as much as I can for the moment (BOSH release works and I've created a concourse pipeline to build it)  I also have a few notes/questions 

1. This bosh release can be extended to support  a lot of additional features (possibility to skip logs from some jobs, setup multi line patterns and provide custom parsing rules via bosh properties are a good candidates for such features) What I suggest to do is to try this bosh release in 18F environment first, and then decide whether this features are required or not.  I can't do this by myself, because I don't have any accesses. 

2. Probably we need similar thing for influxdb/riemann. 

@jmcarp  @sharms  what do you think?

**Comment by rogeruiz** [comment]
This needs to be deployed to `GovCloud` concourse to verify the boshrelease.

**Comment by sharms** [comment]
This is currently broken and will hold awslogs handles open after they have been rotated causing file systems to reach 100% full.  Reverting

**Comment by mogul** [comment]
Is this closed as "won't revisit after reverting", or was it fixed before closing?
