### ISSUE TITLE
Search for docs

### ISSUE THREAD

**Issue by msecret** [18F/cg-product#194]
In order for a cloud.gov developer to easily find documentation they're looking for, there should be a search interface for the docs.cloud.gov site.

From previous issue (now closed): 

Visitors can search cloud.gov content from the global navigation

Benefits
- Help users find existing documentation when it's not obvious to them how to navigate toward what they're looking for
- See the task list for implementing search.usa.gov, which we've already provisioned.

**Comment by suprenant** [comment]
Also discussed: 
 - Reconfigure it so it doesn’t show Twitter results
 - Remove hamburger?

**Comment by suprenant** [comment]
Closing up this epic – replacing with a label

**Comment by mogul** [comment]
Long since done... Woohoo!
