### ISSUE TITLE
Advance breaking change notifications

### ISSUE THREAD

**Issue by berndverst** [18F/cg-product#199]
In order to minimize application downtime or impact on functionality, as a user, I want to have advance notification for upcoming breaking changes that without my intervention would affect my application uptime.

**Comment by berndverst** [comment]
Depending on the complexity of the work required by the user, advance notification of at least 30-90 days for breaking changes is very standard. For major architectural changes, this may even be 6-12 months.

Enterprise customers typically expect a breaking change policy with such an advance lead time.

Note:
On the engineering side we need a better change management and sign-off process to facilitate this external communication of breaking changes.

**Comment by brittag** [comment]
Noting that we have some relevant documentation for announcing advance notice of downtime: https://docs.cloud.gov/ops/making-announcements/

We also have a draft backlog for an upcoming breaking change (GovCloud) at https://github.com/18F/cg-atlas/issues/59 - which is helpful since we can build lightweight general guidelines (such as a checklist template) based on a real example that we're handling.

**Comment by berndverst** [comment]
A perfect example of the breaking change notification would be the announcement of the eventual E/W shutdown you reference in 18F/cg-atlas#59 which is inherently different from system downtime as it requires active steps to be taking by the developer / team.

We will need a general policy (which we can publish on the website) that outlines how much notice we will give for these kinds of changes. We also need to actually start executing against that policy.

Now is definitely a good time to get traction on 18F/cg-atlas#59 and related work. /cc @nikzei

**Comment by nikzei** [comment]
PI8 75% assessment:

MUST/SHOULD: This is important for our customer experience + potentially important for prospective customers. Seems feasible to set a policy at the least during PI8.

**Comment by mogul** [comment]
We notify people as best we're able depending on how disruptive the change is as a general practice now,
