### ISSUE TITLE
Investigate Cloud Foundry Acceptance Test failures

### ISSUE THREAD

**Issue by sushiandbeer** [18F/cg-product#202]

**Comment by sushiandbeer** [comment]
The `cf copy-source` test is failing, apparently due to the S3 bucket policy that requires the `x-amz-server-side-encryption` header.  A fog library trace reveals the header is not being supplied when doing the `x-amz-copy-source` operation.

**Comment by sushiandbeer** [comment]
@jmcarp issued this PR for the fix:  https://github.com/cloudfoundry/cloud_controller_ng/pull/658

**Comment by rogeruiz** [comment]
After talking with @jmcarp and @sushiandbeer, we're going to be looking into removing encryption on the bucket(s) via Terraform that are being used for the acceptance tests and then run the `encrypt-blobstore-boshrelease` to explicitly encrypt those specific buckets after the fact.

**Comment by jmcarp** [comment]
And we're going to file an issue to restore the encryption check after the upstream issue is resolved.
