### ISSUE TITLE
Ramp up Andrew on cloud.gov team

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#203]
In order to get Andrew productively contributing to the cloud.gov team, Nikki should help Andrew complete a prescribed set of tasks that will bring them up to speed.

# Directions:
**Andrew and Nikki:** Try to go through your checklists in order.
**Nikki:** If you can’t complete any of the items on your checklist personally, _you are responsible for ensuring that an appropriate person does it_.

## Andrew checklist (includes items required for compliance purposes)
- [x] Take judicious notes on what about this onboarding process or cloud.gov is confusing or frustrating. If you notice a problem (especially with things like documentation), you are more than welcome to fix it! At the very least, please share this information with your buddy (or someone) at some point so we can make the team/platform better. (You can also file issues and pull-requests on [the template for Onboarding issues](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md).)
- [x] Figure out who your onboarding buddy is (they should reach out to you) and make sure this issue is assigned to them)
- [x] Read [the team onboarding document](https://github.com/18F/cg-product/blob/master/Onboarding.md) for more context about cloud.gov
- [x] Read the ["What is it?"](https://docs.google.com/presentation/d/1nCcti3dXG9TVGW3OqaWtnf96oXX8U8SBTM_WePFO_dg/edit#slide=id.p) presentation for a rundown of what cloud.gov is and does
- [x] Check out the [roadmap](https://18f.aha.io/published/068c364a0302b89521045f9fbd258374) to get a high-level view of recently-completed, in-progress, and upcoming features
- [x] Install the [ZenHub](https://zenhub.io) browser extension to enable you to see kanban boards, hierarchical issues, and burndown charts in GitHub
- [x] Read the [Delivery Process document](https://github.com/18F/cg-product/blob/master/DeliveryProcess.md) to learn about how we work
- [x] Read the [18F Security Policies and Procedures](https://github.com/18F/compliance-docs). These documents (which are mostly quite short) explain the high-level policies and procedures we must comply with while running cloud.gov.
- [x] Read the [Incident Response Guide](https://docs.cloud.gov/ops/security-ir/).
- [x] Coordinate with your onboarding buddy to go through Incident Response Training within 60 days of joining the team (and annually after that).
- [x] Read the [Contingency Plan](https://docs.cloud.gov/ops/contingency-plan/).
- [x] Coordinate with your onboarding buddy to go through Contingency Planning training within 10 days if you'll be taking on a significant role in our Contingency Planning processes (or annually if not).
- [x] Read the [Configuration Management Plan](https://docs.cloud.gov/ops/configuration-management/).
- [x] Subscribe to the [cg-docs](https://github.com/18F/cg-docs) GitHub repository notifications
- [x] Subscribe to [the cloud.gov team calendar](https://calendar.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks@group.calendar.google.com&ctz=America/Los_Angeles) (click the + in the bottom right) so you know when assorted team meetings are happening in the various streams
- [x] Join [the cloud.gov support Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov-support), so you can see how we handle non-18F support and get visibility of technical discussions happening with outside groups
- [x] Figure out what themes you're likely to work in, and complete the checklist below that relates to it
- [x] Once you've finished the remaining checklists below, make suggestions for steps that would have improved your onboarding experience as pull-requests on [the onboarding checklist template](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md) used to make this issue

### Optional items

- [ ] Read through [the Introduction section of docs.cloud.gov](https://docs.cloud.gov/) for a broader understanding of cloud.gov, especially as we present it to potential customers/users
- [ ] Read the [January 2016 cloud.gov "Executive Business Case" document](https://docs.google.com/document/d/138OcG0Lt6gr9J0wM0TzzPNyTROmYAwfLIDujtweiwGw/edit#) for greater context about cloud.gov's potential impact in government
- [ ] Try to [deploy a sample application to cloud.gov](https://docs.cloud.gov/getting-started/your-first-deploy/) to get familiar with the basics of the PaaS from a user's perspective

### Liberator-specific items
- [x] Join the `#cloud-gov-liberator` channel on Slack
- [x] Ping @standup-bot for instructions on front end channel standup
- [x] Review the main [front end board](https://github.com/18F/cg-dashboard/pulls#boards?repos=55727091,39210774,49169967,40567233&labels=Liberator&showPRs=false) (ensure to filter by the "Liberator" label)
- [x] Bookmark link to [design folder](https://drive.google.com/drive/u/1/folders/0BwLqM4Nicmq-bUt0NjRjclFMUEU)
- [x] Review the primary cloud.gov sites: [the dashboard](https://dashboard.cloud.gov/#/), [main landing page](https://cloud.gov/), and [documentation](https://docs.cloud.gov/).
- [x] [Request access to 18F Google Analytics](https://handbook.18f.gov/google-analytics/), so you can view cloud.gov site analytics ([including for the dashboard](https://docs.google.com/document/d/1gSbP2ak2a3QLpCZIF_KlbQ2QHE6RjDI-7ZnnrJZvMDE/edit))
- [x] Ask for an invite to a DigitalGov Search account for cg-docs, so you can configure it and view analytics

---
## Buddy checklist
- [x] Introduce yourself to the new team member and give them some of your background so they know who you are
- [x] Make sure they're listed in [the list of people working on the project](https://docs.google.com/spreadsheets/d/1mW3tphZ98ExmMxLHPogSpTq8DzYr5Oh8_SHnOTvjRWM/edit#gid=0)
- [x] Add them to the @cloud-gov-team in Slack’s Team Directory (which also adds them to the right channels)
- [x] Add them to the recurring cloud.gov meetings that are relevant for them in [the team calendar](https://calendar.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks@group.calendar.google.com&ctz=America/Los_Angeles)
- [x] Setup a cloud.gov user account for them via [the “send an invite” page](https://invite.cloud.gov)
- [x] Identify a straightforward, well-groomed story in progress that involves their skills domain, schedule a meeting with the owner for an introduction (if it's not you), and setup pairing sessions several times in the first week on the project.
- [x] Identify a straightforward, well-groomed first story, ideally something they could conceivably complete in their first two/three weeks using their existing skills. Discuss the context with them, then make them the assignee for the card.
- [ ] Make suggestions for how your onboarding experience could have been improved as PRs on [the onboarding template](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md).
- [x] Confirm they have 2FA enabled for GitHub, and ask `#admins-github` to have them added to the [@18F/cloud.gov team](https://github.com/orgs/18F/teams/cloud-gov) on GitHub

**Comment by nikzei** [comment]
@suprenant, here's you're personal checklist for when you go through onboarding materials.

**Comment by suprenant** [comment]
@nikzei very helpful, thanks! Will work through these and mark here when they're done

**Comment by mogul** [comment]
Can you pick up documenting progress here? We need to be really explicit for compliance purposes. (Seems it fell through the cracks due to lack of a label; have addressed that now so at least it will show up on board views.)

**Comment by suprenant** [comment]
@mogul yes – I'm planning on making progress here during our IP sprint FYI

**Comment by nikzei** [comment]
@suprenant following the checklist, let me know if you'd like to pair on issue grooming. I know that you are likely experienced at this point, but maybe we can knock this out this week and get those boxes checked.

**Comment by suprenant** [comment]
@nikzei thanks! I'm feeling good about grooming so went ahead and checked those items. I plan to knock out the rest and close this issue during the IP sprint.

**Comment by suprenant** [comment]
Updated from latest template to reflect items required for compliance purposes: https://github.com/18F/cg-product/edit/master/OnboardingChecklist.md

**Comment by suprenant** [comment]
Coordinating with @nikzei for Contingency Planning and Incident Response Training. Considering this issue done!

**Comment by suprenant** [comment]
@nikzei @mogul could one of you please close this out?
