### ISSUE TITLE
Two-page printable intro to cloud.gov

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#204]
In order to quickly understand the basics of cloud.gov, CIOs want a one-page fact sheet / sell sheet summarizing what cloud.gov is and can do for their agency, and how they can make use of it.

## Acceptance criteria

* [x] There is a one-page PDF with high-level information about cloud.gov
* [x] The reader understands how pricing works for cloud.gov

Working copy:
https://docs.google.com/document/d/1e0E96Cw-S8lFqIH20CxX-JzMV7p0wQHK583GlL4Nyb0/edit

**Comment by afeld** [comment]
Getting started here: https://docs.google.com/document/d/1WU25V2SN2t9pc-_GKwTqwv9d3oT6iPCubkHkEOHg_1U/edit

**Comment by berndverst** [comment]
This is being reviewed for copyediting by the writing lab:
https://github.com/18F/writing-lab/issues/202

**Comment by mogul** [comment]
@jameshupp you might want to put some eyes on this too.

**Comment by berndverst** [comment]
This is the document in question:
https://docs.google.com/document/d/1e0E96Cw-S8lFqIH20CxX-JzMV7p0wQHK583GlL4Nyb0/edit

**Comment by berndverst** [comment]
@jameshupp added you as another assignee. Just let me know when you had a chance to take a pass.

Of course we can iterate on this later, but just need something we can send to interested executives / program management staff.

**Comment by berndverst** [comment]
Moving this to awaiting acceptance and making  @jameshupp the verifier :)

**Comment by jameshupp** [comment]
Looks good. Let's get it out there and see how it does and revise based on what we hear.

**Comment by berndverst** [comment]
Anyone at GSA with this link can view:
https://drive.google.com/a/gsa.gov/file/d/0BwaT7mee_Zc7NkhMelBsN1JhcXc/view?usp=sharing

**Comment by berndverst** [comment]
We will adjust the document based on feedback. Closing this as v1 is complete.
