### ISSUE TITLE
As members of Skyporter and Liberator, we want to agree on the best way to make website changes

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#208]
Our new Skyporter team, which is business and customer focused, wants to make changes to public facing materials including the website - to ensure that our communication with customers is clear, compelling. Skyporter is new and Liberator has been responsible for designing these materials. Let's all get on the same page and figure out how we want to work on this together.

**Comment by nikzei** [comment]
I'll put something on the calendar - most likely for the week of 8/15.

**Comment by brittag** [comment]
https://pages.18f.gov/lean-product-design/ seems useful for us to read before the meeting, as a documented process for product design used in some ways around 18F - to help us have a shared vocabulary.

**Comment by nikzei** [comment]
Takeaways from our meeting:

Review Processes

Always need one person to review changes made. Liberator typically makes decisions by consensus but we’re not doing this with marketing-related content and design changes.

**Content Review:** Changes made to online content related to marketing:
If Bernd makes changes, he needs to get review from one person within Skyporter/Liberator → can get merged.
If anyone else makes content changes, get Bernd’s review before getting merged

**Design Review:** Changes made
Everyone is invited to sketch
Liberator merges pull request
“I need design help.” → slack it in the Liberator channel

Responding to Requests for Immediate help or review
For liberator, bring to Sprint review to discuss whether they’re able to prioritize new issue
Generally, try not to present emergency issues

For the Future: 
What is the role of content design in this process? :D
What should be our process for working on print materials?
Responding to requests for immediate help
