### ISSUE TITLE
Provide tools / guidance for migrating stateful services

### ISSUE THREAD

**Issue by jbarnicle** [18F/cg-product#211]
Running `cf marketplace` currently shows these services available on cloud.gov

- aws-rds   
- cdn-route                          
- elasticsearch-swarm-1.7.1   
- rds                         
- redis28-swarm  
- s3

We've discussed that elasticsearch has been billed as a 'use at your own risk' service - need to decide on what support we provide for migrating users using that service

For any additional services created by the user, it will be up to them to migrate any associated resources.

- [ ] create test case for each service instance and associated customer facing documentation

**Comment by brittag** [comment]
I'm filing individual cards to reflect this need:

* aws-rds (and rds) - postgresql https://github.com/18F/cg-product/issues/230
* aws-rds (and rds) - mysql https://github.com/18F/cg-product/issues/231
* cdn-route - https://github.com/18F/cg-product/issues/232
* elasticsearch - https://github.com/18F/cg-product/issues/233
* redis - https://github.com/18F/cg-product/issues/234
* s3 - https://github.com/18F/cg-product/issues/235

**Comment by afeld** [comment]
This has been split to more specific stories.
