### ISSUE TITLE
Provide guidance on DNS transition

### ISSUE THREAD

**Issue by jbarnicle** [18F/cg-product#212]
Need to provide support for transitioning DNS for current cloud.gov tenants when moving to GovCloud

Where DNS is currently hosted

DNS Managed by us
- update entry in Route 53 to point to new ELB
- aws does not support DNSSec (?)

Self-Managed DNS
- update dns to point to ELB
- [ ] Identify which tenants are managing DNS vs those managed by Route 53
- [ ] Create appropriate documentation for each
- [ ] Impact of creating and destroying ELBs in Terraform

**Comment by jezhumble** [comment]
For systems where 18F managed DNS:

Currently 18F's DNS is hosted in two places:

1. The legacy 18F enterprise AWS account, which hosts discovery.gsa.gov.
analytics.usa.gov. openopps.digitalgov.gov. open.foia.gov. https.cio.gov. open.fec.gov. calc.gsa.gov. my.usa.gov. 18f.gov. pulse.cio.gov. beta.fec.gov. sbst.gov. collegescorecard.ed.gov. regulations.atf.gov. gsaforecast.gsa.gov. cld.epa.gov.
2. The new TTS prod AWS account, which hosts everything else, and is managed via Terraform configured from GitHub here: https://github.com/18F/dns

As we migrate systems to new cloud.gov, we should migrate the DNS as well. In the case of domains delegated to us, we should work with the agencies to change their NS records to point to new versions set up through https://github.com/18F/dns

**Comment by afeld** [comment]
There is also a wrinkle around shared domains (such as `*.18f.gov`), since they can't span both environments. Seems like they will need to have DNS records for each of the subdomains during the transition.

Also also, for apps with custom domains, we should probably wait on https://github.com/18F/cg-product/issues/499 so that we don't need to change the internal domain twice.

**Comment by konklone** [comment]
@jezhumble et al - Would https://github.com/18F/dns be usable for partner apps as well, like analytics.usa.gov or https.cio.gov?

**Comment by jezhumble** [comment]
Yes, absolutely.

**Comment by suprenant** [comment]
@afeld is there any reason you can think of to not close this issue?

**Comment by afeld** [comment]
Nope!
