### ISSUE TITLE
Draft intro para on ATO for 2 pager geared toward CIOs

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#214]
We're drafting a two-pager on cloud.gov intended to help us explain and market the product to CIOs. Since CIOs ask about the ATO process, we'd like to include a paragraph in this two-pager covering general, basic information about the ATO process (ie what it is, perhaps the parts (controls) for which a tenant might be responsible if using cloud.gov, etc.).

Prioritized by squad 3 during 2nd sprint.

**Comment by afeld** [comment]
Part of https://github.com/18F/cg-product/issues/204.
