### ISSUE TITLE
Figure out an overall internal team training plan/schedule

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#216]
In order for the cloud.gov team (which frequently has new members) to train ourselves on our important internal processes, we should have some reasonable plan for teaching required team trainings on a regular basis. It's a good idea for us, and it also helps us fulfill our compliance requirements. :D

I'm not totally sure how this responsibility would break down into specific tasks; for now I'm just writing down that this is a thing we should plan for. This might include:
- Scheduling incident response training every two months instead of once a year, so that we always catch new people (who are required to do this within 60 days).
- Putting info about trainings in some tidy internal place: videos/notes from past trainings, lesson outlines/materials for training leaders, keywords for searching Google Calendar to find the next time we're doing training on a topic.

**Our training requirements:**

_See also: [our onboarding checklist](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md)._

Security incident response training and testing:
- Each new team member needs this within 60 days of joining the team.
- Each team member needs a training session at least annually.
- If anything about the cloud.gov system or organizational environment (aka GSA or 18F) changes significantly in a way that affects our plan, we need to revise the plan, and then everyone needs a new training.
- We need to test our IR plan (do an IR exercise) at least annually. We should coordinate these exercises with GSA IR - we should reach out to them ahead of time and work with them on this.

Contingency planning training and testing:
- Each team member who has a role relevant to [contingency planning](https://docs.cloud.gov/ops/contingency-plan/) (which we can decide internally, but should include people who would have the skills and access to help recover from some major problem) should get training on this within 10 days of assuming that responsibility.
- The cloud.gov team needs to do a contingency planning test/exercise at least annually.

Planning of contingency planning is tracked here in detail: https://github.com/18F/cg-product/issues/201

**Optional training things that would be nice:**

Running retrospectives:
- All of our work would be supported by occasional training on running retrospectives. @jacobian has volunteered to help with this (https://github.com/18F/cg-docs/pull/362).

**Comment by mogul** [comment]
Add to the list: 

- Technical and documentation content that should never appear in a public repository

**Comment by brittag** [comment]
Chatted with our 18F-wide onboarding lead (Keith) about ideas for tracking this, ended up with a little draft of a spreadsheet that could serve as a dashboard for tracking our training requirements - [stuck a draft here](https://docs.google.com/spreadsheets/d/1hqU6cNeEB293OT0j3OvbdAFRkrf2zDOrPVxGfnr4sSw/edit#gid=0), leaving in icebox for now.

**Comment by brittag** [comment]
I gave [that draft spreadsheet some formulas](https://docs.google.com/spreadsheets/d/1hqU6cNeEB293OT0j3OvbdAFRkrf2zDOrPVxGfnr4sSw/edit#gid=0), so it can now serve as a training tracker.

**Comment by brittag** [comment]
We made a bunch of progress on this with our recent round of trainings, but we still need to do the remaining parts of making sure the incident response and contingency planning tests happen annually + making sure our annual refresher training happens.
