### ISSUE TITLE
Better SSH/SCP/cron/port-forwarding capability

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#22]
What we're after: Users can easily run commands in, transfer files to/from, and forward ports from their app containers

Benefits/why:
- Easier to script bootstrap and cron processes
- Enables use of local tools for manipulating managed services (initialize/query/dump/restore)
- Support long-lived connections

**Note: *\* While this will almost certainly involve getting the Diego back-end deployed, **exposing the ability to push Docker images to users at this point is out-of-scope**! We want to start by just improving the SSH experience they're having. (The UK GDS is taking the same approach, and [documents it for their users,](https://government-paas-developer-docs.readthedocs.io/en/latest/deploying_apps/limitations/) having said "Buildpack lifecycle diego apps in garden seem pretty similar to warden containers on DEAs security-wise. Once we've got our heads around what we would need to do to make docker-images-as-apps OK, we'll look at that again".) A [separate feature](https://18f.aha.io/features/CGP-215) covers enabling pushes of Docker images.
## Acceptance Criteria

(Merging AC from https://github.com/18F/cg-atlas/issues/102)

In order to approve Diego for production and ready for use in GovCloud the following criteria must be met:
- [ ]  Diego deployed
- [ ]  Run automated tests from upstream
- [ ]  Deploy cloud.gov apps with monitoring
- [ ]  Migrate some 18F apps
- [ ]  Migrate sandboxes
- [ ]  Migrate more risky stuff
- [ ]  Migrate Dept of ED, college scorecard
- [ ] Demo Diego

**Comment by rogeruiz** [comment]
Let's maintain feature parity across the two environments for cloud.gov, (e/w and govcloud).

> it makes the most sense to ensure both environments are consistently working so we don't waste time talking about why they were not

**Comment by mogul** [comment]
Thanks for breaking this down so thoroughly! Can you put all of the sub-issues in `Icebox` or `Backlog` as appropriate for the work to be done soon? `New issues` overfloweth...

**Comment by mogul** [comment]
test comment

**Comment by mogul** [comment]
another test comment

**Comment by mogul** [comment]
Diego is up and running!
