### ISSUE TITLE
Create universal CF dashboard for Grafana, that will contain all metrics, available from firehouse nozzle. 

### ISSUE THREAD

**Issue by s-matyukevich** [18F/cg-product#220]
Actually, all logs and metrics, that CF provides, follow the (same structure)[https://github.com/cloudfoundry/sonde-go/blob/master/events/envelope.pb.go#L103]
We can utilize this fact, and create a universal dashboard for grafana, that will be able to display all available metrics. This should be a grafana (scripted dashboard)[http://docs.grafana.org/reference/scripting/ ]
When executed, this dashboard should query influxdb and group all records by their (metric name)[https://github.com/cloudfoundry/sonde-go/blob/master/events/metric.pb.go#L23] This will provide us with a list of all available metrics. Then for each metric we can build individual graph, that will display the value for this metric.

Because CF provides us with very large amount of metrics, we should also provide a way of filtering this graphs. We can build special control, that will have a tree structure, with check box on each level.  Items in this tree, will correspond to different parts of CF metric names, splited by "."  (for example, for the following metric name 'cf.cc.total_users' we will have 3 nested levels) By clicking on checkboxes, operator will be able to show and hide graphs for individual metrics, as well as for the whole metric group. 

CF have different event types, that can be interesting for us from monitoring perspective (this is not only metrics, but also counter events, container metrics, http events, the full list is here https://github.com/cloudfoundry/sonde-go/blob/master/events/envelope.pb.go#L56) we can also create similar dashboards, or extend our original dashboard to support this types of events.

**Comment by s-matyukevich** [comment]
I've finished this task. There is a set of pull request that makes it possible to create such dashboard 

https://github.com/18F/cg-riemann-boshrelease/pull/27
This PR adds tag fields to riemann config, so this fields are added to influx db as tags and not as ordinary fields

https://github.com/18F/riemann-firehose-nozzle/pull/5
This PR adds additional field, that riemann-firehouse-nozzle will transfer ti riemann. This field is used in the dashboard

https://github.com/18F/cg-deploy-monitoring/pull/78
And finally this PR adds dashboard itself.

**Comment by sushiandbeer** [comment]
Blocked waiting for the merges above.

**Comment by mogul** [comment]
@sharms we're trying to figure out the status here and see if we can move this to complete. Can you assess it?

**Comment by rogeruiz** [comment]
@rogeruiz will take a look at the related tickets that came out of this.

**Comment by sharms** [comment]
![screen shot 2016-10-05 at 1 01 54 pm](https://cloud.githubusercontent.com/assets/95657/19123269/fa481e26-8afb-11e6-9891-f7c717b837bd.png)
