### ISSUE TITLE
As a user, I would like an easy way to enable auth for my application

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#221]
I thought we had this as an issue somewhere already, but I couldn't find it.

Before an application receives an ATO, a system must not be available to the public.

https://pages.18f.gov/before-you-ship/ato/types/#pre-authorization

Right now, applications need to add basic auth into their code, but it would be helpful to have a simple way to do it for applications that don't otherwise need auth. We could use something like [oauth2_proxy](https://github.com/bitly/oauth2_proxy) along with [route services](http://docs.cloudfoundry.org/services/route-services.html) to add a single-signon wall in front of any application with a single command. This was the impetus for [enabling route services](https://github.com/18F/cg-deploy-cf/pull/40).

**Comment by mogul** [comment]
There's an upstream feature in Aha about this, and it's currently prioritized for PI8. There's more detail to the user needs than just what's represented here, based on recent meetings with agencies.

**Comment by afeld** [comment]
Ah sorry, I searched before but missed it.

https://18f.aha.io/features/CGP-262
