### ISSUE TITLE
Mirror certs+ELBs in GovCloud

### ISSUE THREAD

**Issue by jbarnicle** [18F/cg-product#224]
SSL certs need to be pulled out of E / W and installed into GovCloud

- [ ] Identify certs / locate original certs
- Notify users of the cut-off date for ELB/cert change requests in the E/W environment
- Install certs in the GovCloud environment
- Setup ELBs in the GovCloud environment

**Comment by afeld** [comment]
Let's go with getting people to [use the CDN broker](https://cloud.gov/docs/apps/custom-domains/#managed-service-method) instead.
