### ISSUE TITLE
List our tenants who will need to be migrated

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#229]
In order for our team to plan this migration, we need a sense of who we're working with and what they need.

We need an authoritative list of:

* Names of projects
* Key contact who will be responsible for coordinating the migration
* Whether they have technical labor funding+staffing for this or will need to scramble (a risk for lagging)
* All services the project is using

Acceptance criteria:

- [ ] We have a spreadsheet in Google Drive that has enough of this info that we can comfortably proceed

**Comment by brittag** [comment]
Noting that we need to have both a name and an email address for the key contact.

**Comment by brittag** [comment]
We will likely also use this spreadsheet to track their progress: 

* Have they acknowledged receipt of the message that they will need to do this (https://github.com/18F/cg-product/issues/238)?
* Do they seem to be on track to transition on time or are they lagging behind and may need help (https://github.com/18F/cg-product/issues/239)?

**Comment by datn** [comment]
Should this list exclude all "sandbox" orgs?

**Comment by brittag** [comment]
I'd recommend including a list of sandbox orgs, since that serves our purpose of having a sense of who we're working with and what they need. People using sandbox orgs don't need migration of services for those orgs (for example), but they still need communications, etc.

**Comment by datn** [comment]
Document shared with Britta, Diego and John B. Please let me know if you need it modified -- script to be checked in shortly.

**Comment by brittag** [comment]
Yay thanks! I moved it over to our cloud.gov team folder so that other team members can see it as well (since we'll likely be collaborating with others); it's [over here](https://docs.google.com/spreadsheets/d/1vvRrkrPctG7qmCOP_vc7eXzWBWfqeWoxqbqPzAH4Iwo/edit).

**Comment by datn** [comment]
Great! Wasn't sure who to share it with, so thanks for sharing it appropriately :)

**Comment by brittag** [comment]
I estimate that in order for this to be usable for our next steps, we'll need to keep this open until we list who is the key contact + list whether they have technical labor funding+staffing, so I'll reopen it for now. We may need to reassign it for that info (it's also ok with me if we consider that a new story).

**Comment by brittag** [comment]
(Also I made a new tab of the spreadsheet for turning this into more human-usable info, without messing with the nice tidy info straight from CF.)

**Comment by datn** [comment]
Didn't mean to close it -- sorry about that!

**Comment by datn** [comment]
This info can be regenerated at a moment's notice using [this script](https://github.com/18F/cg-scripts/blob/master/cf-orgsinfo.rb).

**Comment by datn** [comment]
@mogul points out that the services call in this script shows *available* services, not used services. While we probably want a deeper analysis of app usage (cf. #247), we should at least develop this initial list based on actual app usage. I'm reworking the script to show only services with a service binding.

**Comment by jbarnicle** [comment]
@brittag I think this issue overlaps and is adequately covered by the spreadsheet produced in https://github.com/18F/cg-product/issues/247.  Can we close?

**Comment by brittag** [comment]
@jbarnicle What's the current link to the spreadsheet produced by #247? (I checked those comments but wasn't quite sure.) That would be nice to have in these comments for the record (in case somebody finds this issue while looking for it). Then I think we can close it!

**Comment by jbarnicle** [comment]
@brittag Here is the last one that I ran - https://docs.google.com/spreadsheets/d/1Ur3ciaTrrlriJ5HNsGLyBgaWDLjcFZutxqWuB4fVSJg/edit#gid=580587808

**Comment by brittag** [comment]
@jbarnicle OK! I moved that to the [cloud.gov team folder](https://drive.google.com/drive/u/0/folders/0Bx6EvBXVDWwheUtVckVnOE1pRzA) so that it's easier for other people to find. I see there are a couple earlier iterations of this document in that folder as well - up to you how you want to manage them.
