### ISSUE TITLE
Create plan for migrating service: cdn-route

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#232]
In order for our cloud.gov team to help our users migrate, we need to figure out how each service will get migrated.

Write down:
* This is what you have to do to migrate it now without tools

Evaluate:
* Can we expect users to do that?

Evaluate:
* Do we need to build a tool?

Acceptance criteria:

- [ ] We have a tenant-friendly written document somewhere that explains this.
- [ ] This document has been vetted by an Atlas team member as usable and workable.
- [ ] We've filed next steps as GitHub issues.

**Comment by afeld** [comment]
Just as easy to set this up from scratch, so closing.
