### ISSUE TITLE
Create plan for migrating service: elasticsearch

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#233]
In order for our cloud.gov team to help our users migrate, we need to figure out how each service will get migrated.

Write down:
- This is what you have to do to migrate it now without tools

Evaluate:
- Can we expect users to do that?

Evaluate:
- Do we need to build a tool?

Acceptance criteria:
- [ ] We have a tenant-friendly written document somewhere that explains this.
- [ ] This document has been vetted by an Atlas team member as usable and workable.
- [ ] We've filed next steps as GitHub issues.

**Comment by suprenant** [comment]
Noting that we'll only do this if a concrete need arises.

**Comment by suprenant** [comment]
We currently have no way to migrate this. We'll monitor and, if needed, develop an approach, though this will likely take a fair amount of work to figure out.

**Comment by mogul** [comment]
No longer necessary.
