### ISSUE TITLE
Create plan for migrating service: redis

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#234]
In order for our cloud.gov team to help our users migrate, we need to figure out how each service will get migrated.

Write down:
- This is what you have to do to migrate it now without tools

Evaluate:
- Can we expect users to do that?

Evaluate:
- Do we need to build a tool?

Acceptance criteria:
- [ ] We have a tenant-friendly written document somewhere that explains this.
- [ ] This document has been vetted by an Atlas team member as usable and workable.
- [ ] We've filed next steps as GitHub issues.

**Comment by afeld** [comment]
This is low priority, because data in Redis is normally considered ephemeral, or at least short-lived.

**Comment by suprenant** [comment]
[@James Scott] can you tell us the status of this one if you have information here? I'm having a hard time by looking at this issue if this is work that is done, needs to be picked up, or should be iceboxed.

**Comment by jmcarp** [comment]
My unsolicited opinion is that this should be iceboxed for the reason listed above:

> because data in Redis is normally considered ephemeral, or at least short-lived.

**Comment by jcscottiii** [comment]
Let's Icebox it for now. Only one app requested something like this. I think Gilbert said it was Hubot? (We did something hand propped for it) For the same reasons as Josh mentioned, not sure why it was used as a primary datastore since redis is used as temporary usually.

**Comment by mogul** [comment]
No longer necessary.
