### ISSUE TITLE
Document process for migrating s3

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#235]
In order for our cloud.gov team to help our users migrate, we need to figure out how each service will get migrated.

Write down:
- This is what you have to do to migrate it now without tools

Evaluate:
- Can we expect users to do that?

Evaluate:
- Do we need to build a tool?

Acceptance criteria:
- [ ] We have a tenant-friendly written document somewhere that explains this.
- [ ] This document has been vetted by an Atlas team member as usable and workable.
- [ ] We've filed next steps as GitHub issues.

**Comment by afeld** [comment]
This can likely be accomplished via the AWS CLI, or a very simple script around it.

**Comment by suprenant** [comment]
Noting that we'll only do this if a concrete need arises.

**Comment by suprenant** [comment]
From grooming –we're seeing this come up fairly often, so documenting what this would take would be helpful.

**Comment by mogul** [comment]
No longer necessary.
