### ISSUE TITLE
Help users manage the transition to .fr.cloud.gov

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#237]
- DNS users get separate guidance; not in scope here!
- Explain the plan to the users (eg that eventually the .fr will be dropped from their URLs)
- help them replace their *.apps.cloud.gov apps in E/W with a tiny redirect app that we provide (eg looks at env var to figure out what the correct URL in the FR environment is, and then sends a 301 redirect to that location)
## Acceptance criteria

There is a page that explains the following about the migration:
- [ ] The criteria (blockers) to move
- [x] The path - https://github.com/18F/cg-site/pull/480
- [x] The expected level of effort - https://github.com/18F/cg-site/issues/487
- [ ] The level of support from the cloud.gov team
- [ ] The timeline/deadlines - https://github.com/18F/cg-product/issues/403

**Comment by afeld** [comment]
> the .fr will be dropped from their URLs

Hmmm, this seems like it will be a hard transition to make. What if we made domains `*.app.cloud.gov` for GovCloud?

**Comment by afeld** [comment]
Bumped up the priority of this story, since @jameshupp said he'd like to link _somewhere_ from [the initial broadcast message](https://github.com/18F/cg-product/issues/238). There will likely be more detailed stories that come out of this for filling in details.

**Comment by afeld** [comment]
This has been split out to more specific issues.
