### ISSUE TITLE
Track which projects are lagging behind in E/W -> GovCloud transition

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#239]
In order for our E/W -> GovCloud migration to work smoothly, we need to figure out who's lagging (who hasn't completed their transition) and see if we need to help them or otherwise call in support.

At some point in the process, for each tenant we need to check signs like:
- Have they created a GovCloud account?
- Have we heard anything from them?

We can track this in our tenants list (https://github.com/18F/cg-product/issues/229).

This task needs more grooming/planning.

**Comment by datn** [comment]
I agree with others' assessment that this is a task for down the line a bit, but as I envision it, this would involve a small tool that enumerates and connects the same client's assets/services/state on both E/W and GovCloud, making it clear what is missing on the target side.

**Comment by afeld** [comment]
I think this is going to be somewhat obvious as we see what issues remain open in https://github.com/18F/cg-migration/issues over time. Closing for now, unless we think something is needed on top of that.
