### ISSUE TITLE
PI7 FedRAMP JAB TR remediations

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#243]
What we're after: Points raised by the FedRAMP JAB TRs as blocking P-ATO authorization of cloud.gov are resolved

Benefits/why:
- FedRAMP JAB Authorization is the key to removing the barrier to adoption by agencies

**Comment by mogul** [comment]
We're waiting on more information from the JAB TR on the [additional remediation points they raised](https://docs.google.com/document/d/1I3khQhNNwAsZBLOsbZvQ3g_4CVeSwDF6PObhpuAPVFc/edit) before creating additional issues here.

**Comment by brittag** [comment]
Closing this since this is old - anything current is in the PI8 epic: https://github.com/18F/cg-product/issues/379
