### ISSUE TITLE
Analyze all platform logs with severity warn and error

### ISSUE THREAD

**Issue by s-matyukevich** [18F/cg-product#245]
Currently our monitoring dashboard tells that Cloud Controller component constantly generates a few error and warn messages. I don't have access to all logs, but I suspect that other components do the same. 

What we can do is the following:
1. Classify all error and warn messages generated by the platform. This will split all error messages by classes, where all similar errors will belong to the same class.
2. For each error message class we should provide a resolution by either making some configuration change, or making PR to the upstream, or adding this error class to the list of know errors.
3. We should generate pager duty alert, in case if an error occurred, that don't belong to the list of known error.

**Comment by sushiandbeer** [comment]
I agree.  We should look for and address warnings and errors for all platform components.

**Comment by sushiandbeer** [comment]
We should make sure bosh and its components are included, in addition to all other services provided (k8s, logsearch, etc.)

Related: https://github.com/18F/cg-atlas/issues/106
