### ISSUE TITLE
Service usage inventory by org

### ISSUE THREAD

**Issue by datn** [18F/cg-product#247]
In order to effectively focus our efforts in creating migration assistance materials, Squad 2 wants an inventory of which services+plans are used the most and who we can talk to about them.

**Acceptance Criteria**

- [x] We can easily identify which services+plans are instantiated the most
- [x] For a given service+plan, we can identify org+space in which it's used
- [x] For a given space, we can identify who to talk to about the services inside it (eg the set of people with SpaceDeveloper or SpaceManager roles)
- [x] It should be possible to annotate the information for purposes of further communication/tracking 

**Implementation ideas**

CSV-based:

- [ ] We'll generate a CSV with one line per service instance binding and import it into a spreadsheet
  - [ ] Can we generate this directly from a DB rather than traversing the API?
- [ ] For each service instance, we'll include the `org, space, app, service+plan, set of Space[Managers|Developers]`
- [ ] To make it easy to answer the questions in the ACs, we'll make some pivot tables in other tabs that render the raw data into a higher-level form

cf #229 .

**Comment by datn** [comment]
Question for the team: how will we take user-provided service instances into account in our migration planning?

**Comment by datn** [comment]
Okay, I got the word -- we don't need to take user-provided service instances into account.

I'm mostly done with this work, but I'm unclear on exactly what information from this API call will be useful to the team: https://apidocs.cloudfoundry.org/240/service_plans/list_all_service_plans.html

**Comment by datn** [comment]
Script to date committed to branch respect_service_bindings [here](https://github.com/18F/cg-scripts/pull/20).

**Comment by mogul** [comment]
@datn: 

> Question for the team: how will we take user-provided service instances into account in our migration planning? 

Their content is completely owned by the customer, and ordinarily I'd say that's reason enough that they would need to set it up again in the new environment. However, I think we have the actual UPS content in the DB, so it may be something that we can auto-migrate over! It's probably a separate story from the regular services; want to create a separate issue in the backlog?

**Comment by mogul** [comment]
@jbarnicle: I took a look at [two](https://docs.google.com/spreadsheets/d/1Ur3ciaTrrlriJ5HNsGLyBgaWDLjcFZutxqWuB4fVSJg/edit?ts=57c8653f#gid=1045067861) [sheets](https://docs.google.com/spreadsheets/d/1edJzZC3DjcsZj2UZ-mMxrz7QKP71fC48yW-5gIoY25M/edit#gid=1984181281) I had open in my browser. I'm not sure what link I followed to open them or what the difference between them is although at first glance they look identical. 

Review points:

- I'm seeing a lot of `,,` among the OrgManagers and SpaceManagers... Seems like that's likely a bug.
- We need to see SpaceDevelopers rather than SpaceManagers... They're the ones who are responsible for manipulating apps and services in a space and therefore the ones to talk to.
- The data looks like it will be useful, but I can't really tell until I see some pivot tables based on it that help us answer the questions in the ACs above. Give me a DM if you have trouble figuring out how to set those up.

**Comment by jbarnicle** [comment]
@mogul That SpaceManagers column is mislabeled - those are actually SpaceDevelopers (I don't think there is a role SpaceManager).  I'll fix that.   I'll also look into the `,,` issue.

WRT to pivot tables - I might need a little input on what's needed there.  I think the data is there to support the acceptance criteria - but there are definitely opportunities to present it in a more clear fashion.  It would be nice to filter out dev / stage and other org data that is clearly not part of the migration plan.

**Comment by jbarnicle** [comment]
@mogul I made the following changes to the script and reloaded the data
- fixed `,,` issue by ignoring OrgManager / SpaceDeveloper entries without a username
- removed spaces that were obviously non-prod
- sorted the data by org
- removed any services columns that had no instances
- corrected SpaceDeveloper heading and added column for SpaceManagers

I think it's fairly straightforward to glean the data from the existing sheet
- _We can easily identify which services+plans are instantiated the most_
  - Instance totals are summed at the bottom of each column
- _For a given service+plan, we can identify org+space in which it's used_
  - Instance usage is totaled for each org+space in the service plan column
- _For a given space, we can identify who to talk to about the services inside it_
  - Space Developers / Space Managers are listed per space when available
- _It should be possible to annotate the information for purposes of further communication/tracking_
  - The google sheet is editable

Let me know what you think.

**Comment by mogul** [comment]
If we're talking about [this file](https://docs.google.com/spreadsheets/d/1Ur3ciaTrrlriJ5HNsGLyBgaWDLjcFZutxqWuB4fVSJg/edit?ts=57c8653f#gid=580587808), LGTM. 

So the information we learned is that this is the order we should be prioritizing our efforts to document/make tools:

- 26 RDS Database Broker : shared-psql	
- 13 Redis 2.8 service for application development and testing : standard	
- 9 Amazon S3 is storage for the Internet. : basic	
- 9 Elasticsearch 1.7.1 : 1x	
- 4 RDS Database Broker : shared-psql	
- 3 RDS Database Broker : medium-psql	
- 3 MySQL 5.6 service for application development and testing : standard	
- 2 MongoDB service for application development and testing : free	
- 2 MongoDB 2.6 service for application development and testing : standard	
-  1 Elasticsearch 1.7.1 : 3x	
- 1 Redis 2.8 service for application development and testing : free	
- 1 RDS Database Broker : shared-mysql	
- 1 CouchDB 1.6 service for application development and testing : free	
- 1 Elasticsearch 1.7.5 : 3x	
- 1 RDS Database Broker : micro-psql

...and we have a list of people we can talk to for feedback/testing on them as we go.
