### ISSUE TITLE
idp.cloud.gov users can reset their own password

### ISSUE THREAD

**Issue by LinuxBozo** [18F/cg-product#249]
In order to ensure password reset functionality for users without their own IDP, we need to provide a password-reset UX via idp.cloud.gov

**Acceptance Criteria**
- [x] Allow for users to reset password easily, like when is about to or does expire.
- [x] Create email flow for allowing users to reset a forgotten password.

**Implementation sketch**
-

**Comment by mogul** [comment]
Does UAA actively thwart its own password reset flow when the origin is not `uaa`? I suspect it will, and this might result in some curious messages for users (eg "your password is not managed via cloud.gov; talk to your identity provider") unless we support a separate password-reset flow on the cloud.gov IDP.

**Comment by LinuxBozo** [comment]
@mogul You have it correct. Hence the need for this alternative.

**Comment by suprenant** [comment]
@rogeruiz @LinuxBozo checking in here. Do y'all have a rough idea of when this might fall into the PI? 

From reviewing Mural, it looks like it could possibly be toward Sprint 4, but – whenever it happens – please give us Navigator folks a heads-up before you'll want us to pick this up so we can make sure to allocate time.

**Comment by jbarnicle** [comment]
@suprenant It's looking like we will likely start picking up this work Sprint 3.

**Comment by suprenant** [comment]
@jbarnicle got it, good to know, thanks – let's keep in touch so we can figure out the best way for us to support this on the Navigator side.

cc @thisisdano @vz3 @msecret @line47 @adborden

**Comment by suprenant** [comment]
@jbarnicle we're starting in on this sprint. If you'd like our support on this, let's set up a half hour to talk about what might be needed here.

**Comment by LinuxBozo** [comment]
@suprenant initially, I'm not sure we'll need quite as much time from Navigator as first thought on the MVP. We'll be rolling this functionality into the invitation app which already has pretty standard look/feel which was can leverage. 
However, given we do have the MVP of the cloud.gov IdP in production, it would be worthwhile to go through that process of invitation, to acceptance, etc, of a non-GSA email (like a gmail account) and figure out what would be good design changes. Much of that is stock `shibboleth` views with just a logo change.

**Comment by jbarnicle** [comment]
Adding to the formerly invite app which is now cg-uaa-extras

**Comment by jbarnicle** [comment]
Forgot password is working - reset password work is in progress.

**Comment by jbarnicle** [comment]
Ran across this issue when testing the change password functionality 

https://github.com/18F/cg-uaa-extras/issues/56

**Comment by jbarnicle** [comment]
We should disable the existing `uaa` for password reset

https://github.com/18F/cg-uaa-extras/issues/57

**Comment by mogul** [comment]
@LinuxBozo says the bug mentioned above is fixed. The password reset will be taken care of when we do design changes on the login page.

**Comment by jbarnicle** [comment]
Verified that the bug is fixed - closing.
