### ISSUE TITLE
UAA-SAML users know how to reset MFA token if lost/stolen

### ISSUE THREAD

**Issue by LinuxBozo** [18F/cg-product#250]

**Comment by rogeruiz** [comment]
This will require updating the TOTP plugin to allow for reseting the MFA. We will also need to have backup codes to allow user to get access to reset their token.

**Comment by rogeruiz** [comment]
We're saying that this is not necessary for MVP.

**Comment by mogul** [comment]
We're saying now that MVP includes (1) documenting how admins can help users who have this problem (including verifying them as humans) and (2) ensuring users know when and how they should contact admins.

**Comment by LinuxBozo** [comment]
@brittag btw, here's the issue we discussed about what happens when folks lose their token

**Comment by rogeruiz** [comment]
We're waiting on feedback from the BU (cc @khandelwal) to make updates to [our documentation](https://cloud.gov/docs/getting-started/accounts/) to address @mogul's points from Dec 21, 2016.

**Comment by mogul** [comment]
We're good here now per https://cloud.gov/docs/getting-started/accounts/#if-you-can-t-access-your-token-codes
