### ISSUE TITLE
Take a look at sandbox account use

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#251]
Can we develop insights about our users from this?
(came up during 8/23/16 meeting w Bret, Britta)

**Comment by berndverst** [comment]
The answer is definitely yes, but I'm not sure what we are trying to accomplish.

@nikzei do you want to add more information or close this issue?

**Comment by nikzei** [comment]
This is a research task that will give us information that will be useful for our future outreach. We're hoping that someone from the Atlas team will be able to write a script to export the following data:

- provide every name and owner address of every sandbox account;
- number of applications deployed to that sandbox;
- for each application, the build pack and the number of instances and memory used, last modification (e.g. deploy, change to number of instances, etc)

e.g.
```
org: gsa-sandbox
   sandbox: bernd.verst@gsa.gov-sandbox
      owner: bernd.verst@gsa.gov
      num_applications: 1
      applications: [
         "bernds_app": ["java", 5, 512]
         "last_modified": "09/18/2016"
      ]
```

**Comment by nikzei** [comment]
@mogul, we're dropping this in the Atlas backlog but let me know if there is a better way to handle this.

**Comment by mogul** [comment]
OK, we'll take a look at it. Any particular deadlines or other blocked tasks waiting on it?

**Comment by nikzei** [comment]
Nope, @mogul, this doesn't block anything for us other than potentially having new insights to share with everyone and to shape upcoming outreach. Thanks!

**Comment by mogul** [comment]
We're `Icebox`'ing this as it seems people have been able to get what they need out of the admin UI, exports from there, and custom filtering in a spreadsheet. Besides which, we want to get rid of long-lived sandboxes as a thing.
