### ISSUE TITLE
present Compliance Masonry to GSA Senior Management

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#253]
[Slides](https://docs.google.com/presentation/d/1l8i9I0BeFJjQiMlW2-0Oo4U4lAY00g5IFuRWD2u9ZE4/edit)

---

Presentation is 8/30 3-4:15pm ET for 15-20 minutes.

My first attempt at explaining Masonry to a compliance-literate audience, which I'll be translating into the presentation:

https://docs.google.com/a/gsa.gov/document/d/1mNV7yzrorBF4YD9uIOr75KOPCrta8eMkk0Gf8edhyZs/edit

The slide deck template:

https://docs.google.com/presentation/d/1XSOsPNV0K38Ftiw3KLCvPH1LRh9jeZCQiLU5IyxkiZ0/edit#slide=id.g1572d11920_0_82

## TODOs

* [x] Determine whether we can have slides outside of the two in the template
* [x] Come up with some metrics

**Comment by afeld** [comment]
Per @brittag:

> it took me 1 hour to update our CIS

https://18f.slack.com/archives/cg-squad-3/p1472147289000022

and @mogul pointed out that the CIS is immediately out-of-date once it's updated.

**Comment by brittag** [comment]
(The CIS worksheet is out of date as soon as I go update more controls in the SSP.)

**Comment by mogul** [comment]
Link to the [slides-in-progress](https://docs.google.com/presentation/d/1EmiSXj9PnCnc3AX5V99arBFILI3gqy-7CtZaFq1iXDE/edit#slide=id.g15dfa23e63_2_64).

**Comment by nikzei** [comment]
I'm wondering if you can start off with a quick mention of the broader problem that cloud.gov addresses and then introduce masonry in the context of how it fits within. Even with a compliance-literate audience, making sure that everyone is on the same starting page might be worthwhile and might give you a better foundation to show how masonry is important in a larger context (I put notes in the document but to reiterate here).

**Comment by afeld** [comment]
Fixed the link to the slides above.

**Comment by afeld** [comment]
Didn't end up happening 😢 Ah well!

**Comment by nikzei** [comment]
Sounded to me like it might happen in 6 weeks or so? In which case, should we leave this one in ready in case the meeting gets rescheduled and you want to grab it and do a little bit more prep?

**Comment by afeld** [comment]
Let's re-open when/if the date gets confirmed. And yes, more prep would be great :grin: 

/cc @wslack
