### ISSUE TITLE
Sprint 27: unplanned work

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#254]
## Drop comments below so that we can track our whitenoise (unplanned work that takes less than 1 hour to complete).

People from different squads have mentioned that they sometimes get pulled off what they're working on to help out with other projects. It's great for folks to help each other out, and it's important for folks on the team to find space for flow while they work. We want to make sure that we are creating space for both.
 
To this end, we'd like to keep track of unplanned work. 2 options:

- Does it take less than an hour to do? In which case, it's not worth the overhead (to create a card, groom it, set acceptance criteria and put it on the board) but still worth noting it here in a quick comment. --> it's whitenoise. write a comment below in this issue noting the unplanned work.

- does it take an hour or more? --> make an issue in the board.

**Comment by suprenant** [comment]
Is this issue still useful? The idea seems helpful, but it's been sitting on the same place in the board for a month. 

Maybe this information is better suited for one of our process documents rather than an issue on the board?

cc @nikzei @mogul

**Comment by mogul** [comment]
We've got enough process in flight that it's hard to get people to use this
habitually. I'd say let's kill this and just double-down on getting team
members to put up cards for anything that crosses the white-noise
threshhold (more than an hour of work/attention) when distractions are
mentioned in standups.

On Thu, Sep 22, 2016 at 10:50 AM, Andrew Suprenant <notifications@github.com

**Comment by suprenant** [comment]
OK, closing this up
