### ISSUE TITLE
marketing our prototyping account

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#257]
Prototyping accounts are good for agencies that want their dev teams to get familiar w cloud.gov while we're awaiting JAB authorization. Start by reaching out to users of our free sandbox accounts and see if they want to upgrade to prototyping. (sandbox accounts set up by cloud-gov-support@).

**Comment by berndverst** [comment]
So is this a sales activity for up-selling?

**Comment by nikzei** [comment]
We want to market at all levels, but certainly need basic marketing for this level of account, particularly in prep for sending email out to our inquiry list encouraging prototyping accounts as an intro to the product.

**Comment by nikzei** [comment]
Prototyping accounts  = sandbox + the ability to create multiple spaces for different projects + access to more than 1GB of data, yes? @bernd and I hypothesize that this is less of a customer segment for us to focus on than prospective sandbox users (helping the curious enter the stream) and prospective FISMA package users.

Let's have a quick team conversation about what we want to do with this, and then close this.
@dlapiduz @mogul @jameshupp

**Comment by mogul** [comment]
> Prototyping accounts = sandbox + the ability to create multiple spaces for different projects + access to more than 1GB of data, yes?

Prototyping basically gives them a new prototyping org, an OrgManager role in that org, access to paid managed services, and the ability to increase the quota available to the org.

**Comment by nikzei** [comment]
Do we need to make a concerted effort marketing this level or are we ready to close this issue @mogul?

**Comment by dlapiduz** [comment]
@nikzei I think the point of the prototyping account is not _just_ to get a bit more resources in terms of cloud.gov but the ability to offer agencies a place to host apps during development phases so they can make a switch to a full plan easily.

I think it as a stepping stone and if we offer it "office"/"team"/"agency" wide we can get a foot in the door since the early stages and offer a place for people to try things out.

What do you think?

cc @mogul @berndverst

**Comment by nikzei** [comment]
Ok, maybe that's the messaging then @diego. Am I understanding correctly that the benefit of using a prototyping account over a sandbox is less about what it's like *using* the account (for that experience, the sandbox would be fine), and more about being able to start working in the environment that they will eventually use when they get a FISMA plan; so the switch over is fast and easy? I can see this being a selling point, potentially - paying for this account (rather than working in the sandbox for free) because I'll save on labor later on?

**Comment by mogul** [comment]
The benefit of the prototyping plan is that you get OrgManagers who can
see/manage access and raise the quota for the org beyond 1GB/user, and they
can use paid managed service plans.

**Comment by nikzei** [comment]
Let's make sure to discuss the value of prototyping accounts on the page where we discuss the different types of access packages that we offer (we need to create this page! Currently, we only talk about our different packages [in the context of how much they cost](https://cloud.gov/overview/pricing/rates/). We should consider having a page where we describe the value proposition for each package). 

I'm noting this in #346 and closing this issue.
