### ISSUE TITLE
Adequately document IA controls in SSP

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#261]
In order for compliance reviewers to understand our system, we need to update this family of control statements to explain our system (and policies and procedures) in more precise and thorough detail.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

* [IA Google Doc](https://docs.google.com/document/d/14hcnX4JPlehBO3QjL56zyD3dwzvPERF9Kb4_wQ3gpqU/edit)

**Acceptance criteria**

Overall:
- [x] "Not applicable" is changed to "Implemented" where suitable, including if our implementation is that we delegate auth to agency SSO. [PMO comments]
- [x] We clearly mark and document Customer Responsibility in any control where that's part of how cloud.gov implements the control. Figure out whether "cloud.gov PaaS access" should be renamed to "Customer Responsibility" in most cases, or otherwise rephrased/reframed to explain what cloud.gov customer responsibilities are. [PMO comments]
- [x] In general when appropriate, control statements talk about how we implement the requirements for all our major families of account types (AWS, cloud.gov PaaS, GitHub).

IA-1:
- [x] IA-1 control statements are updated to reflect 18F/cloud.gov policies and procedures. This depends on https://github.com/18F/cg-compliance/issues/179 [SRTM low (row 61, 64)]

IA-2 (1)
- [x] The sentence explaining "18F implements the use of multifactor authentication (MFA) to add an extra layer of security for login access to its GitHub Repository and Slack communications channel account." is expanded to include details about how we do this (or reference other parts of the SSP where we explain this, such as in AC). [PMO comment]

IA-2 (11):
- [x] Empty parameter (Parameter IA-2(11)) is filled out with something that makes sense.
- [x] Statement is updated to explain how we fulfill the requirement for our AWS and GitHub accounts (to reflect SRTM notes). (We can ask our ISSO or PMO for help interpreting what this requirement means.) [SRTM low (row 67)]

IA-5 overall (find appropriate places within this control to add these details):

- [x] We have detailed documentation about the ways that external and internal users authenticate with cloud.gov, and that this documentation discusses that, "cloud.gov system doesn't autocomplete passwords after a user types a few characters (users need to type in their whole password, or use a password manager application on their computer (or the password manager feature of their browser) to input the whole password.)" [JAB Comments]

- [x] Our "use of password managers is documented well." [JAB Comments]

- [x] It provides an explanation (or link to an explanation on docs.cloud.gov) for when we use Fugacious, what kind of data should go through it, and what configuration should be used. Explain that Fugacious runs inside the cloud.gov security boundary. [JAB Comments]

- [x] It explains that "[p]er NIST guidance, at e-Auth level 3, in-person identity proofing is required. Identifying attributes must be verified by an authorized representative of the CSP through examination of physical documentation as described in SP 800-63A." [JAB Comments]

- [x] It explains that "managing the strength of authenticators for Cloud.gov platform access using agency credentials is the responsibility of the agency and not the organization." [SRTM]

- [x] It provides artifacts that document our process of protecting authenticators from "unauthorized disclosure and modification.

Specific parts of IA-5:

- [x] IA-5.c explains our authenticator requirements and how we ensure that administrator passwords are strong. [SRTM moderate (row 20)]

- [x] IA-5 (d) includes specific details for "GSA has policies and procedures for appropriately handling situations where GSA smartphones are lost or stolen." such as the name of the policy/procedure or where to find it. [PMO comment]

- [x] IA-5.d.1 documents that we've developed, documented, and implemented administrative procedures for initial authenticator distribution. [SRTM low (row 80)]

- [x] IA-5.d.2 documents our administrative procedures for lost/compromised or damaged authenticators. [SRTM low (row 81)]

- [x] IA-5.d.3 documents our administrative procedures for revoking authenticators. [SRTM low (row 82)]

- [x] IA-5.h documents our process to protect authenticators from unauthorized disclosure and modification. [SRTM moderate (row 21)] 

- [x] IA-5.i.2 documents our process to protect authenticators using device specific security safeguards. [SRTM moderate (row 23)]

IA-5 (3)

- [x] IA-5(3).1 documents which authenticators require authenticators that need to be received in person/by trusted 3rd party. [SRTM moderate (row 40)]

- [x] IA-5(3).1 documents how we ensure strong passwords for administrator accounts: a list of mandatory criteria for passwords is listed in SRTM, row 40 (see https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=2114760911). [SRTM moderate]

- [x] IA-5(3).2 documents where we've defined the registration authority with oversight of the authenticator registration process. [SRTM moderate (row 41)]

- [x] IA-5(3).3: documents where we've defined personnel/roles responsible for authorizing organizational-defined registration authority? [SRTM moderate (row 42)]

- [x] IA-5(3).4 documents that we've defined whether registration must happen in person or by trusted 3rd party. [SRTM moderate (row 43)]

- [x] IA-5(3).5 says that the registration process must be conducted in person or by trusted 3rd party w auth by defined personnel or roles. [SRTM moderate (row 46)]

IA-5 (6):

- [x] IA-5(6).1 documents our process to protect authenticators, including showing how it is commensurate with the security category. [SRTM moderate (row 51)]

IA-5 (11):

- [x] IA-5(11).1, defines how the token quality requirements are satisfied. [SRTM low (row 90)]

IA-8 (3):
- [x] "GitHub and AWS: Non-organizational users do not have privileged access to GitHub or AWS." is updated to make more sense. [PMO comment]

**Implementation guidance**

During grooming, take items from the following and list them as specific tasks above.

- [x] [Required JAB reviewer items](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) ([additional notes here](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit))
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "moderate" differential (if not already marked green there).
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "low" differential (if not already marked done there).
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our ISSO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [ ] ~Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our PMO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.~ **Noah:** I read their comments, I'll pick this up as I do final edit and review.
- [x] Any relevant notes in the [SSP check working space](https://docs.google.com/document/d/1k-qiOF66o4ssBr6kEO_akaGNsku2zt2jrcawZGg7ZsA/edit#)
- [x] Check that control origination statements make sense (look for [notes here](https://docs.google.com/spreadsheets/d/1Yxt1mMZAdSyKt2OGY1qdkkfZhBiKV6ZuD7sZPKxikuQ/edit#gid=600210940) and look through the controls); if you change a checkbox, make a note in that spreadsheet.

**Comment by brittag** [comment]
This is partially blocked on https://github.com/18F/cg-compliance/issues/179, but a bunch of these can be sorted out before we finish that project - for example, we can write up Fugacious documentation. I'd be happy to help identify those; let me know if I can help.

**Comment by brittag** [comment]
- [ ] IA-5 (d) needs more information about cloud.gov offboarding.

**Comment by brittag** [comment]
Notes about additional progress that should happen:

- [ ] IA-4's various parts need more revising to be more consistent. For example, c, d, and e all need information about all three major relevant account types (AWS, cloud.gov, and GitHub).

- [ ] Throughout these controls (and probably throughout the SSP), we should standardize how we refer to cloud.gov PaaS / Customer Responsibility. Possible way to standardize:

> **cloud.gov PaaS (including Customer Responsibility):**
> Team: cloud.gov delegates authentication for team members to the GSA single sign on system.
> Customers: cloud.gov delegates authentication to customer-provided single sign on (SSO) systems.

**Comment by brittag** [comment]
Issues identified while working on this so far, which may need their own stories:

* IA-2 (11): we need a team policy that we need to have our MFA running on GSA devices, and possibly that we have to use Google Authenticator.

* https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md#atlas-specific-items-1 "Grant them access to the following (where applicable): AWS, New Relic, PagerDuty, StatusPage” needs more detail about what our actual policy/procedure is (including specifically about AWS and PagerDuty). In general, we need to write out more detail in the Onboarding Checklist about how people get access to things including GitHub.

* We need a Fugacious policy somewhere in the 18F or cloud.gov docs.

* We probably need a policy that cloud.gov team member need to have stronger GitHub passwords than the GitHub default requirement ("Use at least one lowercase letter, one numeral, and seven characters.”).

* We need a cloud.gov offboarding checklist.

* We need to require cloud.gov team members to use password managers.

**Comment by NoahKunin** [comment]
Seems like I have the ability to make any needed new policies and properly document. Taking this over.

**Comment by NoahKunin** [comment]
Final notes before I close:

> IA-2 (11): we need a team policy that we need to have our MFA running on GSA devices, and possibly that we have to use Google Authenticator.

Nope, we shouldn't make this a requirement. Too brittle for audits.

>  In general, we need to write out more detail in the Onboarding Checklist...

Yes. We have an Off-Boarding Checklist already, I'm pretty sure we have an Onboarding one as well.

> We need a Fugacious policy somewhere in the 18F or cloud.gov docs...

On it. And this: https://github.com/fugacious/fugacious/issues/66

The rest will be caught up in my QA as well.

**Comment by brittag** [comment]
Yes, onboarding checklist is here: https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md
