### ISSUE TITLE
Adequately document AU controls in SSP

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#262]
In order for compliance reviewers to understand our system, we need to update this family of control statements to explain our system (and policies and procedures) in more precise and thorough detail.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

* [AU Google Doc](https://docs.google.com/document/d/1Kkzke1jv5y1hrGrvs9y6zMAAtddgvmUqHxGPiOzaSiA/edit#)

**Acceptance criteria**

AU-1:
- [x] Update this just like the other -1 controls.

AU-2 (3):
- [x] We've checked whether we're actually doing this right now, and updated this control based on whether this is a real actual thing or a planned thing. [ISSO comment]

AU-6:
- [x] Part a: Define the types of inappropriate or unusual activity to look for when information system audit records are reviewed and analyzed is not defined. [SRTM low]
- [x] Part b: Define a formal process to review the audit records/logs on a weekly basis, to report findings to organizational personnel, such as the system owner and ISSO. (Or mark this as planned.) [SRTM low]

AU-6 (1):
- [x] Define a formal process to review the logs. SRTM says "automated mechanisms are in place to enable administrator to conduct audit log reviews, however these reviews are not yet formalized"; add documentation to resolve that issue. [SRTM low]

AU-6 (3):
- [x] SRTM says "a formal process to correlate the records has not yet been put in place"; "automated mechanisms are in place to enable administrator to conduct audit log reviews, however the correlation of these logs has not yet been configured". Add documentation to resolve these issues or mark as planned. [SRTM low]

AU-9:
- [x] This is marked as Implemented rather than Planned. Check whether we're actually doing this already, and update accordingly. [ISSO comment]

AU-9 (2):
- [x] This is marked as Implemented rather than Planned. It includes details from the SRTM to reflect our implemented system. ("Cloud.Gov sends all audit logs to encrypted S3 buckets.") [SRTM low]

AU overall:
- [x] This family of controls may need information about how we scan/audit open source we ingest, such as reporting when the scans provide alerts of problems. Coordinate with people working on open source scanning + CM family work to see what support AU family should provide. (Look at AU family with CM family person and see what relevant details you can add to AU controls.) AU family should say *something* about open source code auditing, in any relevant control statements. [See JAB notes for context.](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit) [JAB item 8]
- [x] We've checked the rest of the AU controls to see if they make sense. For example, for all of the other ones marked "planned" - check if we've actually already implemented them, and update accordingly. Check that control originations and responsible roles make sense as well.

**Implementation guidance**

During grooming, take items from the following and list them as specific tasks above.

- [x] [Required JAB reviewer items](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) ([additional notes here](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit))
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "moderate" differential (if not already marked green there).
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "low" differential (if not already marked done there).
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our ISSO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our PMO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Any relevant notes in the [SSP check working space](https://docs.google.com/document/d/1k-qiOF66o4ssBr6kEO_akaGNsku2zt2jrcawZGg7ZsA/edit#)
- [x] Check that control origination statements make sense (look for [notes here](https://docs.google.com/spreadsheets/d/1Yxt1mMZAdSyKt2OGY1qdkkfZhBiKV6ZuD7sZPKxikuQ/edit#gid=600210940) and look through the controls); if you change a checkbox, make a note in that spreadsheet.

**Comment by brittag** [comment]
Moving this to In Progress since Dan is researching these things! (See his email from today for more info about what he's looking for.)

**Comment by mogul** [comment]
@datn is going to harmonize with related controls in IA and SI.

**Comment by datn** [comment]
Language has been harmonized with IA & SI as needed, and a couple of cross-refs added. I spent today wack-a-moling a bunch of comments.

Next steps are nailing down some of Britta's thornier observations relevant to areas outside those mentioned in the ACs above.

**Comment by datn** [comment]
I've put this doc in as good a state as I currently know how. Adding @rjbator as assignee for much-needed feedback and further comments.

**Comment by brittag** [comment]
Thank you so much @datn, this is looking good! I went though and accepted a bunch of the suggestions and refined a few of the statements. I'm moving this to Awaiting Acceptance!

**Comment by rjbator** [comment]
I have reviewed all of AU and left my comments/notes.

**Comment by NoahKunin** [comment]
Will resolve @rjbator's comments and accept.

**Comment by mogul** [comment]
Closing as "what we did on AU during PI7"; afawk AU is done.
