### ISSUE TITLE
Adequately document AT controls in SSP

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#263]
In order for compliance reviewers to understand our system, we need to update this family of control statements to explain our system (and policies and procedures) in more precise and thorough detail.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

The AT document is [this Google doc](https://docs.google.com/document/d/1b-nGAqwrIGnzk-h1Sd58U1lBfY728jWFi1pn3XKBgL0/edit).

**Acceptance criteria**

- [ ] AT-1 is updated to document our 18F/cloud.gov security awareness and training _procedures_, not just policies. This depends on https://github.com/18F/cg-compliance/issues/179 getting sorted out. [SRTM]

- [ ] All control statements are updated to include information about 18F-specific and/or cloud.gov-specific training policies and procedures, if the update to AT-1 requires this. [Source is Britta's instinct about what we need to do; there are only a few controls in this family, so this shouldn't be a big task.]

- [x] AT-2 is updated to explain GSA's anti-phishing training. This should include: that the 18F/cloud.gov team uses GSA phishing training due to being part of GSA and using GSA communication tools (specifically GSA Gmail); 18F/cloud.gov does not have a separate email system; as part of GSA, we are all required to take a proactive anti-phishing awareness training course. In general, explain the GSA procedures/process, and that this is a corp originated control. In general, include the name of the specific OLU training and any other specific relevant details. [JAB item 14]

**Implementation guidance**

During grooming, take items from the following and list them as specific tasks above.

- [x] [Required JAB reviewer items](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) ([additional notes here](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit))
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "moderate" differential (if not already marked green there).
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "low" differential (if not already marked done there).
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our ISSO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our PMO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Any relevant notes in the [SSP check working space](https://docs.google.com/document/d/1k-qiOF66o4ssBr6kEO_akaGNsku2zt2jrcawZGg7ZsA/edit#)
- [x] Check that control origination statements make sense (look for [notes here](https://docs.google.com/spreadsheets/d/1Yxt1mMZAdSyKt2OGY1qdkkfZhBiKV6ZuD7sZPKxikuQ/edit#gid=600210940) and look through the controls); if you change a checkbox, make a note in that spreadsheet.

**Comment by jbarnicle** [comment]
@brittag The only remediations I'm seeing are WRT to phishing training.  The CSP response was 

> The 18F/cloud.gov team uses GSA phishing training due to being part of GSA and using GSA communication tools (specifically GSA Gmail); 18F/cloud.gov does not have a separate email system. As part of GSA, we are all required to take a proactive anti-phishing awareness training course. We plan to document this in the SSP.

Is this your understanding as well - or am I missing something?

**Comment by brittag** [comment]
Thanks @jbarnicle, I went through and finished grooming this - the basic thing I did was add the AT-1 item from the SRTM. I also looked at the current state of the AT family and realized it'll need an overall update based on the AT-1 update. Moving this to ready.

**Comment by brittag** [comment]
Status of this one: AT-3 and AT-4 need research!

**Comment by NoahKunin** [comment]
I have the answers. Taking it from here.

**Comment by mogul** [comment]
Closing as "what we did on AT in PI7"; there's a followup issue https://github.com/18F/cg-product/issues/419
