### ISSUE TITLE
Adequately document CA controls in SSP

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#264]
In order for compliance reviewers to understand our system, we need to update this family of control statements to explain our system (and policies and procedures) in more precise and thorough detail.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

[CA Google Doc](https://docs.google.com/document/d/1LnjqxvB9QhY8xLFw2B-LAu0nsChldsul4c1dducqal4/edit)

**Acceptance criteria**

CA-1:
- [ ] Control statements are updated to include cloud.gov/18F _procedures_ as well as policies. This depends on https://github.com/18F/cg-compliance/issues/179. [SRTM low]

CA-3 (3) is filed separately here: https://github.com/18F/cg-product/issues/293

CA-7:
- [x] Control statements are updated to reflect our Continuous Monitoring Strategy. The latest version is [in this folder](https://drive.google.com/drive/u/0/folders/0B1cewEqKcWCbOG9SRmZEVjM3MDg) - use that as a reference. Each individual CA-7 control statement part should have a sub-heading noting whether that aspect is "planned", "partially implemented", or "implemented"; based on that status, the implementation status is updated to reflect the the appropriate mix of "planned", "implemented", and/or "partially implemented". Make sure any items that remain "planned" are filed as an issue somewhere, possibly on the issue at https://github.com/18F/cg-product/issues/290 to convert it to cg-docs. [SRTM moderate]

CA-8:
- [ ] The control statement sentence *"Penetration testing of the Virtual infrastructure is outside of the boundary for the cloud.gov. This includes services such as Amazon S3, CloudFront and Route 53 which are considered external services outside of a virtual private network."* prompted this question: *"If it is outside the boundary are we then implying it is n/a or just we can’t do it ourselves?  If the implication it is n/a due to it being a hosted offering then why go into the AWS pentesting specifics?"* This control statement should be updated to clarify the answer to that question. [ISSO comments]

CA overall, to check for common problems:
- [x] Verb tenses are correct - it uses past or present tense for things we've implemented, and future tense only for planned items.
- [x] Implementation statuses and control originations make sense.
- [x] Control statements explain which roles do which actions, generally using the formal role names listed in the Types of Users table. (Convert passive voice to active voice whenever possible.)

**Implementation guidance**

During grooming, take items from the following and list them as specific tasks above.

- [x] [Required JAB reviewer items](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) ([additional notes here](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit))
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "moderate" differential (if not already marked green there).
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "low" differential (if not already marked done there).
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our ISSO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our PMO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Any relevant notes in the [SSP check working space](https://docs.google.com/document/d/1k-qiOF66o4ssBr6kEO_akaGNsku2zt2jrcawZGg7ZsA/edit#)
- [x] Check that control origination statements make sense (look for [notes here](https://docs.google.com/spreadsheets/d/1Yxt1mMZAdSyKt2OGY1qdkkfZhBiKV6ZuD7sZPKxikuQ/edit#gid=600210940) and look through the controls); if you change a checkbox, make a note in that spreadsheet.

**Comment by jbarnicle** [comment]
The CA document is ready for review @rjbator

**Comment by rjbator** [comment]
I have reviewed all of CA and made several comments and revisions.

**Comment by brittag** [comment]
From my perspective, current blockers to moving this to "closed":

* CA-1 needs work, like all our other -1 controls.
* Parameter CA-7(g)-2 has a question that needs to be answered.
* I'm not sure if our approach to CA-7 is right - not sure if we need to include more summary info in those statements.
* CA-8 is confusing to me since I don't know how to interpret whether AWS qualifies as a "connection to other external systems". I'm not sure how to evaluate or resolve CA-8.

**Comment by NoahKunin** [comment]
Third bullet is resolved (it isn't) and I'll answer the rest.

**Comment by NoahKunin** [comment]
I'll also do final checks on this: https://github.com/18F/cg-product/issues/293

**Comment by mogul** [comment]
Closing as "what we did on CA during PI7"; afawk CA is done.
