### ISSUE TITLE
Adequately document CM controls in SSP

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#265]
In order for compliance reviewers to understand our system, we need to update this family of control statements to explain our system (and policies and procedures) in more precise and thorough detail.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

* [CM Google Doc](https://docs.google.com/document/d/1xpDOLtcq30nMjNvizqq_W-k3hssvcAqiwzJeVkFpYTc/edit)

**Acceptance criteria**

CM-3, CM-8, and any other relevant CM control:
- [x] [JAB item 8] These controls are updated to explain how we ingest upstream open source code and how we mitigate risks from this code (what we do when we take possession of upstream open source and move it into production). This partially depends on https://github.com/18F/cg-product/issues/260 ("Upstream code is scanned for vulnerabilities before being allowed into production"), but we can do some work on it before that is done. Types of questions to answer in these statements:
  * What is our operational and technical process when we take possession of open source code? Do we scan it, recompile it, etc.?
  * How do we review new additions since the last update?
  * What controls are in place to prevent deploying code with known CVEs? (How do we know that open CVEs are not injected?)
  * What toolkits do we use to analyze the code?
  * How do we minimize our attack surface? (For example, that we're not using open source in C.)
  * How do we mitigate the possibility of mistakes or bad actors in upstream open source contributors?

CM-1:
(Context for this one includes https://github.com/18F/cg-compliance/issues/179)
- [x] Control statement (a) is updated to note our cloud.gov CM Plan (https://docs.cloud.gov/ops/configuration-management/), and that we review and update it at least annually (coordinate with the team to make sure that's logged as a thing that should happen). [SRTM low]
- [x] Control statement (b) explains where to find the revision history of the cloud.gov CM Plan. [SRTM low]
- [x] Review control origination - "We have SP Corporate yet include both SP Corporate and SP System Specific info it seems." [ISSO]

CM-9:
- [x] For part (b), explain either that the CM Plan does "establish a process for identifying configuration items throughout the system development life cycle and for managing the configuration of the configuration items" (and summarize that process) or write that this is planned. [SRTM low]
- [x] For part (c), explain in a little more detail what the CM Plan includes to address this requirement (so that reviewers don't have to switch back and forth to read both documents on first review). (That all application and OS changes to the cloud.gov environment are controlled by 18F's configuration management process; configuration changes for cloud.gov are managed using GitHub repositories; etc.) [SRTM low]

CM-10:
- [x] Explain what restrictions we have on the use of open source software and where we document that. This could include https://github.com/18F/open-source-policy/blob/master/policy.md#exceptions and https://github.com/18F/open-source-policy/blob/master/practice.md#protecting-sensitive-information. [ISSO] [Also filling out more detail here would help with JAB item 8 noted above]

CM overall:
- [ ] Make implementation statuses and control origination statuses fully reflect our system. Especially check any implementation status marked N/A or inherited (make sure they rely on things that really are inside the GovCloud boundary). [SSP notes]

**Implementation guidance**

During grooming, take items from the following and list them as specific tasks above.

- [x] [Required JAB reviewer items](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) ([additional notes here](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit))
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "moderate" differential (if not already marked green there).
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "low" differential (if not already marked done there).
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our ISSO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our PMO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Any relevant notes in the [SSP check working space](https://docs.google.com/document/d/1k-qiOF66o4ssBr6kEO_akaGNsku2zt2jrcawZGg7ZsA/edit#)
- [x] Check that control origination statements make sense (look for [notes here](https://docs.google.com/spreadsheets/d/1Yxt1mMZAdSyKt2OGY1qdkkfZhBiKV6ZuD7sZPKxikuQ/edit#gid=600210940) and look through the controls); if you change a checkbox, make a note in that spreadsheet.

**Comment by mogul** [comment]
@cnelson: This probably needs an update to describe that we now use a protected master branch with required reviews.

**Comment by brittag** [comment]
👏  Wrote a bunch of comments to help with the "CM overall" criteria - this is progressing a lot, hooray!

**Comment by brittag** [comment]
CM-11 is blocked on GSA/TTS policy input (filed as a note [here](https://docs.google.com/document/d/1DJOsX77FhDlEnaizkXv8D_VSLmUz62uYKFxwdyloI1s/edit)); otherwise this seems ready for Awaiting Acceptance.

**Comment by brittag** [comment]
CM-11 is no longer blocked! I have some very minor comments on a few controls, but overall this looks excellent and full of really good updated info, so I'm going to move this to Awaiting Acceptance. @rjbator, can you take a look at it overall?

(Then during Awaiting Acceptance we can address a fresh set of comments all at once to get a final version, instead of addressing my minor comments and *then* getting more comments.)

**Comment by rjbator** [comment]
On my list for today/tonight....

**Comment by rjbator** [comment]
Completed my pass and put in comments/once looked at I am good to go on this section.....
