### ISSUE TITLE
Adequately document CP controls in SSP

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#266]
In order for compliance reviewers to understand our system, we need to update this family of control statements to explain our system (and policies and procedures) in more precise and thorough detail.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

* [CP Google Doc](https://docs.google.com/document/d/10xXG8Fju4qPSlvtJjYu0ZO1zTUrL8o5Zk6TTi9FgtBE/edit#)

**Blocker**

This is blocked on revising the contingency plan, which is filed at https://github.com/18F/cg-product/issues/311

**Acceptance criteria**

- [ ] All relevant CP controls are updated to reflect the revised plan. This includes that some may need to be switched from "Planned" to "Partially implemented" or "Implemented" (including evaluating CP-4 (1), CP-9, CP-9 (1), CP-10). [JAB item 13]
- [ ] CP-9 control statement explains how we backup system documentation. [SRTM low]
- [ ] CP controls are checked and updated overall to make sense.

**Comment by NoahKunin** [comment]
Should cross reference #311

**Comment by mogul** [comment]
Closing as "what we did on CP in PI7"; afawk CP is done now.
