### ISSUE TITLE
Adequately document IA controls in SSP

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#267]
In order for compliance reviewers to understand our system, we need to update this family of control statements to explain our system (and policies and procedures) in more precise and thorough detail.

**Acceptance criteria**

Take the latest relevant control statement chunk [from the Google Drive "SSP draft chunks" folder](https://drive.google.com/drive/u/0/folders/0B1cewEqKcWCbR3hvajNiR0IwUVU), turn on track changes (if it isn't on already), and update that document. Fix the following problems, and put the updated document in that folder, adding the time and date to the filename. Upload it frequently (at least once a day, each time with the current date and time in the filename) so that others can refer to it.

- [ ] [fill out during grooming]

**Implementation guidance**

During grooming, take items from the following and list them as specific tasks above.

- [ ] [Required JAB reviewer items](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705)
- [ ] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "moderate" differential (if not already marked green there).
- [ ] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "low" differential (if not already marked green there).
- [ ] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our ISSO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [ ] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our PMO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [ ] Any relevant notes in the [SSP check working space](https://docs.google.com/document/d/1k-qiOF66o4ssBr6kEO_akaGNsku2zt2jrcawZGg7ZsA/edit#)
- [ ] Check that control origination statements make sense

**Comment by brittag** [comment]
We already have IA filed at https://github.com/18F/cg-product/issues/261, so I'll close this duplicate.
