### ISSUE TITLE
Adequately document PL controls in SSP

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#268]
In order for compliance reviewers to understand our system, we need to update this family of control statements to explain our system (and policies and procedures) in more precise and thorough detail.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

* [PL Google Doc](https://docs.google.com/document/d/1lcKT2PZ0ShwKiHiuuj2pvb2aIQgOfFUXLr3r9iAnHtc/edit)

**Acceptance criteria**

- [ ] PL-2 (especially PL-2 part e) explains in detail that we have documented types of sensitive information that we do not publish, as part of 18F's team guidance for implementing our 18F open source policy: https://github.com/18F/open-source-policy/blob/master/practice.md#protecting-sensitive-information (and we have proactively shared that update with a notification to all 18F team members about it, along with linking it from https://docs.cloud.gov/ops/procedures/). [JAB item 17]
- [ ] PL-4 (1) addresses this SRTM issue: "Tested GSA's processes for establishing a policy on posting GSA information on public websites by analyzing the GSA IT RoB and determined that GSA does not explicitly prohibit the posting of GSA-related information via the web."
- [ ] We've updated PL overall to make sure it has reasonable responsible roles, implementation statuses, control originations, and control statements.

Related issue: https://github.com/18F/cg-product/issues/313 (Update our documentation about sensitive info with more detail)

**Comment by NoahKunin** [comment]
on it

**Comment by mogul** [comment]
Closing as "what we did on PL during PI7"; taking up further PI8 remediations to PL in 18f/cf-product#418
