### ISSUE TITLE
Adequately document PS controls in SSP

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#269]
In order for compliance reviewers to understand our system, we need to update this family of control statements to explain our system (and policies and procedures) in more precise and thorough detail.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

* [PS Google Doc](https://docs.google.com/document/d/19SaO2Q5ao2WANT4tbKqCJdvKc05S_0CLjLq2OIQFY7g/edit)

**Acceptance criteria**

PS-1:

- [ ] Control statements are updated to explain where to find 18F/cloud.gov Personnel Security procedures. This depends on https://github.com/18F/cg-compliance/issues/179 [SRTM low, (PS row 5, 7 + 11)]

PS-7:

- [x] Find out what evidence might exist indicating that GSA monitors 3rd party providers on monthly basis for compliance and security policies. Then update statement by writing, "GSA monitors third party providers on a monthly basis for compliance with security policies by [list evidence here]" ). [SRTM moderate, CtrlSummary (row 69) + PS (row 54)]

PS-8 (b):

- [x] Control statement is updated to explain our organizational processes for managing personnel sanctions, specifically: 
* Veris says that, while we state that 18F will contact the 18F Security Office immediately if an employee security breach were to occur, *"18F could not provide evidence demonstrating that the appropriate organizationally-defined personnel or roles are notified immediately when a formal sanctions process is initiated, identifying the individual sanctioned and the reason for the sanction."*
* To that end, have we implemented processes and procedures to ensure that the appropriate organizationally-defined personnel or roles are notified immediately when a formal sanctions process is initiated, identifying the individual sanctioned and the reason for the sanction?
* Update the control to reflect this. (Put simply, they want us to provide the name(s) and roles of those individuals that we will contact immediately to tell about the security breach.)
* [This is SRTM low, PS (row 58)]

PS overall:
- [ ] Control statements, implementation statuses, control originations, and parameters are checked and make sense overall.

**Implementation guidance**

During grooming, take items from the following and list them as specific tasks above.

- [x] [Required JAB reviewer items](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) ([additional notes here](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit))
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "moderate" differential (if not already marked green there).
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "low" differential (if not already marked done there).
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our ISSO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our PMO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Any relevant notes in the [SSP check working space](https://docs.google.com/document/d/1k-qiOF66o4ssBr6kEO_akaGNsku2zt2jrcawZGg7ZsA/edit#)
- [x] Check that control origination statements make sense (look for [notes here](https://docs.google.com/spreadsheets/d/1Yxt1mMZAdSyKt2OGY1qdkkfZhBiKV6ZuD7sZPKxikuQ/edit#gid=600210940) and look through the controls); if you change a checkbox, make a note in that spreadsheet.

**Comment by brittag** [comment]
This whole control family needs to be updated to talk about GSA policy. We need a subject matter expert on that to fix the problems identified with comments in the Google document.

**Comment by brittag** [comment]
Since this is stuck on GSA policy input, I [put in a note here to ask for help from Noah](https://docs.google.com/document/d/1DJOsX77FhDlEnaizkXv8D_VSLmUz62uYKFxwdyloI1s/edit).

**Comment by brittag** [comment]
Status:
* Noah addressed the two main SRTM comments.
* -1 will be handled separately, like the other -1 controls, at https://github.com/18F/cg-product/issues/306
* There are a few small remaining items flagged as suggestions/comments; Noah is working these out.

**Comment by NoahKunin** [comment]
on it

**Comment by NoahKunin** [comment]
This also got done!
