### ISSUE TITLE
Adequately document SC controls in SSP

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#272]
In order for compliance reviewers to understand our system, we need to update this family of control statements to explain our system (and policies and procedures) in more precise and thorough detail.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

* [SC Google Doc](https://docs.google.com/document/d/1sCMbQREGqT-5-IG-JG2m7eWCblhcMe7w9ERgHjLTEkA/edit)

**Acceptance criteria**

SC-8:
- [x] Determine if Entry number 1 in the JAB Comments [spreadsheet](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) is really for SC/ SC-8
- [x] Once, the appropriate location is determined, the control statement should be updated to:
  - [x] Indicate that cache control is the customer responsibility and why does cloud.gov choose not to control cache.

SC-12 (2):
- [x] Control statement is updated to reflect the current version of OpenSSL we are using.
- [x] Control statement is updated to indicate the source of where we get OpenSSL.
- [x] Control statement is updated to reflect that we are now using FIPS ciphers in the proscribed modes.

SC-13:
- [x] Control statement is updated to include that we use FIPS ciphers in the proscribed modes.

SC-7 (12):  @brittag - (SC-7 looks good; just going to worry about the enhancement)
- [x] Control statement is updated to reflect that the platform level firewall rules are set at the AWS level
- [x] Control statement is updated to reflect how AWS firewall rules work
- [x] Control statement is updated to reflect that the application security groups is based on tenant level iptable rules which happen at the container level.
- [x] Control statement is updated to reflect how the application security groups work.

SC-20 / SC-21
- [x] Control statement should include a short reiteration of the points mentioned in the JAB [comments](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) items 20 & 21 

SC-4:
- [x] Verify that the control statement matches the observations and evidence given in the [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=889700776) notes. Check with a member of the team who understands the system to ensure that the result is accurate and complete.

SC-7(4): 
- [x] Verify that the control statement matches the observations and evidence given in the [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=889700776) notes. Check with a member of the team who understands the system to ensure that the result is accurate and complete.

SC-13:
- [x] Add a checkmark for `Service Provider System Specific` for this control. Afterwards, update the CIS spreadsheet. https://docs.google.com/spreadsheets/d/1Yxt1mMZAdSyKt2OGY1qdkkfZhBiKV6ZuD7sZPKxikuQ/edit#gid=600210940

SC-22:
- [x] Ensure that the observation and evidence in the [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=889700776) still match with the control statements in the SSP

SC-23:
- [x] Ensure that the observation and evidence in the [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=889700776) still match with the control statements in the SSP

SC-28:
- [x] Check with the team if 1) EBS encryption for all EBS volumes has been enabled and 2) Server Side Encryption has been enabled for all S3 volumes as mentioned in the [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=889700776). If it has not, update the implementation status to `partially implemented` and update the control statement. Either case, update the control statement to ensure the status of both are reflected.

SC-28(1):
- [x] As mentioned in the  [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=889700776), add the missing parameters in the table, otherwise change to `partially implemented`
- [x] Check with the team if 1) EBS encryption for all EBS volumes has been enabled and 2) Server Side Encryption has been enabled for all S3 volumes as mentioned in the [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=889700776). If it has not, update the implementation status to `partially implemented` and update the control statement. Either case, update the control statement to ensure the status of both are reflected.

SC overall:

- [x] Check the responsible roles, implementation statuses, and control originations for each control. (Including that "Infrastructure as a Service Provider" shouldn't be in the responsible role - since AWS isn't responsible for these things - instead, we're responsible for making sure our implementation of AWS satisfies these things.)

**Implementation guidance**

During grooming, take items from the following and list them as specific tasks above.

- [x] [Required JAB reviewer items](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) ([additional notes here](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit))
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "moderate" differential (if not already marked green there).
- [x] [SRTM](https://docs.google.com/spreadsheets/d/1R4B0IM3PMUgxvUywYwSq5aSFifQGrD7bYe9qGJJ4iho/edit#gid=31728390) items identified by our 3PAO as "low" differential (if not already marked done there).
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our ISSO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Word doc comments ([in Google Drive](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0)) from our PMO (which provide a helpful reader perspective on confusing bits). They don't all need to be addressed, but useful as guidance.
- [x] Any relevant notes in the [SSP check working space](https://docs.google.com/document/d/1k-qiOF66o4ssBr6kEO_akaGNsku2zt2jrcawZGg7ZsA/edit#)
- [x] Check that control origination statements make sense (look for [notes here](https://docs.google.com/spreadsheets/d/1Yxt1mMZAdSyKt2OGY1qdkkfZhBiKV6ZuD7sZPKxikuQ/edit#gid=600210940) and look through the controls); if you change a checkbox, make a note in that spreadsheet.

**Comment by mogul** [comment]
@dlapiduz: Put you as one of the assignees on this one... We're anticipating that you're an SME in this area (HTTPS, DNSSEC, etc)

**Comment by brittag** [comment]
- [ ] Check the responsible roles, implementation statuses, and control originations for each control. (Including that "Infrastructure as a Service Provider" shouldn't be in the responsible role - since AWS isn't responsible for these things - instead, we're responsible for making sure our implementation of AWS satisfies these things.)

**Comment by brittag** [comment]
Review status: 

* Noah K has reviewed the DNSSEC controls (SC-20 / SC-21). ✅ 
* There are a few controls that need additional fact-checking by Diego.
* Randy plans to take a look soon.

**Comment by brittag** [comment]
Diego has done his fact-checking! ✅ 

Randy put in a few comments. ✅ 

I've asked Bridget to take a look.

**Comment by mogul** [comment]
Per discussion with Noah today: @rjbator will be the one to sign off on this issue and move it from `Awaiting Acceptance` to `Closed`.

**Comment by brittag** [comment]
Status of review:
- [ ] Check overall to make sure references to "Cloud Foundry" aren't confusing to reviewers.
- [ ] Check overall whether AWS inherited needs to be checked in any additional origination checkboxes: "For any control that leverages components or features of the underlying IaaS, the "Inherited" box should also be checked."
- [ ] There are also some specific problems to resolve, flagged in comments.

**Comment by NoahKunin** [comment]
Given that this hasn't happened yet, taking it over.

**Comment by mogul** [comment]
Closing this one as "what we did on SC during PI7"
