### ISSUE TITLE
Update SSP to reflect Diego architecture

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#274]
In order for JAB TRs to have an accurate picture of the system they're evaluating, we should ensure that our SSP material is updated to reflect the Diego architecture/deployment in GovCloud.

**Comment by afeld** [comment]
I'm assuming someone is on this... @NoahKunin?

**Comment by brittag** [comment]
Yes, Noah is making sure this happens.

**Comment by brittag** [comment]
We went through and did this as part of overall SSP work.
