### ISSUE TITLE
Polish assembled SSP prior to JAB submission

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#275]
In order to have confidence in the quality and consistency of our SSP, we need to do some overall review and checking of important aspects of the final draft, as part of putting together a full SSP package.

**Acceptance Criteria**

We have:

- [ ] Looked through the [JAB spreadsheet](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) and [JAB notes](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit) to see if there are any lingering points from those notes that can be addressed with simple cross-references in the right places.
- [x] Reviewed the SSP content for fact-checking and final clarifications by people with first-hand knowledge of the system.
- [x] Checked for consistent use of important terms, such as "GSA SSO" / "SecureAuth" and "jump box" / "bastion host".
- [ ] Made headings consistent, such as consistently formatting bold subheadings for things like AWS/GitHub/etc.
- [ ] Fixed any messy or inconsistent formatting, so that we have a professional-looking SSP document.
- [x] Updated the Control Implementation Summary attachment.
- [x] Updated and organized the rest of our full set of SSP attachments.
- [x] Made sure all SSP attachments are listed properly in the SSP table of contents and SSP final page.

We have also copyedited the following after we finished drafting them:
- [x] Sections 1-11
- [x] AC & IA
- [x] CA, CP, MA, MP, PS, RA, SA, SI
- [x] AU, AT, CM, IR, PE
- [ ] PL, SC

Nice but not necessary to have:
- [ ] Updated the Customer Responsibility Matrix. (Jez has been working this out for the subset of controls that are in the GSA LATO.)
- [ ] Checked links to docs.cloud.gov and converted to docs.fr.cloud.gov (same for dashboard links and anything else relevant).
- [ ] If helpful, included a table of referenced docs.fr.cloud.gov and diagrams.fr.cloud.gov documents, with revision dates/histories.

**Comment by brittag** [comment]
Noting for future reference - at this end stage, we may need to think about:

* Fixing formatting
* Updating the Control Implementation Summary
* Updating the Customer Responsibility Matrix
* Making sure our SSP attachments are updated and organized properly

**Comment by mogul** [comment]
> Updating the Customer Responsibility Matrix

Noting for when we review this later... [Jez has been working this out for the subset of controls that are in the GSA LATO](https://18f.slack.com/archives/cloud-gov-highbar/p1473890542000870).

**Comment by mogul** [comment]
Per Bridget, the CRM can be low in priority.

**Comment by brittag** [comment]
Language consistency checks at the end may need to include:
* GSA SSO / SecureAuth
* jump box / bastion host

**Comment by brittag** [comment]
* Check links to docs.cloud.gov and convert to docs.fr.cloud.gov
* Consider including a table of referenced docs.fr.cloud.gov and diagrams.fr.cloud.gov documents, with revision dates/histories.

**Comment by brittag** [comment]
Make headings consistent, such as:
* For controls with multiple implementation statuses or control originations, explaining which is which
* Consistently formatting bold subheadings for things like AWS/GitHub/etc.

**Comment by brittag** [comment]
Another item for a final polishing stage: take a look through the [JAB spreadsheet](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) and [JAB notes](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit) and see if there are any lingering points from those notes that can be addressed with simple cross-references in the right places.

**Comment by brittag** [comment]
I took all the notes from these comments above and made them into a checklist in the story description above.

**Comment by brittag** [comment]
Our [SSP drafts folder](https://drive.google.com/drive/u/0/folders/0B6fPl5s12igNX3JwR2xFZVpmek0) now has a doc titled `cloud.gov SSP Noah Version 1.3 (11 am PT) - copyedits sections 1-11 Britta.docx` - that has some lightweight suggestions (with "track changes" on) and comments for polishing sections 1-11.

**Comment by mogul** [comment]
Everything remaining to be done here is either already covered elsewhere (eg https://github.com/18F/cg-product/issues/420) or not worth doing.
