### ISSUE TITLE
Increase use of Masonry at GSA

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#276]
In work I'm doing with @nvembar, @jezhumble, @NoahKunin, and others, it's becoming increasingly clear how much potential impact Masonry could have if applied more broadly. 18F, for example, is going to have a large batch of ATOs coming through soon, and I believe this will be a _lot_ easier if Masonry can be used for it.

@jcscottiii and I's recent work on Masonry has been all around FedRAMP, but there may be some work needed for the GSA LATO process:
- Fields that aren't represented in the [schema](https://github.com/opencontrol/schemas) that differ from what FedRAMP needs
- Rendering to the GSA LATO Word doc template
  - Does anyone know where to find this?
  - Pranjali and Man from OCISO indicated to @jcscottiii and I that they might be open to alternate formats.
- Building up a library of templates that can be inherited for different architectures (static sites, etc.)
- Making sure that [the cloud.gov compliance docs](https://github.com/18F/cg-compliance) are updated and easily inheritable
- etc.

We might want to investigate what other blockers might be, and potentially get some additional staff to help with this, so we don't have to reduce efforts around FedRAMP needs.

**Comment by eddietejeda** [comment]
This issue is stale. Closing.
