### ISSUE TITLE
Find alternate funding for Masonry work

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#277]
Related to https://github.com/18F/cg-product/issues/276.

To increase the usage / use cases for Masonry, we would need to do more work than we have capacity for right now (development, content, user research, etc.) cloud.gov's financial situation is hopefully changing for the better soon where we have to worry about 💰 less, but ideally any GSA-specific work (for example) wouldn't be funded out of cloud.gov's budget.

@NoahKunin indicated that there may be some funding sources that could be available to the project, and I've also been mentioning in various meetings I've been having with @nvembar and others that we could increase scope (and potential!) with some additional bandwidth.

**Comment by mogul** [comment]
@lanebecker also wants to help with this.

**Comment by mogul** [comment]
@dlapiduz and @ric7694 should be subscribed here too.
