### ISSUE TITLE
Update AC-2 control sub-family to accurately reflect our system for review

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#280]
In order for compliance reviewers to understand our system, we need to update this sub-family of control statements to explain our system (and policies and procedures) in more precise and thorough detail.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

**Acceptance criteria**

See https://github.com/18F/cg-compliance/issues/176 for the rest of the AC family.

AC-2:
- [x] AC-2 statement provides a high-level overview of the various types of accounts we use - "The cloud.gov team uses several types of accounts to manage and update the PaaS. The following are the core account types and their function: AWS (description), Cloud Foundry/cloud.gov (description), GitHub (description), etc." - and refers to the SSP attachment table of services for more detail. [Derives from the JAB reviewer items (number 10) and ISSO comments]
- [x] AC-2 part e is updated to reflect in depth our actual approval system for getting access to GitHub, AWS, and cloud.gov user access (instead of generically stating "18F requires approvals by the project lead and System Owner for requests to create information system accounts. All accounts will be documented within the GitHub ticketing and tracking system with their respective information systems, detailing their group, role membership, and access authorizations.") [SRTM low]
- [x] AC-2 (f) is updated to explain where we have documented our procedures or conditions for getting accounts. [SRTM low]
- [ ] AC-2 (f) explains "What log or record do we have for AWS account requests, creation of accounts, modification of accounts, removals of accounts, etc.?" [ISSO comments]
- [x] AC-2 (f) explains procedures for privileged accounts other than just AWS accounts (such as cloud.gov access) [PMO comments]
- [x] AC-2 is consistent about using present tense for things we've implemented (avoid future tense). [PMO comments]
- [x] AC-2 is consistent about using one title for program lead / program manager / product manager. [PMO comments]
- [x] AC-2 reference to "Table 9-2. Cloud Foundry User Roles and Privileges" is updated. [PMO comments]
- [ ] AC part j is updated to reflect our actual cloud.gov account review process (Do we remove user accounts due to inactivity, or do we fully delegate that kind of monitoring to the agency SSO? Do we monitor Org accounts?) [SRTM low]

AC-2 (1):
- [ ] Control statement is updated to explain that we currently have a manual off-boarding process for terminating AWS accounts, and that we plan to implement automated mechanisms to help us manage accounts. (Find out what we're planning and add detail about that, or coordinate to get that in the backlog.) [SRTM low]

AC-2 (3):
- [ ] AC-2 (3) answers these questions: "Which account access does this refer to?  Also the requirement is to automatically disable accounts after 90 days of inactivity.  Are the identifiers automatically disabled – and if so, how?" and "What is GitHub’s policy on inactive accounts?" [PMO comments]

AC-2 (5):
- [ ] Control statement is updated with details about GitHub, AWS, and cloud.gov account activity time-out periods - see SRTM notes for details, and verify with an Atlas team member what the actual behavior is. [SRTM low]

**Comment by brittag** [comment]
Noah did some work on this in https://docs.google.com/document/d/16Ao-FCFv1RacjTyvxUqc26ZoJRA-Q7efYBSaAmeFPJg/edit# - so some of these acceptance criteria items may be met already.

**Comment by afeld** [comment]
> AC-2 (f) explains "What log or record do we have for AWS account requests, creation of accounts, modification of accounts, removals of accounts, etc.?" [ISSO comments]

@rjbator @brittag There is no mention of logging in [AC-2(f)](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=AC-2)...maybe this was a mistake and was intended for a different control?

**Comment by afeld** [comment]
> AC part j is updated to reflect our actual cloud.gov account review process (Do we remove user accounts due to inactivity, or do we fully delegate that kind of monitoring to the agency SSO? Do we monitor Org accounts?) [SRTM low]

Is this referring to _all_ cloud.gov accounts, or just administrative ones? The control itself doesn't specify.

**Comment by afeld** [comment]
> AC-2 (5): Control statement is updated with details about GitHub

Not seeing

**Comment by NoahKunin** [comment]
Absorbed into final AC review.
