### ISSUE TITLE
remove information about squads

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#283]
Might be as simple as reverting https://github.com/18F/cg-product/commit/6a4acf23133822765f4b41c0d3932c800daec290 ...?

**Comment by mogul** [comment]
I think they just need a rename... Tried that and a little more in https://github.com/18F/cg-product/pull/289

**Comment by jmcarp** [comment]
I promise I'm not trolling, but if themes and squads have a one-to-one relationship, what's the value of holding on to both concepts?

**Comment by mogul** [comment]
I want to hold out for a while longer, just until we're sure that AgentQ and Atlas are not just separate themes, but separate squads... I want to see what the steady state looks like with Coresphere out, Dan and Chris on, and the current all-hands-on-HighBar-and-Atlas situation behind us.

**Comment by mogul** [comment]
Closing... Readily apparent now that AgentQ is not a separate squad at this team size!
