### ISSUE TITLE
Invite collaborators with pre-assigned roles

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#284]
What we're after: OrganizationManagers can invite users not visible (and potentially not already present in cloud.gov) directly to their spaces with roles pre-set for when the invitation is confirmed.

Benefits/why:
- Eliminate the burden for OrganizationManagers to know who is and isn't already a cloud.gov user
- Eliminate the delay between having an invitation confirmed and having the new collaborator actually able to work with the team

Potential metrics:

- How long does it take for an OrgManager to get a new collaborator set up with the expected roles on one of her spaces?

**Comment by mogul** [comment]
My understanding from @LinuxBozo is that accounts with a pending invitation exist in the DB and are marked "inactive"... At the API level it may be possible to grant them roles even while they're in the inactive state. It may then be possible to query for them and show them in the UI based on roles that they have on the current space.

**Comment by suprenant** [comment]
Items we previously discussed around this (to be broken out into stories):
 - Conduct UX research
 - Do some sketches
 - Add org, space, roles and permissions to dashboard

cc @thisisdano

**Comment by suprenant** [comment]
For managers: should be able to invite someone via email address and be done.

For users: should be able to quickly accept invitation and get started

One possible problem – users have reported not having a good understanding of roles, so we want to give managers understanding of the impact of the invitations.

**Comment by msecret** [comment]
This story should include re-building the UI portion of the user management UI in the dashboard as that UI is currently showing incorrect editing states and is very hard to understand and use.

**Comment by rememberlenny** [comment]
From [@msecret - Marco Segreto] 

Add service with user-defined settings
flowchart: https://gsa.invisionapp.com/share/7RB49CEZM#/226617419_add-Service-Flow
mockup: https://gsa.invisionapp.com/share/A7B49BTHU#/209994627_Marketplace-Adv-Default (use arrows to page through; not set up for clicks)
Add user with predefined roles
wireframe flow: https://gsa.invisionapp.com/share/MEB49D2TC#/226320802_add-User-Flow
org users annotated mockup: https://gsa.invisionapp.com/share/UYB49DU6V#/208480409_Org-Users
space users annotated mockup: https://gsa.invisionapp.com/share/ZTB49IIF7#/208480531_Space-Users
Add app to a space
wireframe flow: https://gsa.invisionapp.com/share/6DB3HCSVJ#/226367368_add-App-Flow

**Comment by msecret** [comment]
https://gsa.invisionapp.com/share/UYB49DU6V#/screens/208480409_Org-Users

**Comment by rememberlenny** [comment]
Estimated to take 2-3 sprints.

1. Visual UI work needs to be fleshed out. Existing UX flow exists.
2. Update current user management UI to existing mockups.
2.5. User test new user management UI.
3. Develop invite collaborators UI.
4. User test new UI.
5. Refine.
6. Launch.

[@msecret - Marco Segreto]

**Comment by mogul** [comment]
[@suprenant - Andrew Suprenant] Did I hear something in the quarterly review about the need to do additional work here for invite UX to appear on spaces, as well as orgs? Or was it expected that this functionality is only accessed at the org level?

**Comment by suprenant** [comment]
[@mogul - Bret Mogilefsky] FYI, I'm following up on this now. More soon..

**Comment by mogul** [comment]
Believe it or not this is once again relevant in 2019 until we have deployed the new version of Stratos.
