### ISSUE TITLE
OrgManagers can set roles for users even if they don't exist

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#285]
In order to eliminate the burden and delay for OrganizationManagers who don't know whether someone already has a cloud.gov account, OrganizationManagers should be able to set any e-mail address as having a set of roles in their org+spaces without having to hassle with invitations.

**Comment by afeld** [comment]
...or maybe setting a role could send the invitation if they don't already have an account?

**Comment by mogul** [comment]
Right, the idea is that whatever needs to get done gets done, even if we have to say "That person's not available yet... Send them an invitation to use cloud.gov?"
