### ISSUE TITLE
Live billing data in dashboard

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#287]
What we're after: Organization managers can easily understand the burn rate for their org based on recent data, and how that is derived per space, app, and managed service.

Benefits/why:
- Enable decision-making about how much/little to use cloud.gov
- Minimize surprises and disputes at invoice time

Ideally this is live, graphed data in the UI, but this start as a static report (eg as part of [CGP-243-1](https://18f.aha.io/requirements/CGP-243-1)): “Based on your org's footprint over the last XX days, your predicted usage costs will come to around $YY this month. Here is how that has been tallied across your apps and services that were running in your spaces during that time." 

Notes on use cases:

_FYI, very good example of a common use-case that can be made easier via the dashboard happening now in #cloud-gov-support… “I just hit a limit and can’t deploy more apps… How is my quota being consumed by my apps across all the spaces in my org?"_

_“Oh, I can see that they’re using less than they’ve been allocated… I can reduce the amount of memory they’re using and fit better, rather than asking for an increased quota which results in spending more money."_

Notes from previous issue: 
In order for the team to bring billing information to the dashboard, we should bring billing data into the dashboard.

Research w/Diego:
https://docs.google.com/document/d/1rOmK-7Fb8nWKpQjwxCM6NIcT1Fue7YABzrq1Tm_sLjs/edit\

Research w/Bret:
https://docs.google.com/document/d/1CD8wGERKulleuXXVwngAfUYAAF6dyDwtYoEkVbFlZM8/edit

Would be about getting Abacus set up
Do we want to go straight for live billing? Or is there an MVP around way to provide information?

**Comment by suprenant** [comment]
Previously discussed related to this:
 - Should talk to Diego about this to learn more about how billing/pricing works
 - Need for this has been validated by talking to several PMs

**Comment by suprenant** [comment]
Proposed meeting w/Diego and the squad on 9/22 for a info download on billing

**Comment by suprenant** [comment]
Possibly related issue on pricing: https://github.com/18F/cg-product/issues/299

**Comment by mogul** [comment]
[@brittag - Britta Gustafson] [did some prototyping](https://docs.google.com/document/d/1yk6hXPtBMqWGGehgSQcF4mO-BHcCRirAzrd1ny0c5nI/edit) for the first part of this with a customer.
