### ISSUE TITLE
Update CA-3 (3) to explain potential customer TIC options

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#293]
In order for compliance reviewers to understand our system, we need to update CA-3 (3) to explain our system in more precise and thorough detail.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

[CA Google Doc](https://docs.google.com/document/d/1LnjqxvB9QhY8xLFw2B-LAu0nsChldsul4c1dducqal4/edit)

This is part of the larger set of CA control family tasks filed here: https://github.com/18F/cg-product/issues/264

Noah K has context on this topic and how to implement these fixes; you can coordinate with him for help.

**Acceptance criteria**

For context, see the [required JAB reviewer items](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) ([additional notes here](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit)).

CA-3 (3):
- [ ] Control statement is updated with diagrams and additional info that map the use case for moderate systems in the TIC Reference Architecture to possible cloud.gov solutions. [JAB item 16]
- [ ] Control statement is updated to include more info: get from DHS/18F/GSA TIC Overlay collab extra data we send out. [JAB item 16]

Also:
- [ ] Any non-trivial diagrams (and source files for diagrams) are [in this folder](https://drive.google.com/drive/u/0/folders/0B1cewEqKcWCbZlI3cFdibzEwNzQ) so they can be easily updated/modified by other people in the future.

**Comment by NoahKunin** [comment]
on it

**Comment by NoahKunin** [comment]
Ok, re-wrote it, will have to do the diagrams too now.

**Comment by NoahKunin** [comment]
Closing to keep open issue sanity.
