### ISSUE TITLE
Complete our services table so that it can be a SSP attachment

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#294]
In order for compliance reviewers to understand our system, we need to have an SSP attachment that is a table of services (both inside and outside our boundary), including comprehensive details about them.

**Setup**

[We have a draft table here](https://docs.google.com/document/d/1xZI6mTbJpXVG90rGL1LswgPf6YUN7FM2yBPhfPhRgw8/edit#heading=h.h6noyq8mrmk2) with context.

The notes from the relevant JAB meeting are in [this spreadsheet](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) and [this additional notes doc](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit).

Related issues include https://github.com/18F/cg-product/issues/291 ("Update SSP section 10.7 (Data Flow) to explain external services") and https://github.com/18F/cg-compliance/issues/176 ("Update AC controls to accurately reflect our system for review").

Before you start working on this task:

- [ ] Chat with Britta to get additional context and understanding for the task. :)

**Acceptance criteria**

- [ ] Table addresses JAB item 10 (expand our draft service documentation table to cover additional columns and types of services [both services inside our boundary and outside it].
- [ ] Table addresses JAB item 3 and 22 (Google Analytics)
- [ ] Table addresses JAB item 19 (Fugacious)
- [ ] Table addresses JAB item 23 (don't include Trusted Advisor)
- [ ] This document has formal formatting so that it looks like [other SSP attachments](https://drive.google.com/drive/u/0/folders/0B1cewEqKcWCbeUI1TmdzQkRVVVU), including the templated front page, page numbers, etc. (Hand this off to Britta for this one.)

Document is listed in the SSP as an attachment in all the relevant places:
- [ ] Table of contents and attachment pages
- [ ] Referenced in the system overview sections
- [ ] Referenced in AC and IA family where appropriate

**Comment by brittag** [comment]
This is getting some great progress, thanks Josh!!! I added in a little bit of formatting and stuck in the new columns for the other tables too.

**Comment by jmcarp** [comment]
@sharms and I added what we could, but there are still gaps on external services that we aren't familiar with. @brittag: can you nominate somebody who knows about google analytics, aha!, etc.?

**Comment by brittag** [comment]
I suspect we'll need to include these tools in the tables too: "All open source code that is used in the system is scanned using AST tools from Hewlett-Packard including Fortify and Gas." (quoted from [SI family](https://docs.google.com/document/d/1suPHrUZUps1mWctbTXBK7qsMTEDw0envn10A9scOEPA/edit)).

**Comment by jmcarp** [comment]
Update: we don't need to include fortify or gas here. @mogul suggested that Aha! can be removed--anybody have thoughts on that? I didn't put it there and don't know whether it belongs. @brittag: can you nominate someone who knows more about these external services (and about which of them need to be included) to complete this?

**Comment by brittag** [comment]
Removing Aha seems fine to me since it doesn't affect our security posture at all.

**Comment by brittag** [comment]
Next steps / missing info right now includes: Does StatusPage have MFA? Who has access to Mandrill/Mailchimp, and does it have MFA? Who has access to New Relic, CodeClimate, Travis CI, Codecov, and CircleCI?

**Comment by mogul** [comment]
Just confirmed that StatusPage does *not* have MFA. I am pretty sure people
on the team are logging in with their GSA Google Account, but there's
nothing in place to measure/enforce that.

@dlapiduz has access to Mandrill and Mailchimp.

Can't speak to New Relic.

CodeClimate, Travis CI, Codecov, and CircleCI all auth against GitHub AFAIK.

**Comment by NoahKunin** [comment]
I'll take it from here.

**Comment by brittag** [comment]
We delivered a services table attachment; further improvements should be new issues.
