### ISSUE TITLE
Adequately document IR controls

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#298]
In order for compliance reviewers to understand our system, we need to update this family of control statements to explain our system (and policies and procedures) in more precise and thorough detail.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

* [IR Google Doc](https://docs.google.com/document/d/1lxXoEIw5pQRO3RSOcKfMZ9_Z2LO2J0pZ0TZkDtqUtJw/edit)

**Acceptance criteria**

IR-1:
- [ ] This is fixed like the other -1 controls.

Overall:
- [x] Controls are checked for accuracy and updated (including checking responsible roles, parameters, implementation statuses, and control originations). *There are many comments on specific aspects of controls that may need more work.*
- [x] https://github.com/18F/cg-postmortems readme is updated to include a reminder that we don't post sensitive info in that repo.

**Comment by brittag** [comment]
Steve, Joshua, and I updated a bunch of the control statements here. We've done as much as we can on this one. There are a few comments pointing out places where we need feedback on policy - we've tagged Noah, Randy, and Jacob KM for help.

**Comment by brittag** [comment]
@rjbator I believe this is in good enough shape for your review!

Notes:

* IR-1 will be handled by https://github.com/18F/cg-product/issues/306
* IR-9 (4) isn't filled out yet; Noah will handle that one.

**Comment by rjbator** [comment]
Roger that I will go back and do another pass.

**Comment by rjbator** [comment]
I am done with IR pass .....I have some comments in there.

**Comment by NoahKunin** [comment]
Will resolve comments and approve.

**Comment by NoahKunin** [comment]
Done for now with these passes, will come back as the calendar dictates.
