### ISSUE TITLE
revise pricing pace on website

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#299]
Just talking with Leah about https://docs.cloud.gov/intro/pricing/rates/ , she pointed out how when you read the fees under "Access Package," for each package, it says "No" for usage charges. I found it confusing as well; I think that what we intended to say here was, "usage charges are not included in the Access Package - you will be charged separately for them." Instead, it initially reads as "you do not pay usage charges when you purchase these access packages." Let's fix this page so that it is clearer.

**Comment by mogul** [comment]
Fixed by https://github.com/18F/cg-docs/issues/415
