### ISSUE TITLE
Consolidate CI tools

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-product#301]
We're currently using concourse, travis, and circle for ci services (wercker is on the way out because it was only used for a few repos). This is more than we need. Plus, switching between tools is potentially confusing, and each external ci integration gets write access to all our repos, because github.

I'd like to consolidate to either one ci tool (just concourse) or two (concourse and a single hosted service). Now that concourse has teams, we might be able to get away without any hosted tools--but if not, let's stick to a single hosted service. Sounds like @jcscottiii likes circle, so that might be a good choice.

No doubt this is a low priority, but it should also be easy to fix. At the very least, let's pick a preferred ci tool to use for all new repos going forward.

cc @mogul

**Comment by brittag** [comment]
For future reference - I dug up a few details about why we're still using Travis at https://github.com/18F/cg-product/issues/519#issuecomment-262326781 - cg-compliance could probably pretty easily switch to CircleCI or Concourse, but cg-uaa and cg-uaa-extras use Travis because upstream uses Travis, so those are less of a good idea to switch away from Travis.

**Comment by brittag** [comment]
Also for future reference: reminder to update our Services table (SSP attachment) when we add or remove a service.

**Comment by jmcarp** [comment]
I understand the point about cg-uaa, since that's a fork, but cg-uaa-extras isn't. Not that I'm arguing that it's a priority, or even worthwhile, to change ci on extras--just want to make sure I understand.

**Comment by brittag** [comment]
Ah good point! I don't know why cg-uaa-extras has Travis too; I was assuming just to match with cg-uaa, but that could be wrong.

**Comment by brittag** [comment]
We seem to also be using Travis for these:

* https://github.com/18F/cf-cdn-service-broker
* https://github.com/18F/cg-quotas-db

**Comment by jmcarp** [comment]
FWIW, cg-quotas-db is basically abandonware and should be replaced by abacus soon.

**Comment by cnelson** [comment]
cg-uaa-extras [already runs tests in concourse](https://github.com/18F/cg-uaa-extras/blob/staging/ci/test.yml), we could drop travis for that now (although it might be nice to add a pr status check to the pipeline)
