### ISSUE TITLE
Adequately document MA, MP, and PE controls in SSP

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#307]
In order for compliance reviewers to understand our system, we need to make sure these families of control statements explain our system (and policies and procedures) in more precise and thorough detail.

These three families are primarily answered by "this is inherited from AWS", so there shouldn't be a ton to do for them, but we should still look over them to make sure they're ok.

**Setup**

Read the guidance in [HOWTO update the SSP](https://docs.google.com/document/d/1ltS7Lh8tdWeaDyABEupvHQDCpdaDMNlerrMcvrR5bio/edit) before working on this.

* [MA - Maintenance](https://docs.google.com/document/d/1sQWs2u1GJFZ6rW9IyQKu0ibnB21PG_1g3rjzP5rn98Q/edit)
* [MP - Media Protection](https://docs.google.com/document/d/1OcB8m3auEwzGf-GBmqentvsqStlxLlnCEpddlZrr4RE/edit)
* [PE - Physical and Environmental Protection](https://docs.google.com/document/d/1LihvdNAAKYNPlp0WpNMLKLu3Sqs2wsDjkk2Fj_A13Ss/edit)

**Acceptance criteria**

For these, ignore the -1 controls (since taking care of that is filed separately at https://github.com/18F/cg-product/issues/306).

The overall task is to check all of the following and make sure the following make sense for each family, flagging and fixing anything that looks problematic:

MA:
- [x] Boilerplate AWS control statements makes sense. We've figured out whether to rework these to match PE.
- [x] We've checked whether MA-4, MA-4 (2), MA-5, MA-5 (1), and MA-6 make sense (whether virtual components should be addressed in these control statements), and updated them if not.
- [x] Responsible roles make sense.
- [x] Parameters make sense. (Maybe matching PE?)
- [x] Implementation statuses make sense.
- [x] Control originations make sense.

MP:

- [x] Control statements make sense. We've figured out whether to rework the templated control statement to match PE.
- [x] Responsible roles make sense.
- [x] Parameters make sense.
- [x] Implementation statuses and control originations make sense.

PE:
* The "Responsible roles" field has a known potential problem (is it ok for "Infrastructure as a Service provider" to be the responsible role?), but that's tracked separately at https://github.com/18F/cg-compliance/issues/165
- [x] We've checked the document overall to see that parameters, implementation statuses, control originations, and control statements make sense.

**Comment by NoahKunin** [comment]
did quick scan of @sharms stuff, good for now, grabbing, thx!

**Comment by NoahKunin** [comment]
Done. For now.
