### ISSUE TITLE
Make NTP config geographically diverse

### ISSUE THREAD

**Issue by datn** [18F/cg-product#309]
As part of our audit of the AU family in the SSP, it came to light that we should be using geographically diverse NTP servers (AU-8(1) req.1). Using 0|1|2.pool.ntp.org, as I see in the repo, does not guarantee geographical diversity.

We should change our configs to guarantee geographical diversity to satisfy the SSP, perhaps by using the continental zones: http://www.pool.ntp.org/zone/@

**Comment by datn** [comment]
https://github.com/18F/cg-deploy-bosh/pull/25 and again

**Comment by datn** [comment]
Just waiting on a thumbs-up and merge so we can redeploy and test.

**Comment by rogeruiz** [comment]
ssh into anything and dump out the CTP config.

**Comment by datn** [comment]
We logged into a random box and deduced where ntp corrections come from (root's crontab runs `ntpdate` every 15 minutes, coming from [here](https://github.com/cloudfoundry/bosh/blob/cc49a8ee67434b3ac89deae81724403283c51bfa/stemcell_builder/stages/bosh_ntpdate/apply.sh) ). We observed the correct configuration in `/var/vcap/bosh/etc/ntpserver`.

**Comment by rogeruiz** [comment]
paired with @datn and verified 🎉

**Comment by rogeruiz** [comment]
This is something that should be put into 18F/cg-atlas#125 the Runbook issue. Something that can come out of this _today_ would be to put @datn's comment into `cloud.gov/docs` under some Runbook heading in `Contributions > Opersations > Runbook?`. We're not sure on the name. But the 

NTP settings aren't easily discoverable in the bosh documentation. @datn and I had to go through some source in `cloudfoundry/bosh` and within the vms to find out how it was being put into root's crontab.
