### ISSUE TITLE
Configure Nessus scans

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#31]
In order to actually derive benefit from all our work to embed scanning agents in all hosts, we need scans configured to run and be reported on a regular basis.

**Acceptance Criteria**

* [x] Every host in production runs a daily Nessus scan that includes the CIS1 benchmark

**Comment by dlapiduz** [comment]
I did this yesterday... 
![screen shot 2016-06-15 at 9 27 33 pm](https://cloud.githubusercontent.com/assets/4604/16103667/0426ddba-3340-11e6-922b-cf98accb9bf2.png)

**Comment by rogeruiz** [comment]
Looks good to me.
