### ISSUE TITLE
Revise our contingency plan to cover the case of GitHub being unavailable

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#311]
This is related to the task at https://github.com/18F/cg-product/issues/266 ("Adequately document CP controls in SSP").

See the [JAB spreadsheet](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) and [JAB notes](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit) for context.

**Acceptance criteria**

- [x] Our contingency plan is revised to cover a specific set of important major outage scenarios (including needing to rebuild cloud.gov in a new AWS account, retaining customer data, including in the case of unavailability of GitHub). This may involve updating https://docs.cloud.gov/ops/contingency-plan/ and consolidating the formal (Word doc) contingency plan into it, or deciding that the formal plan is the one we're using (and updating that one). [JAB item 13]

**Comment by NoahKunin** [comment]
Looks like this is one thing that is truly WIP and can't absorb. Let's make sure there's a formal work session this week to ship it.

**Comment by mogul** [comment]
What remains to be done here to have it sufficiently complete for JAB purposes?

**Comment by cnelson** [comment]
¯\_(☁️)_/¯  - It's done as far as I'm concerned / what the AC says.

**Comment by mogul** [comment]
Assigning to Noah to accept

**Comment by NoahKunin** [comment]
on it

**Comment by brittag** [comment]
@NoahKunin I pushed up the draft I worked on a bit, in case it's helpful for your work: https://github.com/18F/cg-docs/commit/fe5c8d6e76c67366a066d3a36c261ffd4e1c3791 - it gets rid of some non-essential stuff and adds in a little more of an actual plan outline.

**Comment by wslack** [comment]
Aidan and I made some edits in https://github.com/18F/cg-docs/pull/448
