### ISSUE TITLE
Write a "how we use Fugacious" entry in the Handbook

### ISSUE THREAD

**Issue by NoahKunin** [18F/cg-product#312]
Putting this here so it gets tracked as SSP work.

**Comment by brittag** [comment]
Bringing over notes from Slack: 

* This needs some info about what is appropriate/acceptable to share over Fugacious and what isn’t - see line 19 at https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705 for details.
* We should link back to this new handbook page from https://github.com/18F/open-source-policy/blob/master/practice.md#protecting-sensitive-information when it’s ready.

**Comment by brittag** [comment]
Reopening this issue since this page needs to have very clear, direct guidance about what is appropriate for 18F to share over Fugacious (and what isn't) - I wrote a couple comments at https://github.com/18F/handbook/pull/98#discussion_r80546013 with suggestions. :)

**Comment by brittag** [comment]
Also, is it possible to get https://fugacious.18f.gov/ to link to 18F-specific guidance about use of Fugacious? That would improve confidence that we comply with our guidance. I don't know if we want that version to use a generic fork though.

**Comment by NoahKunin** [comment]
I think we might need to have a more substantive conversation then. The JAB concern was about guidance on time frames - not on the data content.

But secondly, one of my foundational compliance values is we turn back the tide on government making rules (either for others our ourselves) that we cannot enforce.

To that end, we are in a weird (but good) situation with Fugacious. The only way to enforce, say, that PII isn't sent via Fugacious (which I think is debatable) would be for us to scan for data that looks like PII that is sent to or stored in Fugacious, but us *not* doing exactly that *for any info* is why Fugacious is great / secure.

**Comment by brittag** [comment]
Oh hmm, I read our notes for [item 19 here](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) as asking us to give team guidance about content - I'm ok with interpreting that as giving recommendations about content rather than requirements (or interpreting that entirely differently).

**Comment by NoahKunin** [comment]
@brittag Good catch. Blergh, missed this in the written version, was reflecting the conversation we had with them in-person.

Even though it's clunky (would rather an 18F level policy) you're right the fastest way to solve this w/o more meetings is just making a pure cloud.gov policy, and then re-factoring later to a more general guidance (for ex: there's no reason why 18Fers can't use Fugacious to send SSNs).
