### ISSUE TITLE
Update our documentation about sensitive info with more detail

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#313]
In order for our cloud.gov team to have a clear shared understanding about sensitive info we shouldn't share publicly (and demonstrate to compliance reviewers that we have this clear shared understanding), our policy/practices documentation should explain a few additional types of info that we don't share.

See item 17 in [this notes spreadsheet](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) for details, along with the discussion about item 17 in [this notes doc](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit). This may include "details of known weaknesses and mitigations should not be open; details about defenses; external attributions; document more about our processes for keeping the postmortem repo clean" - but the work of this story is to figure out what exactly we should say.

**Acceptance criteria**
- [x] We've added any relevant details to [the 18F Open Source Policy practices section](https://github.com/18F/open-source-policy/blob/master/practice.md#protecting-sensitive-information).
- [x] We've added any relevant details to [cg-postmortems repo readme](https://github.com/18F/cg-postmortems) - https://github.com/18F/cg-postmortems/pull/11
- [x] We've updated any parts of the SSP that need updating after we update the two above issues, such as PL-2, or we have that task tracked, or at least the relevant person knows to update it.

Related issues:
* PL family in SSP - https://github.com/18F/cg-product/issues/268
* Documenting Fugacious - https://github.com/18F/cg-product/issues/312

**Comment by brittag** [comment]
Reopening since the merged PR doesn't fully take care of this issue - the SSP part may still remain ("We've updated any parts of the SSP that need updating after we update the two above issues, such as PL-2, or we have that task tracked, or at least the relevant person knows to update it").

**Comment by NoahKunin** [comment]
I think we'll just have to pick that up as we go along. Re-closing!
