### ISSUE TITLE
As a user, I want a self-service way to set up automated deployment

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#32]
As noted in https://github.com/18F/cg-docs/pull/262#issuecomment-221426769, it isn't currently possible for non-admins to create deployer credentials for themselves. This is a barrier to users setting up automated deployment, which is a behavior we want to encourage.

**Comment by afeld** [comment]
As noted [in Slack](https://18f.slack.com/archives/cloud-gov-support/p1465855139000063), creating tokens is preferable to creating dedicated users, since passwords expire.

**Comment by afeld** [comment]
Token conversation broken out to https://github.com/18F/cg-docs/issues/286.

**Comment by mogul** [comment]
To be taken up in future using UAA OAuth tokens now that it's possible, but closing for now.
