### ISSUE TITLE
Improve team onboarding checklist 

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#321]
In order to improve our own compliance with our requirements, we should fix up our onboarding checklist to have specific in-context reminders about the bits of the process that are critical for compliance.

Brainstorming some things we should do to fix up https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md, cc @mogul.

* Fix up ["Required items for all team members"](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md#required-items-for-all-team-members) to reflect our current understanding of our all-team compliance requirements, and explain why they're required. (People should be familiar with all the policies, rather than just those three, etc.)
* Under ["Buddy checklist"](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md#buddy-checklist), split out "required for compliance" items and regular items.
* Improve the Buddy checklist for [Atlas-specific items](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md#atlas-specific-items-1) to explain which items are Really Important Compliance Items and which are nice-to-have items. Clarify whether joining Atlas means becoming "Cloud Operations" (with all the corresponding requirements and responsibilities listed in the SSP). (Also, adding people to PagerDuty can have $ implications; we might need to adjust that item.)

**Comment by brittag** [comment]
We might also want to add our own "complete within 30 days of joining the team" deadline to compliance items that don't already have a deadline from the SSP, just to make sure they happen.

**Comment by afeld** [comment]
> split out "required for compliance" items and regular items

I'd advocate for using some sort of indicator (e.g. an asterisk at the end of the line or an inline HTML comment or something) to identify the ones that are for compliance, so that we can keep the tasks grouped/ordered in the way that makes most sense for _us_, not the auditors.

**Comment by brittag** [comment]
For us as a team, it's helpful for us to know which items are required for compliance and which items are helpful guidance/context. This helps a new person and their buddy prioritize onboarding tasks and evaluate whether onboarding is adequately complete. :)

**Comment by mogul** [comment]
@brittag are you arguing not to do what @afeld suggested? It seems like we can satisfy both team members and auditors by using some in-situ indicator and a key (eg "bold items are required for compliance by all team members and must be completed within 30 days of joining the team").

**Comment by brittag** [comment]
I believe this is mostly done! Just waiting to close this until https://github.com/18F/cg-dashboard/pull/640 gets merged.

**Comment by brittag** [comment]
@mogul Ah sorry, I missed your comment yesterday despite adding my own after it! You're right, my comment was vague!

I believe any way of indicating which tasks are compliance requirements - asterisks, sections, bold, etc. - will satisfy our requirements just fine. But from a content design perspective, I prefer to avoid "coded" methods that require referencing a key (such as bold or asterisks), since that can be confusing for the reader. I prefer arranging the content so that the reader just has to read ordinary sentences and phrases, with useful context in the right places. :D

**Comment by brittag** [comment]
Closing this since https://github.com/18F/cg-dashboard/pull/640 got merged, so this story is complete! We could have a new story for further checklist improvements!
