### ISSUE TITLE
Ramp up Aaron on cloud.gov liberator team

### ISSUE THREAD

**Issue by msecret** [18F/cg-product#324]
@adborden: Try to go through your checklists in order.
**Buddy:** If you can’t complete any of the items on your checklist personally, _you are responsible for ensuring that an appropriate person does it_.
### Getting to know cloud.gov
- [x] Take judicious notes on what about this onboarding process or cloud.gov is confusing or frustrating. If you notice a problem (especially with things like documentation), you are more than welcome to fix it! At the very least, please share this information with your buddy (or someone) at some point so we can make the team/platform better. (You can also file issues and pull-requests on [the template for Onboarding issues](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md).)
- [x] Figure out who your onboarding buddy is (they should reach out to you) and make sure this issue is assigned to them), it's Marco
- [x] Read [the team onboarding document](https://github.com/18F/cg-product/blob/master/Onboarding.md) for more context about cloud.gov
- [x] Check out the [roadmap](https://18f.aha.io/published/068c364a0302b89521045f9fbd258374) to get a high-level view of recently-completed, in-progress, and upcoming features
- [x] Install the [ZenHub](https://zenhub.io) browser extension to enable you to see kanban boards, hierarchical issues, and burndown charts in GitHub
- [x] Read the [Delivery Process document](https://github.com/18F/cg-product/blob/master/DeliveryProcess.md) to learn about how we work
- [x] Join [the cloud.gov support Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov-support), so you can see how we handle non-18F support and get visibility of technical discussions happening with outside groups
- [x] Join [the cloud.gov team Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov), so you can participate in team-wide internal communication
- [x] Once you've finished the remaining checklists below, make suggestions for steps that would have improved your onboarding experience as pull-requests on [the onboarding checklist template](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md) used to make this issue
### Required items for all team members
- [x] Read the [Incident Response Policy](https://github.com/18F/compliance-docs/blob/master/IR-Policy.md) and [Incident Response Guide](https://docs.cloud.gov/ops/security-ir/). Coordinate with your onboarding buddy to go through Incident Response Training within 60 days of joining the team (and annually after that).
- [x] Read the [Contingency Planning Policy](https://github.com/18F/compliance-docs/blob/master/CP-Policy.md) and [Contingency Plan](https://docs.cloud.gov/ops/contingency-plan/). Coordinate with your onboarding buddy to go through Contingency Planning training within 10 days if you'll be taking on a significant role in our Contingency Planning processes (or annually if not).
- [x] Read the [Configuration Management Policy](https://github.com/18F/compliance-docs/blob/master/CM-Policy.md) and [Configuration Management Plan](https://docs.cloud.gov/ops/configuration-management/).
- [x] Subscribe to [the cloud.gov team calendar](https://calendar.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks@group.calendar.google.com&ctz=America/Los_Angeles) (click the + in the bottom right) so you know when assorted team meetings are happening in the various streams
- [x] Subscribe to the [cg-docs](https://github.com/18F/cg-docs) GitHub repository notifications
### Liberator-specific items
- [x] Join the `#cloud-gov-liberator` channel on Slack
- [x] ~Ping @standup-bot for instructions on front end channel standup~ (currently disabled)
- [x] Review the main [front end board](https://github.com/18F/cg-dashboard/pulls#boards?repos=55727091,39210774,49169967,40567233&labels=Liberator&showPRs=false) (ensure to filter by the "Liberator" label)
- [x] Review the cloud.gov [delivery process](https://github.com/18F/cg-product/blob/master/DeliveryProcess.md) to understand how the agile boards and workflow works.
- [x] Bookmark link to [design folder](https://drive.google.com/drive/u/1/folders/0BwLqM4Nicmq-bUt0NjRjclFMUEU)
- [x] Review the primary cloud.gov sites: [the dashboard](https://dashboard.cloud.gov/#/), [main landing page](https://cloud.gov/), and [documentation](https://docs.cloud.gov/).
- [x] Double check anything missing from the new [onboarding checklist](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md)
#### If developing
- [x] Set up [the dashboard](https://github.com/18F/cg-dashboard) and [style](https://github.com/18F/cg-style) locally
- [x] Have Marco send the cg-dashboard testing env vars through fugacious
- [x] Review [dashboard contributing guide](https://github.com/18F/cg-dashboard/CONTRIBUTING.md) and [cloudgov-style standards](https://github.com/18F/cg-style/blob/master/documentation/frontend_standards.md)
#### For review
- [ ] Review the [design principals](https://docs.google.com/spreadsheets/d/14Y3RKaLUt6RPX5w13iz7oaSCpojEQ-Wqjnd8Ie_VkCc/edit#gid=259774738) to get a sense of how the cloud.gov team feels about the product
- [x] Review the [cloudgov-style styleguide](https://pages.18f.gov/cg-style/) to get a sense of the global cloud.gov visual style.
- [ ] Review the [US Web Design Standards](https://standards.usa.gov/) as cloudgov-style was built from it.
- [x] Review the dashboard, current [prod](https://dashboard.cloud.gov/#/), [master](https://dashboard-master.apps.cloud.gov/#/) and [staging](https://dashboard-staging.apps.cloud.gov/#/)
- [ ] Read the [January 2016 cloud.gov "Executive Business Case" document](https://docs.google.com/document/d/138OcG0Lt6gr9J0wM0TzzPNyTROmYAwfLIDujtweiwGw/edit#) for greater context about cloud.gov's potential impact in government
---
## Buddy checklist
- [x] Introduce yourself to the new team member and give them some of your background so they know who you are
- [x] Make sure they're listed in [the list of people working on the project](https://docs.google.com/spreadsheets/d/1mW3tphZ98ExmMxLHPogSpTq8DzYr5Oh8_SHnOTvjRWM/edit#gid=0)
- [x] Add them to the @cloud-gov-team in Slack’s Team Directory (which also adds them to the right channels)
- [x] Add them to the recurring cloud.gov meetings that are relevant for them in [the team calendar](https://calendar.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks@group.calendar.google.com&ctz=America/Los_Angeles)
- [x] Setup a cloud.gov user account for them via [the “send an invite” page](https://invite.cloud.gov)
- [x] Identify a straightforward, well-groomed story in progress that involves their skills domain, schedule a meeting with the owner for an introduction (if it's not you), and setup pairing sessions several times in the first week on the project.
- [x] Identify a straightforward, well-groomed first story, ideally something they could conceivably complete in their first two/three weeks using their existing skills. Discuss the context with them, then make them the assignee for the card.
- [ ] Make suggestions for how your onboarding experience could have been improved as PRs on [the onboarding template](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md).
- [x] Confirm they have 2FA enabled for GitHub, and ask `#admins-github` to have them added to the [@18F/cloud.gov team](https://github.com/orgs/18F/teams/cloud-gov) on GitHub

**Comment by suprenant** [comment]
@adborden looks like this is moving along. If you're hitting any significant blockers, let us know.

**Comment by suprenant** [comment]
Noting that we're targeting to finish the top-priority items here during this first sprint of PI8.
