### ISSUE TITLE
Ramp up Roger on cloud.gov team

### ISSUE THREAD

**Issue by rogeruiz** [18F/cg-product#335]
John ( @jbarnicle ) has agreed to be Roger's on-boarding buddy.

# Directions:
**Roger ( @rogeruiz ) and Buddy:** Try to go through your checklists in order.
**Buddy:** If you can’t complete any of the items on your checklist personally, _you are responsible for ensuring that an appropriate person does it_.

### Getting to know cloud.gov
- [x] Take judicious notes on what about this onboarding process or cloud.gov is confusing or frustrating. If you notice a problem (especially with things like documentation), you are more than welcome to fix it! At the very least, please share this information with your buddy (or someone) at some point so we can make the team/platform better. (You can also file issues and pull requests on [the template for Onboarding issues](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md).)
- [x] Figure out who your onboarding buddy is (they should reach out to you) and make sure this issue is assigned to them
- [x] Read [the team onboarding document](https://github.com/18F/cg-product/blob/master/Onboarding.md) for more context about cloud.gov
- [x] Read the ["What is it?"](https://docs.google.com/presentation/d/1nCcti3dXG9TVGW3OqaWtnf96oXX8U8SBTM_WePFO_dg/edit#slide=id.p) presentation for a rundown of what cloud.gov is and does
- [x] Read through [the Introduction section of docs.cloud.gov](https://docs.cloud.gov/) for a broader understanding of cloud.gov, especially as we present it to potential customers/users
- [x] Read the [January 2016 cloud.gov "Executive Business Case" document](https://docs.google.com/document/d/138OcG0Lt6gr9J0wM0TzzPNyTROmYAwfLIDujtweiwGw/edit#) for greater context about cloud.gov's potential impact in government
- [x] Try to [deploy a sample application to cloud.gov](https://docs.cloud.gov/getting-started/your-first-deploy/) to get familiar with the basics of the PaaS from a user's perspective
- [x] Check out the [roadmap](https://18f.aha.io/published/068c364a0302b89521045f9fbd258374) to get a high-level view of recently-completed, in-progress, and upcoming features
- [x] Install the [ZenHub](https://zenhub.io) browser extension to enable you to see kanban boards, hierarchical issues, and burndown charts in GitHub
- [x] Read the [Delivery Process document](https://github.com/18F/cg-product/blob/master/DeliveryProcess.md) to learn about how we work
- [x] Join [the cloud.gov support Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov-support), so you can see how we handle non-18F support and get visibility of technical discussions happening with outside groups
- [x] Join [the cloud.gov team Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov), so you can participate in team-wide internal communication
- [x] Figure out what themes you're likely to work in, and complete the checklist below that relates to it
- [x] Once you've finished the remaining checklists below, make suggestions for steps that would have improved your onboarding experience as pull requests on [the onboarding checklist template](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md) used to make this issue

### Required items for all team members

These items help us fulfill security and compliance requirements (including for FedRAMP). If you get stuck, or if these requirements are confusing, ask for help from your buddy or in a cloud.gov channel.

- [x] Read the [18F Security Policies and Procedures](https://github.com/18F/compliance-docs). These documents (which are mostly quite short) explain the high-level policies and procedures we must comply with while running cloud.gov.
- [x] Read the [Incident Response Guide](https://docs.cloud.gov/ops/security-ir/).
- [x] Coordinate with your onboarding buddy to go through Incident Response Training within 60 days of joining the team (and annually after that).
- [x] Read the [Contingency Plan](https://docs.cloud.gov/ops/contingency-plan/).
- [x] Coordinate with your onboarding buddy to go through Contingency Planning training within 10 days if you'll be taking on a significant role in our Contingency Planning processes (or annually if not).
- [x] Read the [Configuration Management Plan](https://docs.cloud.gov/ops/configuration-management/).
- [x] Subscribe to [the cloud.gov team calendar](https://calendar.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks@group.calendar.google.com&ctz=America/Los_Angeles) (click the + in the bottom right) so you know when assorted team meetings are happening in the various streams
- [x] Subscribe to the [cg-docs](https://github.com/18F/cg-docs) GitHub repository notifications

### Theme-specific items

For explanations of our theme names, see [this glossary](https://github.com/18F/cg-product#sub-teamsthemes-of-work).

#### Atlas-specific items

- [x] Bookmark [the Atlas kanban board view](https://github.com/18F/cg-product#boards?labels=Atlas&showPRs=false)
- [x] Join the #cloud-gov-atlas channel on Slack
- [x] Watch [Build Your Own Private Cloud Foundry](https://www.youtube.com/watch?v=v85r4Hy3jbs) to learn about running Cloud Foundry
- [x] [Set up Cloud Foundry locally](https://docs.cloud.gov/ops/creating-a-local-dev-environment-in-Virtual-Box/) and push an app to it
- [x] Learn about [BOSH](http://bosh.io/): watch [this video](https://www.youtube.com/watch?v=2jpN1mSPZ4Q) and see [our manifests](https://github.com/18F/cg-manifests) (and read [this](http://events.linuxfoundation.org/sites/events/files/slides/seven-stages-of-bosh.pdf) for levity)
- [ ] Get to know how UAA is deployed/integrated
- [x] Get familiar with [Terraform](https://www.terraform.io/) by going through the [getting started guide](https://www.terraform.io/intro/getting-started/install.html)
- [x] Learn about [Concourse](https://concourse.ci/) and try a [tutorial](https://github.com/starkandwayne/concourse-tutorial)
- [x] Check out our [staging](https://ci-stage.cloud.gov/) and [production](https://ci.cloud.gov) Concourse instances, and take a look at some of [our pipelines](https://github.com/18F?utf8=%E2%9C%93&query=cg-deploy)
- [x] Join [the Cloud Foundry Slack](http://slack.cloudfoundry.org/)
- [x] Get familiar with our AWS setup

#### Agent Q-specific items
- [ ] Bookmark [the Agent Q kanban board view](https://github.com/18F/cg-product#boards?labels=AgentQ&showPRs=false)
- [ ] Join the #cloud-gov-agent-q channel on Slack
- [ ] Read about Cloud Foundry [services from a user perspective](http://docs.cloudfoundry.org/devguide/services/)
- [ ] Read about [implementing services](http://docs.cloudfoundry.org/services/)
- [ ] Take a look at [our existing brokers](https://github.com/18F?utf8=%E2%9C%93&query=broker)
- [x] Learn about [Concourse](https://concourse.ci/): check out our [staging](https://ci-stage.cloud.gov/) and [production](https://ci.cloud.gov) instances, and take a look at some of [our pipelines](https://github.com/18F?utf8=%E2%9C%93&query=cg-deploy)
- [ ] Join [the Cloud Foundry Slack](http://slack.cloudfoundry.org/)

#### Liberator-specific items

- [x] Join the `#cloud-gov-liberator` channel on Slack
- [x] Ping @standup-bot for instructions on front end channel standup
- [x] Review the main [front end board](https://github.com/18F/cg-dashboard/pulls#boards?repos=55727091,39210774,49169967,40567233&labels=Liberator&showPRs=false) (ensure to filter by the "Liberator" label)
- [x] Bookmark link to [design folder](https://drive.google.com/drive/u/1/folders/0BwLqM4Nicmq-bUt0NjRjclFMUEU)
- [x] Review the primary cloud.gov sites: [the dashboard](https://dashboard.cloud.gov/#/), [main landing page](https://cloud.gov/), and [documentation](https://docs.cloud.gov/).

##### If developing
- [x] Set up the [landing page](https://github.com/18F/cg-landing), [dashboard](https://github.com/18F/cg-dashboard), [docs](https://github.com/18F/cg-docs), and [cg-style](https://github.com/18F/cg-style) locally
- [x] Set up cg-style to be [linked to the other sites locally](https://github.com/18F/cg-style#development-and-contributing-setup).
- [ ] Have cloud.gov person send the cg-dashboard testing env vars through Fugacious
- [ ] Review [dashboard contributing guide](https://github.com/18F/cg-dashboard/CONTRIBUTING.md) and [cg-style standards](https://github.com/18F/cg-style/blob/master/documentation/frontend_standards.md)

##### For review
- Review the [design resource request document](https://docs.google.com/document/d/1s96VP6PB7fbc8g_GwgAZ1hCPmew-J35ZOJx772c1AZ4/edit) if you haven’t already to get a sense of your role on the project
- Review the [design principles](https://docs.google.com/spreadsheets/d/14Y3RKaLUt6RPX5w13iz7oaSCpojEQ-Wqjnd8Ie_VkCc/edit#gid=259774738) to get a sense of how the cloud.gov team feels about the product
- Review the [competitive analysis](https://docs.google.com/spreadsheets/u/1/d/194tGz75NFwFyH8jT7zY_n-O0I7N4yAGYtIG4hw9qPcQ/edit?usp=drive_web) to get a sense of our "competitors" and their dashboards.
- Review the [cg-style styleguide](https://pages.18f.gov/cg-style/) to get a sense of the global cloud.gov visual style.
- Review the [US Web Design Standards](https://standards.usa.gov/) as cg-style was built from it.
- Review the dashboard: current [prod](https://dashboard.cloud.gov/#/), [master](https://dashboard-master.apps.cloud.gov/#/) and [staging](https://dashboard-staging.apps.cloud.gov/#/)
- Review the Cloud Foundry [community UI](http://ui.apps.cloud.gov/), a UI that members of the Cloud Foundry community created and that we're using a basis for our own dashboard design

#### HighBar-specific items
- [x] Bookmark [the HighBar kanban board view](https://github.com/18F/cg-product#boards?labels=HighBar&showPRs=false)
- [x] Make sure you join the #cloud-gov-highbar channel on Slack
- [ ] Read through the description of [Compliance Toolkit](https://github.com/18F/compliance-toolkit/#readme)
- [ ] Watch [Handling FISMA Faster and Better](https://www.youtube.com/watch?v=T1S52B1-NT4) for important context and background on the federal regulatory context in which cloud.gov operates.
- [x] Do a cursory read of [Before You Ship](https://pages.18f.gov/before-you-ship/)
- [x] Read [the intro to Compliance Masonry](https://github.com/opencontrol/compliance-masonry#readme)

---
## Buddy checklist
- [x] Introduce yourself to the new team member and give them some of your background so they know who you are
- [x] Identify a straightforward, well-groomed story in progress that involves their skills domain, schedule a meeting with the owner for an introduction (if it's not you), and setup pairing sessions several times in the first week on the project.
- [x] Identify a straightforward, well-groomed first story, ideally something they could conceivably complete in their first two/three weeks using their existing skills. Discuss the context with them, then make them the assignee for the card.
- [x] Make suggestions for how the onboarding experience could have been improved as PRs on [the onboarding template](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md).

### Required items for all team members

These items help us fulfill security and compliance requirements (including for FedRAMP).

- [x] Make sure they're in [the list of people working on the project](https://docs.google.com/spreadsheets/d/1mW3tphZ98ExmMxLHPogSpTq8DzYr5Oh8_SHnOTvjRWM/edit#gid=0)
- [x] Add them to the @cloud-gov-team in Slack’s Team Directory (which also adds them to the right channels)
- [ ] Add them to the recurring cloud.gov meetings that are relevant for them in [the team calendar](https://calendar.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks@group.calendar.google.com&ctz=America/Los_Angeles)
- [x] Ask `#admins-github` to add them to the [@18F/cloud.gov team](https://github.com/orgs/18F/teams/cloud-gov) on GitHub

### Atlas-specific required items

- [x] Help them review and understand the responsibilities of becoming a Cloud Operations team member, as listed in our SSP
- [x] Ask `#admins-github` to have them added to the [@18F/cloud-gov-ops](https://github.com/orgs/18F/teams/cloud-gov-ops) team on GitHub **(For contractors: Confirm they have cleared GSA security review before doing this one!)**
- [ ] If the new person is a contractor, ask `#admins-github` to have them added to the [@18F/cloud-gov-contractors](https://github.com/orgs/18F/teams/cloud-gov-contractors) team on GitHub
- [x] Grant them access to the following: AWS GovCloud, Nessus Manager GUI, New Relic, PagerDuty, StatusPage
- [x] [Make them an admin](https://docs.cloud.gov/ops/managing-users/#managing-admins) of the platform
- [x] Take them through [AWS onboarding](https://docs.cloud.gov/ops/aws-onboarding/)
- [x] Give them a walkthrough of cloud.gov from an architecture and repository perspective

**Comment by rogeruiz** [comment]
Will pair with @jbarnicle on the following 

#### Atlas
> - Take them through AWS onboarding
> -  Set up Cloud Foundry locally and push an app to it

#### Highbar
> - Watch Handling FISMA Faster and Better for important context and background on the federal regulatory context in which cloud.gov operates.

#### Liberator
> - Set up the landing page, dashboard, docs, and cg-style locally
> - Set up cg-style to be linked to the other sites locally.
> - Have cloud.gov person send the cg-dashboard testing env vars through Fugacious
> - Review dashboard contributing guide and cg-style standards

**Comment by rogeruiz** [comment]
Let's ~~add~~_evaluate_ [the Pivotal Training](https://www.cloudfoundry.org/cloud-foundry-foundation-and-pivotal-to-open-source-training-materials) that was mentioned [in Slack](https://gsa-tts.slack.com/archives/cloud-gov/p1474482489000504)

**Comment by rogeruiz** [comment]
@mogul I don't seem to have access to this calendar. 

> - Subscribe to the cloud.gov team calendar (click the + in the bottom right) so you know when assorted team meetings are happening in the various streams

**Comment by rogeruiz** [comment]
Ran into a _real fun_ error on the UAA side... Steps to reproduce below. I definitely need help here.

```
$ uaac token client get admin -s <MANIFEST_SECRET_FROM_JUMPBOX>

Successfully fetched token via client credentials grant.
Target: https://uaa.fr.cloud.gov
Context: admin, from client admin
```

Which works great. And then when I tried to fetch my own user to check the scope. I get the following error.

```
$ uaac user get roger.ruiz@gsa.gov

CF::UAA::BadResponse: CF::UAA::BadResponse
```

I'm a 😢 🍌 right now, but I'm not sure what it's related too. I also can't seem to delete my user either.

```
uaac user delete roger.ruiz@gsa.gov

CF::UAA::NotFound: roger.ruiz@gsa.gov not found in https://uaa.fr.cloud.gov/Users

```

Which is really strange. But I do come up in the list of users with the following.

```
$ uaac users -a name | grep -B3 roger
  -
    name
      familyname: gsa.gov
      givenname: roger.ruiz

```

**Comment by rogeruiz** [comment]
The above ☝️ was related to user error in reading the docs here on [creating admins](https://docs.cloud.gov/ops/managing-users/#creating-admins). Don't target the wrong UAA server when using `uaac` scripts because you're gonna have a bad time.

![read-the-docs](https://cloud.githubusercontent.com/assets/706004/19162632/a616cc8c-8bc6-11e6-82bb-0b9870df2320.jpg)

**Comment by mogul** [comment]
Sorted!

> @mogul I don't seem to have access to this calendar. 
> 
> > - Subscribe to the cloud.gov team calendar (click the + in the bottom right) so you know when assorted team meetings are happening in the various streams

**Comment by rogeruiz** [comment]
Something that would be great to bring up in onboarding is some sort of dashboard of things that _you need to know_ on your particular theme. I'll reach out to other themes to get updates, but there should definitely be something along the lines of this.

---

#### Bookmarks to check
- Concourse
- docs.cloud.gov
- Atlas Github Board
- _current card on the board_ ( updated as necessary )
- etc...etc...

**Comment by rogeruiz** [comment]
Leaving this open until I bring my opinions into the onboarding checklist from above. Giving myself a deadline of 3 days.
