### ISSUE TITLE
Capture point-in-time representation of referenced docs

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#336]
In order to make the SSP easier to read and ensure reviewers see the version we intended, we should include a static capture of any referenced GSA policy documents in our SSP package.

**Acceptance Criteria**

- [ ] It's possible for a reviewer to read any referenced GSA policy doc without following a URL away from the submitted SSP materials

**Implementation sketch**

- Start by searching for the word "policy"
- Look under "Directives" on InSite

**Comment by brittag** [comment]
I've put together [a list of the SSP's references to InSite documents](https://docs.google.com/document/d/1rfEvo9uqByyzcLrTuQ5TeH3x2-y1c3Xy2p5BSICoxNE/edit), with direct links to the PDFs and Word docs. Some of these are referenced from old-style -1 control statements, so we may want to check whether we're keeping those statements before putting together the PDF "book".

I also noticed as part of this process that the SSP's references to those documents are inconsistent - different parts of the SSP use slightly different names for the same document.

**Comment by mogul** [comment]
(Assigned @NoahKunin as he said that's the best way to get his attention on a GitHub issue.)

@NoahKunin can you verify whether the old-style -1 control statements are staying or going at this point?

**Comment by brittag** [comment]
Just based on my notes in the doc, I made a folder of these InSite docs at https://drive.google.com/drive/u/0/folders/0B1cewEqKcWCba2I5UnlKLWZ3eHc (with some files renamed to include context) - so that's ready to be shipped with the SSP, if we shipped the SSP as-is.

**Comment by NoahKunin** [comment]
Looks like this was resolved by the briefing book. Closing it out!
