### ISSUE TITLE
Ensure SSP diagrams are legible and understandable

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#337]
In order to ensure our new [code-driven diagrams](https://diagrams.fr.cloud.gov/) are properly understood by JAB technical reviewers, we want to ensure they appear in a legible and easy-to-understand form in the SSP.

**Acceptance Criteria**
- [x] Exported PNGs are as legible offline as they are on diagrams.fr.cloud.gov
- [x] Boundaries are clearly visible against the background
- [x] Fix arrow in 10-1: AWS console should be bidirectional with Cloud Operations
- [x] Fix arrow in 10-1: Reverse Cloudability/API arrow
- [x] Fix 10-4.1, which appears to not be rendering correctly
- [x] Fix 10-4.3 layout to have fewer overlapping arrows
- [ ] ~~Meet 508 compliance needs~~ 👀 18F/cg-diagrams#10

**Implementation Sketch**

- Get the source out of Adam's hands so other people can update the source if needed
- Adjust CSS to ensure borders and background show up well, particularly when printed 18F/cg-diagrams#12
- Fix PNG export if possible 18F/cg-diagrams#12

**Comment by rogeruiz** [comment]
Once 18F/cg-diagrams#12 lands on `master`, the following issue should be addressed.
>  Exported PNGs are as legible offline as they are on diagrams.fr.cloud.gov 
>  Boundaries are clearly visible against the background

**Comment by rogeruiz** [comment]
I believe that following item is being addressed by splitting up the diagrams even further and linking between them. Is that right, @afeld?
> -  Fix 10-4.3 layout to have fewer overlapping arrows

**Comment by afeld** [comment]
Yep! Moved to https://github.com/18F/cg-diagrams/issues/13.

**Comment by mogul** [comment]
(Please reference this issue in other issues and PRs so they'll show up here.)

**Comment by afeld** [comment]
Left some open issues in https://github.com/18F/cg-diagrams/issues, but I think we can call this "good enough for now".
