### ISSUE TITLE
Ramp up Mike Jacobi on cloud.gov team

### ISSUE THREAD

**Issue by sushiandbeer** [18F/cg-product#34]
In order to get Mike Jacobi productively contributing to the cloud.gov team, Buddy should help Mike complete a prescribed set of tasks that will bring them up to speed.

# Directions:
**Mike and Buddy:** Try to go through your checklists in order.
**Buddy:** If you can’t complete any of the items on your checklist personally, _you are responsible for ensuring that an appropriate person does it_.

## New Person checklist
- [x] Take judicious notes on what about this onboarding process or cloud.gov is confusing or frustrating. If you notice a problem (especially with things like documentation), you are more than welcome to fix it! At the very least, please share this information with your buddy (or someone) at some point so we can make the team/platform better.
- [ ] Figure out who your onboarding buddy is (they should reach out to you) and make sure this issue should be assigned to them)
- [x] Read [the team onboarding document](https://github.com/18F/cg-product/blob/master/Onboarding.md) for more context about cloud.gov
- [ ] Read the ["What is it?"](https://docs.google.com/presentation/d/1nCcti3dXG9TVGW3OqaWtnf96oXX8U8SBTM_WePFO_dg/edit#slide=id.p) presentation for a rundown of what cloud.gov is and does
- [x] Read through [the Introduction section of docs.cloud.gov](https://docs.cloud.gov/) for a broader understanding of cloud.gov, especially as we present it to potential customers/users
- [ ] Read the [January 2016 cloud.gov "Executive Business Case" document](https://docs.google.com/document/d/138OcG0Lt6gr9J0wM0TzzPNyTROmYAwfLIDujtweiwGw/edit#) for greater context about cloud.gov's potential impact in government
- [ ] Try to [deploy a sample application to cloud.gov](https://docs.cloud.gov/getting-started/your-first-deploy/) to get familiar with the basics of the PaaS from a user's perspective
- [x] Check out the [roadmap](https://18f.aha.io/published/068c364a0302b89521045f9fbd258374) to get a high-level view of recently-completed, in-progress, and upcoming features
- [x] Install the [ZenHub](https://zenhub.io) browser extension to enable you to see kanban boards, hierarchical issues, and burndown charts in GitHub
- [x] Read the [Delivery Process document](https://github.com/18F/cg-product/blob/master/DeliveryProcess.md) to learn about how we work
- [x] Subscribe to [the cloud.gov team calendar](https://calendar.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks@group.calendar.google.com&ctz=America/Los_Angeles) (click the + in the bottom right) so you know when assorted team meetings are happening in the various streams
- [ ] Join [the cloud.gov support Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov-support), so you can see how we handle non-18F support and get visibility of technical discussions happening with outside groups
- [x] Figure out what streams you're likely to work in, and complete the checklist below that relates to it
- [ ] Once you've finished the remaining checklists below, make suggestions for steps that would have improved your onboarding experience as pull-requests on [the onboarding checklist template](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md) used to make this issue

### Atlas-specific items
- [x] Bookmark [the Atlas kanban board view](https://github.com/18F/cg-product#boards?repos=55727091,56184868&showPRs=false)
- [x] Make sure you join the #cloud-gov-atlas channel on Slack
- [x] Watch [Build Your Own Private Cloud Foundry](https://www.youtube.com/watch?v=v85r4Hy3jbs) to learn about running Cloud Foundry
- [x] [Set up Cloud Foundry locally](https://docs.cloud.gov/ops/creating-a-local-dev-environment-in-Virtual-Box/) and push an app to it
- [x] Learn about [BOSH](http://bosh.io/): Watch [this video](https://www.youtube.com/watch?v=2jpN1mSPZ4Q) and see [our manifests](https://github.com/18F/cg-manifests) (and read [this](http://events.linuxfoundation.org/sites/events/files/slides/seven-stages-of-bosh.pdf) for levity)
- [ ] Get to know how UAA is deployed/integrated _(TODO: We need a link here)_
- [x] Learn about [Concourse](https://concourse.ci/) and try a [tutorial](https://github.com/starkandwayne/concourse-tutorial)
- [ ] Check out our [staging](https://ci-stage.cloud.gov/) and [production](https://ci.cloud.gov) Concourse instances, and take a look at some of [our pipelines](https://github.com/18F?utf8=%E2%9C%93&query=cg-deploy)
- [x] Join [the Cloud Foundry Slack](http://slack.cloudfoundry.org/)
- [x] Get familiar with AWS in general if you're not already _(TODO: We need some pointers here)_

---
## Buddy checklist
- [x] Introduce yourself to the new team member and give them some of your background so they know who you are
- [ ] Make sure they're listed in [the list of people working on the project](https://docs.google.com/spreadsheets/d/1mW3tphZ98ExmMxLHPogSpTq8DzYr5Oh8_SHnOTvjRWM/edit#gid=0)
- [ ] Add them to the @cloud-gov-team in Slack’s Team Directory (which also adds them to the right channels)
- [ ] Add them to the recurring cloud.gov meetings that are relevant for them in [the team calendar](https://calendar.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks@group.calendar.google.com&ctz=America/Los_Angeles)
- [x] Setup a cloud.gov user account for them via [the “send an invite” page](https://invite.cloud.gov)
- [ ] Identify a straightforward, well-groomed story in progress that involves their skills domain, schedule a meeting with the owner for an introduction (if it's not you), and setup pairing sessions several times in the first week on the project.
- [ ] Identify a straightforward, well-groomed first story, ideally something they could conceivably complete in their first two/three weeks using their existing skills. Discuss the context with them, then make them the assignee for the card.
- [ ] Make suggestions for how your onboarding experience could have been improved as comments on [the onboarding template card](https://trello.com/c/0AJyOrxG/649-template-ramp-up-newperson-on-cloud-gov-team).
- [ ] Ask `#admins-github` to have them added to the [@18F/cloud.gov team](https://github.com/orgs/18F/teams/cloud-gov) on GitHub

### Atlas-specific items
- [ ] Ask `#admins-github` to have them added to the [@18F/devops-staff](https://github.com/orgs/18F/teams/cloud-gov-ops) team on GitHub
- [ ] If the new person is a contractor, ask `#admins-github` to have them added to the [@18F/devops-staff](https://github.com/orgs/18F/teams/cloud-gov-contractors) team on GitHub
- [ ] Grant them access to the following (where applicable): AWS, New Relic, PagerDuty, StatusPage
- [ ] Take them through [AWS onboarding](https://docs.cloud.gov/ops/aws-onboarding/) (if applicable)
- [x] Give them a walkthrough of cloud.gov from an architecture perspective

**Comment by sushiandbeer** [comment]
@mogul: I've requested access to these resources several times as we discussed in a couple/few meetings.  How can we rectify this?

1. Cannot view https://handbook.18f.gov/#teams referenced in https://github.com/18F/cg-product/blob/master/Onboarding.md  No GSA account.
2. Could not access the “cloud.gov team roster sheet” referenced in the onboarding doc.  Requested access to the Google Drive.
3. Could not access the "What is it?" presentation.  Requested access to the Google Drive.
4. Cannot login to cloud.gov support group at Google Groups:
> Authorization Failed
> This group is on a private domain.
> Please sign in with an authorized account to view this content.

**Comment by sushiandbeer** [comment]
@mogul: I've requested a buddy several times per the task above, titled, "Figure out who your onboarding buddy is (they should reach out to you) and make sure this issue should be assigned to them)"  No one is volunteering and no one has been assigned.  Should I just disregard this task?

**Comment by sushiandbeer** [comment]
@mogul: I apparently need a GSA account in order to access the FedRAMP Cloud Foundry instance.  I can imagine I need it to access other resources as well.  How can we make this happen?  @dlapiduz and I had chatted about it last week, but I thought I should document that here.

**Comment by sushiandbeer** [comment]
@mogul: What Slack channels should I monitor?

**Comment by sushiandbeer** [comment]
Regarding the next to last item, I can confirm I do indeed need an AWS account.  This is critical, for example, to be able to view instance state and logs when debugging stemcell creation issues.

**Comment by rogeruiz** [comment]
Closing for now, since some parts of onboarding may need to be re-evaluated. We can reopen this later.
