### ISSUE TITLE
Website improvement for visitors arriving after FedRAMP outreach campaign

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#346]
two week period during which we focus on getting the website in better shape for our outreach efforts. @berndverst and @jameshupp taking the lead.

Some items on the list include:
- Landing page needs more focus
- Understanding of offering, pricing, including deep dive into compliance etc
- No non-technical content in (tech) docs! / developer section

But that list above is not exclusive! They might make even more improvements depending on their visions . . .

**Comment by nikzei** [comment]
Docs section can feel confusing, partly because docs listed do not all have the same intended users. We list docs for our internal team as well as docs for our users - without clear distinction (if one finds a doc page via a keyword search, it's very easy to end up for a user to end up relying on docs that are for the internal team, for example).

To do:
Revisit whether internal documentation should live on this docs page rather than just on GitHub. Let's get clearer on benefits/detriments. @berndverst and I are not convinced that they should be here.

@mogul, @dlapiduz

**Comment by brittag** [comment]
@nikzei We have a related issue filed at https://github.com/18F/cg-docs/issues/333 ("Separate cloud.gov user documentation from contribution documentation") - although just an Icebox idea without specific action items. We also may have the option of keeping ops/team documentation in Hugo (instead of moving it to GitHub) but separating it from the user documentation in a UX sense.

**Comment by nikzei** [comment]
For you both to consider when you work on this:

The website isn't easy to use for someone going there to purchase services. Our communications seem geared for a pre-sales phase and need to be adjusted so that they match where we are now, which is the beginning of an active sales phase. 

For example, our contact description line is "Sign up for updates about the availability of cloud.gov from 18F," rather than something like, "if you are interested in purchasing cloud.gov services, send us an email with the following information" or whatever.

**Comment by nikzei** [comment]
Another thing:
Responsibility of tenants - I can't find this in my 3 minute search through the docs. I know that we have plans to do this in a much more thorough way (see #300), but that's not in progress for the next while.

In making our site more customer friendly, we should state that the tenant has the responsibility to get ATO for their application layer. This is important for potential customers to understand from the onset.

**Comment by nikzei** [comment]
from @brittag in #300: a page illustrating customer responsibilities: https://docs.cloud.gov/intro/technology/responsibilities/
cc: @jameshupp, @berndverst

**Comment by nikzei** [comment]
Based on conversation w @berndverst  and @mogul: 

Regarding a "What’s included page:"
- We will not be responsible for application logic, unless we made changes to the application beforehand
- Deprecation: since our IAAs are a 12 month term, should we make 12 month deprecation plan? 
- We'll provide configuration federation if you have SAML metadata for your IDP (Identity Provider) 
         - We have this in ops docs, but we need to have this up for customers to see as related to    SOW terms

**Comment by nikzei** [comment]
This is for Sprint 1, ending on 11/2.

@jameshupp @berndverst

**Comment by nikzei** [comment]
The overview page should offer an introduction to cloud.gov that might help a prospective customer or other interested party understand the basics of our offerings and possibly point attention to the pages listed in the overview menu on the left (pricing, security, technology). 

Currently, https://cloud.gov/overview/ is the same page as https://cloud.gov/docs/, which offers an introduction to those already using and contributing to cloud.gov. We need to draft the overview so that it speaks to an audience that is not yet using or contributing to cloud.gov.

ht to @jameshupp for catching this. cc @berndverst

**Comment by berndverst** [comment]
Little side note:
Quickly update technical docs with S3 public access info in GovCloud based on https://gsa-tts.slack.com/archives/cloud-gov-support/p1477439493002940

**Comment by afeld** [comment]
Moved the S3 thing to https://github.com/18F/cg-docs/issues/490.

**Comment by mogul** [comment]
Just want to chime in late to agree with this: 

> We also may have the option of keeping ops/team documentation in Hugo (instead of moving it to just GitHub) but separating it from the user documentation in a UX sense.

...and plug again for having redirects to wherever we move it. There's a lot of stuff pointing to operator docs now for compliance purposes, and the version control history in GitHub is important to maintain. (Please **don't** take this post as me saying "don't change it"! I'm all in favor of greater separation/a separate URL, and a link from a "contributing" page to the new location as Britta suggested would be ideal.)

**Comment by dlapiduz** [comment]
To be honest, I'd rather keep the docs as part of the main site rather than having it only in github. We can make it so its not linked directly from the docs page but its just a new section.

**Comment by nikzei** [comment]
[Notes](https://docs.google.com/a/gsa.gov/document/d/1snPsfFvZdredvuaTPfrXAPS258UDoRSoZkj2WtgLHm8/edit?usp=sharing) from our brainstorming session 11/16.

**Comment by nikzei** [comment]
Currently, we only talk about our different packages[ in the context of how much they cost](https://cloud.gov/overview/pricing/rates/). Might be good to have a page where we describe the value proposition for each package? 

Related to this, see #257 re: presenting the value proposition of our prototyping account.

**Comment by nikzei** [comment]
See https://github.com/18F/cg-site/issues/405

During our 11/16 brainstorm, @brittag mentioned including examples of tech that we support and tech that we don't (for example, "if you're using an Oracle database, we're likely not a match for you"). Dropping this here for quick reference.

**Comment by nikzei** [comment]
PI8 75% assessment:
MUST
--> this is work that must be completed in time for FedRAMP authorization anticipated to happen at the end of the PI.

**Comment by jameshupp** [comment]
I'd like to close this, as there's a lot more specificity in #627 which addresses a lot of the exact same user needs. It also keeps user feedback in the picture more clearly. Objections?

**Comment by nikzei** [comment]
No objections - let's close it.
