### ISSUE TITLE
Create whitelist of users for migration bot

### ISSUE THREAD

**Issue by jbarnicle** [18F/cg-product#349]
We are holding off on deploying the migration bot on govcloud until we are in a better position to migrate users / orgs / spaces / apps.  In the meantime, we need the ability to migrate selected users for early adopters.  

[ ] Add whitelist of email addresses as an env variable
[ ] Deploy to migration to production govcloud (PR to merge staging branch to master branch in GH)

**Comment by afeld** [comment]
Issue moved to [18F/cg-migration-bot #12](https://github.com/18F/cg-migration-bot/issues/12) via [**ZenHub**](https://www.zenhub.com/)
