### ISSUE TITLE
Upgrade all schema_versions from 2.0.0 to 3.0.0

### ISSUE THREAD

**Issue by rogeruiz** [18F/cg-product#35]
The schema versions for `2.0.0` contain breaking changes for version `3.0.0` 
and need to be updated. While we're filling out the SSP, this work is necessary 
since it will help in reviewing the content of the SSPs in `18F/cg-compliance` 
that have been finished.

- [x] `CICloudGov/component.yaml|15 col 1| schema_version: 2.0`
    - https://github.com/18F/cg-compliance/pull/124
- [x] `CloudCheckr/component.yaml|127 col 1| schema_version: 2.0`
    - https://github.com/18F/cg-compliance/pull/125
- [x] `CP_Policy/component.yaml|13 col 1| schema_version: 2.0`
    - https://github.com/18F/cg-compliance/pull/126
- [x] `ELKStack/component.yaml|89 col 1| schema_version: 2.0`
    - https://github.com/18F/cg-compliance/pull/127
- [x] `JumpBox/component.yaml|115 col 1| schema_version: 2.0`
    - https://github.com/18F/cg-compliance/pull/129
- [x] `MA_Policy/component.yaml|9 col 1| schema_version: 2.0`
    - https://github.com/18F/cg-compliance/pull/130
- [x] `MP_Policy/component.yaml|9 col 1| schema_version: 2.0`
    - https://github.com/18F/cg-compliance/pull/131
- [x] `PE_Policy/component.yaml|9 col 1| schema_version: 2.0`
    - https://github.com/18F/cg-compliance/pull/132
- [x] `PL_Policy/component.yaml|34 col 1| schema_version: 2.0`
    - https://github.com/18F/cg-compliance/pull/133
- [x] `PS_Policy/component.yaml|9 col 1| schema_version: 2.0`
    - https://github.com/18F/cg-compliance/pull/134
- [x] `RA_Policy/component.yaml|34 col 1| schema_version: 2.0`
    - https://github.com/18F/cg-compliance/pull/135
- [x] `SC_Policy/component.yaml|29 col 1| schema_version: 2.0`

cc: @jcscottiii @afeld @jbarnicle @frsfx @clovett3

**Comment by rogeruiz** [comment]
CM_Policy has been done here 18F/cg-compliance#113

**Comment by jbarnicle** [comment]
SC_Policy has been done here https://github.com/18F/cg-compliance/pull/115

**Comment by rogeruiz** [comment]
Alrighty, all the items I marked above are done / ready for review.

**Comment by afeld** [comment]
Thanks so much for doing all of that!
