### ISSUE TITLE
Remove Julia from cloud.gov team

### ISSUE THREAD

**Issue by suprenant** [18F/cg-product#350]
In order to complete @juliaelman exit from the cloud.gov team, the assignee should complete a prescribed set of tasks that will remove any special access.

# Directions:
**Assignee:** If you can’t complete any of the items on your checklist personally, _you are responsible for ensuring that an appropriate person does it_.

### For people leaving the team
- [x] Remove them from the project in Float
- [x] Remove them from [GitHub teams that start with cloud-gov](https://github.com/orgs/18F/teams?utf8=%E2%9C%93&query=cloud-gov)
- [x] Remove them from [the cloud.gov team Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov)
- [x] Remove them from [the cloud.gov support Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov-support)
- [x] Remove them from [the cloud.gov inquiries Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov-inquiries)
- [x] Remove them from the @cloud-gov-team in the Slack Team Directory
- [x] Remove them from any IAM roles they hold in AWS
- [x] Remove them from [the list of people working on the project](https://docs.google.com/spreadsheets/d/1mW3tphZ98ExmMxLHPogSpTq8DzYr5Oh8_SHnOTvjRWM/edit#gid=0)
- [x] Remove them as invitees for any meetings on the cloud.gov calendar
- [x] Remove any special Org or Space roles that their cloud.gov account holds
- [x] Remove their access via the operator UAA
- [x] Remove their admin scope in the Cloud Foundry UAA
- [x] Remove their access to StatusPage
- [x] Remove their access to PagerDuty
- [x] Remove their access to New Relic
- [x] Remove their access to [Aha!](https://18f.aha.io)
- [x] Remove their membership in cloud.gov-specific Trello boards (eg the business-tracker)
- [x] Ensure any keys they had direct access to are rotated

**Comment by suprenant** [comment]
@mogul I tackled a few of these but would need admin access for a few others. Can you help here or let me know who might be able to?

**Comment by suprenant** [comment]
Checked with Bret, he'll follow up here before too long

**Comment by mogul** [comment]
All set!

**Comment by suprenant** [comment]
Awesome! Thanks
