### ISSUE TITLE
Develop approach to consolidate strategic docs/assets/deliverables into a wiki

### ISSUE THREAD

**Issue by thisisdano** [18F/cg-product#352]
We have all kinds of strategic docs — docs on our users, research, goals, competitive analysis, design strategy, interviews, etc. — but they're all over the place, in different folders and systems. I'd like to take a crack at using a repo wiki to be a place to coordinate and consolidate this documentation.

Acceptance criteria: 
- [x] Create artifact articulating preliminary strategy
- [ ] Schedule time to meet and discuss with the team

**Comment by suprenant** [comment]
Could be cross-program interest

**Comment by thisisdano** [comment]
First step: auditing what's in the Google Drive
https://docs.google.com/a/gsa.gov/spreadsheets/d/1Zg5LciEeJFjtjBhdmHD2bvNiUemFG7Rn2e3ekT15a_4/edit?usp=sharing

I've gone through and listed what's in the drive — now I'd like to look through some of it and think about how we'd develop a higher-level framework to point to this documentation.

**Comment by brittag** [comment]
This is a cool idea! I probably wouldn't be able to devote a lot of time to this since I have to prioritize HighBar work, but I'm interested in helping think about effective ways to do this.

I'd encourage maintaining this as files in git (aka in the normal GitHub repository style) instead of a GitHub wiki, since our cloud.gov team currently primarily uses git + pull requests as a collaboration style. :)

**Comment by thisisdano** [comment]
I don't think I know how a wiki would work as files. Might need more discussion — the important thing for me is structure and ease of use. — With the overall goal that the project has some kind of shape, reasoning that is clear and available, an easy way to access primary documention, and a reason that the documents exist.

**Comment by thisisdano** [comment]
Having a wiki in GH seems 1. very achievable as MVP for this idea; 2. Very easy to find/read

**Comment by brittag** [comment]
I imagine that we could do this similar to how https://github.com/18F/cg-product works - it has a collection of .md files that we maintain with PRs, and there's an index file (in this case the README) with an explanation of purpose and an overview of the contents. It's nice that we use PRs to maintain this, since it means that anyone interested in a page can get notifications (and has an opportunity to give input before it gets merged). I don't think that GitHub wikis have a built-in feature right now to allow people on the team to get notified when a person makes a change.

**Comment by thisisdano** [comment]
Thinking through this here: https://github.com/18F/cg-product/wiki

**Comment by suprenant** [comment]
@thisisdano FYI I updated the title to rein in the scope here and also updated the acceptance criteria.

**Comment by thisisdano** [comment]
Merrily we sprint along, tirelessly iterating with boundless agility. Toward what goal? Ha! We know better than to chase anything so prescriptive as a goal for anything as important as a project! But still, even as we eschew the rigidity of a long-term predefined endpoint we still must consider the reason we make the decisions we do make on a day-to-day basis and the principles that help us evaluate these decisions.

I wanted to think about how we know what we know and save the present and future team from the duplicative effort of having to learn our principles individually and idiosyncratically. I wanted to help communicate what we believe and what we value.

Unfortunately, I've found that if these statements of principle and value exist, they're in the product documentation, other apps, buried in the catacombs of a google drive, hidden in slide 12 of a presentation, or only exist tacitly and have never been explicitly addressed in any documentation. And if and when they _do_ exist, how do they relate to each other? What's the research behind this user need? How does Business Goal B relate to that user need?  How do our design principles relate to the those user needs, our body of research, our business goals, our competitive marketplace, and any established aesthetic tone?

What I'm hoping to try and develop is a common place for the assets, documents, and other artifacts (or links to them!) that help us make decisions that reflect our common priorities, regardless of individual skillset.

These kinds of things program-level docs like:

- Why cloud.gov exists
- Market analysis
- Users and needs
- Mission statement
- Product values, keywords, attributes
- Product roadmap and key features
- User stories

Design-focused documents that draw on that framework: 

- Design principles
- Style tiles
- Flows, feedback, and interaction
- Information architecture
- Wireframes/prototypes
- Framework
- Pattern library

On general findings like: 

- User research
- Blog posts
- Presentations

A wiki is a nice, easy-to-navigate, low-overhead way to add new findings to the common store. What it lacks in tracking and discussions, it gains in speed, simplicity, and lessened cognitive overhead. Good wiki citizens would probably open issues for serious edits, changes, or other actions that would be better served by more communication! But really, it matters less about the specific where and how than about the _principles_ behind the idea: that the team benefits from a common location for a coherent framework of values and reasoning; and that it's more valuable when it's used.

I've sketched out the outline of this kind of wiki at https://github.com/18F/cg-product/wiki

I'm also very interested in talking through this idea with anyone who feels it might be of value.

**Comment by suprenant** [comment]
I'll set up time with @thisisdano and possibly others, if interested, to discuss!

**Comment by suprenant** [comment]
Scheduled meeting for next Thursday. Closing this up.
