### ISSUE TITLE
[spike] Make a demo of compliance data displayed in the eRegs UI

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#354]
In order for our team and our target users (or proxies for our target users) to give feedback on whether the eRegs UI helps them read complex compliance documentation, we need to build a simple demo that people can click around and try out.

**Implementation sketch:**

This could be as simple as a static HTML demo (perhaps hosted in a cloud.gov sandbox space, using the static buildpack...) where we manually stick compliance information into a static copy of the eRegs frontend. This will partly depend on our technical research (https://github.com/18F/cg-product/issues/353).

**Acceptance criteria:**

A reader can look at and click around eRegs-style pages that show:

- [ ] Part of a SSP frontmatter section (loosely structured content)
- [x] A few controls from a SSP control family (highly structured content)
- [ ] A sidebar cross reference to another part of the SSP
- [x] A sidebar definition
- [x] A diff

Nice to have:
- [ ] A search page
- [ ] A commenting interface (although keeping in mind that eRegs has two separate varieties: sidebar with context _or_ sidebar with commenting)

**Comment by mogul** [comment]
Did this one get done?

**Comment by brittag** [comment]
We have a demo live with data, definitions, and a diff! [URLs are in Slack here.](https://gsa-tts.slack.com/archives/cloud-gov-highbar/p1476751990004222)

I think this story counts as complete for the purposes of the research sprint.
