### ISSUE TITLE
[spike] Get feedback on demo of compliance data displayed in the eRegs UI

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#355]
In order for us to decide whether we should pursue the idea of displaying compliance data with the eRegs UI, we need feedback on a live demo from key target users (or proxies for target users): auditors and compliance reviewers.

**Implementation sketch:**

We need to find people who either _are_ our auditors and compliance reviewers, or who have that kind of experience and can provide a similar perspective. We should figure out whether we can ask for a little bit of time (aka a ~15 minute videocall/screenshare) from somebody at our 3PAO, the GSA CIO office, etc., to look at a demo and tell us whether eRegs-style compliance info would be helpful to them (or whether they actually prefer a straightforward linear Word doc).

**Acceptance criteria**

We've chatted with somebody who can represent the following perspectives, and we have notes from the conversation in a doc in Google Drive:
- [ ] A compliance reviewer perspective (such as a JAB TR perspective or equivalent)
- [ ] An auditor perspective (such as a FedRAMP 3PAO perspective or equivalent)

Nice to have:
- [ ] An authorizing official perspective
- [ ] A FedRAMP PMO perspective

**Comment by afeld** [comment]
I know of a couple of people who deal with ATOs for GSA...would be great to talk to the JAB, or potentially people from other agencies. I'll send some emails.

**Comment by afeld** [comment]
@brittag Are you ok reaching out to Bridget to see if we can get some time with the JAB?

**Comment by afeld** [comment]
Let's wait to reach out until next week or the one after, so we have a little time to put some polish on it if we want.

**Comment by brittag** [comment]
We have a basic demo linked in the comments of https://github.com/18F/cg-product/issues/354 - I'm guessing though that we should icebox this for now, since we may not get time soon to get informal feedback on it.

**Comment by brittag** [comment]
Moving this back to "ready" since we'll look for informal feedback at the OpenControl Summit this week. :D

**Comment by mogul** [comment]
Do we have notes on how the demo at the OpenControl event went?

**Comment by afeld** [comment]
Even better - we have a recording! https://vimeo.com/188888704

**Comment by mogul** [comment]
I jumped straight to the demo... Who's the female voice commenting at 44:00
to 46:00?

**Comment by afeld** [comment]
Someone from the FedRAMP team.

**Comment by mogul** [comment]
Anyone in favor of keeping this open? I feel like we have the feedback we can afford to seek/respond to at this point. Otherwise I'll close.

**Comment by afeld** [comment]
I think we got out of it what we wanted to...closing.
