### ISSUE TITLE
CloudFoundry-l-ELB-YWDSV69AFFFK needs to be updated or deleted

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#358]
Currently uses invalid certificate
<img width="420" alt="screen shot 2016-10-11 at 9 58 17 am" src="https://cloud.githubusercontent.com/assets/95657/19273173/87d7858c-8f99-11e6-8610-162b3d559c22.png">

**Comment by rogeruiz** [comment]
Not sure what it is, but seems unrelated to CF or anything FR related. Might be specific to a partner agency. @dlapiduz ?

**Comment by dlapiduz** [comment]
This was the first ELB for CF. Deleting it was long overdue but I am a melancholic person.

Here is proof for posterity on what it was:

<img width="1017" alt="screen shot 2016-10-16 at 10 47 12 pm" src="https://cloud.githubusercontent.com/assets/4604/19424868/a2cb3106-93f2-11e6-9d0b-59d41b57585e.png">

**Comment by rogeruiz** [comment]
Thanks @dlapiduz!
