### ISSUE TITLE
cf-app-router needs to be updated or deleted

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#359]
<img width="437" alt="screen shot 2016-10-11 at 10 01 41 am" src="https://cloud.githubusercontent.com/assets/95657/19273243/c314fb02-8f99-11e6-90a4-465cf9cee8f2.png">

**Comment by rogeruiz** [comment]
This should be done.

**Comment by dlapiduz** [comment]
Deleted it...

**Comment by dlapiduz** [comment]
deleted it
