### ISSUE TITLE
Deprecate OpenFOIA ELB

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#360]
Should this be named something referencing FOIA?  Is that the only client?

**Comment by rogeruiz** [comment]
Not sure what it is, but seems unrelated to CF or anything FR related. Might be specific to a partner agency. @dlapiduz ?

**Comment by dlapiduz** [comment]
This is the Open FOIA ELB, given that we will have to move them to GovCloud soon I'd say lets not mess with it. Not sure how it got that name but we can't rename it.

**Comment by mogul** [comment]
Should this be marked blocked and move back to the `Backlog` pending GovCloud activity?

**Comment by mogul** [comment]
This should be closed just be migrating OpenFOIA to GovCloud, so I'm attaching it to that epic and marking it blocked.

**Comment by afeld** [comment]
Is this something we (the cloud.gov team) will need to handle, or is there a point of contact on the system owner side?

**Comment by mogul** [comment]
I renamed the issue to more accurately reflect that this issue is strictly about deprecating the ELB. 

@afeld, OpenFOIA is just yet-another-migration to happen via your normal processes. This issue just  happens to get unblocked after that particular migration happens.

**Comment by mogul** [comment]
Long since done.
