### ISSUE TITLE
apps-gov is completely unused

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#364]
This ELB is currently completely unused

**Comment by NoahKunin** [comment]
cc @stroupaloop?

**Comment by stroupaloop** [comment]
Not sure if this is a config issue on 18F infra side, but `apps-gov` (`cf target -o pif -s apps-gov`) is where the production apps.gov is currently being served from and `apps-gov-2` is where the v2 is deployed, pending ATO review.
