### ISSUE TITLE
Channel alerts are incorrect

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#365]
<img width="400" alt="screen shot 2016-10-11 at 10 38 30 am" src="https://cloud.githubusercontent.com/assets/95657/19274684/e111fb50-8f9e-11e6-832d-5b0505a9b65b.png">

This alert came through however prod had not deployed in 10d, and the build it links to is 125d old.

**Comment by sharms** [comment]
<img width="394" alt="screen shot 2016-10-11 at 10 39 47 am" src="https://cloud.githubusercontent.com/assets/95657/19274723/0f0e033c-8f9f-11e6-923e-9af3a9bd19f9.png">

This alert links to a build which is 129d old

**Comment by rogeruiz** [comment]
Alerts are back in Slack, but the links are all broken now for `View build details`.
