### ISSUE TITLE
Review and respond to open security issues

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#368]
Review reports and determine what is being remediated / false positives

**Comment by sharms** [comment]
Blocked by #369

**Comment by mogul** [comment]
The blocker's closed... Is this issue unblocked now?

**Comment by mogul** [comment]
Is this issue still a thing, @sharms and @jmcarp ?

**Comment by mogul** [comment]
Closing on the assumption that this is now being taken care of via the routine ConMon process, where everything we know about is documented and tracked.
