### ISSUE TITLE
Simplify bosh manifests, migrating from spiff to spruce

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#370]
https://github.com/18F/cg-deploy-bosh/pull/21

**Comment by sharms** [comment]
Spiff is depreciated and causes friction in bosh deploys currently

**Comment by rogeruiz** [comment]
We've already deployed using Spruce. So this should be good to close.

**Comment by rogeruiz** [comment]
Related to #406

**Comment by mogul** [comment]
(Adam thinks this should be constrained to the manifests for BOSH itself, and is likely done.)
