### ISSUE TITLE
As TTS staff, I want to see StatusPage updates appear in Slack

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#371]
Seems the integration was never re-enabled...?

/cc @konklone

**Comment by konklone** [comment]
StatusPage.io is an approved app in TTS Slack -- anyone should be able to create an integration without admin approval.

**Comment by afeld** [comment]
This was more about "it should be working...we should look into why it isn't."

**Comment by konklone** [comment]
What happens when people try?

**Comment by suprenant** [comment]
@afeld it doesn't look like there's anything immediately here for Navigator to do, so I removed that label. Please let us know if you'd like to discuss or if there is something you'd like us to pick up related to this.

**Comment by cnelson** [comment]
Maybe violating the WIP rules I agitated for but I this was white-noise to enable.  So it's enabled:

https://gsa-tts.slack.com/archives/cloud-gov-support/p1485475248002715
