### ISSUE TITLE
Improve customer experience from inquiry to initial stages of using cloud.gov

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#380]
What we're after: Customers who want to buy cloud.gov can easily understand and get themselves through the agreement process

Benefits/why:

- Reduce barriers for customer acquisition
- Reduce overhead we pay per-customer acquisition

Metrics:

- Time from first contact to IAA-in-flight
- Number of interactions needed to get to IAA-in-flight

**Comment by mogul** [comment]
@nikzei @jameshupp SkyPorter still has a several stories `In progress` for this Feature. Questions:

- Do y'all think those stories are going to finish soon enough that we should carry on with them at the beginning of sprint 9.1 and treat them as a "rounding error" from PI8?
- If not, does this Feature still rank higher than [other Features selected for PI9](https://18f.aha.io/releases/CGP-R-58/features), such that we should include it in PI9 planning?

**Comment by mogul** [comment]
*ping*! I notice that many of the remaining issues are in `Ready`... Do you plan to continue work under this feature? Unless you think you're going to blow through the `Ready` work in the next sprint, I suggest clearing your pipeline and starting fresh, reparenting the issues here that still make sense under the features we took on for PI9, and putting the rest in the `Icebox`.

**Comment by nikzei** [comment]
Thanks for this @mogul. I'm just getting back and will go through this with @jameshupp and make a plan.

**Comment by nikzei** [comment]
We will be working on this during PI9 - improvements to the website (IA and content) fall within this feature and will be underway this PI.

Stories for upcoming work forthcoming. In the meantime, here is an outline of identified changes that we need to make: https://docs.google.com/document/d/18oj6xv5b5t76kj_Ex1ID6bdlLSDA7tprenh5FhmO8ZY/edit
