### ISSUE TITLE
Automatically generate per-organization data for monthly invoices

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#386]
What we're after: BU personnel can generate authoritative monthly invoices for a customer's IAA based on their orgs' access packages, the quota for the orgs over the month, and the actual usage of application instances in each org.

Benefits/why:
- Cut down on confusion, manual overhead, and potential for human error
- Confidence that we are actually charging all our tenants for their access/usage
- Enabler for lower and more accurate bills for tenants (once managed services are also metered and we switch away from quota-based billing)

Metric:
- The effort needed for any given person on the operations team to generate accurate invoices for all billable orgs

**Comment by nikzei** [comment]
PI8 75% assessment:

COULD/WON'T (but really, not sure): This has not been more Atlas and less Skyporter during PI8. Also, this was converted into an epic recently, which makes me think that there will be more work for this that will extend beyond PI8. I am unsure how much of this is feasible during PI8.

**Comment by mogul** [comment]
This will definitely be extending into PI9.

**Comment by mogul** [comment]
This is a MAYBE for PI9 at this point

**Comment by suprenant** [comment]
Key information: quota, reserved, actual usage 

Also need to look at Amazon and figure out what they're charging (especially since GovCloud rates are higher than E/W)

**Comment by suprenant** [comment]
Followup question – why is it Elasticsearch that has the data?

**Comment by mogul** [comment]
ElasticSearch is the "E" in ELK, which is the backend for logs.fr.cloud.gov.
Basically all logging and metric data from the platform flows through
there, and it's the appropriate place to query to get aggregations (eg
"show me all the memory used by this app for this date range"), since
that's something ES is good at.

**Comment by suprenant** [comment]
https://drive.google.com/file/d/0Bw50xHl95jZwVGxCSGM1WDQtSlU/view is an example of what the customer receives. "Cloudfoundry" means usage fees

**Comment by mogul** [comment]
[@jcscottiii - James Scott] and [@suprenant - Andrew Suprenant] : Please meet with [@brittag - Britta Gustafson] as it's very unclear to her what data she should refer to and what her process should be following the work put into this feature!

**Comment by mogul** [comment]
Per [@brittag - Britta Gustafson] 
> BU perspective:
> 
> Success looks like:
> 
> BU can easily generate a CSV with basic info (customer info + quota usage) to prepare each monthly billing sheet for Finance.
Related but separate thing: BU wants to be able to know how much each org costs in terms of managed services - https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-627
