### ISSUE TITLE
Community support facilities (3)

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#389]
What we're after: cloud.gov users should be able to collaborate with their peers and surface common needs

Benefits:
- cloud.gov users can get help in a cloud.gov-specific context without unduly flooding the support alias
- cloud.gov users can highlight/fill holes in cloud.gov documentation and help resolve each other's inquiries
- 18F can test the "will attract a vibrant community" hypothesis

Implementation ideas:
 - Poll users on features

**Comment by nikzei** [comment]
@berndverst I'm going to let you set the next steps for this one since you're leading customer support.

**Comment by mogul** [comment]
@dlapiduz scheduled a meeting to discuss this week.
