### ISSUE TITLE
Close POAM V3-AC-2: Lack of procedures for information system accounts

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#395]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

**Implementation sketch**

See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details, under V3-AC-2

The described issue is:
- Various missing procedures and processes for account management.

Todo items:
- [x] Ask 3PAO to test what we've done on this.

**Acceptance Criteria**:
- [x] 3PAO has verified that we've handled this issue.

**Comment by mogul** [comment]
@dlapiduz Per the SSP, we now have documentation that we rely on GSA processes, and also have onboarding and off-boarding checklists. Can you ask Veris to check what we have and give us feedback?

**Comment by brittag** [comment]
We're waiting for an email response from Veris.

**Comment by brittag** [comment]
Closed as resolved on 11/28/16.
