### ISSUE TITLE
Close POAM V4-AC-2(12): Atypical usage monitoring and reporting

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#396]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

**Implementation sketch**

See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.

The described issue is:
- Monitor and report atypical usage of information system accounts.

For reference, the key part of the AC-2 (12) control statement is:

> Cloud Operations and ISSOs actively monitor information system accounts related to cloud.gov for suspicious activities, atypical usage, and unused or expired accounts. Since cloud.gov is a new system, a normal behavior baseline is undefined. As the system grows, 18F will implement additional definitions or methodologies to identify atypical usage.

And the [NIST guidance includes](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=AC-2):

> Atypical usage includes, for example, accessing information systems at certain times of the day and from locations that are not consistent with the normal usage patterns of individuals working in organizations.

Todo items:
- [x] We identify metrics.
- [x] We implement monitoring/alerting.
- [x] We ask 3PAO to verify.

**Acceptance Criteria**:
- [ ] 3PAO verifies that rationale.

**Comment by mogul** [comment]
@sharms and @jmcarp: I know you've been reviewing for signs of compromise manually and buffing up automated alerting as you go... Have we done anything concrete in this particular area (eg alert on signs of attack on opslogin)?

**Comment by cnelson** [comment]
After discussion we generated two new stories to implement this monitoring ☝️.  Goal is to have them completed by Friday.

**Comment by brittag** [comment]
Status: We've documented the results of this test in [a draft email](https://docs.google.com/document/d/1zOqMD6-m_0KItYFIUJkXelBw4UhzHLsQuLAJQKE9Sq4/edit#bookmark=id.wn12b6ujd62o); we can send that draft email after it gets a 👍  from one of our product leaders.

**Comment by brittag** [comment]
We've sent this email; moving to Awaiting Acceptance.

**Comment by rogeruiz** [comment]
@brittag says we're still waiting on Auditor's responses

**Comment by brittag** [comment]
According to SAR, AC-2 (12) was closed as resolved on 11/28.
