### ISSUE TITLE
Close POAM V9-CA-7: Continuous monitoring strategy

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#397]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

**Implementation sketch**

See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.

The described issue is:
- We need to have a detailed continuous monitoring strategy with metrics.
- [x] Ask 3PAO to review our continuous monitoring strategy ([the latest one here](https://drive.google.com/drive/u/0/folders/0B1cewEqKcWCbOG9SRmZEVjM3MDg)).

**Acceptance Criteria**:
- [x] 3PAO verifies that we've handled this risk.

**Comment by mogul** [comment]
@dlapiduz can we have Veris look at the latest Continous Monitoring plan (link above) and let us know if they think this there's any other aspect that needs to be addressed?

**Comment by brittag** [comment]
We're waiting for an email response from Veris.

**Comment by brittag** [comment]
Closed as resolved on 11/28/16.
