### ISSUE TITLE
Close POAM V10-CP-4 and V11-CP-4(1): contingency plan testing

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#398]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

**Implementation sketch**

See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.

The described issue is:
- Contingency plan testing has not taken place.
- Contingency plan testing has not taken place, thus the plans are not coordinated with incident response activities.

Additional context: [Required JAB reviewer items](https://docs.google.com/spreadsheets/d/1DrijIZDu0tltgKR8q36dnk00Z86b2yoQ_wO0kSIq1sM/edit#gid=622192705) ([additional notes here](https://docs.google.com/document/d/1xIt84KHrmcOvymfoK-Tzz-_uahIgfL6tGGVdHnAESuo/edit))).

Todo items:
- [x] Plan test scenario where GitHub is unavailable and there is some sort of related security incident.
- [ ] Schedule meeting to do this test, with one Cloud Ops member to execute the plan, one Cloud Ops "game master" to run the plan, and one additional cloud.gov team member to take notes.
- [x] Run the test and document it.
- [x] Ask 3PAO to verify this.

**Acceptance Criteria**:
- [x] 3PAO verifies that we've handled this risk.

**Comment by mogul** [comment]
Plan here: 

- Britta will work with someone in the team to run a training
- Select a GameMaster to moderate the tabletop exercise, ideally @jacobian or @kimberbat or someone they recommend

**Comment by brittag** [comment]
@datn and I talked about this and figured out a specific plan with a narrowed scope that satisfies the specific requirements for the POAM:

* Dan (to serve as a tester) and another Cloud Ops team member (to serve as "game master") will outline a specific scenario to test where GitHub is unavailable and there is some sort of related security incident.
* There will be a test meeting, where the game master runs the test, Dan serves as the person who will try to solve the problem according to the contingency plan, and I will take notes to help us document the test and gather ideas for plan improvement & training. We'll invite other cloud.gov team members to attend, but it'll be optional for everyone else.

Outside of this 10/25 deadline, Atlas/Highbar should figure out a contingency plan training session and make a contingency plan checklist (in the style of our [security incident checklist](https://docs.cloud.gov/ops/security-ir-checklist/)) for use during a contingency planning situation.

**Comment by datn** [comment]
Contingency plan for updating stemcell without Github is more or less working, but needs some testing.

**Comment by datn** [comment]
Related: #416

**Comment by datn** [comment]
ACCESS_KEY = # AWS access key
SECRET_KEY = # AWS secret key
PATH_TO = # location of docker-mountable directories
STEMCELL_VERSION = # version of stemcell with critical changes. latest as of this writing is 3263.8

latest copy of https://github.com/cloudfoundry-incubator/aws-light-stemcell-builder
latest copy of https://github.com/18F/cg-deploy-aws-light-stemcell-builder

wget https://d26ekeud912fhb.cloudfront.net/bosh-stemcell/aws/bosh-stemcell-$STEMCELL_VERSION-aws-xen-ubuntu-trusty-go_agent.tgz

docker run \
-e ami_access_key=$ACCESS_KEY \
-e ami_bucket_name=cg-stemcell-images \
-e ami_description="Cloud.gov BOSH Stemcell" \
-e ami_region=us-gov-west-1 \
-e ami_secret_key=$SECRET_KEY \
-e ami_virtualization_type=hvm \
-e ami_visibility=private \
-v $PATH_TO/cg-deploy-aws-light-stemcell-builder:/builder-config \
-v $PATH_TO/aws-light-stemcell-builder:/builder-src \
-v $PATH_TO/input-stemcell:/input-stemcell \
boshcpi/aws-light-stemcell-builder builder-config/tasks/build.sh

**Comment by brittag** [comment]
We're documenting the results of this test in [a draft email](https://docs.google.com/document/d/1zOqMD6-m_0KItYFIUJkXelBw4UhzHLsQuLAJQKE9Sq4/edit#bookmark=id.wn12b6ujd62o); I'm going to consider this "in progress" until we've emailed our 3PAO, but I'll reassign to me since @datn's part of this work is done as far as I can tell!

**Comment by brittag** [comment]
We've sent this email; moving to Awaiting Acceptance.

**Comment by rogeruiz** [comment]
@brittag says we're still waiting on Auditor's responses

**Comment by brittag** [comment]
Yeah, I just took the Atlas label off of this (and https://github.com/18F/cg-product/issues/396) - the remaining work here is really HighBar work (getting the POAM closed on a compliance level) rather than technical work.

**Comment by brittag** [comment]
According to SAR: CP-4(1) was closed as resolved on 11/14/16, and CP-4 was verified as closed on 11/28.
