### ISSUE TITLE
Close POAM V12-IA-5(6): Check protection of system authenticators

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#399]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

**Implementation sketch**

See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.

The described issue is:
- Develop, document, and implement a process to protect authenticators commensurate with the security category.

We've revised IA-5 (6) in our SSP with a better explanation of how we do this.

Todo items:
- [x] Ask 3PAO to verify this.

**Acceptance Criteria**:
- [x] 3PAO verifies that we've handled this risk.

**Comment by mogul** [comment]
@dlapiduz can you ask Veris to verify that our updated statement in IA-5(6) is sufficient?

**Comment by brittag** [comment]
We're waiting for an email response from Veris.

**Comment by brittag** [comment]
Veris told us we can move this one to the closed tab.
