### ISSUE TITLE
Close V14-PL-2: System Security Plan improvements

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#400]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

**Implementation sketch**

See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.

The described issue is:
- Update SSP to be complete and clear.
- Analyze what aspects of the SSP can and should be made publicly available (especially contents of https://compliance.cloud.gov/ and https://github.com/18F/cg-compliance).

Todo items:
- [x] Ask 3PAO to verify this.

**Acceptance Criteria**:
- [x] 3PAO verifies that we've handled this risk.

**Comment by mogul** [comment]
@dlapiduz we think this is going to be addressed by the work these past weeks with Noah to polish up the SSP, and further/separate work isn't needed. Do you agree? If so, can you you ensure Veris is prepared to verify that this is addressed?

**Comment by brittag** [comment]
We're waiting for an email response from Veris.

**Comment by brittag** [comment]
We're switching this one to operational requirement - we've [drafted the rationale here](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit#heading=h.rzfgvwyxjyee). It'll need to get approved by our AO and verified by our 3PAO.

**Comment by brittag** [comment]
This is already in SAR 0.6 as an operational requirement, so this is done.
