### ISSUE TITLE
Decide on source of truth for tenant system owners

### ISSUE THREAD

**Issue by jcscottiii** [18F/cg-product#402]
As a system operator, I would like to maintain knowledge of the owner for a particular application to prevent stale apps from taking up resources.

Ideas of implementation:
- A Registry like [Chandika](https://github.com/18F/chandika)

**Comment by afeld** [comment]
...particularly for systems operated by GSA, per @jezhumble.

**Comment by afeld** [comment]
Other places this information is being tracked:

* [ATOs spreadsheet](https://docs.google.com/spreadsheets/d/1Llv4EVrnH-LrH2YO2y2WlaR6t3-VZexLp3ncORCQAD0/edit#gid=0)
* https://github.com/18F/cg-migration/issues
* `OrgManager`s in cloud.gov

**Comment by afeld** [comment]
@jezhumble @nikzei @mogul @berndverst Would love your input on how we can reduce the number of canonical sources here. Happy to set up a meeting, if that's the best way to do it.

**Comment by mogul** [comment]
My intention was that the sheet tracking results from the org request form start acting as the single list. All of the others are hand-managed and have no standards around how the information is gathered, refactored, and updated. At least with the survey sheet we know that other groups aren't using it for other purposes. My hope is that we eventually hold this information in a microservice, but so long as we're using the form and avoiding hand-editing of the sheet, I think it's a good place in the meantime.

**Comment by suprenant** [comment]
This is now redundant per https://github.com/18F/cg-migration/issues/42 and some other issues that came out of PI planning
