### ISSUE TITLE
Define timeline for the cut off for E/W tenants

### ISSUE THREAD

**Issue by jcscottiii** [18F/cg-product#403]
As system operators, we want our customers to have clear and helpful guidence on when E/W is shutting down.
- We need to decide the drop-dead date when we turn off E/W
- We need to define target date for apps to be moved (drop-dead minus X)
- We need to communicate the deadline to agency partners

Related: https://favro.com/organization/1e11108a2da81e3bd7153a7a/e166f9041ce97085a6cdd859

**Comment by afeld** [comment]
Per @dlapiduz [in Slack](https://gsa-tts.slack.com/archives/cloud-gov-migration/p1477512121000016), setting a shutdown date is blocked (at least for non-GSA/EPA accounts) by https://github.com/18F/cg-product/issues/138.

**Comment by mogul** [comment]
In Slack, @dlapiduz suggested that we [announce we're retiring the sandbox spaces in mid-December](https://gsa-tts.slack.com/archives/cloud-gov-skyporter/p1479936131004187). @berndverst said he thinks we should give people at least two weeks notice.

**Comment by mogul** [comment]
(Also MFA is no longer a blocker.)

**Comment by afeld** [comment]
Just decided in a meeting: we're going to cut the sandboxes December 31st.

* [ ] Send an announcement
    * Note that invites are coming for those without access, and that they will need to act on that quickly.
* [ ] Send GovCloud invites to all non-GSA/EPA/FDIC users in East/West, if they don't have accounts already

**Comment by mogul** [comment]
Now that invitation tokens have _very short lifetimes_, so you might have to think of a way for people to self-provision them 

(Cadillac version: Stick a button on the `cg-uaa-extras` post-login screen in E/W that will simply tickle an app that sends the user an invitation to GovCloud.😎)

**Comment by afeld** [comment]
> you might have to think of a way for people to self-provision them

https://github.com/18F/cg-product/issues/532

**Comment by mogul** [comment]
Per discussion yesterday: We want to hold off on migration for all users until we've tested the provisioning process for idp.cloud.gov and determined that we're seeing a high success rate, so that they have a place to go to get a new sandbox space. So we need to hold off on the communication, which means maybe we need to hold off on the deadline.

**Comment by porta-antiporta** [comment]
@afeld (or whoever may know).  Did invites the following happen?

> - [ ] Send an announcement
> - [ ] Note that invites are coming for those without access, and that they will need to act on that quickly.
 Send GovCloud invites to all non-GSA/EPA/FDIC users in East/West, if they don't have accounts already

If so, when and if the user took no action, have the invites now expired.  Asking as a few folks at the FEC may have sandbox accounts on E/W but did not activate their invites to GovCloud.

**Comment by porta-antiporta** [comment]
huh?  I didn't unassign either of those folks. ^^

**Comment by afeld** [comment]
No, we were waiting on the usability of the cloud.gov-offered auth to improve. Not sure about the unassigning, but don't worry- they are no longer on the team :crying:

/cc @suprenant

**Comment by suprenant** [comment]
Per [@Bret Mogilefsky - TEABA] in Slack:
_Per discussion elsewhere: We are deliberately avoiding setting a deadline until (1) they’re all able to self-generate an invitation to get into the GovCloud environment , and (2) all people (not just FDIC, EPA, and GSA) are able to log into our GovCloud environment without confusion (right now there’s a vestigial form that confuses everything and causes support requests for people not in those agencies). We’re scheduled to remove those blockers over the next couple weeks. Once we’ve done that, we’ll send out more signals and be able to set a deadline._

**Comment by fureigh** [comment]
Closing this, as we set a deadline (March 15th for externally-operated apps) and communicated it last week.
