### ISSUE TITLE
False positives during log pruning

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#404]
Elasticsearch will periodically purge logs once they are six months old.  Because this action issues a _update or _delete method call, this will trigger our security alerts(1).  So far, this activity appears to be initiated by only ElasticSearch master jobs.
1. https://18fi.pagerduty.com/i/789

Acceptance Criteria:
- [ ] Routine log maintenance will not alert team
- [ ] Non routine activity will continue to alert

Technical details:
- Request originates from a master node
- Snort rules identify activity and send alert to Riemann
- Riemann sends alert to Pagerduty

**Comment by datn** [comment]
This is the snort-level fix: https://github.com/18F/cg-deploy-logsearch/pull/31

Now to make it work across n levels of templating

**Comment by datn** [comment]
First, make rules get ingested as a list:

https://github.com/18F/cg-snort-boshrelease/pull/10

**Comment by datn** [comment]
Next, present rules as list:

https://github.com/18F/cg-deploy-logsearch/pull/32

**Comment by datn** [comment]
Changes have been merged to seeming success. Last step per @cnelson is to test that the proper alerts are still coming through to PagerDuty.

**Comment by datn** [comment]
PagerDuty reacted when I did `curl -X DELETE http://localhost:9200/arb-prod/logs-platform` from the elasticsearch_master (as it should), but did not react when I did `curl -X DELETE http://10.10.30.20:9200/arb-prod/logs-platform` from the cluster_monitor.

**Comment by cnelson** [comment]
👍
