### ISSUE TITLE
SSP document remediations

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#41]
In order to ensure our SSP is ready for JAB technical reviewers, we need to remediate the points raised by our 3PAO interviews.

_(Note: Be careful to ensure that your changes are made in the right place to find their way back into the YAML! See in particular 18F/cg-atlas#91.)_

**Acceptance Criteria**

- [x] IR: Incident Response Plan should include:
  - [x] Frequency of testing/tabletop exercises (yearly)
  - [x] Frequency of review of the IRP (yearly)
  - [x] Who is notified, and how they are notified about IRP changes (Make an issue in GitHub and @-cloud-gov-team)
- [x] PL: PL-1b reads “The 18F Program Office will review and update the current 18F Identification and authorization Policy at least every 3 years and any documented procedures at least annually.” when it should say “Security planning policy” instead.
- [x] AU: AU-3 (1) should remove the section about BOSH CLI
- [x] CP: Need to mark everything as planned controls.
- [x] AT: Need to mark AT-1 and AT-2 as partially implemented since we don’t have a cloud.gov-specific training plan _(Adam sez: Veris seems to think this is entirely covered by GSA training, which applies to all employees and contractors! Double-check and if so ignore this one.)_
- [x] AT: Add training on the IRP, CPP, CMP, etc. to the Onboarding Checklist
- [x] MA/MP/PE: Need to change from N/A to Inherited from AWS GovCloud FedRAMP package and mark everything as Implemented.
- [x] CM: Configuration Management
  - [x] Replace all the references of Trello to GitHub
  - [x] Replace “18F DevOps and SecOps” to “cloud.gov operators”
  - [x] CM: CM-2 (3) Needs to read: “If there is any manual change on any part of the infrastructure Bosh and Terraform will correct the settings and revert back to the known state.”
  - [x] CM: We should remove the reference to the number of VMs
  - [x] CM: CM-2 (7) Needs to read: “Per Federal policy 18F employees are not allowed to take equipment outside of the United States without explicit permission.”
  - [x] CM: CM-8: Add “Bosh continuously maintains inventory of all instances and configuration”

**Comment by dlapiduz** [comment]
@clovett3 can you pick these changes from cg-compliance?
