### ISSUE TITLE
Atypical usage raises non-critical alerts in PagerDuty

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#410]
In order to ensure cloud.gov is continuously monitored for atypical usage as Cloud Operations I want to be automatically notified when metrics that we determine indicate atypical behavior change so that I can investigate the cause immediately.

**Acceptance Criteria**
- [ ] When any of the metrics on the dashboard created by https://github.com/18F/cg-product/issues/409 exceed a moving average based on historical data an alert in PagerDuty is raised.

This is in support of https://github.com/18F/cg-product/issues/396

**Comment by brittag** [comment]
I believe this is complete, based on [the draft email explanation of this work](https://docs.google.com/document/d/1zOqMD6-m_0KItYFIUJkXelBw4UhzHLsQuLAJQKE9Sq4/edit#heading=h.poq1w6bz974) (with screenshots, aw yeah!), so I'll close this up. Feel free to reopen if there's something lingering that I missed.

**Comment by cnelson** [comment]
Yes. This is done
