### ISSUE TITLE
Logsearch data is preserved in S3

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#412]
In order to trust our log storage I want all data in logs.cloud.gov to be duplicated in S3 for 548 days so that we have a trusted secondary source for log data.

**Acceptance Criteria**
- [x] Data sent to logs.fr.cloud.gov is replicated to an s3 bucket
- [x] Data in that s3 bucket is purged after 548 days

**Comment by mogul** [comment]
> 365 days

I think we said because we weren't sure if the one-year is *after* the initial six months or concurrent, we were going to do 1.5 years to cover all of our bases. Is that right?

**Comment by cnelson** [comment]
I didn't recall exactly where we left it, but it's NBD to change it to 548.  

Although this is becoming much more effort than originally estimated (see atlas channel for more info)

**Comment by cnelson** [comment]
This is complete.  The data is stored in the `logsearch-cf-staging` and`logsearch-cf-production` buckets.  These buckets are created by [terraform with a lifecycle expiration date set to 1.5 years](https://github.com/18F/cg-provision/blob/master/terraform/modules/cloudfoundry/buckets.tf#L29).

@mogul or @jmcarp Can one of you accept/close this?
