### ISSUE TITLE
Close POAMs CM-6, AC-6(2), AC-6(10), AC-7, AC-22, SC-12(2), SI-4(23)

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#414]
In order to demonstrate that our system has an acceptable level of risk, we need to close these identified potential risks as resolved or invalid.

**Implementation sketch**

See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.

Our plan for these is to document that our 18F AO considers these to be false positives, with approved rationales.
- [x] Our 18F AO has reviewed, fixed, and approved [our draft rationales](https://docs.google.com/document/d/1zOqMD6-m_0KItYFIUJkXelBw4UhzHLsQuLAJQKE9Sq4/edit#)
- [x] We've emailed our 3PAO to ask them to verify these rationales.

**Acceptance criteria**
- [ ] 3PAO verifies that we've handled this risk.

**Comment by NoahKunin** [comment]
LGTM. :shipit:

**Comment by brittag** [comment]
Sent this email; moving to "Awaiting Acceptance" while waiting for response.

**Comment by brittag** [comment]
Checklist for tracking items verified by 3PAO as closed:

- [ ] CM-6
- [x] AC-6(2)
- [ ] AC-6(10)
- [ ] AC-7
- [ ] AC-22
- [ ] SC-12(2)
- [ ] SI-4(23)

**Comment by brittag** [comment]
Items verified by 3PAO as closed:

* AC-6(2)
* AC-6(10)
* SI-4(23)

Can't close yet:

* AC-7 - probably needs to be an operational requirement - drafting at https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit
* AC-22 - remaining work tracked at https://github.com/18F/cg-product/issues/546
* SC-12(2) - waiting for JAB opinion

Unclear status:

* V2-CM-6 (Kibana directory browsing)

**Comment by jmcarp** [comment]
We agreed to close the kibana directory listing issue last time we talked about it--iirc, @NoahKunin was willing to accept risk. Has anything changed there?

**Comment by brittag** [comment]
That part is totally fine - we wrote the rationale & Noah approved it. We just have a third step where Veris says "yeah that's fine", and I haven't yet tracked down whether they've already 👍  or whether we need to ask them to let us know what they think.

**Comment by brittag** [comment]
Ah ha, we can close V2-CM-6 as a risk! It's listed as `9-FP-WS` in table E-2 in the latest SAR.

Closing this issue since all the work is done or tracked elsewhere.
