### ISSUE TITLE
Set admin-ui to auto-deploy on new stemcell

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#416]
In order to have a secure environment, we need our deployments to trigger on a stemcell update.

Acceptance Criteria:
- [x] When a new stemcell is released, it is automatically patched

**Comment by datn** [comment]
Aside from working on compiling a stemcell manually, here's the pipeline change:

https://github.com/18F/cg-deploy-admin-ui/pull/19

**Comment by datn** [comment]
Changes made and pipeline reflown.

**Comment by datn** [comment]
https://ci.fr.cloud.gov/teams/main/pipelines/deploy-admin-ui/jobs/deploy-admin-ui-staging/builds/34

**Comment by datn** [comment]
This and 19 were the PRs in question: https://github.com/18F/cg-deploy-admin-ui/pull/20
