### ISSUE TITLE
RSC-C: Ensure EBS data is encrypted at rest in GovCloud deployment

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#42]
In order to comply with `NIST 800-53 SC-*`, the cloud.gov team should ensure that all EBS data is encrypted at rest.

**Acceptance Criteria**

- [x] Make sure that all EBS volumes are encrypted

**Implementation Sketch**

* Update BOSH manifests to include encryption on EBS (now that it's working correctly)
  - [x] admin-ui ( https://github.com/18F/cg-deploy-admin-ui/pull/5 )
  - [x] bosh ( https://github.com/18F/cg-deploy-bosh/pull/6 )
  - [x] concourse ( https://github.com/18F/cg-deploy-concourse/pull/16 )
  - [x] docker-swarm-broker ( https://github.com/18F/cg-deploy-docker-swarm/pull/21 )
  - [x] logsearch
  - [x] monitoring ( https://github.com/18F/cg-deploy-monitoring/pull/57 )
  - [x] nessus-manager ( https://github.com/18F/cg-deploy-nessus-manager/pull/1 )

**Comment by mogul** [comment]
@sharms says break this one up; will do shortly.

**Comment by mogul** [comment]
@dlapiduz is wrestling with this via cloudfoundry-incubator/bosh-aws-cpi-release#34

**Comment by mogul** [comment]
I split [S3](18F/cg-product#46) and [RDS](18F/cg-product#47) out into their own issues.

**Comment by rogeruiz** [comment]
@jmcarp and I are tackling these in tandem, and editing the comment above with links to the PR ☝️.

When these changes are merged in, we can start ticking off boxes. So if you're merging in a PR, please tick off the box that it covers.
