### ISSUE TITLE
Address POAM points raised in JAB Q&A sessions

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#422]
In order to satisfy the needs of the JAB technical reviewers, we want comments in the latest version of the ["Cloud.gov JAB Review Comments Workbook Master"](https://drive.google.com/drive/folders/0Bw50xHl95jZwWGdxSTBtblUxYlU) referring to the POAM left in the "active" state to be addressed via an updated POAM.

See [shared meeting notes here](https://docs.google.com/document/d/1EmSIfoMfV21LVGg5BKfJaQGjiNUqJiBugNfUMtMGcTY/edit#heading=h.1q8np41g5svr) for additional detail.

**Acceptance Criteria**

By December 2 ConMon report delivery:
- [x] 1020, 1012, 521, 1016 - For each non-closed item, explain in better detail the plan for remediation and milestones to complete the overall remediation plan. Give enough information to understand what will be improved or implemented to resolve the weakness, and give milestones with dates to track those activities.
- [x] 1015 - Remove "queued for compleittion" - use implementation status language that aligns with our language in the SSP.

In general:
- [x] 522 - This is confusing - we need to look at this one again and figure out what's going on there.
- [x] V73 is only listed once
- [x] There is one low vuln that is not listed in the SAR or captured in the POA&M. (Find out from PMO what this is.)

To sync up our POA&M with our other documentation, our POA&M has the following statuses:

- [x] V2 is listed as a pending false positive
- [x] V14 is _not_ listed as a pending false positive
- [x] We've figured out whether to list V73 as a pending false positive and synced it up with the work at https://github.com/18F/cg-product/issues/477 + https://github.com/18F/cg-product/issues/447

To sync up our POA&M with our other documentation, we've done this follow-up work:

- [ ] For V19 (since it's listed as an OR), we've provided a justification along with any compensating controls, and we've documented it in the SAR.

**Comment by brittag** [comment]
Also: integrate the status updates drafted in [this copy](https://docs.google.com/spreadsheets/d/1hGEFwpxmbpMLf3Ya3vKOMOsgjZMz1h2GKeRU5ovTBH4/edit#gid=1701775784) and then delete that copy.

**Comment by brittag** [comment]
And we have V73-IA-5 listed twice in the current POAM, so we should fix that.

**Comment by brittag** [comment]
Updated the story with the task to fix V73 as well as notes from the comments at https://github.com/18F/cg-product/issues/477

**Comment by brittag** [comment]
Progress: I've updated 6 out of 15 of the non-closed items due by 10/25 with details about plans for remediation and milestones.

**Comment by brittag** [comment]
V19 (item 522 in the comments workbook) is the only remaining item here, and I suspect that'll get resolved on its own when we get the revised SAR, so I'm going to consider this done.
