### ISSUE TITLE
(SC-10) Inactive sessions should terminate after 30 minutes

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#424]
In order to comply with NIST control SC-10, SSH connections established via the Diego SSH proxy or Concourse should be terminated after 30 minutes of inactivity.

**Acceptance Criteria**
- [ ] An otherwise idle session established via the Diego SSH proxy (eg `cf ssh` or using the [alternative no-CF CLI method](https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-apps.html#ssh-env)) is terminated after 30 minutes.
- [ ] An otherwise idle session established via Concourse intercept is terminated after 30 minutes.

**Implementation sketch**
- Limit at the ELB
- Fix the code we use that might have its own methods for keeping connections opens:
  - The Diego SSH proxy should [set an explicit timeout duration immediately after the clientConfig is created](https://github.com/cloudfoundry/diego-ssh/blob/master/proxy/proxy.go#L300). See the [Go clientConfig reference](https://godoc.org/golang.org/x/crypto/ssh#ClientConfig)
  - Modify [Concourse's intercept code](https://github.com/concourse/atc/blob/master/api/containerserver/hijack.go) to set a timeout

**Comment by mogul** [comment]
We don't think there's any specific deadline for this one so we're going to wait to tackle it.

**Comment by mogul** [comment]
I'm about 90% sure we tackled this already or found we didn't need to based on existing settings. Do you remember @LinuxBozo?

**Comment by mogul** [comment]
(cc @brittag)

**Comment by sharms** [comment]
We verified our timeouts on ELBs are much less than 30 minutes already, that proposed solution will not work.

**Comment by mogul** [comment]
Sorry, I don't understand... If they're under 30 minutes already, that's a good thing, right?

**Comment by jmcarp** [comment]
Diego SSH defaults to a five-minute idle timeout: https://github.com/cloudfoundry/diego-ssh/blob/master/cmd/ssh-proxy/config/config.go#L55
Working on adding ATC-level intercept timeouts to concourse: https://github.com/concourse/atc/pull/222

**Comment by brittag** [comment]
Re the first part, SSH client implements keep-alive. If it weren't on, we'd have timeouts. The server-side implements timeouts. This just needs discussion about whether it's sufficient.

Concourse PR just needs review.

**Comment by brittag** [comment]
Waiting for next Concourse release.

**Comment by brittag** [comment]
SSH server-side timeout seems sufficient. We could provide evidence that it's configured correctly.

**Comment by brittag** [comment]
Write revised SSP narrative (like 2 short paragraphs size)

**Comment by jmcarp** [comment]
Suggested text for SSP update at https://docs.google.com/document/d/1dYnMMjFy4ZnyrzwBzlRstAqgjwPjCslz2Aw1RywQydg/edit#.

**Comment by brittag** [comment]
Excellent!
