### ISSUE TITLE
Deliver ConMon update on Wednesday November 2nd

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#425]
In order for us to update the JAB on our compliance in a consistent way, we need to deliver a Continuous Monitoring report on November 2nd.

**Implementation checklist for POAM**

- [x] Include the V73 item
- [x] Move any web scanner items that should be moved to closed (in other words, items originally found by a scanner where we have new scans that prove these things are fixed)
- [x] For all the items due 10/25: update the fields to explain (at least briefly) our plans and statuses
- [x] For all the open web scanner items: update the fields to explain (at least briefly) our plans and statuses
- [ ] Change the status date column when we submit it

**Acceptance criteria**
- [x] Our POAM is up to date
- [x] We have fresh scan results in XML format
- [x] We've emailed our ConMon report (including POAM and scan results) to our PMO

**Comment by brittag** [comment]
We have a meeting scheduled for Friday 12-12:30 pm Eastern to work on a component of updating the POAM for this:

> This POA&M should:
> * include the findings identified in Table 4-1 of the SAR
> * exclude any of the web vulnerabilities that have since been closed (and verified via the newly submitted demo scans). These would be moved to the Closed POA&M items tab.
> * include any new web or OS vulnerabilities identified by the newly submitted demo scan (our ConMon team has already verified that the newly submitted Nessus demo scan did not result in any vulnerabilities)

**Comment by brittag** [comment]
[Notes from that meeting](https://docs.google.com/document/d/1aGTtm-Zp63jsRd4YRfWPwvEtET8M40hN9a2kAlEhodk/edit#)

**Comment by brittag** [comment]
Also: [OWASP ZAP planning 10/31/16](https://docs.google.com/document/d/1E6g96F6YpBjikey7kehLdQwGjjMcI1mBZcMwvYJ7AUM/edit) - notes about getting fresh scans together.

**Comment by brittag** [comment]
Working in a copy of the POAM [over here](https://docs.google.com/spreadsheets/d/1hGEFwpxmbpMLf3Ya3vKOMOsgjZMz1h2GKeRU5ovTBH4/edit#gid=1701775784). So far, I wrote a revision for the V2-CM-6 fields.

**Comment by brittag** [comment]
We sent this! Noting for next time that we should have checkboxes for both web scans and system scans (OWASP ZAP and Nessus).

**Comment by mogul** [comment]
Done, will capture a new template for ConMon next time.
