### ISSUE TITLE
Set Criteria for determining who can benefit from cloud.gov

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#426]
[Sprint 1]

We want to identify who can be a cloud.gov customer at this stage of the product. What requirements must they meet? Who can we say that we definitely won't be able to work with yet?  Can we present these so that  will use this to (1) help customers understand whether cloud.gov could address a need of theirs, and (2) help us shape the basic pitches that our evangelists use on our behalf. 

Acceptance criteria:
- [x] identify any characteristic that disqualifies a prospect from becoming a customer
- [ ] one liner for outreach to use for blogposts that might best attract our targeted audience
- [ ] one line pitch for engagement managers who might pitch cloud.gov to their agency partners

**Comment by nikzei** [comment]
From #429, which I closed bc it was a duplicate:


Right now, our [Who Can Use Cloud.gov](https://cloud.gov/overview/overview/who-can-use-cloudgov/) page states that:

> "18F is now working with a set of agencies who are willing to help us uncover and work through the challenges involved in a new service. While we aren’t yet at the point where agencies can use cloud.gov on their own, we are learning to scale support, processes, and infrastructure."

But it's not accurate to say that we can work with "any agency willing to help us uncover and work through the challenges involved in a new service." We will be able to more quickly connect with viable customers if we break it down as something along the lines of,

> "Are you interested in cloud.gov? Here are the requirements that you'll have to meet to be able to work with us at this point:
> 
> - 12 factor app (?)
> - FISMA low or moderate compliance needs (we can't currently help with FISMA high needs. To learn more about how you might evaluate the FISMA level of your app, visit [this link]
> - and so on and so forth . . .

**Comment by mogul** [comment]
Good signs for cloud.gov readiness:

- You have technical staff available who understand how to stand up your applications
- Your applications do not depend on the local filesystem as the only option for durable data storage 
- Your applications do not depend on Windows-specific APIs or operating environments (.net core is fine)
- Your applications do not depend on proprietary databases

**Comment by mogul** [comment]
- Your applications' dependencies can be installed automatically (eg using a package manager)
- Your applications are not amalgams of multiple language runtimes, but collections of discrete single-language ones

**Comment by mogul** [comment]
Aus DTO gave us a pointer to their readiness checklist: http://docs.cloud.gov.au/usage/orca/

**Comment by nikzei** [comment]
@mogul, I'm getting a 404 for that link :(.

We've put up a page with this criteria for now. @berndverst, @brittag @jameshupp and I have begun conversations about improving the landing page and overview page and we likely will decide to put this readiness criteria on one of those pages as it is something that prospective customers want to understand off the bat.
Closing this.
