### ISSUE TITLE
Raise alert when Nessus Manager license needs to be refreshed

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#427]
In order to ensure that Nessus is constantly scanning, the operations team needs to be alerted when Nessus is currently unavailable due to licensing.

Acceptance Criteria:
- Operations team receives an alert when nessus cannot contact the licensing server

**Comment by rogeruiz** [comment]
@jmcarp will help verify this

**Comment by mogul** [comment]
Verified by Josh
