### ISSUE TITLE
Quotas are not defined programmatically

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#428]
In order for quotas not to depend on good natured folks typing randomly on the CLI, we should have quotas be stored and assigned in a configuration file.

Acceptance Criteria:
- Quotas exist in Staging
- Quotas exist in Production
- Quotas can be replicated
- Quotas have a history of who changed them and when

**Comment by jbarnicle** [comment]
Sandbox / space are also created in the `sandbox-bot`. 

https://github.com/18f/cg-sandbox-bot

**Comment by mogul** [comment]
Closing; mid-term goal is to have customers be able to change their own quota as needed, so we don't want this in code.
