### ISSUE TITLE
setting criteria for our customers

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#429]
We want to communicate what the requirements are for using cloud.gov, enabling us to target our potential customers and weed out those that we can't help right now (perhaps we can make a "Who can use Cloud.gov?" page in our overview section). We also want to be able to use this information to inform the pitches that we give out to the cloud.gov evangelists in 18F partner agencies, in our own agency partnerships, and throughout 18F. 

This list is open for team contributions (a continuation of a conversation that we had in today's Skyporter standup). cc @berndverst @dlapiduz @mogul @jezhumble @afeld @jcscottiii @jameshupp 

**Please make contributions this week (by Friday, 10/28)**

**Comment by afeld** [comment]
> perhaps we can make a "Who can use Cloud.gov?" page in our overview section

Like this one? 😉  https://cloud.gov/overview/overview/who-can-use-cloudgov/

**Comment by nikzei** [comment]
I say we need to revise this and make it a specific listing o the criteria that must be met to work with us. 
Right now, this page states that:

> "18F is now working with a set of agencies who are willing to help us uncover and work through the challenges involved in a new service. While we aren’t yet at the point where agencies can use cloud.gov on their own, we are learning to scale support, processes, and infrastructure."

But it's not accurate to say that we can work with "any agency willing to help us uncover and work through the challenges involved in a new service." We need to make something more along the lines of 

We will be able to more quickly connect with viable customers if we break it down assomething along the lines of,
"Are you interested in cloud.gov? Here are the requirements that you'll have to meet to be able to work with us at this point:

- 12 factor app (?)
- FISMA low or moderate compliance needs (we can't currently help with FISMA high needs. To learn more about how you might evaluate the FISMA level of your app, visit [this link]
- and so on and so forth . . .

**Comment by nikzei** [comment]
This is a duplicate of issue #426. Closing this one

**Comment by nikzei** [comment]
CUSTOMERS MUST HAVE:



SHOULD HAVE:
- Has a SAML IDP

**Comment by mogul** [comment]
This issue's closed... I thought we moved this over to #426?

(I don't recommend using "12-factor" as a signifier because many potential customers won't know what that means; made specific recommendations for some of the factors in #426.)

**Comment by dlapiduz** [comment]
@mogul thats exactly what we did here https://github.com/18F/cg-site/pull/504
