### ISSUE TITLE
RCA-A: Develop and publish Continuous Monitoring Plan

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#43]
In order to comply with `NIST 800-53 CA-*` cloud.gov should have a published continuous monitoring plan.

**Acceptance Criteria**

- [ ] docs.cloud.gov includes an explicit continuous monitoring plan sufficient to meet the "explains" section of `CA-*`
- [ ] Actual monitoring practices are in sync with the published plan
- [ ] The SSP `CA-*` sections are updated to point to this information

**Comment by mogul** [comment]
@afeld

**Comment by afeld** [comment]
Is this closed by https://github.com/18F/cg-docs/pull/313?

**Comment by dlapiduz** [comment]
Let me double check with Veris...

**Comment by mogul** [comment]
@dlapiduz any word on what we should do here?

**Comment by dlapiduz** [comment]
@mogul not sure, but closing it out for now until we hear anything back.

**Comment by mogul** [comment]
Why are we closing it out? Aren't we still on the hook to provide this?

**Comment by dlapiduz** [comment]
It turns out we are not, we just need to follow the continuous monitoring Fedramp practices per https://github.com/18F/cg-docs/pull/313
