### ISSUE TITLE
Update our SecureAuth MFA policy

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#431]
In order to satisfy the requirement in [IA-2 (11)](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=IA-2) that MFA for our team needs to involve "a device separate from the system gaining access", we need to minimize the risk of GSA SecureAuth including email as a MFA option.

**Acceptance criteria**
- [x] Remove email as a SecureAuth MFA method for Ops UAA.
- [x] Update IA-2 (11) to say that cloud.gov doesn't use email for SecureAuth MFA for the Ops UAA login system.
- [ ] Update [our IA procedures](https://github.com/18F/compliance-docs/blob/master/IA-Policy.md) to match that policy.

**Comment by brittag** [comment]
Note: this needs further discussion, since this doesn't address how we would implement the requirement of "a device separate from the system gaining access" for operator access to the cloud.gov platform from a GSA smartphone (for example checking on the status of a long-running task).

**Comment by brittag** [comment]
(Asked for advice on next steps for this, since we may need to adjust this task list before starting it.)

**Comment by brittag** [comment]
Our next steps are to continue with this plan!

**Comment by dlapiduz** [comment]
Filled in ticket #CHG0165593

**Comment by brittag** [comment]
@dlapiduz Which task is filed in that ticket?

**Comment by mogul** [comment]
This one:

> Remove email as a SecureAuth MFA method for Ops UAA.

This is effectively blocked waiting on GSA IT to do that.

**Comment by mogul** [comment]
Update on this: It seems like they're working on it, but it appears they made the change to the wrong system (`login.fr.cloud.gov` rather than `opslogin.fr.cloud.gov`) as we saw [turbulence for users in support today](https://gsa-tts.slack.com/archives/cloud-gov-support/p1479144156004099), eg `your profile data is missing` when they had no phone number set.

**Comment by brittag** [comment]
Updating the SSP to mark IA-2 (11) as "partially implemented" for now, with a description of the plan. so that at least the SSP is accurate with our current status. We can update it again when this is finished.

**Comment by brittag** [comment]
Ops UAA seems to be updated! Example of logging into Concourse:

![screen shot 2016-11-29 at 9 25 54 am](https://cloud.githubusercontent.com/assets/391313/20727666/468b877e-b62f-11e6-9ccb-10d4a8febe9c.png)

So this is unblocked now.

**Comment by mogul** [comment]
I updated IA-2 (11) in the SSP (and will curry the changes to @brittag for incorporation), but I'm unclear on what might need to change here:

>  Update [our IA procedures](https://github.com/18F/compliance-docs/blob/master/IA-Policy.md) to match that policy

...since the policy doesn't actually go to the same level of detail as the SSP. So I'm skipping that for now. For this one:

> Reach out to GSA to determine if/when they plan to remove the email method agency-wide.

I'm going to remove it as an AC because right now it seems like this is not actually being questioned or holding us up in any way.

**Comment by mogul** [comment]
For reference, here're the necessary changes in the SSP...

- In IA-2 (1), "via either government ~~email,~~ text,"
- In IA-2 (11)
  - change the "partially implemented" checkbox to "implemented"
  - remove "partially implemented" text and change the "Operations UAA" paragraph to say "This is configured similar to Client UAA. GSA SecureAuth is configured to only provide MFA tokens over government text, automated phone call, or mobile device application (without the email option) for Operations UAA."

Assigning to @brittag to decide what to do about the compliance doc AC, but also moved to `Awaiting Acceptance` as I figure we're done here.

**Comment by brittag** [comment]
Updated in the SSP!
