### ISSUE TITLE
Auto-create and distribute deployer accounts

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#437]
In order to remove the operator burden for creating, rotating, and destroying deployer credentials users should be able to request/remove a long-lived deployment credential tied to a particular space without asking for support.

**Acceptance Criteria**
- [ ] Scenario: A user can setup a deployer account by creating a service  
  GIVEN a SpaceDeveloper Bob  
  AND Bob is logged in  
  WHEN Bob runs `cf create-service deployer plain hal`  
  THEN A deployer account is created in the deployer zone  
  AND the deployer account has the SpaceDeveloper role on the space  
  AND the deployer account's credentials are visible when Bob runs `cf env | jq '.VCAP_SERVICES["deployer"][0].credentials'`
- [ ] Scenario: A user can remove a deployer account by deleting a service  
  GIVEN a SpaceDeveloper Bob  
  AND Bob is logged in  
  AND there's a pre-existing deployer service `hal` in the space  
  WHEN Bob runs `cf delete-service hal -f`  
  THEN the deployer account is made inactive  
  AND the deployer account's role on the space is removed  
  AND the deployer credentials are no longer available when Bob `cf env | jq '.VCAP_SERVICES["deployer"][0].credentials'`

**Implementation sketch**
- Create deployer account zone in UAA with restrictions on password-changes and extra-long password age limits
- Modify deployer-creator script to use UAA and put deployer users in that zone
- [Provide SkyPorters with a UAA client that has `scim.write` in order to be able to use the script]
- Create a broker that instantiates a deployer user in the space and causes the deployer's creds to appear in the VCAP_SERVICES for the space

**Comment by rogeruiz** [comment]
https://gist.github.com/jmcarp/004ee5ddf490c460c93c32f32325dc0b

**Comment by rogeruiz** [comment]
There's a repo now. Thanks @jmcarp 🎉 https://github.com/18F/deployer-account-broker

**Comment by rogeruiz** [comment]
Cleaning up metadata and adding tests today @jmcarp. ~~We'll need to make a separate story about how we offer this users.~~ @mogul says let's document this for users for _GovCloud only_.

**Comment by mogul** [comment]
@jmcarp is this done and deployed, or is there more work? We want to merge [the docs change](https://github.com/18F/cg-site/pull/521) so that @berndverst can link to them from a newsletter.

**Comment by jmcarp** [comment]
Shipped it.
