### ISSUE TITLE
Close POAM V17-CM-6: X-Content-Type-Options Header Missing

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#438]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

[Document for drafting operational requirements](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit)

**Acceptance Criteria**:
- [x] Where possible, we have OWASP ZAP scans that show this is fixed.
- [x] For the rest that depend on upstream PRs, we've documented an operational requirement
- [x] Rationale has been approved by our AO.
- [x] Sent rationale to 3PAO.
- [x] 3PAO has verified our rationale.

**More Information**
- See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.
- [NIST Special Publication 800-53 (Rev. 4) CM-6](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=CM-6)

**Comment by cnelson** [comment]
This has been remediated for sites behind secureproxy, but has not been remediated for other sites (concourse, metrics, etc)

**Comment by brittag** [comment]
Updated acceptance criteria, since we can close OWASP ZAP items by providing updated scans.

**Comment by cnelson** [comment]
Outstanding issues related to this:

https://github.com/18F/cg-product/issues/472
https://github.com/18F/cg-product/issues/469

**Comment by brittag** [comment]
Updated acceptance criteria again to reflect our approach to this one. [Drafted rationale here](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit), sent to AO for approval (https://github.com/18F/Infrastructure/issues/745).

**Comment by brittag** [comment]
There's no more active work on this one to do for now.
