### ISSUE TITLE
Assemble documents for JAB package

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#44]
In order to submit a complete JAB package for Technical Review, we must assemble related documents that will be bundled alongside the SSP in our package.

**Acceptance Criteria**

- [ ] The following documents are all delivered alongside the SSP in [max.gov](https://community.max.gov/display/FedRAMPExternal/GSA+18F+Cloud.gov+Submissions)
  - [x] 5 signed Rules of Behavior sheets
  - [ ] 5 completed role-based training records
  - [ ] 5 completed security awareness training records
  - [x] Incident Response Plan
  - [x] Contingency Plan - https://github.com/18F/cg-docs/issues/284
  - [x] Contingency Plan Testing/Results
  - [ ] User Acceptance Policy/Employee Handbook
  - [x] Configuration Management Plan
  - [ ] Service Level Agreements/MOUs
  - [x] Ports, Protocols and Services Matrix (in SSP already, section 10.8)
  - [x] Information System Architecture (in SSP already, section 9.4, figure 10.1)
  - [x] Incident Response Plan Testing/Results (RAR also states tabletop exercises have been done)
  - [x] Copy of actual training provided to users
  - [x] LATO
  - [x] GSA personnel policies and procedures documentation – hiring & screening, acceptable use policy, etc.

**Comment by jwitles** [comment]
- [ ] A screenshot of the bucket policy and/or object-level ACL associated with 5 S3 buckets currently employed in the Cloud.gov environment to store non-public data
- [ ] A screenshot of the encryption mechanisms currently employed for 5 RDS database instances (if encryption is currently being employed)
- [ ] A screenshot of a user authenticating to the AWS console via multi-factor authentication
- [ ] A screenshot of a user authenticating via SSH to the Cloud Foundry bastion host

**Comment by jwitles** [comment]
- [ ] 5 Stories executed in the Cloud.Gov environment
- [ ] 5 Cards executed in the Cloud.Gov environment
- [ ] 5 Pull Requests executed in the Cloud.Gov environment
- [ ] 5 Screenshots of integration testing failures

**Comment by src-veris** [comment]
PL-2.a.9: Proof that the SSP is reviewed/approved by Cloud.gov Executive Dir and/ GSA CISO
PL-2.b.2: Example of emails sent to users to notify them the SSP has been updated
PL-4.d: Copy of an employee-signed RoB agreement

**Comment by src-veris** [comment]
CM-5.3 / CM-5(3).2 / CM-5.4: Copy of AWS Access Policy

**Comment by andrewledford** [comment]
- [ ] Artifacts demonstrating Cloud.gov lockout after 15 minutes of inactivity including a screen shot after the initial login with a timestamp, a screen shot after 15 minutes of inactivity showing the session timed out and requires reauthentication including the timestamp, and the code indicating when users sessions lockout after a period of inactivity.

- [ ] Documentation explaining how passwords/authenticators are to be protected, safeguarded, and managed.

**Comment by AliMassihi** [comment]
Contingency Plan Updates needed:

- [ ] Populate Recovery Time Objectives (RTO) throughout Contingency Plan

- [ ] Populate Contact Information in Contingency Plan (Section 3.1 - Table 3-1 and Appendix A)

- [ ] Populate Plan Approval information in Contingency Plan

- [ ] Populate Appendix J in Contingency Plan (Test/Maintenance Schedule)

- [ ] Populate Key Roles in Contingency Plan and state they will be notified of changes to CP

- [ ] Include any coordination with IR personnel/AWS etc.

- [ ] Include Information for Alternate Processing Site (Appendix C.2)

- [ ] Populate Appendix C.3 (inherited) in Contingency Plan

- [ ] Populate backup information

**Comment by andrewledford** [comment]
- [ ] Artifacts showing that account creation, modification, enabling, disabling, and removal activities are being logged and alerted for GitHub and AWS.

- [ ] Artifacts that account usage such as successful login attempts, unsuccessful login attempts, etc. are being logged, monitored, and reported.

- [ ] Artifacts showing how duties are separated and how users don't have excessive privileges.

**Comment by src-veris** [comment]
•	PS-2.c.2: Proof that GSA has reviewed & updated position risk description within the last 3 years
•	PS-3.b.3: Proof that 18F employees have been re-screened (redact PII)
•	PS-3(3).a: Sample copy of a completed and signed access authorization form (redact PII)
•	PS-3(3).b.2: Confirm whether or not there are additional personnel screening requirements for Cloud.gov
•	PS-4.b: Proof that employee credentials (badges, tokens, etc..) are revoked during the off-boarding process/exit interview (redact PII)
•	PS-4.f.3: Copy of email notifying personnel when an employee is terminated (redact PII)
•	PS-6.c.2.2: Copy of a re-signed access agreement (redact PII)
•	PS-7.e: Proof that GSA monitors 3rd party vendors monthly for compliance with security policies
•	PS-8.b.3: Copy of employee sanction process being initiated (or completed) (redact PII)

**Comment by src-veris** [comment]
PS-3b.2: How often are employees re-screened? Annually? According to type of background check - public trust vs secret security clearance?

**Comment by afeld** [comment]
Let's link to the relevant stories for each of the tasks, since this is kind of an Epic.

**Comment by rogeruiz** [comment]
@mogul: ~~We either need to break this up or~~ Let's have people assign themselves to each box

**Comment by mogul** [comment]
From Veris via e-mail:
> In order to hit the 7/15 date for delivery of the SAR, we need to have all evidence in hand by end of day Wednesday 7/8. That will allow us time to wrap up the write-ups and put together the SAR. Feel free to still collect additional evidence and we can review it as part of the mitigation process post-delivery of the draft SAR. We just need time to piece it all together beforehand.

**Comment by rogeruiz** [comment]
@dlapiduz Can you make sure that this card is update?

**Comment by andrewledford** [comment]
- [ ] Artifacts showing that local accounts are disabled by default and that no local accounts exist.

**Comment by dlapiduz** [comment]
FYI, I've been checking things off. The only things really missing is the GSA retraining proofs

**Comment by mogul** [comment]
Veris said in the FedRAMP PMO chat this morning that they're going to give us a consolidated list of what's outstanding; apparently mostly screenshots.

**Comment by mogul** [comment]
@dlapiduz Can you give a status update on this one and/or move it if warranted?

**Comment by rogeruiz** [comment]
We've sent them as much as we could. 👍
