### ISSUE TITLE
Close POAM V19-CM-6: Cross-Domain JavaScript Source File Inclusion

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#440]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

**Implementation sketch**:

- [x] We've written an operational requirement rationale in [this document](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit).
- [x] Our 18F AO has approved this rationale.
- [x] We've emailed this to our 3PAO.

**Acceptance Criteria**:
- [ ] 3PAO verifies that rationale.

**More Information**
- See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.
- [NIST Special Publication 800-53 (Rev. 4) CM-6](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=CM-6)

**Comment by cnelson** [comment]
I believe this to be a false positive / operational requirement.   The cross-domain files in question are analytics (google and DAP) and the statuspage.io widget.

**Comment by brittag** [comment]
Noting for future reference: we also now include search.usa.gov JavaScript on some pages.

**Comment by brittag** [comment]
Updated the story with an implementation sketch that links to a [document for drafting rationales](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit).

**Comment by brittag** [comment]
[Drafted rationale here](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit), sent to AO for approval (https://github.com/18F/Infrastructure/issues/745).

**Comment by brittag** [comment]
There's no more active work on this one to do for now - it's filed in the POAM appropriately.
