### ISSUE TITLE
Close POAM V20-CM-6: Incomplete or No-Cache-control and Pragma HTTP Header Set

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#441]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

[Document for drafting operational requirements](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit)

**Acceptance Criteria**:
- [x] Update POAM to show that some of the results are resolved with new scans, and that the rest are "operational requirement" while we wait for upstream to merge PRs
- [x] Get operational requirement approval from AO
- [x] Email rationale to 3PAO
- [ ] 3PAO verifies it

**More Information**
- See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.
- [NIST Special Publication 800-53 (Rev. 4) CM-6](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=CM-6)

**Comment by cnelson** [comment]
This needs discussion, we need to decide if we want to remediate this very low risk at the expense of performance and user experience.

**Comment by brittag** [comment]
Updated the acceptance criteria on this one to TODO. The acceptance criteria (the tasks to close the POAM) depend on whether we'll fix this or accept the risk:

* If we fix this, we can close this in the POAM just by providing a new OWASP ZAP scan that shows it fixed.
* If we accept the risk, we need to put a rationale in [this document](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit#), get it approved by our 18F AO, and get it verified by our 3PAO.

**Comment by cnelson** [comment]
This is in progress, but some remediations are going to require upstream changes.  Our response to this is going to be a mixed bag:  In some cases we'll have remediated it and can provide clean scans,  in others, we'll need to accept the risk while we wait for upstream to merge our PRs, in others we just won't fix and will need to perm accept risk because it's not appropriate to set hyper-restrictive cache control headers.

Details for each impacted component are in the linked issues above ☝️

**Comment by brittag** [comment]
Updated acceptance criteria!

**Comment by brittag** [comment]
This OWASP ZAP item ("Incomplete or No-Cache-control and Pragma HTTP Header Set") is apparently already tracked as an operational requirement in our SAR, with the comment of "Cloud.gov requires caching to ensure normal operations. The browser cannot be limited in caching the page." [See page 31 here.](https://docs.google.com/document/d/1z2yYlBULCWdO3YHr8x1Sy4xFnp3zBE_pohk6BV_Q7vE/edit#)

I believe this means we don't need to actually fix this one, unless we think it's worth fixing.

**Comment by brittag** [comment]
Since we have an update for this one, we'll document it anyway. [Drafted rationale here](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit), sent to AO for approval (https://github.com/18F/Infrastructure/issues/745).

**Comment by brittag** [comment]
There's no more active work on this one to do for now - we'll just update the POAM item when https://github.com/18F/cg-product/issues/469 and https://github.com/18F/cg-product/issues/472 make progress.
