### ISSUE TITLE
Close POAM V22-CM-6: Cookie Without Secure Flag

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#443]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

[Document for drafting operational requirements](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit)

**Acceptance Criteria**:
- [x] Update POAM to show that some of the results are resolved with new scans, and that the rest are "operational requirement" while we wait for upstream to merge PRs
- [x] Get operational requirement approval from AO
- [x] Send to 3PAO
- [ ] Approved by 3PAO

**More Information**
- See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.
- [NIST Special Publication 800-53 (Rev. 4) CM-6](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=CM-6)

**Comment by cnelson** [comment]
This issue is real, but I think needs discussion on if we want to remediate this issues or accept the risk as we do not allow any non-HTTPS services under the cloud.gov domain.

Remediation would likely require PR changes to Concourse and Community, and making simple changes to the console and invite apps.

**Comment by brittag** [comment]
Updated the acceptance criteria on this one to TODO. The acceptance criteria (the tasks to close the POAM) depend on whether we'll fix this or accept the risk:

* If we fix this, we can close this in the POAM just by providing a new OWASP ZAP scan that shows it fixed.
* If we accept the risk, we need to put a rationale in [this document](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit#).

**Comment by cnelson** [comment]
This is in progress, but some remediations are going to require upstream changes.  Our response to this is going to be a mixed bag:  In some cases we'll have remediated it and can provide clean scans,  in others, we'll need to accept the risk while we wait for upstream to merge our PRs.

**Comment by brittag** [comment]
Thank you, updated acceptance criteria!

**Comment by brittag** [comment]
[Drafted rationale here](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit), sent to AO for approval (https://github.com/18F/Infrastructure/issues/745).

**Comment by NoahKunin** [comment]
See comment in Google Doc, otherwise approved.

**Comment by brittag** [comment]
Updated draft rationale to be extra clear: https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit?disco=AAAAA4zUNUE

**Comment by brittag** [comment]
There's no more active work on this one to do for now - we'll just update the POAM item when https://github.com/18F/cg-product/issues/469 and https://github.com/18F/cg-product/issues/472 make progress.
