### ISSUE TITLE
Close POAM V23-CM-6: Password Autocomplete in Browser

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#444]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

**Implementation sketch**:

- [x] We've written a false positive rationale in [this document](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit).
- [x] Our 18F AO has approved this rationale.
- [ ] We've emailed this to our 3PAO.

**Acceptance Criteria**:
- [ ] 3PAO verifies that rationale.

**More Information**
- See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.
- [NIST Special Publication 800-53 (Rev. 4) CM-6](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=CM-6)

**Comment by cnelson** [comment]
This is a false-positive.  metrics and community are both configured to use MFA auth via UAA/Secureauth.  User/pass authentication is not allowed.

**Comment by brittag** [comment]
Updated the story with an implementation sketch that links to a [document for drafting rationales](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit).

**Comment by brittag** [comment]
This OWASP ZAP item ("Password Autocomplete in Browser") is apparently already tracked as an operational requirement in our SAR, with the comment of "Turning off autocomplete disables the password managers in place for the system." [See page 31 here.](https://docs.google.com/document/d/1z2yYlBULCWdO3YHr8x1Sy4xFnp3zBE_pohk6BV_Q7vE/edit#)

I believe this means we don't need to actually document this one.

**Comment by brittag** [comment]
Since there's an update to this item, we're documenting it anyway for now. [Drafted rationale here](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit), sent to AO for approval (https://github.com/18F/Infrastructure/issues/745).

**Comment by brittag** [comment]
Decided that sending an update for this isn't necessary. Closing this.
