### ISSUE TITLE
Close POAM V24-CM-6: Secure Pages Include Mixed Content

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#445]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

**Implementation sketch**:

- [x] We've written a false positive rationale in [this document](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit).
- [x] Our 18F AO has approved this rationale.
- [x] We've emailed this to our 3PAO.

**Acceptance Criteria**:
- [ ] 3PAO verifies that rationale.

**More Information**
- See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.
- [NIST Special Publication 800-53 (Rev. 4) CM-6](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=CM-6)

**Comment by cnelson** [comment]
This is a false positive.  It refers to insecure URLs in _comments_ in https://logs.fr.cloud.gov/bundles/commons.bundle.js:

    /**
         * @ngdoc directive
         * @name ngSrc
         * @restrict A
         * @priority 99
         *
         * @description
         * Using Angular markup like `{{hash}}` in a `src` attribute doesn't
         * work right: The browser will fetch from the URL with the literal
         * text `{{hash}}` until Angular replaces the expression inside
         * `{{hash}}`. The `ngSrc` directive solves this problem.
         *
         * The buggy way to write it:
         * ```html
         * <img src="http://www.gravatar.com/avatar/{{hash}}" alt="Description"/>
         * ```
         *
         * The correct way to write it:
         * ```html
         * <img ng-src="http://www.gravatar.com/avatar/{{hash}}" alt="Description" />
         * ```
         *
         * @element IMG
         * @param {template} ngSrc any string which can contain `{{}}` markup.
         */

I have also manually loaded logs.fr.cloud.gov and verified that all resources are accessed via `https` scheme

**Comment by brittag** [comment]
Ha! This seems like a bug in OWASP ZAP - we might want to investigate whether they're fixing this upstream.

**Comment by brittag** [comment]
Updated the story with an implementation sketch that links to a [document for drafting rationales](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit).

**Comment by brittag** [comment]
[Drafted rationale here](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit), sent to AO for approval (https://github.com/18F/Infrastructure/issues/745).

**Comment by brittag** [comment]
There's no more active work to do for this one - it's filed in the POAM appropriately.
