### ISSUE TITLE
Close POAM V73-IA-5: Weak Password Requirements

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#447]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

**Implementation sketch**:

- [x] We've written a false positive rationale in [this document](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit).
- [x] Our 18F AO has approved this rationale.
- [x] We've emailed this to our 3PAO.

**Acceptance Criteria**:
- [ ] 3PAO verifies that rationale.

**More Information**
- See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.
- [NIST Special Publication 800-53 (Rev. 4) IA-5](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=IA-5)

**Comment by cnelson** [comment]
I believe this one to be a false-positive.  The last comment is:

> cloud.gov doesn't use password based accounts on the metris app. Needs re testing with 3PAO

☝️ That is correct; although grafana displays a user/pass as part of the login UI, we only use third-party authentication. Is it possible we gave the 3PAO a user/pass based account for testing?

**Comment by brittag** [comment]
Updated the story with an implementation sketch that links to a [document for drafting rationales](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit).

**Comment by brittag** [comment]
Related task: https://github.com/18F/cg-atlas/issues/175 ("Authenticate metrics against in-boundary IDP")

**Comment by mogul** [comment]
Yes, I believe we should be marking this as a false-positive. That said, we still need to change metrics.fr.cloud.gov from GitHub to UAA as the authentication provider, and that will need testing once it's done. I suggest we leave this one open and have Veris retest metrics.fr.cloud.gov when we're on UAA, which will address the false-positive finding (eg we can show them that we're not using local accounts) as well as the test needed after we change to UAA; this will cut down on tracking overhead.

**Comment by brittag** [comment]
We chatted about this, and we'll continue with the plan as currently written in the story - we'll handle this as a false positive for the POA&M in order to meet the POA&M requirements and deadlines, and separately we'll also do the related GitHub -> UAA work tracked at https://github.com/18F/cg-atlas/issues/175

**Comment by brittag** [comment]
[Drafted rationale here](https://docs.google.com/document/d/1sMVT-lcgHzzNvsvxqpEJ3OY04WXwAQhY5ObA0gIPrzg/edit), sent to AO for approval (https://github.com/18F/Infrastructure/issues/745).

**Comment by brittag** [comment]
There's no more active work on this one to do for now - it's filed in the POAM appropriately.
