### ISSUE TITLE
IAA Process Status Updates

### ISSUE THREAD

**Issue by berndverst** [18F/cg-product#456]
Appropriate users are notified when IAAs move along

**Comment by nikzei** [comment]
Ideas?

I imagine that we could do this in stages:
- the first stage being that we/you @berndverst send email notifications along the way as you receive information from ops;
- second stage would be some automated version of this (not optimistic that this will be possible in the immediate future).

**Comment by nvembar** [comment]
Before you go down the road of automating the IAAs yourself, we've been working on doing just that and including Matt Spencer in it. So, we may be already working along the same lines.

**Comment by nikzei** [comment]
@nvembar  - would love to hear about it!

**Comment by nvembar** [comment]
Let me find us some time....

**Comment by nvembar** [comment]
So - Romke and Matt Spencer have been working with my team on building out the capabilities around sales + IAAs. There is future planned integration that would make the connection you're talking about, but we're capturing the stories from those two for our implementation. You may want to talk to them and then float into the discussions. I think we're probably pretty far along what you need!

**Comment by nikzei** [comment]
Following up, the plan on our end:
- looking forward to staying synched with Romke, Matt, et. al. and seeing the forthcoming demo. Thanks Navin! 
- @bernd, let's still continue to track needs specific to our use case and seek to solve them in lightweight ways.
