### ISSUE TITLE
Raise alert on unmonitored system

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#458]
In order to ensure that all systems on the network are being monitored, we should raise an alert when we detect a system which is not currently logging metrics

Acceptance Criteria:

- [x] Host with collectd stopped raises alert
- [x] Host without any reporting raises alert

**Comment by cnelson** [comment]
@sharms WDYT about those PRs?

**Comment by sharms** [comment]
Looks good, merged!

**Comment by cnelson** [comment]
Anything else we need to do (other than roll this out to prod to close this card?)

**Comment by sharms** [comment]
Roll it out, create a new EC2 instance, verify alert is raised, and delete the instance

**Comment by cnelson** [comment]
While testing this in staging today, I noticed that bosh not emit metrics for complication or errand VMs, so any time one of those is created, we will get false-positive alerts for those VMs.

I'm unsure how to solve this problem, as errand and compilation VM resources are ephemeral so whitelisting them isn't an option.

Anyone have any bright ideas?

**Comment by jbarnicle** [comment]
@cnelson Is monitoring for false positives at the moment.

**Comment by cnelson** [comment]
Assigning to @sharms to accept and close.
