### ISSUE TITLE
trainings for new customers

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#459]
Acceptance Criteria tbd (based on feedback from users?).  

Cloud Foundry training for technical customers --> we should tap into existing resources like https://www.cloudfoundry.org/training

cc @mogul @berndverst

**Comment by afeld** [comment]
My agendas from past trainings I've run: https://docs.google.com/document/d/1N0VQf5y0ZeO-9BS0Xk1W2p-YetF7HUqzSB4D-Kj7MXw/edit

**Comment by nikzei** [comment]
Navin expressed interest in having a training for his team. We'll keep circling back to him to see what he needs - might make most sense to start by shaping it to what he's looking for?

**Comment by afeld** [comment]
@nvembar ^

**Comment by mogul** [comment]
Talk to Steve Greenberg about his previous work to develop the official training materials and certification exam for the CF Foundation!
