### ISSUE TITLE
RSC-A: Ensure S3 data is encrypted at rest in GovCloud deployment

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#46]
In order to comply with `NIST 800-53 SC-*`, the cloud.gov team should ensure that all data in S3 is encrypted at rest.

**Acceptance Criteria**

- [x] Make sure that all S3 buckets are encrypted

**Implementation Sketch**

* Investigate whether Diego's new Go-based S3 encryptor can be run in CF as he expects without access issues
* Josh says BOSH is accepting a PR to encrypt log files as they're uploaded to S3 without shenanigans

**Comment by dlapiduz** [comment]
@sharms are we encrypting all buckets/some buckets? how does it work?

**Comment by dlapiduz** [comment]
I see encrypted files!
