### ISSUE TITLE
Write response comments for AT, IR, PE, PL, SA, SC, SI

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#460]
In order for our next JAB Q&A meeting to run smoothly and effectively, we need to review their comments ahead of time and write response comments.

We should send our PMO a copy of our response comments as soon as we can.

We're writing comments in [this copy of the workbook](https://docs.google.com/spreadsheets/d/1mGkPwJFh2-dftFB6WF189g55Jl4WpnQcE_vX9iibRpM/edit#gid=694365809).

Note: We don't yet have a *complete* set of comments - one of the TRs is still working on AT, PE, PL (expected soon) - but we can still get started on this.

Ideally we should send this by COB Wednesday.

**Acceptance criteria**

We have response comments for all of the following:

- [x] 0 AT items
- [x] 21 IR items
- [x] 1 PE item
- [x] 1 PL item
- [x] 3 SA items
- [x] 20 SC items
- [x] 28 SI items

And:
- [x] We've emailed the updated workbook to our PMO

**Comment by brittag** [comment]
I wrote draft comments for about ~18 easy ones. There are tricky IR ones about information spillage, and a lot of the SC and SI ones are specific technical questions that I can't answer.

**Comment by brittag** [comment]
Updated the workbook link to one with additional IR and SI comments.

**Comment by mogul** [comment]
Sent and meeting held
