### ISSUE TITLE
RSC-B: Ensure RDS data is encrypted at rest in GovCloud deployment

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#47]
In order to comply with `NIST 800-53 SC-*`, the cloud.gov team should ensure that all RDS data is encrypted at rest.

**Acceptance Criteria**

- [x] Make sure that all terraform provisioned RDS instances are encrypted
 - [x] tooling BOSH
 - [x] staging BOSH
 - [x] production BOSH
 - [x] staging concourse
 - [x] production concourse

**Implementation Sketch**

* Take backups of BOSH and Concourse RDS instances
* Update Terraform config to require encryption on RDS
* Run Terraform to recreate RDS instances with encryption
* Restore BOSH and Concourse RDS data
* Re-deploy BOSH and Concourse with new RDS urls

**Comment by afeld** [comment]
@LinuxBozo Mind listing tasks or linking to other more specific issues?

**Comment by mogul** [comment]
All set!
