### ISSUE TITLE
Dashboard should return secure HTTP headers

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#470]
In order to be in compliance with best practice security guidelines I want this application to send the appropriate HTTP headers.

**Acceptance Criteria**
- [x] Cookies should be set with [secure](https://github.com/18F/cg-product/issues/443) and [HttpOnly](https://github.com/18F/cg-product/issues/442) flags where appropriate

**Comment by jbarnicle** [comment]
@adborden reviewing PRs for this
