### ISSUE TITLE
Community should return secure HTTP headers

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#471]
In order to be in compliance with best practice security guidelines I want this application to send the appropriate HTTP headers.

**Acceptance Criteria**
- [x] Cookies should be set with [secure](https://github.com/18F/cg-product/issues/443) and [HttpOnly](https://github.com/18F/cg-product/issues/442) flags where appropriate 
- [x] Include a ["Cache-Control" header with "no-cache, no-store, must-revalidate, private" and "Pragma: no-cache" header](https://github.com/18F/cg-product/issues/441) where appropriate

**Comment by cnelson** [comment]
Discourse CD pipeline was updated:

https://github.com/18F/aws-broker/pull/24
https://github.com/18F/cg-deploy-discourse/pull/1 
https://github.com/18F/discourse/pull/3

**Comment by jmcarp** [comment]
I have a few questions about configuring email and oauth for @dlapiduz in https://github.com/18F/cg-deploy-discourse/pull/2 and https://github.com/18F/cg-deploy-discourse/pull/3 that are blocking deploy to production. Once those are resolved, we can rerun scans and verify that this is done.

**Comment by cnelson** [comment]
@jmcarp looks like both those PRs were merged by @dlapiduz, is this still blocked?

**Comment by cnelson** [comment]
@jmcarp I (and ZAP) are seeing the `HttpOnly` flag on cookies, but not the `secure` flag.  Can you take a look?

**Comment by jmcarp** [comment]
So discourse only appears to apply `Secure` to the `_t` cookie when `force_https` is set--which cookies are missing the `Secure` header?

**Comment by cnelson** [comment]
OWASP is complaining about `_forum_session`

**Comment by jmcarp** [comment]
I did some more reading on this, and it looks like discourse recently put in a fix to set the secure header on `_forum_session` too: https://meta.discourse.org/t/secure-cookie-flag/28058/40. I'll try merging the latest release into our fork and update here when it's working.

**Comment by cnelson** [comment]
Verified this is fixed and have a clean ZAP scan to prove it.  Closing
