### ISSUE TITLE
"fail closed" when logging isn't possible

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#476]
In order to comply with NIST 800-53's AU-5 control while minimizing our chances of a full system shutdown, we want our logging capability to benefit from the high SLA for AWS CloudWatch.

**Acceptance Criteria**

- [x] Atlas: If a host can't log locally (eg both syslogd AND cloudwatchd are MIA), then the host shuts down for later forensics/log-mining/reingestion
- [x] Atlas: A CloudWatch nozzle is attached to Loggregator (so if ELK breaks the platform continues to serve traffic)
- [x] HighBar: SSP and related diagrams are updated to show that all logs also go to CloudWatch
- [x] HighBar: We document the operational requirement to keep customer apps up and handling traffic even when their logs aren't reaching Loggregator.

**Implementation sketch**

Current logging paths:

- App logs: ELB -> VPC flow logs -> router-> app [ ->] Loggregator (buffers, etc) -> ELK -> S3
- Platform logs: local logs -> syslog server -> CloudWatch
- Host logs: local logs -> syslog server -> CloudWatch

**Comment by cnelson** [comment]
The PRs above ☝️ are a sketch of how we could go about satisfying the first AC.  I propose the following:

- Modify rsyslog so it emit's MARK messages on a regular interval.  This ensures that we know that the syslog -> cloudwatch pipeline running on each host will have new events (heartbeat) on a known frequency regardless of the workload on that instance
- Extend the existing check-awslogs job to emit per-instance metrics for the LogGroup that contains these MARK heartbeat entries
- Extend the existing unknown-vms job to emit uptime metrics for all known VMs
- Add new alerts/actions in riemann when known VMs have been up for > X minutes and haven't logged for Y minutes
  - Rate limit the number of destructive actions (stopping VMs) that are automatically triggered so that a general failure of cloudwatch doesn't immediately take down our entire system

**Comment by mogul** [comment]
Interesting! So instead of host-based behavior, it's handled at the whole-system level... It feels a bit like cauterizing a wound, but I like it! It emphasizes the onus on us to try to flush out remaining single-points-of-failure going forward, but it's not like it wasn't there before.

**Comment by cnelson** [comment]
The riemann piece of this is now in place.  From the PR linked above:

- [riemann config for running an external script when vms aren't logging](https://github.com/18F/cg-riemann-boshrelease/blob/ae373810ccf2d5955e169156be011f16c47d6f0f/jobs/riemann/templates/config/no_logs.clj.erb)
- [the external script used to snapshot and stop-VMs](https://github.com/18F/cg-riemann-boshrelease/blob/ae373810ccf2d5955e169156be011f16c47d6f0f/jobs/riemann/templates/bin/stop-vm.sh)

This is running in staging right now but is being prevented from actually killing VMs by not granting the required permissions to riemann's iam role.

Thoughts on this approach?

**Comment by cnelson** [comment]
I've been testing this all day by stopping the awslogs agent on nodes, and it's working as expected. 

Needs review from someone else, and once they've approved it we probably need to add some ops documentation about this, although I'm not sure exactly where or what form that will take.

**Comment by cnelson** [comment]
Just noting for the record this has been running in staging for 5 days and hasn't had any false positives.

**Comment by mogul** [comment]
@cnelson can you get together with @brittag to address the HighBar ACs on this one? She's working on SSP updates today.

**Comment by mogul** [comment]
@cnelson and I just handled all the necessary HighBar ACs, and I've sent @brittag the SSP changes for incorporation into her next version.

**Comment by cnelson** [comment]
Waiting on #525 to be completed before closing this to ensure that errand VMs are killled as false positives.

**Comment by cnelson** [comment]
Attempted to verify and close this morning and found non of the cron-jobs required to make this happen are running.  Currently investigating why, moving back to in-progress 😢

**Comment by rogeruiz** [comment]
Cron release needs to be removed from addons.

**Comment by cnelson** [comment]
I think these are all the deployments that currently require cronjobs:

- https://github.com/18F/cg-deploy-monitoring
- https://github.com/18F/cg-deploy-nessus-manager
- https://github.com/18F/cg-deploy-bosh
- https://github.com/18F/cg-deploy-kubernetes

**Comment by rogeruiz** [comment]
https://github.com/18F/cg-deploy-monitoring/pull/105
https://github.com/18F/cg-deploy-kubernetes/pull/58
https://github.com/18F/cg-deploy-nessus-manager/pull/8
https://github.com/18F/cg-deploy-bosh/pull/49

**Comment by mogul** [comment]
Given those four PRs have been merged, what remains to be done here?

**Comment by cnelson** [comment]
I just need to review that this is actually running and working.  Apologies for it sitting in my backlog for so long.

**Comment by cnelson** [comment]
@brittag This is now completed. Do you need anything from me/atlas (documentation, POAM response draft, etc) to close V36-AU-5  / CG01-AU-5 ?

**Comment by brittag** [comment]
@cnelson Thank you!! Can you take a look at the [POAM email drafts here](https://docs.google.com/document/d/1YmLBWDiHb5w1NNyhBzMwuJkc4UYDxQMbsuLXesCh_9E/edit#heading=h.g0zgo5fze393) for V36-AU-5 (under "remediated weaknesses") and CG01-AU-5 (under "operational requirements") and see if there's any useful detail that we can add to help Veris understand our work? If you can think of any relevant screenshots or links to configuration info that helps prove we did this work, that can help too.
