### ISSUE TITLE
Shut off access to apps that spam logs

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#478]
In order to prevent DDoS of a hosted app forcing us to take the rest of platform/customers offline (due to AU-5), we want apps which spam Loggregator to be made unavailable, with an alert sent.

**Comment by dlapiduz** [comment]
I'd do this as a technical debt story rather than something that we should tackle now...

**Comment by brittag** [comment]
It's unclear to me right now what the expected due date for this would be, but if this is part of how we plan to fulfill AU-5, we'd likely need to have it done in the next ~3 weeks (and sooner rather than later).

**Comment by brittag** [comment]
Noting that https://github.com/18F/cg-product/issues/476 is the main set of tasks for fulfilling AU-5.

**Comment by mogul** [comment]
Icebox'd as #476 is all we need for now.

**Comment by cnelson** [comment]
@mogul We may want to un-icebox this and consider it for anti-fragility work later in this PI.

I've been reviewing our historical log data while overseeing the logsearch restore process and I've noticed several instances where apps have generated huge amounts of logs and we didn't notice.  

For example, in just 4 days (11/10-11/13) the system generated more logs (250 GB) than all of December and January combined (~ 100 GB / month).  98% of those logs were generated by just two apps stuck in a crash loop logging the same stack trace over and over.

This unchecked logging has several impacts on platform health beyond possibly causing loggregator to drop other logs:
- It's an indicator that the platform may be under attack.  We should know if our log volume suddenly grows by an order of magnitude or more
- We are paying Amazon to retain those logs in S3 and CloudWatch Logs
- If we need to reindex log data in the case of a cluster failure, every additional log entry extends the time it takes for us to bring the logsearch platform back to operational status.
