### ISSUE TITLE
Ramp up Scott on cloud.gov team

### ISSUE THREAD

**Issue by suprenant** [18F/cg-product#480]
In order to get Scott productively contributing to the cloud.gov team, Andrew should help Scott complete a prescribed set of tasks that will bring them up to speed.

# Directions:
**Scott and Andrew:** Try to go through your checklists in order.
**Andrew:** If you can’t complete any of the items on your checklist personally, _you are responsible for ensuring that an appropriate person does it_.

### Getting to know cloud.gov
- [ ] Take judicious notes on what about this onboarding process or cloud.gov is confusing or frustrating. If you notice a problem (especially with things like documentation), you are more than welcome to fix it! At the very least, please share this information with your buddy (or someone) at some point so we can make the team/platform better. (You can also file issues and pull requests on [the template for Onboarding issues](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md).)
- [x] Bookmark the [pertinent links listed here](https://github.com/18F/cg-product/blob/master/PertinentLinks.md).
- [x] Figure out who your onboarding buddy is (they should reach out to you) and make sure this issue is assigned to them
- [x] Read [the team onboarding document](https://github.com/18F/cg-product/blob/master/Onboarding.md) for more context about cloud.gov
- [x] Read the ["What is it?"](https://docs.google.com/presentation/d/1nCcti3dXG9TVGW3OqaWtnf96oXX8U8SBTM_WePFO_dg/edit#slide=id.p) presentation for a rundown of what cloud.gov is and does
- [x] Read through [the Introduction section of docs.cloud.gov](https://docs.cloud.gov/) for a broader understanding of cloud.gov, especially as we present it to potential customers/users
- [x] Read the [January 2016 cloud.gov "Executive Business Case" document](https://docs.google.com/document/d/138OcG0Lt6gr9J0wM0TzzPNyTROmYAwfLIDujtweiwGw/edit#) for greater context about cloud.gov's potential impact in government
- [x] Try to [deploy a sample application to cloud.gov](https://docs.cloud.gov/getting-started/your-first-deploy/) to get familiar with the basics of the PaaS from a user's perspective
- [x] Check out the [roadmap](https://18f.aha.io/products/CGP/feature_cards) to get a high-level view of recently-completed, in-progress, and upcoming features
- [x] Install the [ZenHub](https://zenhub.io) browser extension to enable you to see kanban boards, hierarchical issues, and burndown charts in GitHub
- [x] Read the [Delivery Process document](https://github.com/18F/cg-product/blob/master/DeliveryProcess.md) to learn about how we work
- [x] Join [the cloud.gov support Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov-support), so you can see how we handle non-18F support and get visibility of technical discussions happening with outside groups
- [x] Join [the cloud.gov team Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov), so you can participate in team-wide internal communication
- [x] Figure out what themes you're likely to work in, and complete the checklist below that relates to it
- [ ] Once you've finished the remaining checklists below, make suggestions for steps that would have improved your onboarding experience as pull requests on [the onboarding checklist template](https://github.com/18F/cg-product/blob/master/OnboardingChecklist.md) used to make this issue

### Required items for all team members

These items help us fulfill security and compliance requirements (including for FedRAMP). If you get stuck, or if these requirements are confusing, ask for help from your buddy or in a cloud.gov channel.

- [x] Read the [18F Security Policies and Procedures](https://github.com/18F/compliance-docs). These documents (which are mostly quite short) explain the high-level policies and procedures we must comply with while running cloud.gov.
- [x] Read the [Incident Response Guide](https://docs.cloud.gov/ops/security-ir/).
- [ ] Coordinate with your onboarding buddy to go through Incident Response Training within 60 days of joining the team (and annually after that).
- [x] Read the [Contingency Plan](https://docs.cloud.gov/ops/contingency-plan/).
- [x] Read the [Continuous Monitoring Plan](https://drive.google.com/file/d/0B1cewEqKcWCbZlFuQklZVWpLV1k/view), particularly section 2.5.
- [ ] Coordinate with your onboarding buddy to go through Contingency Planning training within 10 days if you'll be taking on a significant role in our Contingency Planning processes (or annually if not).
- [x] Read the [Configuration Management Plan](https://docs.cloud.gov/ops/configuration-management/).
- [x] Subscribe to [the cloud.gov team calendar](https://calendar.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks@group.calendar.google.com&ctz=America/Los_Angeles) (click the + in the bottom right) so you know when assorted team meetings are happening in the various streams
- [x] Subscribe to the [cg-docs](https://github.com/18F/cg-docs) GitHub repository notifications

### Theme-specific items

For explanations of our theme names, see [this glossary](https://github.com/18F/cg-product#sub-teamsthemes-of-work).

#### Navigator-specific items

- [x] Join the `#cloud-gov-navigator` channel on Slack
- [x] Review the main [front end board](https://github.com/18F/cg-dashboard/pulls#boards?repos=55727091,39210774,49169967,40567233&labels=Navigator&showPRs=false) (ensure to filter by the "Navigator" label)
- [x] Bookmark link to [design folder](https://drive.google.com/drive/u/1/folders/0BwLqM4Nicmq-bUt0NjRjclFMUEU)
- [x] Review the primary cloud.gov sites: [the dashboard](https://dashboard.cloud.gov/#/), [main landing page](https://cloud.gov/), and [documentation](https://docs.cloud.gov/).
- [x] [Request access to 18F Google Analytics](https://handbook.18f.gov/google-analytics/), so you can view cloud.gov site analytics ([including for the dashboard](https://docs.google.com/document/d/1gSbP2ak2a3QLpCZIF_KlbQ2QHE6RjDI-7ZnnrJZvMDE/edit))
- [x] Ask for an invite to a DigitalGov Search account for cg-docs, so you can configure it and view analytics
- [x] Ping @standup-bot for instructions on front end channel standup

##### If developing
- [x] Review [dashboard contributing guide](https://github.com/18F/cg-dashboard/blob/master/CONTRIBUTING.md) and [cg-style standards](https://github.com/18F/cg-style/blob/master/documentation/frontend_standards.md) which help frame what we're looking for in code review
- [x] Set up cg-style to be [linked to the other sites locally](https://github.com/18F/cg-style#development-and-contributing-setup)
- [x] Have cloud.gov person send the cg-dashboard testing env vars through Fugacious

##### For review
- [x] Review the [design principles wiki](https://github.com/18F/cg-product/wiki) which explains the thinking behind the product and where that thinking comes from
- [x] Review the [design resource request document](https://docs.google.com/document/d/1s96VP6PB7fbc8g_GwgAZ1hCPmew-J35ZOJx772c1AZ4/edit) if you haven’t already to get a sense of your role on the project
- [x] Review the [design principles doc](https://docs.google.com/spreadsheets/d/14Y3RKaLUt6RPX5w13iz7oaSCpojEQ-Wqjnd8Ie_VkCc/edit#gid=259774738) to get a sense of how the cloud.gov team feels about the product
- [x] Review the [competitive analysis](https://docs.google.com/spreadsheets/u/1/d/194tGz75NFwFyH8jT7zY_n-O0I7N4yAGYtIG4hw9qPcQ/edit?usp=drive_web) to get a sense of our "competitors" and their dashboards.
- [x] Review the [cg-style styleguide](https://pages.18f.gov/cg-style/) to get a sense of the global cloud.gov visual style.
- [x] Review the [US Web Design Standards](https://standards.usa.gov/) as cg-style was built from it.
- [x] Review the dashboard: current [prod](https://dashboard.cloud.gov/#/), [master](https://dashboard-master.apps.cloud.gov/#/) and [staging](https://dashboard-staging.apps.cloud.gov/#/)
- [x] Review the Cloud Foundry [community UI](http://ui.apps.cloud.gov/), a UI that members of the Cloud Foundry community created and that we're using a basis for our own dashboard design

---
## Buddy (Andrew) checklist
- [x] Introduce yourself to the new team member and give them some of your background so they know who you are
- [x] Identify a straightforward, well-groomed story that involves their skills domain. Discuss the context with them, then either make them the assignee for the card or set up pairing for the owner of this story. 

### Required items for all team members

These items help us fulfill security and compliance requirements (including for FedRAMP).

- [x] Make sure they're in [the list of people working on the project](https://docs.google.com/spreadsheets/d/1mW3tphZ98ExmMxLHPogSpTq8DzYr5Oh8_SHnOTvjRWM/edit#gid=0)
- [x] Add them to the @cloud-gov-team [in Slack’s Team Directory](https://get.slack.help/hc/en-us/articles/212906697-User-Groups#edit-a-user-group), which also adds them to the right channels (or ask #admins-slack if you don't have permission to do this)
- [x] Add them to the recurring cloud.gov meetings that are relevant for them in [the team calendar](https://calendar.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks@group.calendar.google.com&ctz=America/Los_Angeles)
- [x] Ask `#admins-github` to add them to the [@18F/cloud.gov team](https://github.com/orgs/18F/teams/cloud-gov) on GitHub

**Comment by suprenant** [comment]
Noting that @msecret will likely help for the dev-related issues here. Thanks, Marco!

**Comment by line47** [comment]
Under the section **Getting to know cloud.gov**, Bookmark the pertinent links listed here goes to https://github.com/18F/cg-product/issues/PertinentLinks.md which is a 404.

**Comment by suprenant** [comment]
@line47 good catch – please use this. Will update this issue as well as our template. Thanks!

https://github.com/18F/cg-product/blob/master/PertinentLinks.md

**Comment by line47** [comment]
Would be helpful to have the bulleted list under "For Review" in a checklist format as well.

**Comment by suprenant** [comment]
@line47 done. Updating the template, as well.

**Comment by line47** [comment]
I would suggest removing the `"Review the competitive analysis to get a sense of our "competitors" and their dashboards."` checklist item as the analysis didn't seem to be complete and therefore didn't provide much relevant information.

**Comment by suprenant** [comment]
@line47 good catch. Rather than pulling it, I'll plan on fleshing out that page a bit more.

**Comment by suprenant** [comment]
Noting that we're aiming to wrap this in this cycle.

**Comment by line47** [comment]
The cg-product [design principles wiki](https://github.com/18F/cg-product/wiki) is lacking content for many sections.

**Comment by suprenant** [comment]
@line47 yeah, we could keep improving that for sure. Have a new issue for that here FYI: https://github.com/18F/cg-dashboard/issues/775

**Comment by suprenant** [comment]
@line47 looks like this is done. Want to move to Awaiting Acceptance?
