### ISSUE TITLE
Restrict RDS traffic

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#487]
In order to mitigate certain classes of vulnerabilities, we should restrict firewall traffic to RDS subnets to ports `3306` and `5432`

**Acceptance Criteria:**
- [ ] Clients can connect to their databases
- [ ] Databases can respond to the client
- [ ] All traffic other than the above is rejected

**Comment by jmcarp** [comment]
Isn't this already happening in https://github.com/18F/cg-provision/blob/master/terraform/modules/rds_network/sg_postgres.tf#L11-L16 and https://github.com/18F/cg-provision/blob/master/terraform/modules/rds_network/sg_mysql.tf#L12-L17 ?

**Comment by cnelson** [comment]
I think this is about restricting the egress, so that if someone does manage to get code execution on one of our DB servers, they can't exfil data or use it as a jumping off point that's inside our boundary.

@sharms is that what you were thinking?

**Comment by cnelson** [comment]
Bump on this as it's nearing the top of Grooming ☝️ @sharms @jmcarp

**Comment by jbarnicle** [comment]
Restricted!
