### ISSUE TITLE
Raise channel notification when a pipeline is paused

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#490]
Currently it is possible when a system operator pauses a pipeline, for that pipeline to be paused indefinitely.  We need to notify the channel each morning of which pipelines are paused.

Acceptance Criteria:
- [ ] Each morning the channel receives notifications about which pipelines were paused

**Comment by jbarnicle** [comment]
This is currently blocked by this issue in Concourse. https://github.com/concourse/atc/issues/42
Essentially we need a way to authenticate to the Concourse API in a scriptable manner to run the necessary `fly` command(s) to generate these alerts.
