### ISSUE TITLE
Raise slack alert when pipelines do not match

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#492]
In order to ensure the environment is operating as specified, we need to compare the running Concourse configuration against the repo configuration.  Multiple times these have been identified as out of sync due to development work, context switches and other interruptions which have left these as variances.

Acceptance Criteria:
- [ ] Each morning the channel receives a slack notice if a running Concourse config differs from Git + Credentials

**Comment by jbarnicle** [comment]
Along with https://github.com/18F/cg-product/issues/490 this is blocked by not having the ability to authenticate to the concourse api in a script  https://github.com/concourse/atc/issues/42

**Comment by sharms** [comment]
FYI this occurred again today
![screen shot 2016-12-01 at 10 46 22 am](https://cloud.githubusercontent.com/assets/95657/20800446/903226a0-b7b3-11e6-89df-2a40d97de7bd.png)
