### ISSUE TITLE
Resolve failing jobs

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#493]
In order to reduce false positives, we should not receive bosh healthmonitor alerts for `ingestor_syslog` or `nats_to_syslog` unless they are down for an extended peroid.

We will need to validate the above statement, as these components may have legitimate issues?

**Comment by jmcarp** [comment]
This should be resolved in https://github.com/18F/cg-deploy-logsearch/pull/33.

**Comment by mogul** [comment]
@cnelson approves this message.
