### ISSUE TITLE
UAA Account creation flow missing password requirements

### ISSUE THREAD

**Issue by berndverst** [18F/cg-product#496]
Password based account creation is missing password requirements, in particular:

- Length of password
- Required characters
- Allowed characters

Some users are currently struggling to create valid passwords as the UI provides no feedback regarding the requirements.

**Comment by berndverst** [comment]
@cnelson might look into it this week

**Comment by berndverst** [comment]
Some user reports:

> So I tried to create a password but it was not long enough and now my invitation has been invalidated.

also:

> 1.       When I first visited the account creation page in IE11, the text in the “create account” button slightly overflowed the button itself.
> 
> 2.       I typed out my password in the first password field. As soon as I started typing, I got an error message saying “the passwords do not match”. It would be nice if this message were not displayed until I’d actually entered a password in both fields, and had actually made a mistake.
> 
> 3.       When I clicked “create account”, I got an error message saying that my password needed to be 20 characters or more. This was not apparent from the previous screen. I hit “back”, but I then got another error message: “Your invitation code has expired. Please request another.” Now I need to go back to the person who added my account, wait for them to check their email, etc. L

**Comment by mogul** [comment]
Note that we expect guidance to be appearing and can see that the code is included in the page, so this is more a matter of fixing a bug than adding something new.

**Comment by rogeruiz** [comment]
We're syncing upstream with UAA while fixing this, so 🐌 until conflicts and tests pass.

**Comment by rogeruiz** [comment]
This PR is for the updated UAA release.
https://github.com/18F/cg-cf-release/pull/30
