### ISSUE TITLE
Micropurchase: Offer SQS queues via aws-broker

### ISSUE THREAD

**Issue by dlapiduz** [18F/cg-product#5]
**Micropurchase link:** https://micropurchase.18f.gov/auctions/24
**Main repository to create Pull Request:** https://github.com/18f/aws-broker

## Description

Cloud.gov is a deployment and hosting platform for government digital services. Cloud.gov uses brokers to manage the lifecycle of services for its users. Cloud.gov invokes the AWS broker using the [CloudFoundry Service Broker API](http://docs.cloudfoundry.org/services/api.html#api-overview) to manage various AWS services for use by applications deployed to cloud.gov. This issue seeks to enable the AWS broker to also manage Amazon Simple Queue Service (SQS) service instances.

Implementation can be done with any AWS account; no access to existing 18F AWS infrastructure is needed to develop or demo it.

As a user of cloud.gov, I want a queue service in my application with as little hassle as possible, so I want to the ability to self-provision it without depending on the actions of others.

Cloud.gov should allow users to request and view the options available for an SQS service, create an SQS service instance for their Cloud Foundry space, and associate/disassociate the SQS service instance with one or more apps. When the Cloud Foundry service instance is deleted, the SQS service that was instantiated upon service creation and any credentials issued for bind operations should be deleted as well. No demonstration of operation inside cloud.gov should be needed… The behavior can be demonstrated via exercise of the AWS broker’s REST APIs.

**Comment by mogul** [comment]
Closing in favor of 18F/cg-ops/#19
