### ISSUE TITLE
As a cloud.gov admin, I would like an easy way to reverse-lookup domains

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#501]
The issue often comes up where we are given a URL (via a support request, or whatever), and need to determine the org, space, and app it's bound to. This is possible through the admin UI, but it's...sluggish. Would be nice to have a command line plugin to do something like

```
$ cf route-lookup someapp.apps.cloud.gov
Looking...
Found!

Org: someorg
Space: somespace
App: someapp

To target, run

  $ cf target -o someorg -s somespace

```

**Comment by afeld** [comment]
Started hacking on this this weekend: https://github.com/18F/cf-route-lookup

**Comment by afeld** [comment]
@jcscottiii Mind trying to install and use it?

**Comment by jcscottiii** [comment]
```
✗ cf lookup-route james-todo.app.cloud.gov
Bound to:
sandbox-gsa/jamesc.scott/todo-app
```
