### ISSUE TITLE
GovCloud SSLMate SSL certificates not trusted by Air Force

### ISSUE THREAD

**Issue by berndverst** [18F/cg-product#505]
Our certificates for cloud.gov in E/W (Amazon's CA), but also SSLMate in GovCloud are signed by root CAs not trusted by Air Force computers.

Most Air Force personnel won't have the ability to trust these certs and will receive certificate errors (in the best case).

We should consider using a more robust / trusted CA in GovCloud.

**Comment by afeld** [comment]
> root CAs not trusted by Air Force computers

From what I remember @konklone telling me, that is _all_ root CAs that aren't operated by DoD.

**Comment by konklone** [comment]
> We should consider using a more robust / trusted CA in GovCloud.

No, we shouldn't -- we use one of the most robust and security-friendly CAs in existence. The Air Force does vigorous trust store trimming based on their own internal conception of commonly used federal CAs, and they can make further trimming changes any time, and we can't keep up with those decisions they make. In general, we can't meet the lowest common denominator of trusted CAs across all federal environments.

There is an ongoing joint GSA-DoD project to create a new publicly trusted certificate authority (https://github.com/uspki), and the Air Force is participating in this process. I hope that this will result in an automation-friendly free civilian-side CA that might be able to replace our use of Let's Encrypt. 

However, it'll be at least a year or two until it's usable. In the meantime, we should use the CAs that meet our own requirements for security and agility. 

I am also pushing DoD to allow the use of Let's Encrypt specifically in the interim. But @berndverst, if you are on a thread with the Air Force about this issue, I'm happy to be looped in so I can emphasize the above as well.

**Comment by konklone** [comment]
Also, to note, @berndverst was referencing SSLMate, which uses Comodo certificates under the hood, not Let's Encrypt. But the issue is the same.
