### ISSUE TITLE
Search bar styling currently shows a small scrollbar

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#507]
In order to use cloud.gov search without minor distraction/confusion, the search bar shouldn't display a small scrollbar that isn't relevant to its function.

Right now this shows up for me (Chrome and Safari on OS X):

![screen shot 2016-11-15 at 10 57 31 am](https://cloud.githubusercontent.com/assets/391313/20321494/7d90d95a-ab2a-11e6-9eb0-9f8483fc3a63.png)

cc @thisisdano

**Comment by thisisdano** [comment]
Addressed by https://github.com/18F/cg-style/pull/190
