### ISSUE TITLE
Sidebar navigation styling should consistently indicate whether items are pages or parents of pages

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#508]
In order for readers to confidently and quickly navigate cloud.gov content to find the page they want to read, sidebar navigation item styling (for docs and overview) should clearly indicate what that item leads to. (In other words, is it a link to a page, or is it a parent of a set of pages?)

Here's an example of how this isn't quite clearly communicated right now:

<img width="335" alt="screen shot 2016-11-09 at 3 46 43 pm" src="https://cloud.githubusercontent.com/assets/391313/20323484/cd588b8e-ab31-11e6-9f0c-9ab6457d27d0.png">

"Troubleshooting" and "Operations" have the same styling, but "Troubleshooting" is a page and "Operations" is the parent of a set of pages. These two items would benefit from different styling indicating they're different (such as a chevron/arrow on "Operations").

And as @thisisdano said: "it'd also be nice if the arrows accurately reflected the open/closed state of the parent".

**Comment by suprenant** [comment]
Noting that we're planning to at least tackle some of this docs work here: https://github.com/18F/cg-dashboard/issues/796
