### ISSUE TITLE
Monitor network latency

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#509]
In order to decrease time for SRE's to diagnose system issues, we should measure latency and availability of servers.

**Acceptance Criteria:**
- [ ] For each server which reports in to monitoring, monitoring records a ping request each $INTERVAL
- [ ] For each server which reports in to monitoring, monitoring records a status of each ping request

**Rationale:**
Certain days we experience failed deploys with network related failures.  These unique individual issues can be 30+ separate points of inquiry without methods or data to effectively diagnose.

**Comment by cnelson** [comment]
I'm thinking a good approach here might be to have the VMs [ping hosts using collected](https://collectd.org/wiki/index.php/Plugin:Ping) rather than having the central monitoring host ping all machines.

If we do this, we'd need to define what machines they are pinging to monitor connectivity and latency.  Do they ping their bosh director?  A machine on the internet somewhere (8.8.8.8) ?

**Comment by sharms** [comment]
![screen shot 2016-11-28 at 3 25 15 pm](https://cloud.githubusercontent.com/assets/95657/20684653/f0dbe32e-b57e-11e6-825b-f4d26aa7215e.png)
![screen shot 2016-11-28 at 3 25 00 pm](https://cloud.githubusercontent.com/assets/95657/20684660/f6e829bc-b57e-11e6-8927-197ab24db3a2.png)

**Comment by sharms** [comment]
![screen shot 2016-11-30 at 12 31 50 pm](https://cloud.githubusercontent.com/assets/95657/20763669/08dd9456-b6f9-11e6-963b-2d8e290f5847.png)

Uncertainty impacts team again today

**Comment by sharms** [comment]
![screen shot 2016-11-30 at 2 09 04 pm](https://cloud.githubusercontent.com/assets/95657/20767009/a6bf989c-b706-11e6-97f1-5a5822e0627f.png)

**Comment by cnelson** [comment]
The above is totally unrelated to any networking issues, it was a smoke test setting regarding diego.

**Comment by sharms** [comment]
![screen shot 2016-12-01 at 10 41 38 am](https://cloud.githubusercontent.com/assets/95657/20800249/db389fae-b7b2-11e6-9c4f-eb8acdcec331.png)

**Comment by sharms** [comment]
During the above, Concourse bosh worker also showed as 'unresponsive'

**Comment by sharms** [comment]
Today we have 5 people troubleshooting an outage which is likely network related.  Diagnosis time was extended without data to inform staff
