### ISSUE TITLE
Remediate Dashboard DNS

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#511]
While reviewing infrastructure configuration, `dashboard.cloud.gov` has it's own IPV4 A record to the CF ELB.  This should already be covered by `*.cloud.gov`, which would also include IPV6.

Records can be reviewed: https://github.com/18F/dns/blob/deploy/terraform/cloud.gov.tf

**Acceptance Criteria:**
- [ ] DNS uses a common ELB
- [ ] If this is required, verify that GovCloud is configured to allow

**Comment by cnelson** [comment]
Looking at the DNS configuration `console.cloud.gov`, `invite.cloud.gov`, `login.cloud.gov`, and `logs.cloud.gov` all have individual records that point at the same ELB as the `*.cloud.gov` entry.  

Can we just drop all those records? If so see the PR ☝️
