### ISSUE TITLE
Research reducing compliance friction for frontend work

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#514]
In order for Navigator folks (dashboard/cg-style) to be able to deploy updates quickly and frequently without unnecessary frustration, Navigator and HighBar need to research whether there are compliant alternative ways to implement the requirements that are currently slowing down those deployments.

Implementation sketch:

- [x] Britta digs into the FedRAMP requirements, our SSP, and our Configuration Management plan to put together a quick doc that explains what exactly we're required to do and where those requirements come from (the things that are currently implemented with PR reviews and protected master branches).
- [x] Britta, Aaron, and Marco have a 30-45 min meeting to evaluate those compliance requirements against an ideal development process, and we write down our best ideas for reducing friction. This could be ideas for adjusting the SSP, the CM plan, the development process, etc.
- [ ] We evaluate these with our PMs and figure out the right next step!

Acceptance criteria:
- [ ] We're confident that we're making an informed tradeoff between security/compliance and  development requirements.

**Comment by suprenant** [comment]
Checked in with @brittag – she'll find time to take a look here.

**Comment by brittag** [comment]
Dug up requirements for discussion here: https://docs.google.com/document/d/1DKU0j4iQogIE6n9G15HxChNsV01PzFbaYXE43GsbhGI/edit# !

**Comment by brittag** [comment]
Put a short chat on the cloud.gov calendar for Friday.

**Comment by suprenant** [comment]
@adborden @msecret what do you think of any next steps here?

**Comment by msecret** [comment]
Closing this as there isn't really anything we can do at this point?

**Comment by suprenant** [comment]
OK – that's the resolution we came to? Closing this up, then

**Comment by suprenant** [comment]
(thanks @brittag for working through this one with us!)
