### ISSUE TITLE
Update SSP to reflect cloud.gov fallback IdP

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#515]
In order for our SSP and related compliance documents (such as our procedures) to reflect our system, we need to update them to reflect the new cloud.gov IdP authentication option.

**Services table**
- [ ] GSA SecureAuth - remove "could run"

**Diagrams**
- [ ] https://diagrams.fr.cloud.gov/10-1-network.html - add info about IdP to "Private Subnet - Core Tier A"
- [ ] https://diagrams.fr.cloud.gov/10-4.1-customer-data-flow.html - update SSO area, which is currently labeled as customer responsibility - add alternate path for authentication to an in-boundary box.

**SSP** (mainly in the "customer responsibility" sub-sections)

Sections 9 and 10:
- [ ] Mention IdP in "The Core Tier private subnets" paragraph in 10.1.1.2. 
- [ ] Look for other mentions of client UAA. Maybe update 10.3.1.2.

IA:
- [ ] IA-2 (1) - Update - Works the same way as AWS.
- [ ] IA-2 (11) - Update - Works the same way as AWS.
- [ ] IA-2 (12) - Update - We meet the requirement by offering the option to customers to use their own SSO (and heavily encourage that).
- [ ] IA-4 part a - Update - People need to invite people, and people have little to do unless they have a sandbox agency thing or get explicitly assigned responsibilities from others.
- [ ] IA-4 part c - Update - Assigned based on email address.
- [ ] IA-4 part e - **May need implementation work and documentation work** - requires us to disable identifiers after inactivity. **Could mark as planned.** See related AC-2 (3) item.
- [ ] IA-4 (4) - Update content to say that it's customer responsibility for tenants to manage the people in their org. (**Evaluate whether that approach meets requirements; may need to be operational requirement.**)
- [ ] IA-5 part a - Similar to IA-4 (4) customer responsibility.
- [ ] IA-5 part b and c - Update - Same as AWS but at least 20 characters. 
- [ ] IA-5 part d - Update - We can manually revoke authentication.
- [ ] IA-5 part e - Update - There's no default password (users set it upon creation). [May need to update based on https://github.com/18F/cg-uaa-extras/pull/36]
- [ ] IA-5 part f - Update - Passwords expire after 90 days; we prevent people from reusing the previous password. [May need to update based on https://github.com/18F/cg-uaa-extras/pull/36]
- [ ] IA-5 part h - Update - Everything is encrypted at rest in the database; we rely on UAA for password storage; may need to write more here about how UAA works (look at GSA ATO docs).
- [ ] IA-5 (1) - Update. (Currently it prevents password reuse for 1 generation, not configurable right now. Some of these requirements are weird. **May need further study** - [see Slack chat](https://gsa-tts.slack.com/archives/cloud-gov-highbar/p1481055175000115).)
- [ ] IA-5 (4) - Update - Point to appropriate part of IA-5.
- [ ] IA-5 (6) - Evaluate whether to update.
- [ ] IA-5 (11) - Update.
- [ ] IA-8 (1) - Update - Similar to IA-2 (12)
- [ ] IA-8 (2) - Update - We don't accept any third-party credentials. we make people create new cloud.gov accounts.
- [ ] IA-8 (3) - Update - Parameter update and content update similar to IA-8 (2).
- [ ] IA-8 (4) - Update.

AC:
- [ ] AC-2 (3) - **Similar to IA-4 part e, may require implementation and documentation work** - check whether password expiration after 90 days is sufficient implementation for this (as written here for AWS and cloud.gov).
- [ ] AC-2 (5) - Update - cloud.gov IdP users are covered by the 20 minute client UAA timeout.
- [ ] AC-2 (9) - Update - Refer to updated Rules of Behavior (see simple docs update at https://github.com/18F/cg-site/pull/593).
- [ ] AC-2 (10) - Update - Same as AC-2 (9).
- [ ] AC-7 - Update - Check with team for config. 5 attempts in 5 minutes; locked for 20 minutes. keeps locking you out for an additional 20 minutes. **This requires a simple technical update to update the configuration of this feature - filed at https://github.com/18F/cg-product/issues/521.**
- [ ] AC-10 - Update - Reflect existence of IdP. (This change would have to be made in UAA anyway.)

SI:
- [ ] SI-10 - Update - Handled the same way as dashboard.

**SSP Attachments**
- [ ] Update [CIS worksheet](https://docs.google.com/spreadsheets/d/1Yxt1mMZAdSyKt2OGY1qdkkfZhBiKV6ZuD7sZPKxikuQ/edit#gid=600210940)
- [ ] Update [Customer Responsibility Matrix](https://docs.google.com/spreadsheets/d/1Yxt1mMZAdSyKt2OGY1qdkkfZhBiKV6ZuD7sZPKxikuQ/edit#gid=2040237689)

**Procedures**
- [ ] AC - https://github.com/18F/compliance-docs/blob/master/AC-Policy.md - minor updates
- [ ] IA - https://github.com/18F/compliance-docs/blob/master/IA-Policy.md - minor updates

**Scans**
- [ ] Update https://github.com/18F/cg-product/blob/master/ConMonChecklist.md to scan idp.fr.cloud.gov stuff.

**Comment by brittag** [comment]
Emailed PMO to coordinate on next steps for the uncertain items (**IA-4 part e and AC-2 (3)** and **IA-4 (4)**).

**Comment by brittag** [comment]
- [ ] When we're ready to work on this, check on implementation of https://github.com/18F/cg-uaa-extras/pull/36 - if we have temporary passwords anywhere, we may need to update IA-5 part e and IA-5 (1) part f.

**Comment by brittag** [comment]
We have notes from discussion with PMO and Infrastructure about this.

**Comment by brittag** [comment]
https://github.com/18F/cg-product/issues/521 seems done now

**Comment by brittag** [comment]
Currently in suggest mode: [services table update](https://docs.google.com/document/d/1xZI6mTbJpXVG90rGL1LswgPf6YUN7FM2yBPhfPhRgw8/edit#) and [diagrams update](https://github.com/18F/cg-diagrams/pull/45).

**Comment by mogul** [comment]
Per discussion earlier today, we're going to hold off on incorporating info on our IdP until after the P-ATO for the platform generally has been achieved.

**Comment by brittag** [comment]
We should take another look at IA-5 (6) when we do this revision - it may also need an update.

**Comment by mogul** [comment]
Currently we're thinking we're not actually going to have to do this work, as we'd instead put the compliance burden on max.gov or login.gov, and not run our own IdP in-boundary.

**Comment by brittag** [comment]
[Revised draft of this info in this doc](https://docs.google.com/document/d/1muNtVEe2admWd6-3WAw7Qimh_ZJkS9RfabtDcRB61SE/edit).

**Comment by brittag** [comment]
This will be tracked with a new card.
