### ISSUE TITLE
Document Travis CI's requirement for passwords to be escaped

### ISSUE THREAD

**Issue by konklone** [18F/cg-product#517]
I generated a deployer service account as part of setting up continuous deployment. 

During deployment, the login process halts on `sh: 1: Syntax error: "(" unexpected`:
https://travis-ci.org/GSA/https/builds/177378823#L243

During deployments with a separate deployer service account, this did not occur, login worked normally. 

In the one that did not work, the unencrypted password had a left paren in it. (The encrypted version of the password did not.) In the one that did work, the unencrypted password had no parens.

**Comment by jmcarp** [comment]
I'm wondering if you're running into this: https://docs.travis-ci.com/user/encryption-keys#Note-on-escaping-certain-symbols. If you used `travis encrypt`, did you escape special characters in the password first?

**Comment by konklone** [comment]
I did not, so I will definitely try this. However, since I didn't come across this in 2 hours of trial and error and documentation scouring, if this solves it, it's something worth explicitly adding to the cloud.gov docs.

**Comment by mogul** [comment]
BASH's `printf` has a `%q` format string that will BASH-escape an arbitrary string, and apparently this is the only reliable way to do it. 

It's unclear to me why Travis would even allow this condition to persist. Is it that they _want_ you to be able to eval an arbitrary BASH string in place of the password? Maybe so you can dynamically retrieve a credential?

In any case we should probably document this in our docs. I'll make a PR.

**Comment by mogul** [comment]
Doh, @brittag beat me to it! Anyone have suggestions for a one-liner to do the work?

**Comment by brittag** [comment]
Filed local docs PR: https://github.com/18F/cg-site/pull/637

Filed upstream docs PR: https://github.com/travis-ci/docs-travis-ci-com/pull/878

Filed upstream "can you fix underlying thing" suggestion: https://github.com/travis-ci/travis-ci/issues/7035

**Comment by konklone** [comment]
I'm willing to call this fixed by the merging of https://github.com/18F/cg-site/pull/637 and filing the others upstream. Thanks for doing this!

**Comment by brittag** [comment]
Thanks @konklone! @jseppi, do you think these PRs would help prevent the situation you ran into? Should we also file an issue or PR on Travis to add a warning to their web UI, or write something specifically about that in our docs? (I don't think I've used the Travis web UI myself, so I'm less familiar with this bit.)

**Comment by jseppi** [comment]
Hi @brittag - yes, I definitely think these PRs are helpful. 

As a note to https://github.com/travis-ci/docs-travis-ci-com/pull/878: the leak that happened for me in Checklistomania actually took place not in the CloudFoundry deploy script (which I didn't even have hooked up), but in `/home/travis/build.sh: eval: line 57`.

I think it would be awesome if Travis's web UI gave a warning or something if it detected unescaped special characters when adding env vars (or better yet, prevented them totally, as you inquired about in https://github.com/travis-ci/travis-ci/issues/7035).

**Comment by brittag** [comment]
Ah that's a great idea - I added that as a comment on the upstream issue.
