### ISSUE TITLE
Remove all traces of Codecov from cg-style, cg-dashboard, and other repos

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#519]
In order for cloud.gov to minimize its use of redundant external services (and reduce our surface area for potential problems), we should cut off access/connection from Codecov to our cloud.gov repositories (including cg-style and cg-dashboard).

https://codecov.io/gh/18F + https://codecov.io/gh/18F/cg-dashboard - the only cloud.gov project in Codecov is the deprecated dashboard.

Since this affects our "services table" SSP attachment, it'd be great if this were done before November 29 (when we'll ship a finalized SSP to our JAB TRs). It's not a requirement for P-ATO though.

This would also help resolve these two earlier related issues about trimming redundant services: https://github.com/18F/cg-product/issues/301 https://github.com/18F/cg-product/issues/225

**Acceptance criteria**

- [x] Codecov has no access to (or mentions in) cloud.gov repositories
- [x] We've updated our [services table SSP attachment](https://docs.google.com/document/d/1xZI6mTbJpXVG90rGL1LswgPf6YUN7FM2yBPhfPhRgw8/edit#) to reflect updated use of Codecov (in other words, we've removed or updated those two lines). (Coordinate with #cloud-gov-highbar on this part so that @brittag and others know it's getting updated.)

**Comment by brittag** [comment]
Looks like we're still using Travis for https://github.com/18F/cg-compliance

**Comment by brittag** [comment]
Also for https://github.com/18F/cg-uaa-extras and https://github.com/18F/cg-uaa

**Comment by brittag** [comment]
[`cg-uaa uses travis because upstream CF uses travis`](https://gsa-tts.slack.com/archives/cloud-gov-highbar/p1479841556005917) - so those repositories may need to keep it.

**Comment by brittag** [comment]
Updated story to narrow it to Codecov, since we have a legitimate current use for Travis.

**Comment by brittag** [comment]
cc @msecret on updated scope

**Comment by afeld** [comment]
Note sure that we have another good alternative for Go code coverage...

/cc @jcscottiii

**Comment by jcscottiii** [comment]
@brittag are there any services we can use for code coverage? Coveralls?

**Comment by brittag** [comment]
We can keep using Codecov if we have a current purpose for it - right now I just have it in the Services table as "no longer using this". Looks like the Dashboard has stopped using it - but for example, we could keep it if we want to reactivate it for the Dashboard later.

**Comment by brittag** [comment]
https://codecov.io/gh/18F + https://codecov.io/gh/18F/cg-dashboard - the only cloud.gov project we were using it for was the deprecated dashboard.

**Comment by suprenant** [comment]
@brittag we don't think this used anywhere that would affect us directly, so I'm pulling the Navigator label, but please let us know if you have questions or need anything else from us here!

**Comment by brittag** [comment]
@suprenant I believe what we need here is for Navigator to remove the cg-dashboard codecov hook (https://github.com/18F/cg-dashboard/settings/hooks) - and ideally also the Travis integration (https://github.com/18F/cg-dashboard/settings/installations) since that's also no longer in use. Then somebody needs to figure out how to get rid of https://codecov.io/gh/18F/cg-dashboard - I can ask somebody else to do that though if Navigator isn't sure how.

**Comment by brittag** [comment]
Is the Federalist hook at https://github.com/18F/cg-style/settings/hooks something we need/want, or is it something we can remove to minimize attached services?

**Comment by msecret** [comment]
I got rid of the hooks and travis integration. I can't get rid of the dashboard on codecov, maybe @jcscottiii could as he worked on the project a LOOOONG time ago?

**Comment by msecret** [comment]
I also deleted the cg-style hooks for Federalist

**Comment by brittag** [comment]
Thank you! I asked in #admins-github.

**Comment by afeld** [comment]
✅  cg-dashboard removed from Codecov.

**Comment by brittag** [comment]
Thanks all! I removed Codecov from the services table. I'll close this up; we can keep discussing getting rid of Travis over here: https://github.com/18F/cg-product/issues/301
