### ISSUE TITLE
 Host with incorrectly configured metrics address raises alert

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#522]
In order to ensure all systems point to the same metrics deployment, we should consistently set the monitoring endpoint across deployments

Acceptance Criteria:
- [ ] All deployments have `properties.riemann.server` set
- [ ] All deployments have `properties.riemann.port` set
- [ ] Collectd uses the above properties
- [ ] Healthcheck scripts use the above properties, such as ElasticSearch

**Comment by cnelson** [comment]
I wrote a [quick script](https://gist.github.com/cnelson/c439e50ea1e1a8fbbd14e5d08b148519) to examine the riemann configuration in all our manifests and here's the results for GovCloud (we could probably make these the ACs for this story)

# GovCloud

## Tooling

### concourse-production.yml:

- [ ] is missing riemann.server: 'properties'
- [ ] is missing riemann.port: 'properties'
- [ ] is missing collectd.riemann_server: 'properties'


### concourse-staging.yml:

- [ ] is missing riemann.server: 'properties'
- [ ] is missing riemann.port: 'properties'
- [ ] is missing collectd.riemann_server: 'properties'


### monitoring-production.yml:

- [ ] has incorrect riemann.server: Host is: 0.monitoring.monitoring.monitoring-production.bosh.



## Staging

### admin-ui.yml:

- [ ] has incorrect riemann.server: Host is: 0.monitoring.monitoring.monitoring-staging.bosh.


### cf-staging.yml:

- [ ] has incorrect riemann.server: Host is: 0.monitoring.monitoring.monitoring-staging.bosh.


### cf-staging-diego.yml:

- [ ] is missing riemann.port: 'port'
- [ ] collectd settings do not match riemann settings: riemann.server: 0.monitoring.monitoring.monitoring-staging.toolingbosh; collectd.riemann_server: 0.monitoring.monitoring.monitoring-staging.bosh.


### kubernetes.yml:

- [ ] is missing riemann.port: 'port'


### shibboleth-staging.yml:

- [ ] is missing riemann.port: 'port'
- [ ] is missing collectd.riemann_server: 'collectd'


## Production

### cf-production.yml:

- [ ] has incorrect riemann.server: Host is: 0.monitoring.monitoring.monitoring-production.bosh.


### cf-production-diego.yml:

- [ ] is missing riemann.port: 'port'
- [ ] collectd settings do not match riemann settings: riemann.server: 0.monitoring.monitoring.monitoring-production.toolingbosh; collectd.riemann_server: 0.monitoring.monitoring.monitoring-production.bosh.


### kubernetes.yml:

- [ ] is missing riemann.port: 'port'


### shibboleth-production.yml:

- [ ] is missing riemann.port: 'port'
- [ ] is missing collectd.riemann_server: 'collectd'

**Comment by jmcarp** [comment]
Handled by updates to runtime config.
