### ISSUE TITLE
Move common releases to bosh runtime config

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#525]
Currently BOSH Errand VMs do not log to CloudTrail, which will cause monitoring to terminate those VMs.

**Acceptance Criteria:**
- [ ] Errand VMs diligently record logs
- [ ] Monitoring does not identify them as unknown

**Comment by jbarnicle** [comment]
This is fixed via runtime config.

**Comment by jmcarp** [comment]
Retitled to explain that this became the bosh runtime config work. Done!
