### ISSUE TITLE
Updating on-boarding to better limit the scope of AWS on-boarding

### ISSUE THREAD

**Issue by rogeruiz** [18F/cg-product#53]
On the subject of on-boarding, when I was ramping up I did my best to _skip the AWS related on-boarding tasks_ which spoke to gaining access to AWS console directly. With the addition of [Terraform](https://www.terraform.io/intro/) and [Concourse jump boxes](https://docs.cloud.gov/ops/troubleshooting-bosh/), *we don't actually need as much access to AWS as we did previously*.

> - [ ] Get familiar with AWS in general if you're not already (TODO: We need some pointers here)
> - [ ] Grant them access to the following (where applicable): AWS, New Relic, PagerDuty, StatusPage
> - [ ] Take them through AWS onboarding (if applicable)

## Acceptance criteria

The cloud.gov documentation must accurately reflect:

* [x] The level of access provided to the relevant parts of AWS
* [x] The procedures for accessing various AWS systems

**Comment by jbarnicle** [comment]
I think a link to a short background video / tutorial on Terraform would make sense as well.

**Comment by madhujoshi** [comment]
I would be happy to help with AWS ramp up.  I've AWS training / coaching background.

**Comment by afeld** [comment]
Worth noting that https://docs.cloud.gov/ops/aws-onboarding/ isn't accurate anymore, either.

/cc @jmcarp https://github.com/18F/cg-product/issues/280

**Comment by afeld** [comment]
> we don't actually need as much access to AWS as we did previously

Hmm...though we do give full admin access to _some_ people in Atlas (a.k.a. Cloud Operations). Does that segmentation need to be reflected in our documentation and/or the System Security Plan (SSP) somehow?

/cc @LinuxBozo @sharms @NoahKunin

**Comment by LinuxBozo** [comment]
@afeld That segmentation should already be there, as you nailed it, "Cloud Operations" vs "cloud.gov team", which is the larger set. There will always be folks that need elevated access to run the bootstrap terraform.

**Comment by afeld** [comment]
@linuxbozo It seems like there are three tiers, right? For example, I don't have a GovCloud account, sounds like @rogerruiz has a limited account, and you (as I remember) have full admin access. I would consider both of you to be Cloud Operations though.

**Comment by LinuxBozo** [comment]
@afeld @rogeruiz does not currently have an account.

But yes, there is another "readonly" tier, designated for GSA security, which includes folks like Randy Bator and @NoahKunin 

So, if you are saying that having no account is considered a third tier, then sure, there's a third tier. In the case of the SSP, there should only be two I would think.. Cloud Operations and GSA security.
