### ISSUE TITLE
Migrate deployments to runtime configurations

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#531]
In order to simplify configuration and ensure the same set of tools run on each deployment, all deployments should use runtime configuration and remove common-releases.

**Acceptance Criteria:**
- [ ] Awslogs are active on all deployments
- [ ] Tripwire is active on all deployments
- [ ] Nessus agent is active on all deployments
- [ ] Collectd agent is active on all deployments
- [ ] Tooling environment
- [ ] Production environment
- [ ] Staging environment

**Comment by jbarnicle** [comment]
This work is complete.
