### ISSUE TITLE
As a user with brokered RDS instances, I want to be able to create/use read replicas

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#533]
Applications with high data volumes like FEC API need to scale their databases horizontally. Therefore, we should look into providing a way to create read replicas for RDS databases created through [the broker](https://github.com/18f/aws-broker).

**Comment by jmcarp** [comment]
This sounds like a useful feature, but I'm not sure it belongs in our particular broker, which is basically on life support. I would prefer to add this to a broker that's in better shape and actively maintained. The only one I know of that meets those criteria is https://github.com/alphagov/paas-rds-broker.

**Comment by mogul** [comment]
Update: We're moving to that broker.

**Comment by mogul** [comment]
Not doing this any time soon.
