### ISSUE TITLE
As an RDS broker user, I want the ability to make my database accessible from outside of cloud.gov

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#535]
FEC needs their RDS instance to be accessible from the FEC itself, so we should find a way to (in order of preference):

* Make the database instance accessible from external IP address range(s)
* Make the database publicly accessible

Possible that https://github.com/18F/cf-service-proxy can be leveraged here, at least in the short term.

/cc @LindsayYoung

**Comment by jmcarp** [comment]
Can FEC use port forwarding over ssh to address this?

**Comment by afeld** [comment]
@LindsayYoung Is the GoldenGate connection continuous, or in bursts?

**Comment by LindsayYoung** [comment]
It seems like there are always connections and it creates more connections when there is a lot of data coming over. Would you like to to look into it and give you a solid answer?

**Comment by afeld** [comment]
Ah, we should try this! https://docs.cloudfoundry.org/devguide/deploy-apps/ssh-services.html

**Comment by afeld** [comment]
My main question is whether SSH tunneling makes sense for long-lived connections, and whether the overhead of going through the application instance would be a problem.

**Comment by mogul** [comment]
Not going to support this.
