### ISSUE TITLE
Liberator team should have access to some concourse pipelines but not all

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-product#54]
The liberator team should have access to the concourse pipelines that deploy console.cloud.gov (once it exists) and other liberator services, but not to all cloud.gov pipelines. One proposed solution is to spin up a separate concourse instance that deploys liberator services.

@dlapiduz @jcscottiii @msecret

**Comment by afeld** [comment]
Bummer that Concourse doesn't offer [finer-grained access control](https://github.com/concourse/concourse/issues/194).

**Comment by msecret** [comment]
Are there any downsides to having our own concourse? Or is the main downside the time it would take to set that up?

**Comment by afeld** [comment]
Just having the overhead of maintaining multiple, yeah. @s-matyukevich is this something the [BOSH broker](https://github.com/s-matyukevich/bosh-broker) could be useful for?

**Comment by rogeruiz** [comment]
@msecret aside from spinning up a new Concourse, there is the additional overhead of learning how to use Concourse. http://concourse.ci/flight-school.html

**Comment by afeld** [comment]
We decided to punt on this as part of https://github.com/18F/cg-atlas/issues/41. Closing for now.
