### ISSUE TITLE
Close POAM V25-CM-6: Content-Type Header Missing

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#540]
In order to demonstrate that our system has an acceptable level of risk, we need to close this identified potential risk as resolved or invalid.

This is happening specifically for a few URLs on community.fr.cloud.gov.

**Acceptance Criteria**:
- [x] We have OWASP ZAP scans that show this is fixed.

**More Information**
- See [POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784) for details.
- [NIST Special Publication 800-53 (Rev. 4) CM-6](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=CM-6)

**Comment by cnelson** [comment]
I think @jmcarp fixed this specifically for community in https://github.com/18F/cg-product/issues/471, but https://github.com/18F/cg-secureproxy-boshrelease/issues/6 fixes this for all sites behind secureproxy (which includes community).

**Comment by brittag** [comment]
Fixed in scans now. Putting in "Awaiting Acceptance" until we update this in the POAM.

**Comment by brittag** [comment]
Hm, I see a "Content-Type Header Missing" finding in the report from 12/8 at https://drive.google.com/drive/u/0/folders/0B58iDAWKmw_BOS1UOGxPcHQ3VFU - not sure if I'm reading this wrong or if this needs further work (or a re-scan).

**Comment by cnelson** [comment]
We had to disable this secure proxy fix: https://github.com/18F/cg-secureproxy-boshrelease/pull/6 as it was causing problems with the CF acceptance tests. We'll figure out what's wrong with it, and get it back in as soon as I'm back on my feet

**Comment by cnelson** [comment]
Have not gotten to investigating the secureproxy issue yet. Staging is still catching up to the latest stemcells and CF release. If all goes well I'll be working on this tomorrow

**Comment by cnelson** [comment]
@brittag There is a new report in the 12/18 folder that shows this has been remediated.  

Note:  The site's canonical URL is now community.cloud.gov (served via CloudFront), this report will show it scanned that URL and community.app.cloud.gov (which still technically exists as it's the origin URL for CloudFront)

**Comment by brittag** [comment]
YAY I am so excited, thanks! No problem with the URL changes (our compliance reviewers don't seem to mind when those things shift around).

**Comment by brittag** [comment]
I just moved this to the "closed" tab of our ConMon POAM, so I'm considering this accepted and closed. :)
