### ISSUE TITLE
Migrate customers off of *.fr.cloud.gov domain (0.5)

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#541]
What we're after: No customer apps have routes on fr.cloud.gov, and no customer spaces have access to use that domain.

Benefits/why:
* Increase separation between customer and platform namespace
* Avoid confusion for users visiting sites they expect are affiliated with cloud.gov

---
## Notes

fr.cloud.gov - domain reserved for platform components and administrative apps
app.cloud.gov - domain for tenant apps

When we first opened GovCloud, we allowed tenants to use .fr.cloud.gov. We need to go back and change the domain for these tenant apps to a different domain (not just a different subdomain) to reduce the (unlikely) risk of malicious use and reserve this domain for official cloud.gov systems.

**Comment by suprenant** [comment]
[@jcscottiii - James Scott] can you tell is if this is still relevant? Fureigh and I are not too sure at the moment.

**Comment by brittag** [comment]
I know we have customers on this now, such as https://crime-data-explorer.fr.cloud.gov/ - if that helps

**Comment by brittag** [comment]
Thinking about this more, I'm concerned about the user experience cost of disrupting current users who are using `fr.cloud.gov` for their apps.

**Comment by fureigh** [comment]
I share [@brittag - Britta Gustafson]'s concern. Setting up subdomain redirects should suffice, though... is there anything those wouldn't cover?

**Comment by fureigh** [comment]
Here's the current list of routes that include `.fr.cloud.gov`:

```http://18fcg-style.fr.cloud.gov
http://account.fr.cloud.gov
http://acquisitions-staging.fr.cloud.gov
http://acquisitions.fr.cloud.gov
http://adamb-dummy-app.fr.cloud.gov
http://adborden-nodejs.fr.cloud.gov
http://adborden-redirect.fr.cloud.gov
http://analytics-reporter-swirliest-pedi... analytics-reporter-swirliest-p...
http://analytics.fr.cloud.gov
http://atf-eregs.fr.cloud.gov
http://aws-broker.fr.cloud.gov
http://c2-dev.fr.cloud.gov
http://c2-prod.fr.cloud.gov
http://cap.fr.cloud.gov
http://cdn-broker.fr.cloud.gov
http://cdn-cron.fr.cloud.gov
http://cg-style.fr.cloud.gov
http://chandika.fr.cloud.gov
http://community-new.fr.cloud.gov
http://community.fr.cloud.gov
http://compliance.fr.cloud.gov
http://console-redirect.fr.cloud.gov
http://console.fr.cloud.gov
http://crime-data-api-master.fr.cloud.gov
http://crime-data-api-staging.fr.cloud.gov
http://crime-data-api-two.fr.cloud.gov
http://crime-data-api-upload.fr.cloud.gov
http://crime-data-api-user-testing-fbi-h... crime-data-api-user-testing-fb...   
http://crime-data-api.fr.cloud.gov
http://crime-data-api2.fr.cloud.gov
http://crime-data-explorer-master.fr.cloud.gov
http://crime-data-explorer-staging.fr.cloud.gov
http://crime-data-explorer.fr.cloud.gov
http://crime-data-prototypes.fr.cloud.gov
http://crime-data-upload.fr.cloud.gov
http://crm.fr.cloud.gov
http://customer-data.fr.cloud.gov
http://customers.fr.cloud.gov
http://d.fr.cloud.gov
http://dashboard-master.fr.cloud.gov
http://dashboard-staging.fr.cloud.gov
http://dashboard.fr.cloud.gov
http://datn-app.fr.cloud.gov
http://deployer-account-broker.fr.cloud.... 
http://diagrams.fr.cloud.gov
http://discovery-dev.fr.cloud.gov
http://discovery-prod-zebraic-enamoredne... 
http://docs-services.fr.cloud.gov
http://docs.fr.cloud.gov
http://doesthiswork.fr.cloud.gov
http://eqip-prototype-api-dev.fr.cloud.g... 
http://eqip-prototype-api-staging.fr.clo... 
http://eqip-prototype-api.fr.cloud.gov
http://eqip-prototype-dev.fr.cloud.gov
http://eqip-prototype-staging.fr.cloud.g... 
http://eqip-prototype.fr.cloud.gov
http://eregs-ssp.fr.cloud.gov
http://estest.fr.cloud.gov
http://fec-dev-web.fr.cloud.gov
http://fec-feature-web.fr.cloud.gov
http://federalist-adborden.fr.cloud.gov
http://federalist-build.fr.cloud.gov
http://federalist-builder-staging.fr.clo... 
http://federalist-builder.fr.cloud.gov
http://federalist-docker-build.fr.cloud.... 
http://federalist-preview-staging.fr.clo... 
http://federalist-registry-staging.fr.cl... 
http://federalist-registry.fr.cloud.gov
http://federalist-staging-new.fr.cloud.g... 
http://federalist-staging.fr.cloud.gov
http://federalist.fr.cloud.gov
http://fedramp-develop.fr.cloud.gov
http://flask-example.fr.cloud.gov
http://foo.fr.cloud.gov
http://foo2.fr.cloud.gov
http://foozz.fr.cloud.gov
http://forest-service-prototype.fr.cloud... 
http://fs-intake-staging.fr.cloud.gov
http://fugacious.fr.cloud.gov
http://glide-test.fr.cloud.gov
http://go-test.fr.cloud.gov
http://green.fr.cloud.gov
http://headers-test.fr.cloud.gov
http://hello-go.fr.cloud.gov
http://hello-js.fr.cloud.gov
http://hello.fr.cloud.gov
http://helloworld.fr.cloud.gov
http://hhs-acf-uc-dashboard.fr.cloud.gov
http://hhs-uc-api.fr.cloud.gov
http://invite.fr.cloud.gov
http://jamesconsole.fr.cloud.gov
http://jmhooper-get-set-carnivallike-pun... 
http://jmhooper-get-set-client.fr.cloud.... 
http://jmhooper-get-set.fr.cloud.gov
http://jmhooper-show-env.fr.cloud.gov
http://jonathan-hooper-deploys-a-docker-... 
http://kubernetes-broker.fr.cloud.gov
http://landing-a.fr.cloud.gov
http://landing-b.fr.cloud.gov
http://landing.fr.cloud.gov
http://logs.fr.cloud.gov
http://mandrill-fwd.fr.cloud.gov
http://micropurchase-staging.fr.cloud.go... 
http://my-app.fr.cloud.gov
http://notifications.fr.cloud.gov
http://olddocsredir.fr.cloud.gov
http://python-sentinel.fr.cloud.gov
http://review-app.fr.cloud.gov
http://review-test.fr.cloud.gov
http://s3-broker.fr.cloud.gov
http://s3-service-broker.fr.cloud.gov
http://s3-smoke-tests.fr.cloud.gov
http://smoke-tests-medium-mysql.fr.cloud... 
http://smoke-tests-medium-psql.fr.cloud.... 
http://smoke-tests-micro-mysql.fr.cloud.... 
http://smoke-tests-micro-psql.fr.cloud.g... 
http://smoke-tests-shared-mysql.fr.cloud... 
http://smoke-tests-shared-psql.fr.cloud.... 
http://snipeit-test.fr.cloud.gov
http://standup-slack-bot.fr.cloud.gov
http://styleguide.fr.cloud.gov
http://task-hello.fr.cloud.gov
http://test-discovery-prod.fr.cloud.gov
http://test-test-post.fr.cloud.gov
http://testing-ga.fr.cloud.gov
http://ttslicenses.fr.cloud.gov
http://wstest.fr.cloud.gov
http://www.fr.cloud.gov```

Next step is to determine which are 'system administrative apps' and which are tenant apps.

**Comment by fureigh** [comment]
@afeld, are you the/an authority on which of these apps are 'system administrative'?

**Comment by fureigh** [comment]
(for visibility: https://admin.fr.cloud.gov --> Routes is the place to find this list.)

**Comment by afeld** [comment]
I could make some guesses...? The safest way is probably to look at what org each is in - all of the "system administrative" ones should be in one or two specific orgs.

**Comment by fureigh** [comment]
Got it. Thanks, @afeld!

**Comment by brittag** [comment]
[@fureigh – Rhys Fureigh] Re redirects, my concern is that there may be a bunch of tenants who have built things that depend on the `fr.cloud.gov` URLs, so they'll have to do a variety of kinds of manual work to deal with redirects, and their things might break in unexpected ways. It's probably tolerable if they get advance notice and some hand-holding through the process, but that sounds like a lot of work from both us and tenants if not necessary.

**Comment by fureigh** [comment]
@afeld Sincere question: what's the value of doing this? (Requesting context because "why are we doing this?" has been asked elsewhere and though I can make an educated guess, I'd rather go to the source.)

**Comment by fureigh** [comment]
(Anybody else have Gin Blossoms stuck in their head now? Just me? Okay.)

**Comment by fureigh** [comment]
[Added comments in the GitHub issue but they didn't come back to Favro. If you're reading this on GitHub, please ignore.]

**Comment by fureigh** [comment]
In case we're still moving forward with this, I posted a list of org names I believe would be associated with 'system administrative' apps. They're in a new tab in the linked Google Doc. @afeld, please take a look when you get a chance. If someone else should be the person to sign off instead, say the word.

**Comment by brittag** [comment]
[@fureigh – Rhys Fureigh] Can you move the spreadsheet to the cloud.gov team folder? Right now it only gives me view access, not edit/comment access. I think probably a current Cloud Ops member would be able to review this (since Aidan hasn't been on the team for a long time now), but also for example I know `gsa-cto` is a customer org instead of a team org.

**Comment by fureigh** [comment]
[@brittag - Britta Gustafson] Moved! I put it in the Customer team folder; if you encounter access issues, let me know.

**Comment by afeld** [comment]
> what's the value of doing this?

This is the best explanation I found with a quick Google:

https://security.stackexchange.com/a/12419

The short version: you don't want to share cookies between trusted sites and untrusted sites/content. I haven't investigated, but depending on how the cookies are configured for cloud.gov, sites deployed to `*.fr.cloud.gov` might be able to steal users' sessions.

/cc @commit-dkp 

> If someone else should be the person to sign off instead, say the word.

Definitely isn't me! The distinction I see is whether the app is "owned" by the cloud.gov team or not.

**Comment by commit-dkp** [comment]
The link @afeld shared has it right.

The value is that, because browsers do not consistently scope HTTP cookies to the host, it isn't possible to trust the browser to isolate the cookies of administrative apps hosted in fr.cloud.gov from any tenant apps that are hosted in fr.cloud.gov.  Problem is migrating tenants to apps.cloud.gov doesn't solve this problem, as an app hosted at example.apps.cloud.gov that sets a cookie with Domain=cloud.gov will have it scoped to *.cloud.gov and it will still be sent in requests to example.fr.cloud.gov.

**Comment by fureigh** [comment]
Got it. Thanks for the context, @afeld!

**Comment by fureigh** [comment]
@commit-dkp Considering that migrating tenants to apps.cloud.gov won't solve the problem, is there an alternate approach you recommend?

(Moving all tenant apps to somethingelse-cloud.gov would do the trick but would be a significant (and disruptive) undertaking.)

**Comment by fureigh** [comment]
This ticket was intended to fix a security hole. Specifically, having both trusted and untrusted sites on *.fr.cloud.gov leaves the door open for session theft. (Thanks for the context, @afeld.)

However, as @commit-dkp points out, cookies are scoped to the second-level domain (cloud.gov). So moving tenant apps from *.fr.cloud.gov to *.apps.cloud.gov won't actually fix this problem.

Before that was made clear, we speculated about customer value in this Slack thread: https://gsa-tts.slack.com/archives/C4XLJ1JBV/p1500398261422582

As of 7/18, there were 49 active mappings (actually mapped to an app, vs. 128 total routes with the *.fr.cloud.gov domain) that used the fr.cloud.gov domain. This includes our system apps. (Source: @jcscottiii)

The next step is to figure out how best to guard against session theft, considering the circumstances. I can think of at least one other PaaS site that puts tenant apps on a different second-level domain... presumably this is why.

**Comment by fureigh** [comment]
[@suprenant - Andrew Suprenant] I propose we close this ticket in favor of a new one more clearly scoped around preventing session theft.

**Comment by suprenant** [comment]
[@fureigh – Rhys Fureigh] sounds good, thanks for the detail here. Can you please write a draft of the new ticket?

**Comment by fureigh** [comment]
Here's the new, more clearly security-framed ticket: https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-6876

It's possible that we still want to do this ticket, but the other reasons don't seem to be strongly felt. I propose this ticket go back into the icebox or backlog for determining whether it's necessary for consistency, maintainability or some other reason.

**Comment by suprenant** [comment]
[@fureigh – Rhys Fureigh] very good! I'll put this in the icebox and follow up on assessing the priority for the new ticket you wrote.

**Comment by fureigh** [comment]
(Noting that this Favro card is not publicly visible. Considering the security-related content, that's a good thing at the moment.)

**Comment by fureigh** [comment]
Further context: https://docs.google.com/document/d/18cIg6xLSsrOnfne_2xJbVeUu5t8NMEpgQf69_HcsKzU/edit#

**Comment by suprenant** [comment]
Google Doc tracking these apps - we basically need to contact the folks that are highlighted in red: https://docs.google.com/spreadsheets/d/19hGek_emd5nlqEC9TQbY4SFbZZdBCkmlOzHI2z4rfM0/edit

**Comment by mogul** [comment]
Moving task list here that doesn't belong up in the original post (which should just be about the problem to be solved and desired outcome).

## Tasks

* [ ] Verify whether we have options besides moving everyone to a new second-level domain (e.g., thisisthesecondlevel.gov, not x.cloud.gov).
* [ ] If, as @commit-dkp has said, we don't: pick a new domain name and proceed with the remaining steps outlined here.
* [ ] Reserve said domain name.
* [ ] Audit tenant apps that are using `*.fr.cloud.gov`.
* [ ] Audit any processes and URLs that will need to be updated to reference the new domain.
* [ ] Figure out a communications and support plan for getting those apps moved to the new domain. (This won't affect the URL people use for logging in, though, will it?)
* [ ] Change the domain of any said apps.
* [ ] Update documentation to reference the new domain instead of `*.fr.cloud.gov` wherever needed

**Comment by mogul** [comment]
We anticipate that making stuff in sandbox spaces evaporate after 30 days will take care of most of this. Then we can contact those that remain.
