### ISSUE TITLE
Deliver ConMon report for December 30

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#542]
In order for us to update the JAB on our compliance in a consistent way, we need to deliver a Continuous Monitoring report on December 30. We should run the scans on approximately the same day of each month (adjusted for weekends and federal holidays). For context, see our [Continuous Monitoring Strategy](https://cloud.gov/docs/ops/continuous-monitoring/), including [the monthly reporting summary explanation](https://cloud.gov/docs/ops/continuous-monitoring/#monthly-reporting-summary).

Our usual due date is the 2nd of each month, but January 2nd is a holiday, so December 30 is a good target this time.

**Acceptance criteria**

* [@brittag] By COB on December 30, we've done the following:
	-  [x] Uploaded our POA&M to [this folder](https://community.max.gov/pages/viewpage.action?pageId=1034682621)
	-  [x] Uploaded our web scans to [this folder](https://community.max.gov/display/FedRAMPExternal/GSA+18F+Cloud.gov+Web+Scans)
	-  [x] Uploaded our OS scans to [this folder](https://community.max.gov/pages/viewpage.action?pageId=1034682662)
	-  [x] Uploaded our database (RDS) scans to [this folder](https://community.max.gov/pages/viewpage.action?pageId=1034682662)
	-  [x] Emailed our PMO to let them know that's done

**Implementation sketch**

As soon as possible:

- [x] We've scheduled a short Highbar squad meeting for approximately December 21.

Starting approximately at that meeting:

- [x] We had a short Highbar squad meeting to go over the checklist, assign sub-tasks, and adjust the checklist as necessary. When possible, assign a pair of people for each scanning task so that more of us learn how to grab these.

* [@cnelson] On approximately the 23rd of the month, we ran OWASP ZAP on the following domains (using [steps #1-6 of these manual scanning instructions](https://pages.18f.gov/before-you-ship/security/dynamic-scanning/#manual-scanning), authenticated, passive):
	- [x] https://ci.fr.cloud.gov/ - requires Cloud Ops auth
	- [x] https://community.fr.cloud.gov/	
	- [x] https://dashboard.fr.cloud.gov/
	- [x] https://account.fr.cloud.gov/
	- [x] https://landing.app.cloud.gov/
	- [x] https://login.fr.cloud.gov/
	- [x] https://logs.fr.cloud.gov/
	- [x] https://metrics.fr.cloud.gov/ - requires Cloud Ops auth
        - [x] We exported and uploaded those fresh OWASP ZAP results in XML format to [a folder in this folder](https://drive.google.com/drive/u/0/folders/0B5fn0WMJaYDnaFdCak5WNWRGb1U) (you can upload one XML file with results from all the sites, or upload a series of separate XML files with results per site).
        - [x] We also grabbed the OWASP ZAP "context" export with settings info and uploaded it to that folder.
        - [x] We also grabbed the OWASP ZAP scans in human-readable HTML format and uploaded them to that folder.

- [x] [@cnelson] On approximately the 23rd of the month, we grabbed a fresh set of Nessus scans (both OS and database/RDS) from https://nessus.fr.cloud.gov/ in .nessus format and uploaded the fresh results to [a folder in this folder](https://drive.google.com/drive/u/0/folders/0B5fn0WMJaYDnaFdCak5WNWRGb1U) - requires Cloud Ops auth.
	- [x] We also grabbed the [Nessus HTML export](https://docs.tenable.com/nessus/6_8/Content/Exported_Results.htm) for those scans and uploaded them to that folder.

- [x]  [@brittag] If appropriate, email Veris to ask if they have verification adequate to close any of the POAM items.

* [@brittag] We updated [our Google Drive ConMon POA&M right here](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784):
	- [x] We updated all columns to include the most recent info about remediations, milestones, statuses, etc., including updating the status date column.
	- [x] We corrected any items that our process indicated were incorrect last time.
	- [x] We moved any web scanner items that should be moved to closed (items originally found by a scanner where we have new scans that prove these things are fixed).
	- [x] We moved any OS and database scanner items that should be moved to closed (items originally found by a scanner where we have new scans that prove these things are fixed).
	- [x] We listed any new identified web vulnerabilities. (Discard the ones listed as false positives in the SAR, table E-2.)
	- [x] We listed any new identified OS and database vulnerabilities.
	- [x] We did a final check to make sure all columns include recent and accurate info.

- [x]  [@brittag] Update [POAM issues list](https://github.com/18F/cg-product/labels/POAM) with current info, to help us keep track of everything.

- [x]  [@brittag] We opened a PR to update our [ConMon checklist template](https://github.com/18F/cg-product/blob/master/ConMonChecklist.md) with any changes from this month.

**Comment by cnelson** [comment]
Can we use the recent POAM remediation scans for this deliverable or do we need to run again closer to 12/30?  If the latter when?

**Comment by brittag** [comment]
I'm not 100% sure, but I think they like to see scans within a week or so of the due date. I'll ask about this at Monday's check-in call.

**Comment by cnelson** [comment]
I heard that meeting got cancelled today so I'm guessing we don't know?  I'll just plan to run all these scans on the 27th or 28th.  Can you elaborate on what "upload one XML file instead of separate files" means?  

Should we be building one context that scans all of our sites, rather than each one individually?

**Comment by brittag** [comment]
Hmm good point, I didn't follow up on that first question, sorry. Will email to try to figure that out today.

For "upload one XML file instead of separate files", Diego was thinking it's easier for us to provide one big OWASP ZAP scan XML file with all the info from the various sites in it, rather than providing 8 smaller XML files with results from each site. I don't have a preference for this, and I haven't heard any preferences about this from our compliance reviewers.

**Comment by brittag** [comment]
I've updated the POAM, uploaded all the files, emailed our PMO, and filed a checklist template update (https://github.com/18F/cg-product/pull/598). Hooray! Thanks @cnelson for helping with this!
