### ISSUE TITLE
Develop and schedule public information training for cloud.gov team

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#546]
In order for our cloud.gov team to confidently post a wide variety of open source materials publicly (including documentation, pull requests, issues, diagrams, and so on) while making informed decisions about security risk (and complying with all necessary policies), our cloud.gov team should have internal training on this topic.

This will help us comply with [our AC-22 requirements](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=AC-22), especially part b ("Trains authorized individuals to ensure that publicly accessible information does not contain nonpublic information") and part c ("Reviews the proposed content of information prior to posting onto the publicly accessible information system to ensure that nonpublic information is not included").

We already get training from GSA OLU ("IT Security Awareness and Privacy") about PII and CUI, but we need to make sure our team understands our open source policy as well.

We should run this by the end of PI8, which ends approximately 1/11/17. This will help us address POAM item SAR V4-AC-22 (ConMon V8-AC-22).

*This is a draft - requires discussion with @mogul before moving forward, since it affects the whole team.*

**Implementation sketch**

* Decide on frequency - probably same frequency as IR training requirement (within 60 days of joining the team + annual after that) - and list in onboarding checklist.
* Make an outline of key topics to cover, including:
   * [18F open source policy](https://github.com/18F/open-source-policy/blob/master/policy.md), including its [sensitive info guidance](https://github.com/18F/open-source-policy/blob/master/practice.md#protecting-sensitive-information)
   * Definition of controlled unclassified information (CUI)
   * [18F GitHub rules](https://handbook.18f.gov/github/#rules)
   * [18F sensitive information rules](https://handbook.18f.gov/sensitive-information/)
   * [cloud.gov sharing secret keys policy](https://cloud.gov/docs/ops/secrets/#sharing-secret-keys)
   * [cg-postmortems guidelines](https://github.com/18F/cg-postmortems#protecting-sensitive-information)
   * Practical edge cases to discuss, including IP addresses, info about CVEs, scan results, and info that belongs to GSA IT or AWS rather than to us
   * [Incident reporting process](https://cloud.gov/docs/ops/security-ir/)
* Make a template for notes.
* Schedule meeting.

**Acceptance criteria**

- [x] We have a notes template for this training
- [x] We have an outline for this training
- [x] We have an onboarding checklist item for this training
- [x] We've scheduled a time for this training
- [ ] We've done this training once
- [ ] We've sent evidence of training plan (such as an outline) and evidence of completed training (such as notes) to 3PAO
- [ ] We've scheduled a recurring time for this training
- [ ] POAM is updated
- [ ] AC-22 in SSP is updated

**Comment by mogul** [comment]
That looks like a pretty good draft!  I'm not sure what else we could add. (We should discuss how to put this on a calendar with other required trainings... All at the same time, at opposite months, etc.)

**Comment by brittag** [comment]
[Notes template here](https://docs.google.com/document/d/162U09paLbCCNLDbkqpK7AmDoDawMxhvtFe9jAp1VHwM/edit#)

[Started working on slides here!](https://docs.google.com/presentation/d/1uB4MlGCu8ZYUxjKVZKwicQ95MvLxaT4Mh93y6w79GPw/edit)

**Comment by brittag** [comment]
Done with [my rough cut of the public information training slides](https://docs.google.com/presentation/d/1uB4MlGCu8ZYUxjKVZKwicQ95MvLxaT4Mh93y6w79GPw/edit) - probably next step is a quick check from Infrastructure.

**Comment by brittag** [comment]
Checked slides with Infrastructure and got a 👍 .

[Filed onboarding checklist PR](https://github.com/18F/cg-product/pull/593) (and related links added in earlier PR at https://github.com/18F/cg-product/pull/556).

**Comment by brittag** [comment]
We scheduled this for January 9; [notes doc here](https://docs.google.com/document/d/1VBFhlx5J-ZVZUq7Of9Wk3RSzBIxsLm-tqPMgwUqQtA0/edit).

**Comment by brittag** [comment]
We scheduled a second one for January 13 ([notes doc](https://docs.google.com/document/d/1UmPau0asVP2GYpxQrvcRBqtAt_AYkT00zbpbTP3rANA/edit)) to cover a few team members who couldn't attend the first.

**Comment by brittag** [comment]
We completed this requirement, and we have a [training tracker](https://docs.google.com/spreadsheets/d/1hqU6cNeEB293OT0j3OvbdAFRkrf2zDOrPVxGfnr4sSw/edit#gid=0) that will help us maintain our compliance on this! Yay!
