### ISSUE TITLE
Resolve Database Compliance Checks issue (close POAM ID V3-CM-6)

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#548]
In order for us to fulfill our compliance requirements, we need to resolve items listed in scans.

This item is listed as V3-CM-6 in our [ConMon POAM](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784), as well as in our [SAR table 4-1](https://docs.google.com/spreadsheets/d/1AzI5_-pU3Cx8J0IAWFCPF6ia8y05aRkgwdMMtTGyQUM/edit#gid=1276791949).

We have an [old Google Doc about this with outdated info](https://docs.google.com/document/d/1T83PVuS52Q3dUZvA8JeHh4sdc8Ovh6NeDxBq9kzsHZc/edit) - linking it here in case it ends up having something useful in it.

This is due 3/1/2017.

Since this task involves a list of a bunch of scan findings, we should track progress on them somehow - probably comments in the Deviation Request form doc in Google Drive.

We should use our [submitted V3-CM-6 Deviation Request Form](https://docs.google.com/document/d/1z0OUoNet92_OSEtM7E3cK_BtRp0X9-j_RF2FQixg_ig/edit) to guide implementation since it has a list of items we should remediate and items we're requesting operational requirement for.

Added acceptance criteria as task lists in Favro.

**Comment by brittag** [comment]
Diego emailed 3PAO about this.

**Comment by brittag** [comment]
We have an updated plan for this item in this Google Doc: https://docs.google.com/document/d/1T83PVuS52Q3dUZvA8JeHh4sdc8Ovh6NeDxBq9kzsHZc/edit

**Comment by brittag** [comment]
Updated issue with revised plan for completing this POAM item.

**Comment by brittag** [comment]
Updated this story again to reflect my current understanding of how to complete this item.

**Comment by brittag** [comment]
Roger and Lenny are going to investigate the Nessus configuration items and see if they can fix them or if we should update this to make them requirements as well. Then Britta can work on polishing the writing if necessary.

**Comment by brittag** [comment]
The items marked able to correct needs a bit more configuration in Nessus, which Roger will work on.

After we correct these items, we should add info to the POAM spreadsheet to explain that we corrected the items (we don't correct the Deviation Request Form yet).

**Comment by rememberlenny** [comment]
Working on this

**Comment by brittag** [comment]
We can move this to Done after any/all followup tasks are captured on the Highbar & Atlas boards.

**Comment by brittag** [comment]
We have a new card at https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-3551 with the remaining tasks.
