### ISSUE TITLE
Warn users about IA-2 (1) idp.cloud.gov concerns

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#550]
In order to ensure users understand the state of idp.cloud.gov relative to our P-ATO, and that using it entails some ATO risk, the account provisioning and login process associated with idp.cloud.gov should clarify how the account might affect ATO of their systems.

**Acceptance Criteria**

- [ ] A user is unable to provision an idp.cloud.gov account without seeing notice to the effect that "idp.cloud.gov accounts are not included in the cloud.gov FedRAMP P-ATO boundary and may not be suitable for your organization or project. Check with your Authorizing Official or CISO to determine if this is a concern, or [setup single-sign-on with your agency](https://cloud.gov/docs/ops/federated-identity/)!"
- [ ] A user is unable to authenticate via an idp.cloud.gov account without seeing a similar notice.

**Comment by brittag** [comment]
Suggest we make a user-facing docs page that explains identity providers, which can say "we recommend setting up federated identity, here's how to do that - or you can use the fallback IdP which has limitations, check with your AO, etc etc". We can link that from https://cloud.gov/overview/overview/who-can-use-cloudgov/ + https://cloud.gov/docs/getting-started/accounts/ + https://cloud.gov/docs/apps/managing-teammates/ + in the auth flow.

**Comment by NoahKunin** [comment]
My only comment is the judicious use of the word "yet". 

Example: "idp.cloud.gov accounts are not *yet* included..." and so on.

**Comment by LinuxBozo** [comment]
This should also be explained in the [invite email in cg-uaa-extras](https://github.com/18F/cg-uaa-extras/blob/staging/uaaextras/templates/email/body.html) so users can make an informed decision on whether to accept.

**Comment by mogul** [comment]
Is that even possible? Does the mail template have enough context to know what IDP they'll have to use?

**Comment by LinuxBozo** [comment]
So, there's the rub. Technically, you can invite even other SAML enabled users, and when UAA sees the email address, and can match it to a SAML email domain (see: https://docs.cloudfoundry.org/api/uaa/#saml search for `config.emailDomain`) it automatically forwards them on to the SAML provider when users accept the invite. 

In an ideal world, invites would only be sent to our own IdP users, and other SAML users would just be told "Hey, go login with your special button".

Having said that, we could update things to iterate through the SAML provider list, doing some `emailDomain` matching ourselves, and present a different email template to various users.

**Comment by brittag** [comment]
This is outdated.
