### ISSUE TITLE
Remove @jbarnicle from cloud.gov team

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#552]
In order to complete @jbarnicle's exit from the cloud.gov team, the assignee should complete a prescribed set of tasks that will remove any special access.

# Directions:
**Assignee:** If you can’t complete any of the items on your checklist personally, _you are responsible for ensuring that an appropriate person does it_.

### For people leaving the team
- [x] Remove them from the project in Float
- [x] Remove them from [GitHub teams that start with cloud-gov](https://github.com/orgs/18F/teams?utf8=%E2%9C%93&query=cloud-gov)
- [x] Remove them from [the cloud.gov team Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov)
- [x] Remove them from [the cloud.gov support Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov-support)
- [x] Remove them from [the cloud.gov inquiries Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov-inquiries)
- [x] Remove them from the @cloud-gov-team in the Slack Team Directory
- [x] Remove them from any IAM roles they hold in AWS E/W and GovCloud
- [x] Remove them from [the list of people working on the project](https://docs.google.com/spreadsheets/d/1mW3tphZ98ExmMxLHPogSpTq8DzYr5Oh8_SHnOTvjRWM/edit#gid=0)
- [x] Remove them from DigitalGov Search access for cg-site
- [x] Remove them as invitees for any meetings on the cloud.gov calendar
- [x] Remove any special Org or Space roles that their cloud.gov account holds
- [x] [Remove their access as an admin](https://docs.cloud.gov/ops/managing-users/#managing-admins) on the platform
- [x] Remove their access to StatusPage
- [ ] ~~Remove their access to PagerDuty~~
- [x] Remove their access to New Relic
- [x] Remove their access to [Aha!](https://18f.aha.io)
- [x] Remove their membership in cloud.gov-specific Trello boards (eg the business-tracker)
- [ ] Ensure any keys they had direct access to are rotated

### For anyone leaving 18F
- [x] Ensure the [18F Handbook exit process](https://handbook.18f.gov/leaving-18f/#offboarding-process) has been kicked off via the 18F talent team

**Comment by cnelson** [comment]
Did not find any accounts for John in E/W or GovCloud AWS IAM

**Comment by brittag** [comment]
We also have a team list at https://github.com/18F/cg-product/blob/master/DeliveryProcess.md#squads to update.

**Comment by cnelson** [comment]
[@mogul confirmed no access to DigitalGov Search](https://gsa-tts.slack.com/archives/cloud-gov-navigator/p1481137241000243)

**Comment by cnelson** [comment]
@mogul removed access to `cloud-gov*` github teams

**Comment by cnelson** [comment]
Confirmed no access to StatusPage existed

**Comment by cnelson** [comment]
Confirmed no access to NewRelic existed

**Comment by cnelson** [comment]
[#admins-trello removed access to trello](https://gsa-tts.slack.com/archives/admins-trello/p1481213255000011)

**Comment by cnelson** [comment]
@mogul removed access to Aha, and cloud-gov* Google Groups

**Comment by mogul** [comment]
- PagerDuty is pending confirmation as the account is suspended pending acquisitions insanity right now.
- Keys will be rotated tomorrow; Chris was ill today.

**Comment by mogul** [comment]
Key rotation slowly making progress, but takes focus.

**Comment by rogeruiz** [comment]
@cnelson Should be done with East COB today, and there are some scripts coming out of it.

**Comment by cnelson** [comment]
It is currently not possible to rotate the certificates in consul without a brief (< 5 minutes) amount of downtime.  Will discuss next week how/when to rotate prod.

**Comment by cnelson** [comment]
I'll be done with rotating east today, and will not here when it's done.  As we discovered some pretty interesting failure modes in rotating the CF credentials, I think we might want to take a more measured approach to doing it in GovCloud.  As I'm out for the next week and this has been open forever WDYT about closing this, and opening a separate issue specifically about rotating creds in GovCloud which I'll tackle as soon as I return?

**Comment by cnelson** [comment]
Not attempting to rotate west credentials until we can do it once for all the offboarding we need to do.  Currently it doesn't look like we can start that until 1/20 (per jez he needs AWS access until then)

**Comment by mogul** [comment]
Everything's done as of today except for the key rotation, which is being [tracked elsewhere](https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-3296) so we're going to move this card and unclog the board.
