### ISSUE TITLE
Improve Atlas/AgentQ Onboarding experience

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#557]
In order to bring new people on the Cloud Operations team up to speed quickly, we want to reorganize the onboarding checklist/materials and identify gaps that need to be filled.

**Acceptance Criteria**

Processes and procedures
  - [x] A day-to-day task list can be found and is relatively complete
  - [ ] Documentation on "processes" (eg support practices with ZenDesk, Slack, ConMon) can be found and is relatively complete
  - [x] The "required for all team members" reading list includes [how to protect sensitive information](https://github.com/18F/open-source-policy/blob/master/practice.md#protecting-sensitive-information)
  - [x] The list of necessary credentials is comprehensive

Project/team/squad/theme organization
  - [ ] Squad membership and theme definition+artifacts can easily be discerned 
  - [x] The onboarding/offboarding checklist is organized by squad not theme

System architecture and components
  - [x] The reading list forms a logical progression
  - [x] The reading list consists of modern entry points (eg Cloud Foundry training materials)
  - [x] The reading list includes SSP sections 9-10
  - [x] The reading list includes a rundown of systems/tools that are lower-level than the SSP (to include k8s, secrets mgmt, etc)
  - [x] Docs represent current state of affairs; any remaining desired/future state info is consolidated into one obvious "for future" place

Things that don't exist
  - [x] We have a laundry-list of docs that have no existing raw material but should exist

Meta
  - [ ] We have a strategy for minimizing delays on the first day (eg organize both boardee and buddy lists by "T-X" or "T+Y" days)
  - [ ] We have a strategy for keeping the onboarding checklist current
  - [ ] We have a strategy for keeping offboarding checklist in sync
  - [ ] We summarize all of these changes in a sprint review

**Implementation sketch**

- Update onboarding checklist with findings/revisions
- Break out parts of onboarding checklist (reading list, access list)
- Create list of missing docs for making into further issues

**Comment by mogul** [comment]
Be sure to consult with @brittag when you think there's not existing stuff for a given topic... It may be in `cg-site`, `compliance-docs`, or some other places that she's aware of. She'll also have a sense when moving something might be a problem (eg docs that the SSP points to as evidence).

**Comment by datn** [comment]
Working on the implementation sketch, which will include all docs that I think need to exist compared to the list of docs I can actually find.

**Comment by datn** [comment]
I migrated some of my changes into this branch: https://github.com/18F/cg-product/tree/improve_onboarding 

More to come --

**Comment by mogul** [comment]
@datn this one came up at standup today... How's it going?

**Comment by rogeruiz** [comment]
Moving back to Ready until @datn returns.

**Comment by datn** [comment]
Here's the PR -- again, more to come in here: https://github.com/18F/cg-product/pull/599

**Comment by datn** [comment]
Partial list of docs I think are missing:

* Kubernetes overview/quickstart
* Riemann overview/quickstart
* Support process with Zendesk & Slack
* "How to use monitoring" unified overview explaining the difference between and use of pagerduty, statuspage, grafana, loggregator, nessus, etc. (with links to existing docs as needed)  
* Secrets management ([this](https://cloud.gov/docs/ops/secrets/) is somewhat out of date and will hopefully be way out of date with the completion of https://github.com/18F/cg-atlas/issues/95), including canonical scripts new recruits can use to manage secrets as needed (until the new system is in place).
* UAAC overview/quickstart (weaving together [this](https://cloud.gov/docs/ops/deploying-the-admin-ui/) (which needs updating) and [this](https://github.com/cloudfoundry/cf-uaac) in context/with examples of how we use it all, including endpoints).

**Comment by rogeruiz** [comment]
@datn We should have these be issues in 18F/cg-product so we can track them individually. Also, I think some of these were added in the last few weeks as well.

**Comment by datn** [comment]
@rogeruiz Gotcha. I placed them here so that once I was done coming up with the list, @brittag could review them (at @mogul 's request). Whatever is still missing can then be decanted into individual issues or whatever the team wishes.

**Comment by datn** [comment]
I've updated the PR, ACs and the list of docs I think are needed, and I've added @brittag as an assignee to help determine the current and future state of documents (see my comment w/list above). I'm moving to the infrastructure team as of Monday 1/9 but will endeavor to help move this task forward if I can.

**Comment by brittag** [comment]
@datn Cool! Would you be up for a quick chat next week (like, 15 min videochat) to help me understand your thinking in your PR and anything else I should know to help me review this and integrate what you learned? (Any advice on structuring docs in ways that are helpful for Atlas/AgentQ onboarding?) Feel free to put something on my calendar. :)

**Comment by mogul** [comment]
Quick rundown on what we will follow up on now:
* Kubernetes overview/quickstart
* Riemann and monitoring overview/quickstart

The rest of [the things Dan identified above](https://github.com/18F/cg-product/issues/557#issuecomment-270232900) we'll tackle as they come up in the course of onboarding new people.

**Comment by mogul** [comment]
Moving to `Awaiting Acceptance` until @brittag is done with the PR.

**Comment by mogul** [comment]
@mogul will write two stories based on the list above.

**Comment by mogul** [comment]
[@Britta Gustafson] you might want to have a look at the [feedback from the migration onboarding](https://docs.google.com/document/d/1Z2oXZyQcw_B9BWWqi0TmtPUApK6TzsxkCASizuPgwDw/edit#bookmark=id.e38xucomdy35)... It sounds like consolidating the reading list all into one place might be a very positive thing.

**Comment by brittag** [comment]
Unassigning myself from this one since I don't see a way to fit it into my near-term work very well, and I think this is a thing that somebody else on the team would be able to do! (Unlike some of the BU responsibilities which are specific to the BU.)

**Comment by commit-dkp** [comment]
A suggested addition for the meta: "We have a strategy for minimizing delays on buddy assignment and reach-out".  Not everyone who needs to be on-boarded will have figuring out who their buddy is as their highest priority, so we need to be proactive in kicking that off.  Perhaps assign the issue to the buddy first, who then as a part of the on-boarding process also assigns it to the on-boarder.

A suggestion for meta-meta: Each of the current tasks independently improves the on-boarding experience, and yet more improvements may be identified in the future, so break out each of the tasks into its own issue.
