### ISSUE TITLE
Switch to golang s3 broker

### ISSUE THREAD

**Issue by jmcarp** [18F/cg-product#560]
We're currently using a fork of https://github.com/cloudfoundry-community/s3-cf-service-broker to broker s3 access. Since upstream is apparently abandoned and our fork isn't well known, work we do on the broker doesn't have much benefit for the community. The current broker also doesn't conform to the current service broker spec and has a known bug around creating service keys that @berndverst has already run into.

I propose using https://github.com/cloudfoundry-community/s3-broker instead. This project doesn't have much activity (it's just the original developer and me at this point), but I've been able to get patches merged reasonably quickly. This broker uses `brokerapi`, so it complies with the service broker spec and can create service keys. It's also written in go, which I'm guessing our team is more familiar with (and probably enjoys more) than java. I just submitted a few small patches to bring the go broker to parity with our current broker--once those are ready, I think we should switch brokers.

**Comment by jmcarp** [comment]
Made a few updates to https://github.com/cloudfoundry-community/s3-broker, deploying from https://github.com/18F/cg-deploy-s3-broker. All that's left is to make sure we have parity with the java s3 broker and add docs.

**Comment by rogeruiz** [comment]
Migrated with @cnelson and @jmcarp yesterday
