### ISSUE TITLE
Enable app creation via web UI (0.25)

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#563]
What we're after: It's possible to manage an application in cloud.gov using only the web UI (eg push from a .zip file or git URL)

Benefits/why:

- Many agencies have locked down client machines on which they're unable to use the CF CLI, which is currently a prerequisite for use.
- Ensures parity between capabilities of web UI and CLI 
- Improves new user experience by keeping them in the web UI while learning

Potential metrics:

- How far can new user can get through our "your first deployment" guidance without us referencing/requiring them to install the CLI?

Comps:
https://gsa.invisionapp.com/d/main/#/console/8652272/226367368/preview

UX example of a click-to-install-Drupal flow from pantheon.io: https://drive.google.com/open?id=0BxwPU7YHpzDKaGRkWFZZWjFoajg

We would gain this ability easily by adopting the [Stratos UI](https://github.com/SUSE/stratos-ui).

**Comment by suprenant** [comment]
Some users have never used GIT, don't know/don't have access to command line. 

Have discussed pre-canned apps here (e.g. Drupal). Show sample apps, spin up Drupal.

Can check other competitors (Pivotal Web Services, Bluemix, AppFog). 

Dan Williams did some design work for this. 

Would be helpful to know where customers are currently coming from (if not command line, where?) (per James Hupp)

More on metrics:
 - Can you spin up any app at all?
 - Can you spin up your app in the dashboard?
 - Is there a point in the UI where a user logs in and doesn't know what to do?

**Comment by rememberlenny** [comment]
Notes from [@msecret - Marco Segreto] - https://docs.google.com/document/d/1qNwNH4XTJzAnLPdSuaKXhNsLgd_fzK5spG9d3k_cf30/edit#heading=h.tqfsgzosb8rm

**Comment by brittag** [comment]
From sizing meeting: the work for this would overlap a lot with [Click-to-deploy canned application example](https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-7691).

**Comment by mogul** [comment]
Planning to get this by switching to Stratos
