### ISSUE TITLE
One-click app deploys

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#564]
**What we're after:** Enable launching commonly requested applications on cloud.gov from a specially-crafted link, including required services. Viewing a space presents a list of commonly-requested applications that can be launched this way.

**Benefits/why:**

- Make it easy for anyone to try out cloud.gov quickly with a real application example
- Enable rapid provisioning of commonly requested SaaS for non-technical clients using best-practices for Cloud Foundry deployment (non-volatile config and storage, etc.)
- Open another market segment for potential impact-/cost-recovery-multiplier (eg people who want Wordpress, Drupal, Wekan or other common open source SaaS)

**Notes:**

- This is expected to be very similar to  [Deploy to Heroku](https://devcenter.heroku.com/articles/heroku-button)... The link should be clickable anywhere, not just within cloud.gov.

**Comment by jmcarp** [comment]
Prototype at https://github.com/jmcarp/deploy-to-cf. It's less bad than it was last demo.
