### ISSUE TITLE
Ensure riemann alerts from production are emailed if PD is unavailable

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#567]
I have not seen any production riemann alerts emailed to cg-support in the last week, but staging alerts are arriving.  Ensure production is properly notifying cg-support of alerts when PD cannot be reached.

**Acceptance Criteria:**
- [ ] Receive email alert from GovCloud production
- [ ] Receive email alert from East production

**Comment by sharms** [comment]
Also need to backport logic to East

**Comment by sharms** [comment]
This was a configuration issue outside of Riemann - we have switched to cloud-gov-notifications and notifications are coming through

**Comment by cnelson** [comment]
How will we know when Google starts blocking these alerts to the new list?

**Comment by mogul** [comment]
I effectively switched the spam message processing off:
![image](https://cloud.githubusercontent.com/assets/47762/21363472/95a1f000-c6a1-11e6-9210-1d37d80ccca3.png)

Let's see if that's a problem in practice (eg actual spam coming through) given that this address is not advertised.
