### ISSUE TITLE
Allow CDN broker to forward all headers

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#571]
In order to allow applications to work as expected, the original headers need to be sent or otherwise login pages etc may be cached instead of working. 

**Acceptance Criteria:**
- [ ] Method of setting headers to be forwarded when using CDN broker
- [ ] Instructions are on docs.cloud.gov

**Comment by afeld** [comment]
Issue moved to [18F/cf-cdn-service-broker #46](https://github.com/18F/cf-cdn-service-broker/issues/46) via [**ZenHub**](https://www.zenhub.com/)
