### ISSUE TITLE
As an RDS broker user, I want to access stats around my database

### ISSUE THREAD

**Issue by afeld** [18F/cg-product#578]
We determined in https://github.com/18F/cg-migration/issues/23 that it's not possible to sufficiently scope the user in the AWS console. Instead, we want to try giving them the appropriate permissions for retrieving stats about their database(s) from the AWS API/CLI. This can happen one of a few ways:

* Narrowly-scoped
    * Access credentials specific to that service instance
* Widely-scoped, giving access to all RDS instances (or AWS services) that they have access to
    * Single sign-on
    * Access credentials

The good news is that we aren't locked into one or the other, so we can do whichever is easiest to start. Another consideration is if we want to build this into the service broker, or make it more of a meta thing that pulls information from one or more service brokers.

## Acceptance criteria

* [ ] As a user, I am able to view stats around my (non-shared) RDS database

/cc https://github.com/18F/cg-agent-q/issues/10

**Comment by mogul** [comment]
This is the current direction /cc @jmcarp

**Comment by mogul** [comment]
Not doing this any time soon.
