### ISSUE TITLE
Research options for logging Concourse authorization and user event logging

### ISSUE THREAD

**Issue by sushiandbeer** [18F/cg-product#58]
As an SRE, I'd like to be able to restrict access to portions/aspects of Concourse and also determine who did what (basically the last two As in AAA: authorization and accounting)

**Comment by afeld** [comment]
Related issues: https://github.com/18F/cg-product/issues/54 https://github.com/18F/cg-atlas/issues/41 https://github.com/18F/cg-atlas/issues/12
