### ISSUE TITLE
Production-worthy Redis and Elasticsearch plans (8.1)

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#581]
What we're after: Reduce customer-facing outages due to brokered service stability to as close to zero as possible

Benefits/why:

- Increase team confidence in the platform
- Increase reliability of services being delivered to the public
- High-availability without surprise team work

Metrics:

- Are our customer-facing outage events under X time?
- Are our customer-facing outage events less than Y duration for the quarter?
- How many customer-facing outages happen outside business hours?
- How many services include at least one high-availability plan?
- How many services help users pick plans matching their uptime goals for dev, stage, prod, etc. or dissuade use?
- How easily can a customer understand the impact of our service record?
- How confident are we confident in ability to handle outages?
---
Things to consider during PI planning:
* DB upgrades and other compliance-forced activities
* BOSH/CF/Diego/Loggregator dependencies missing
* Managed service stability

Notes from discussion:
 - Customers lose trust when we have service disruptions
 - Bigger customers want more reliability 
 - Want fewer disruptions for team so they’re happier and more productive

**Comment by brittag** [comment]
Would be good to consider doing something like this as well: https://github.com/18F/identity-private/wiki/Production-%7C-Service-Level-Objectives

**Comment by brittag** [comment]
BU perspective:
- High availability Elasticsearch and Redis will remove important blockers to success for current and prospective customers (including ourselves with the dashboard).
- May help with getting new customers.
- Lowers long-term technical/support labor and risk of off-hours pain.

What success looks like for BU:
- This should include some marketing/promotion for the high availability versions, potentially including quotes from current users like Ed, to help us capture potential new interest from customers. Blog post equivalent effort (not too long, but a little more promotion than just an updates post for existing users).
