### ISSUE TITLE
Sort out outage-handling processes

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#582]
In order to for operations to communicate effectively with customers while handling unplanned service interruptions, we want a clear, documented process for interruption handling that fits operational needs while being explicit about responsibility for comms.

**Acceptance Criteria**

- There's an operations-facing doc on cloud.gov about the process
- The process clearly forks to the incident-response and contingency-planning procedures at appropriate points
- The process includes how to handle interruption issues (eg labeling, class of service, assignment)
- The process includes how to identify, document, assign, and delegate the need for comms
- The process has been reviewed with the operations team and fits into their process
- We take steps to ensure people know this exists and use it at the right time
- There's a pointer to templates and guidance for comms

Context: See https://github.com/18F/cg-product/issues/573 for an example where we fell down due to this story not existing.

**Comment by brittag** [comment]
We can adapt https://cloud.gov/docs/ops/making-announcements/ for some of this.

**Comment by mogul** [comment]
@brittag I added the last bullet point above to cover the fact that we have no templates for StatusPage.
