### ISSUE TITLE
Actively notify customers when restage is needed (7)

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#587]
What we're after: Teams are actively notified when new vulnerabilities appear in their app due to outdated buildpacks or obsolete language versions

Benefits/why: 

- Reduce the time between vulnerabilities being identified and remediated
- Support continuous compliance practices

Notes/context: 
 - We want to let users know if a buildpack is no longer supported, needs a fix, etc.
 - What is best way to send message to people in a space? (email/notifications)
 - This is currently happening in the release notes, but users then have to read the notes, parse them, and determine if they're affected by given components of those notes
 - So, there's a possible benefit of notifying folks when their app, specifically, is affected
 - We can currently see what buildpacks are being used but not necessarily the versions

**Comment by nikzei** [comment]
I'd need to know a little bit more about this before setting Skyporter acceptance criteria. That said, I'm not sure that I see this as a PI9 story. I'm blacklogging this on.

**Comment by mogul** [comment]
This one's not a story, but a feature, and it's already been moved out to PI10.

**Comment by suprenant** [comment]
For now, the key here is that we want to inform users.

Really, we just want to tell people they are empowered to make a change and that a buildpack needs to be updated (and why that update needs to happen)

Could be Mailchimp, chron job, anything to get this done.

Would like to do this whenever we update buildbacks. If we don't want to do this too frequently, could pick a scheme (e.g. do this on Mondays)

Could we restage on their behalf? (always possibility that app doesn't come backup) – probably leave this out for now, but people know exactly what they're signing up for. Down the road, we could update apps/take them down for users.

**Comment by brittag** [comment]
BU perspective:

Success looks like:
- Customers are successful at securing their apps.
- Customers are not surprised by not being able to push outdated buildpack versions.

**Comment by mogul** [comment]
Long since done.
