### ISSUE TITLE
Improve auditing and retention capabilities for S3 bucket access (3)

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#588]
What we're after: S3 buckets can be configured to dump access logs to the same/another S3 bucket

Benefits/why:

- Enables easier compliance with NIST controls when using S3 in an application

See also the [discussion about Federalist in the cloud-gov-support channel](https://gsa-tts.slack.com/archives/cloud-gov-support/p1480654555005268); talk to Will Slack for more info.

**Comment by cnelson** [comment]
@mogul Noting for the record that Federalist and FDIC have both asked for this feature this week.
