### ISSUE TITLE
Reduce effort to get customers using cloud.gov effectively (21)

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#589]
What we're after: There's a set of training materials to help people understand how to use cloud.gov effectively and it's been tested at least once

Benefits/why:
- Help non-expert teams become productive with cloud.gov without undue team overhead
- Prepare for regularly-scheduled outreach or paid training engagements

Notes (types of users):
 - People that use cloud.gov but want to better understand it/evangelize/spread in their agencies
 - People that are curious about cloud.gov but not confident in their ability to use it without outsourcing the details

**Comment by suprenant** [comment]
Want to do at least one internal and one external training. Doesn't have to be perfect (e.g. EPA, DigitalGov). Could measure with our support metrics. 

Drupal/Wordpress examples could fall under this. More modular (smaller) could be good. Could include tips in release notes. 

"Here's what you need to know about CF, here's cloud, here's app development in general" (?) General app development/architecture (lots of folks in gov't haven't been exposed to this)

Two CF courses we could adapt (could look at this during PI planning)
 - General CF
 - Architecture

Could be quarterly, eventually.

**Comment by mogul** [comment]
See [notes from our discussion with #infrastructure](
https://docs.google.com/document/d/1yEluXPpguOv-hKe_Q7gRYlmoi2omwl2Odwquwy8C_Qw/edit#heading=h.cb5fmz3n64uu)
this morning... Holly would be a good person to reach out to.

**Comment by suprenant** [comment]
Noting from Britta: Bernadette Adams (formerly in Learn, now in CPS) knows a lot about education and training and may be a resource when working on training materials

**Comment by suprenant** [comment]
We're currently planning the workshop and will use those learnings to inform future work here.

**Comment by brittag** [comment]
[Consider integrating what we've learned from support needs (specifically people coming to us with support questions that revealed much deeper architectural questions) to shape this feature](https://docs.google.com/document/d/1bDGJ9Nhm9PF0ROCAM2EjSjVUJ3ZrOOCTY77n1pMlxeM/edit#)

**Comment by mogul** [comment]
Superseded by [this new card](due to GitHub integration weirdness)
