### ISSUE TITLE
Generate a diagram-as-code for an org

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#591]
What we're after: Customers can auto-generate a diagram-as-code map of their org, spaces, routes, services, and route-services, including boilerplate like space and org roles, and network ingress/egress

Benefits/why:

- Make it easy to create system documentation and keep it up-to-date
- Reduce the effort necessary to document a deployment sufficiently for ATO purposes 

Notes:
 - The expectation here is that we'd automate something similar to what we did for  [https://github.com/18F/cg-diagrams](https://github.com/18F/cg-diagrams) for cloud.gov customers.
 - We're not sure about adoption here. Something simpler could meet needs here

**Comment by hollyallen** [comment]
Example of a system digram it would have been nice to have auto-generated: https://docs.google.com/drawings/d/1nwclBJQfbuzsnGOqe88VukQl3uiH1Jfa4c0FT1Cq43I/edit

**Comment by afeld** [comment]
https://www.terraform.io/docs/commands/graph.html

**Comment by mogul** [comment]
See [the FEC system architecture diagram](https://github.com/18F/FEC/wiki/2.-FEC-system-diagram) for an example
