### ISSUE TITLE
[IP Sprint SPIKE] CI/CD as a brokered service

### ISSUE THREAD

**Issue by LinuxBozo** [18F/cg-product#592]
As a member of the cloud.gov team, I would like to investigate brokering Concourse as a service so that I understand both the Cloud Foundry service broker API, and and I understand what it’d take to provide and support a CI/CD service suitable for use by customers.

Implementation:
 - [x] Concourse running in production VPC for isolation
 - [x] Concourse is running on it's own network CIDR so it is scalable
 - [x] Broker is able to communicate with Concourse to setup teams that authenticate against UAA, using spaces as scope of access

**Comment by LinuxBozo** [comment]
Broker code: https://github.com/18F/concourse-broker/

**Comment by LinuxBozo** [comment]
Some thoughts:
 - Using Concourse was fairly easy once you work around how authentication works to be able to create the teams, since we could tie authentication to CF spaces
 - Since this is not a bindable service, the team is created based on the Org name. The authentication however is bound to the space within which the service instance is created. So all users who need access to Concourse need to have space permissions (Developer, Auditor, etc). This also means that for instance, if someone where to create a instance for a sandbox org, only they would have permissions by default, and no other user could create their own instance for their own sandbox space, since the team name is now already taken.
 - We have to really trust our user base currently: http://concourse.ci/teams.html#section_teams-caveats
 - Because of the preceding two points, access will more than likely have to be tightly controlled rather than just open to everyone, which means, manually adding service access to orgs.

**Comment by LinuxBozo** [comment]
Pivotal is experimenting with this in their PCF offering as well: https://docs.pivotal.io/p-concourse/release-notes.html

**Comment by rogeruiz** [comment]
- Go to the concourse URL
- Create an org
- Create a space
- Make sure you have some sort of space permission
- Create the service, and it creates a team based on your Org name.
- 💥

**Comment by mogul** [comment]
Adam said:
> Since this is not a bindable service, the team is created based on the Org name. The authentication however is bound to the space within which the service instance is created. [...] This also means that for instance, if someone where to create a instance for a sandbox org, only they would have permissions by default, and no other user could create their own instance for their own sandbox space, since the team name is now already taken.

Why is the team name based on solely Org name? I'm assuming the space name is available at provisioning time, or else we wouldn't know which org+space to tie the team's authentication to. Couldn't the team be named after the org+space too? 

Actually it looks like [Pivotal is doing something similar](https://docs.pivotal.io/p-concourse/instances.html#fly): 
> The format of the team name is: `org name` + `space name` + `service instance name` + `4 digit #`.

Adam said:
> So all users who need access to Concourse need to have space permissions (Developer, Auditor, etc). 

My understanding is that there is no role-based access once within the Concourse team; if you can login, you can fly pipelines. If that's right, can we please limit this to just SpaceDevelopers? I'm fairly certain that we wouldn't want someone with read-only access to the space (SpaceAuditor) to have read-write access to Concourse (eg be able to fly new pipelines)!

Adam said:
> Because of the preceding two points, access will more than likely have to be tightly controlled rather than just open to everyone, which means, manually adding service access to orgs.

Understood. I don't think we're ready to go any wider in any case. Were you able to limit specific teams to specific worker pools as you'd hoped?

Roger said:
> Go to the concourse URL

What URL did this end up being?

**Comment by LinuxBozo** [comment]
1. Team based on Org name:  This was more about just getting something working without cluttering up the UI, so the shortest identifier is org
2. Actually, I was incorrect. It is already SpaceDeveloper only: https://github.com/concourse/atc/blob/master/auth/uaa/space_verifier.go#L92
3. We didn't get to individual worker pools per team in this sprint. Just getting an instance up that is ready for the broker, and development of the broker itself with some unit and acceptance testing.
4. concoure-ci.ENV.cloud.gov

**Comment by LinuxBozo** [comment]
Closing, as we've done the MVP demo, and initial testing has happened with @jezhumble and @afeld
