### ISSUE TITLE
Bosh certificates fail with new bosh_cli v2

### ISSUE THREAD

**Issue by rogeruiz** [18F/cg-product#603]
Our current Bosh certificates on GovCloud are busted. Waiting on @cnelson to come back to finish up.

**Comment by cnelson** [comment]
Bosh certificates have been updated, but now all pipelines that interact with bosh need to be updated.  This is in progress.

**Comment by cnelson** [comment]
@rogeruiz  I think we can close this once the PRs above are merged

**Comment by rogeruiz** [comment]
Yup. Thanks!
