### ISSUE TITLE
Pay down dashboard tech+design debt

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#605]
What we're after: Spare some cloud.gov capacity to tackle known bugs, high-priority UI fixes, and interest-bearing tech debt associated with the cloud.gov dashboard

Benefits/why:

- Increase user confidence in using the dashboard effectively
- Put the dashboard in a better state for adoption by and contributions from other teams

**Comment by mogul** [comment]
UI debt is largely captured in [this Doc](https://docs.google.com/document/d/1Hx3QXfkmxdpX-rPxu3XNp2VRuGc8BaNryzshE43dPu0/edit).

**Comment by suprenant** [comment]
More possible UI debt here (may be duplicate issues on the board): https://docs.google.com/document/d/1qSDrAEQ3yIioiWViYuo0hEnt7Jkux5EJaqVXqdjdKgo/edit#

**Comment by mogul** [comment]
We're now deprecating cg-dashboard in favor of Stratos
