### ISSUE TITLE
Marketplace can prompt for service parameters (0.3)

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#609]
What we're after: When a user creates a service instance, they are prompted for all necessary and potential parameters

Benefits/why:

- Support coherent end-to-end workflow in dashboard, and avoid support requests

Potential metrics:

- How far can new user can get through our "your first deployment" guidance without us referencing/requiring them to install the CLI?

**Comment by suprenant** [comment]
Noting (from Fureigh, I think), that this tool could possibly help us here:
https://medium.com/the-u-s-digital-service/building-forms-faster-on-vets-gov-d8619f4e9db

**Comment by suprenant** [comment]
From Britta:
Being able to create a service instance from the dashboard that required giving parameters in order to use the service (could redirect you to the docs for the CF CLI).

**Comment by mogul** [comment]
Noteworthy: There's an effort afoot to make services self-document their available parameters via standardized JSON, so we would no longer have to do this via custom metadata.
https://docs.google.com/a/pivotal.io/document/d/17-g3B9mXXz_5bwlnksr1KeyjvXAeJQtW9jHMNJ3npP0/edit?usp=gmail

**Comment by suprenant** [comment]
Noted in the Github issue from [@mogul - Bret Mogilefsky] (FYI, the comment didn't sync): 

_Noteworthy: There's an effort afoot to make services self-document their available parameters via standardized JSON, so we would no longer have to do this via custom metadata.
https://docs.google.com/a/pivotal.io/document/d/17-g3B9mXXz_5bwlnksr1KeyjvXAeJQtW9jHMNJ3npP0/edit?usp=gmail_

**Comment by mogul** [comment]
This will be especially useful: 
https://github.com/mozilla-services/react-jsonschema-form

...particularly given that OSBAPI is standardizing on always-supply-JSON-schema-for-parameters for all catalog listings!
https://www.openservicebrokerapi.org/blog/2017/09/27/open-service-broker-v2-13-has-landed

**Comment by mogul** [comment]
We're going to get this by switching to Stratos.
