### ISSUE TITLE
Remove Diego from cloud.gov team

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#610]
In order to complete Diego's exit from the cloud.gov team, the assignee should complete a prescribed set of tasks that will remove any special access.

# Directions:
**Assignee:** The tasks below are organized by the role needed to complete them. If you can’t complete any of the items on your checklist personally, _you are responsible for ensuring that an appropriate person does it_.

## Assignee
- [x] Remove them from the @cloud-gov-team in the Slack Team Directory
- [x] Remove them from the [team roster](https://docs.google.com/spreadsheets/d/1mW3tphZ98ExmMxLHPogSpTq8DzYr5Oh8_SHnOTvjRWM/edit#gid=0)
- [x] Remove them from the [squad list](https://github.com/18F/cg-product/blob/master/DeliveryProcess.md#squads)
- [x] Remove them from the [training tracker](https://docs.google.com/spreadsheets/d/1hqU6cNeEB293OT0j3OvbdAFRkrf2zDOrPVxGfnr4sSw/edit#gid=0)
- [ ] Remove them as invitees for any meetings on the cloud.gov calendar
- [x] If they are leaving 18F ensure the [18F Handbook exit process](https://handbook.18f.gov/leaving-18f/#offboarding-process) has been kicked off via the 18F talent team

## Product Owner
- [x] Remove them from [GitHub teams that start with cloud-gov](https://github.com/orgs/18F/teams?utf8=%E2%9C%93&query=cloud-gov)
- [x] Remove them from the [Cloud Foundry Community GitHub org cloud.gov team](https://github.com/orgs/cloudfoundry-community/teams/cloud-gov)
- [x] Remove their access to Zendesk
- [x] Remove their access to StatusPage
- [ ] ~~Remove their access to PagerDuty~~
- [x] Remove their access to New Relic
- [x] Remove their access to [Aha!](https://18f.aha.io)
- [x] Remove them from [the cloud.gov team Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov)
- [x] Remove them from [the cloud.gov notifications Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov-notifications)
- [x] Remove them from [the cloud.gov inquiries Google Group](https://groups.google.com/a/gsa.gov/forum/?hl=en#!forum/cloud-gov-inquiries)
- [x] Remove them from the project in Float
- [x] Remove their membership in cloud.gov-specific Trello boards (eg the business-tracker)
- [x] Remove them from DigitalGov Search access for cg-site

## Cloud Operations
- [x] Remove them from any IAM roles they hold in AWS E/W and GovCloud
- [x] [Remove their access as an admin](https://docs.cloud.gov/ops/managing-users/#managing-admins) on the platform
- [x] Remove any special Org or Space roles that their cloud.gov account holds
- [x] Confirm the Product Owner has removed them from all GitHub teams
- [ ] Ensure any keys they had direct access to are rotated

**Comment by mogul** [comment]
Everything's done as of today except for the key rotation, which is being [tracked elsewhere](https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-3296) so we're going to move this card and unclog the board.
