### ISSUE TITLE
Outline how the current cloud.gov user experience affects a user's "time to ATO"

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#62]
In order for cloud.gov designers to help ourselves apply our expertise to cloud.gov, as designers (and anyone else interested) we should have an outline of where (and how much) the current overall cloud.gov design (UX, visual, content) might slow down a user's "time to ATO".

This should be a short task (a sketch rather than a map) - an experiment to help us think about our work.

I made a doc for this at https://docs.google.com/document/d/1ARKg6TxIbRzt5COgitDwxwO2D9C5C-Z5f7-Tdpwjp80/edit and put a few notes in it.

Acceptance criteria:

- [ ] There's a document in Google Drive with an outline that multiple people have contributed to.
- [ ] Designers have chatted a bit about this outline and what it might suggest for our planning.

**Comment by mogul** [comment]
We'll review the work done to date here in the course of grooming 18f/cg-product#63
