### ISSUE TITLE
Research cause for IPv6/IPv4 routing question

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#639]
In order for tenants to use services for their apps with predictable/understandable routing, we should identify the cause of a recently-noticed confusing routing behavior and figure out whether we should adjust our system and/or document a recommended best practice configuration for tenants. (In the process, we should also answer the person who brought up this question.)

This is in service of the customer question at https://cloud-gov.zendesk.com/agent/tickets/175 - those two emails provide the relevant logs and details.

**Acceptance criteria**

- [x] We've identified why this happens and whether this is the right behavior or whether something (on our end or theirs) needs adjustment.
- [x] We've replied to their question with a recommendation (you can write the response or briefly explain it to @brittag so she can write it - either is fine, up to you).
- [x] We've filed stories or PRs to document the answer in a durable place (such as user docs) and/or make any necessary technical changes.

**Comment by mogul** [comment]
We're going to go for the one-sentence/RTFBP answer here.

**Comment by mogul** [comment]
Chris refers to this: https://tenzer.dk/nginx-with-dynamic-upstreams/

**Comment by cnelson** [comment]
I think this is done;  I replied to Al, and I don't think there's any documentation we need add at this point, this just seems like unfamiliarity with nginx.  

If we get future support requests that touch on this same issue, we can PR some documentation updates to the staticfiles buildpack but I don't think it's worth the effort right now.

**Comment by cnelson** [comment]
Al seems happy with our response, marking resolved
