### ISSUE TITLE
Enable Quotas app in GovCloud

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#655]

**Comment by jmcarp** [comment]
Deployed to govcloud. I don't know enough about the app to be able to verify that it's working as expected; @sharms will take a look.

**Comment by cnelson** [comment]
Couple of things I see:
- Only running 1 instance in prod.  Should we run more than one as our own production-ready guide suggestions
- Looks like the brokered DB is hand-propped?  Can we make the concourse deploy handle that and/or add the service binding to the manifest?

**Comment by cnelson** [comment]
I'm happy to work on the above ☝️ if it's a good idea, so someone else other than @jmcarp knows a little bit about this app.

**Comment by jmcarp** [comment]
I don't know much about this app, but I did set up database provisioning from concourse a while back: https://github.com/18F/cg-quotas-db/blob/master/ci/pipeline.yml#L15-L25. Anyway, yeah, if you want to tackle those issues, that sounds good.

**Comment by cnelson** [comment]
I've added a synthetics check for basic uptime monitoring in new relic
