### ISSUE TITLE
[ RESEARCH: 1 day ] Concourse Credentials should be using Vault to make things easier

### ISSUE THREAD

**Issue by rogeruiz** [18F/cg-product#657]
WIP Proposal:
* Concourse workers can fetch vault secrets used in bosh deploys using [ec2 auth](https://www.vaultproject.io/docs/auth/aws-ec2.html).
    * Alternatively, use [approle auth](https://www.vaultproject.io/docs/auth/approle.html); means concourse jobs must be passed secrets explicitly, but allows for finer granularity between pipelines
* Concourse jobs must pass the correct client nonce in vault authentication
* Bosh deploy manifests fetch secrets from vault using the spruce `vault` operator
* Bootstrapping (based on https://starkandwayne.gitbooks.io/codex/content/aws.html#vault-init)
    * On creating a new environment, deploy a vault-init instance
    * Operator adds secrets to deploy master-bosh, tooling-bosh, main vault
    * After bootstrap, copy secrets from vault-init to main vault and destroy vault-init

Note: this proposal only touches bosh secrets. I'm thinking we might want to defer changes to concourse secrets until concourse adds native support for vault and other backends.

**Comment by pburkholder** [comment]
Test comment

**Comment by pburkholder** [comment]
I have a docker-compose demo of how vault+concourse works (https://github.com/pburkholder/docker-concourse-vault). There are errors in the concourse docs that I'll need to make PRs for, but first I'll make the demo reproducible, then use that to consider a way forward.

**Comment by pburkholder** [comment]
The linkage between Favro and this issue for some reason doesn't let me edit https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-1135, so I'm closing this one and the Favro ticket. The description is rather dated (as it was written before Concourse had built-in Vault integration and there are no comments (other than mine).

**Comment by rogeruiz** [comment]
:eyes: https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-6277
