### ISSUE TITLE
Remove Elasticsearch 1.7 from GovCloud

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#658]
Elasticsearch 1.7 went EOL on 1/16, we should deactivate it in the k8s broker.

**Acceptance Critera**
- [ ] Elasticsearch 1.7 is not available via the marketplace in GovCloud
- [ ] cloud.gov/docs is updated to not reference old versions of ES

**Implementation Sketch**
- Update the concourse pipeline to remove [es17 references](https://github.com/18F/cg-deploy-kubernetes/blob/master/pipeline.yml) (don't miss the `broker-service-names-*` in the secrets)
- Update the [broker itself to remove the es17 plans](https://github.com/18F/kubernetes-broker/tree/master/catalogData/elasticsearch17)
- Check cloud.gov/docs/ for references to ES1.7 as [some pages](https://cloud.gov/docs/apps/managed-services/) use old versions of ES as examples

**Comment by mogul** [comment]
@suprenant per Atlas grooming, we need this one to happen... 1.7 is an obsolete service, and we want people to remove their dependance on it as they migrate!

**Comment by suprenant** [comment]
@mogul ah, ok! Sorry we monkeyed with it, thanks
