### ISSUE TITLE
Aligning with cg business communication goals

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#659]
Skyporter wants to set up a clear way of providing various levels of support for Steve and Britta as they drive our business forward. 

Since our squad is focused on work that improves customer experience from inquiry through early use, we'd love to support by helping develop our team's practices of (1) validating our work with lightweight and regular user testing and (2) ensuring that our have feedback loops that capture customer feedback so we can use it to improve. Let's discuss.

Acceptance criteria:
- [ ] agreement with S+B re: our role in building in a regular practice of incorporating feedback from users into cloud.gov work across squads;
- [ ] agreement w S+B re: how we build in a practice of validation/testing into cloud.gov work across squads;
- [ ] agreement about how we communicate with each other regularly to ensure that Skyporter is serving the business goals as identified by our new leadership.

cc: @jameshupp @brittag @sharms

**Comment by sharms** [comment]
Great idea and supportive of the general narrative.  We need to, as a team, develop quick iteration cycles and determine how our changes impact customers and the above will help address.   

Customer satisfaction, new agreements, retention, support requests, time to resolution and downtime would be a few categories I would love to understand how our agile cycles impact positively or negatively.

**Comment by nikzei** [comment]
Great - I'll put time on the calendar for us to take this further.

**Comment by nikzei** [comment]
our role in building feedback loops: --> skyporter is responsible for reviewing inquiries listserv and making documentation and content updates in response.

our role re building in more testing: --> this will be a case by case thing across squads. We won't lead with this, though we'll support when appropriate

How we communicate: --> one person from BU will attend sprint planning with us. Otherwise, we'll slack and set up meetings as appropriate. Also, we've set more clarity around who owns what.
