### ISSUE TITLE
Documentation followup for January POAMs

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#660]
In order to crank the handle on our ConMon process, we need to follow up on ConMon POAMs with next steps due in January.

See [the January POAMs filter view in the sheet](https://docs.google.com/spreadsheets/d/16igVl8cD3SqeX5_SOn5Su34KmwMRnP20gPbfQlqIwfM/edit#gid=1701775784&fvid=2092381856) except for AC10, filed separately

- [x] V8-AC-22 - Send documentation to Veris @brittag 
- [x] V35-AU-5 - No technical work needed, [drafting here](https://docs.google.com/document/d/1YmLBWDiHb5w1NNyhBzMwuJkc4UYDxQMbsuLXesCh_9E/edit#) @cnelson and @brittag 
- [x] V44-CP-3 - Document that the training was done @brittag 
- [x] V55-SA-2 - Document @brittag 
- [x] V56-SA-3 - Document @brittag 
- [ ] CG04 - Meet with @rjbator to decide on the right approach (false-positive, pre-document BOSH stuff, etc.) @sharms 
- [x] CG06 - Check whether this is addressed on GovCloud once Nessus is enabled there @sharms @cnelson 
- [x] CG05 - Need to badger AWS monthly @sharms will talk to @rjbator about this

**Comment by cnelson** [comment]
Re CG05: Case 2042762941 opened with AWS to inquire about support for Postgres 9.5.5 / 9.4.10.  Will follow up with their response once we have it.

**Comment by brittag** [comment]
Put together info for V35-AU-5, V8-AC-22, V44-CP-3, V55-SA-2, and V56-SA-3; [it's in this Word doc section for visibility](https://docs.google.com/document/d/1YmLBWDiHb5w1NNyhBzMwuJkc4UYDxQMbsuLXesCh_9E/edit#heading=h.nc5cgvdd88ym).

**Comment by cnelson** [comment]
Added additional info for CG04 and CG01-AU-5 in[the doc](https://docs.google.com/document/d/1YmLBWDiHb5w1NNyhBzMwuJkc4UYDxQMbsuLXesCh_9E/edit#heading=h.nc5cgvdd88ym).

Re CG05: Amazon responded with a response that doesn't make sense as Postgres 9.6 is not available in GovCloud:
> RDS currently does not support Postgres 9.5.5 and as of now we have no information if it will be supported in future specially when we already have 9.6.1 version available which has the fix for the issue you have mentioned. 

I responding by reminding them the issue opened was about GovCloud where Postgres 9.6 is not available and am awaiting a response.

**Comment by mogul** [comment]
Modulo what @sharms wants to do about CG04, we're kind of done with this from the Atlas side based on Chris' addition described above.

**Comment by brittag** [comment]
I believe this is done! Submitted ConMon report yesterday evening with documentation for these.
