### ISSUE TITLE
[research: 1 day] Determine best way to automatically identify out-of-date BOSH releases

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#662]
In order to ensure we're running up-to-date compliance tools we want to spend a day to investigate whether we could automate notifications of new upstream versions that should be incorporated into our BOSH releases.

**Acceptance Criteria**

- [ ] Determine if it's a viable path
- [ ] If viable, we know enough to write stories and estimate the effort involved

**Implementation sketch**

- Check to see what we're using that is in [the CPE DB](https://scap.nist.gov/specifications/cpe/)
- Change BOSH blob names to use the CPE names
- Have a script that checks for new entries in CPE for our stuff, inspects the versions in BOSH director and generates a report of what's out of date
- Try to get stuff we use that's not yet in the CPE into the CPE

**Comment by jmcarp** [comment]
Took a quick look at the CPE database at https://web.nvd.nist.gov/view/cpe/search, and I couldn't find current versions of:

* Snort (we're on 2.9, CPE goes up to 2.7)
* Python (goes to 3.5, latest is 3.6)
* Golang (goes to 1.6, latest is 1.7)
* Kibana (goes to 4.2, latest is 5.1)
* Riemann (not found)
* Influxdb (not found)

**Comment by jmcarp** [comment]
Here's a blog post outlining a very simple method for updating blobs: https://dpb587.me/blog/2015/08/03/self-upgrading-packages-in-bosh-releases.html
