### ISSUE TITLE
Platform-critical UAA client credential generation from code

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#665]
In order to make sure we can recover our entire platform in a working state that meets compliance requirements, we want any UAA client secrets used by platform components to be captured in the appropriate CF environment secrets

**Acceptance Criteria**

- [ ] UAA clients for platform services are captured in the proper CF deployment secrets
  - [ ] 18f-console (dashboard)
  - [ ] kibana_oauth2_client (logsearch)
  - [ ] kubernetes-client
  - [ ] ssh-proxy
  - [ ] admin-ui
  - [ ] cloud-gov-community
  - [ ] concourse-broker
  - [ ] uaaproxy (uaa auth service)
  - [ ] uaamonitor (sandbox-bot)
- [ ] UAA client refresh tokens are limited to 72 hours of validity.
- [ ] UAA client access tokens are limited to 10 minutes of validity.

**Comment by LinuxBozo** [comment]
ssh proxy being pulled in from upstream currently: https://github.com/cloudfoundry/diego-release/blob/master/stubs-for-cf-release/enable_diego_ssh_in_cf.yml  To override correctly, we'd have to move from spiff to spruce for our CF deployment
