### ISSUE TITLE
Tooling BOSH UAA dependency causes random pipeline failures

### ISSUE THREAD

**Issue by sharms** [18F/cg-product#666]
Tooling and Primary BOSH use UAA for authentication, which will randomly fail due to UAA authentication failures (despite using the same credentials).

Staging and Production do not leverage UAA and are not experiencing this issue.

**Comment by cnelson** [comment]
This is likely because we are not authenticating correctly in our pipeline tasks with the bosh v2 cli.

If you are using the bosh v2 cli, and UAA you MUST authenticate with a client credentials not user / pass as we currently do.

**Comment by jmcarp** [comment]
OK, let's switch to client credentials like you said--but I still don't understand why auth works most of the time and fails apparently at random.

**Comment by jmcarp** [comment]
Resolved by authenticating to opslogin with client credentials, h/t @cnelson!
