### ISSUE TITLE
Activate our base of inquiries

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#67]
What we're after: Increase the rate of IAAs for cloud.gov from ~15/year to... something higher

Benefits/why:
- Shift focus toward cost-recovery
- Keep funding levels sufficient to sustain velocity
- Increase the impact of the work done to date

Ideas floated
- seminars, blog posts, mailchimp, etc.
- maybe this is where CRM comes in

**Comment by brittag** [comment]
This is related to https://github.com/18F/cg-product/issues/71 (notifications of product changes + incidents + general velocity) - prospective customers and current customers likely both want to hear about these things. Some of the same work would serve both.

**Comment by berndverst** [comment]
This is where the following tasks (currently assigned to me) come in.

CRM (for tracking leads, IAA status, integration status, etc)
https://github.com/18F/cg-skyporter/issues/1 

Reaching out to all Leads who completed our form.
https://github.com/18F/cg-skyporter/issues/2

**Comment by mogul** [comment]
Closing as we have no open work happening on this Feature.

**Comment by mogul** [comment]
Actually going to stick it in the `Feature Backlog` instead.
