### ISSUE TITLE
PI8 product update newsletter

### ISSUE THREAD

**Issue by jameshupp** [18F/cg-product#683]
In order to inform people interested in cloud.gov of changes made in PI8, we need to send a regular quarterly newsletter as soon as our next major event occurs. Note that we will use the newsletter drafted for PI8 as our newsletter template.

- [x] Compile all updates
- [x] Draft
- [x] Set up final copy in MailChimp
- [x] Send (post-acceptance)

Criteria:
- [x] @nikzei signs off on content
- [x] @nikzei signs off on test copy of message for layout/interaction
- [x] real message arrives in team member's inbox who can verify

(NZ additions)
- [x] we have a reusable mailchimp template for future quarterly newsletters 
- [x] we are able to post the newsletter on the website in addition to sending it out via mailchimp
- [x] we ensure that existing customers get a copy of the newsletter (unclear whether all of our customers are on our mailchimp list)
- [x] newsletter is written in plain language so that an audience that is unfamiliar with our day to day team processes can follow it
- [x] newsletter is visible to people who are not on our mailing list yet (maybe posted on website?)
- [x] newsletter is sent to mailing list 
- [x] newsletter is sent to existing customers

**Comment by jameshupp** [comment]
Draft in progress here. @nikzei @mogul @sharms @brittag Would love folks' ideas on what should be included!
https://docs.google.com/document/d/1Qom96yiX0IawkTnT8I41ObqH34nzJ5kEcdUlFinOQjo/edit#

**Comment by brittag** [comment]
We emailed this and put it on the website (https://cloud.gov/updates/2017-02-02-fedramp-authorized/), so this is done!
