### ISSUE TITLE
Increase monitoring of services

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#69]
What we're after: We find out about services being unavailable before our customers

Benefits/why:
- Avoid the team drowning in fire alarms  
- Enable more confident rollout of future services

**Comment by rogeruiz** [comment]
Let's maintain feature parity across the two environments for cloud.gov, (e/w and govcloud).

> it makes the most sense to ensure both environments are consistently working so we don't waste time talking about why they were not

**Comment by mogul** [comment]
We're calling this "good enough" for now in terms of concentrated team focus. From here out it'll be incremental work per-alert as and when we feel it's needed, unless/until we feel we're back in a crisis state on monitoring generally.
