### ISSUE TITLE
Upgrade RDS databases to 9.6.1

### ISSUE THREAD

**Issue by cnelson** [18F/cg-product#690]
In order to resolve POAM CG05 we need to upgrade all RDS databases to 9.6.1 which is the only supported postgres release available via RDS that does not contain the defects referred to by the POAM item.

**Acceptance Criteria**
- [ ] All terraform managed RDS databases are upgraded to 9.6.1
- [ ] Nessus scans no longer identify the defect in question

**Implementation Sketch**
This _should_ be a simple change but after asking around in CF/concourse slacks it does not appear that any of their components (Concourse, BOSH, UAA) have been tested on 9.6.  If we run into issues we will likely need to get PRs merged in upstream before we can upgrade.

Knowing this, we should probably NOT upgrade in place our existing postgres databases, but spin up a new 9.6.1 DB next to our existing DBs and test against that, so we have an easy rollback path if we find problems.

cc: https://github.com/18F/cg-product/issues/660

**Comment by cnelson** [comment]
It may be worth attempting to upgrade our east staging staging environment where 9.6 is available to get ahead of any PRs that may be required upstream.

**Comment by cnelson** [comment]
Update from Amazon:
> Based on latest update from the RDS PostgreSQL internal team, they are currently targeting the week of 2/6 to have PostgreSQL 9.6.1 deployed to GovCloud.

Assuming they hit that date, we should plan on scheduling this work in PI3

**Comment by brittag** [comment]
Yay! Updated description to note this is CG05 instead of CG04.

**Comment by cnelson** [comment]
This is unblocked.  Postgres 9.6.1 is now available in GovCloud.

**Comment by ccostino** [comment]
@cnelson this is awesome news!  In order to make use of this, is there anything we need to do?  What if we have an RDS instance setup in GovCloud now, do we have to recreate it to get the new version?

**Comment by brittag** [comment]
Closing this since this is available now! @ccostino I believe for your project the RDS instances are managed separately, so I'm not sure what the status/management of yours might be.

**Comment by ccostino** [comment]
Thanks, @brittag!  As of now the new GovCloud RDS instances we have running are 9.6.1, so we're okay on our end too. :-)

FYI that 9.6.2 was just released, but not sure if Amazon has support for it yet.  Just wanted to make sure folks were aware!

**Comment by cnelson** [comment]
Are the 9.4 database still online?  Do we have a plan or card to remove them since this story is done?

**Comment by jmcarp** [comment]
I'll write up a patch to delete the old instances.
