### ISSUE TITLE
Evaluating customers from inquiries for continuous improvement on the website.

### ISSUE THREAD

**Issue by nikzei** [18F/cg-product#691]
In order for Skyporter to continuously improve the website, BU needs to gather structured data about each incoming inquiry and their knowledge and readiness to use cloud.gov. This will support business unit operation as well. 

A few examples include:
- what an empowered team looks like
- 1-3 of how well they understand cloud.gov as a product
- do they understand our pricing model and whether it works for them.

Acceptance Criteria
- [x] we have a list of the data elements we want about each inquiry
- [x] we have a way to gather and store this data that Skyporter and BU can both access
- [ ] this information gathering process is established in BU operations as a repeatable process
- [x] we have a repeatable process for Skyporter to review and integrate this information.

**Comment by nikzei** [comment]
Let's get clear with the BU folks about what information they want to track every sprint from the inquiries listserv.

One example seems to be the number of sandbox inquiries made. What else?

**Comment by nikzei** [comment]
Creating a list of data elements that we can gather for each inquiry communication:
 
- this individual understands our value proposition (scale from 1-3: 1 = no, 3 = yes);

- this individual on the : technical team,  non-technical manager, 3- decision maker, or other

- individual is: a current cloud.gov team member, a sandbox user,  a prospective customer; other

- this is a sandbox inquiry

- government versus vendor

cc [@Britta Gustafson], [@Steve Harms - TEAAC]  - would these data elements be useful for you all? If so, we could create a form for you to use as inquiry listserv emails come in?

**Comment by brittag** [comment]
Thanks Nikki! I'm not sure yet what will be helpful, so we can just start with that - especially if all the questions are optional (since for example sandbox inquiries often don't have much info in them).

**Comment by jameshupp** [comment]
Threw together a draft plan on this. It's rough but it's there! https://docs.google.com/document/d/1CbLMvf0ku2KcAbjP5QPhC5pKcH6NqzNMQafqPXXfokU/edit#heading=h.qg2g0bqffvl6

**Comment by jameshupp** [comment]
I think all acceptance criteria are met now so I marked them (easier to track). The fourth one is more implicit than explicit: we have a way to incorporate new inputs into Skyporter's planning that's not specific to this story, but I think it covers this story, as well.

**Comment by jameshupp** [comment]
Whoops, sorry, I wrote this as if it was Skyporter operations, but I see now that the repeatable process part is BU. Not sure if it's something you all can fold in the way it's described or not but would love thoughts on that. [@brittag - Britta Gustafson] [@sharms - Steve Harms]

**Comment by brittag** [comment]
Thanks James! I wrote a few notes in your doc - generally my feeling on this is that the best next step is to start trying this out. :D

**Comment by nikzei** [comment]
We're holding until there is space in WIP to pick it up again.

**Comment by nikzei** [comment]
Have chat w Britta when we are ready to pick this up in case she has new ideas about what will be useful.

**Comment by nikzei** [comment]
Created a first draft for [@brittag - Britta Gustafson] to respond to: https://docs.google.com/a/gsa.gov/forms/d/1yUlnsRYPt_8jxY6cb8vD_P-FQjb6NEa_3wKL5qUl28I/edit?usp=sharing

My thoughts: I'm not 100% clear what the need is here - it would be great to flesh this out more.

I created this simple form based on the assumption that (1) we could use this information to understand what "content marketing" materials might  be the most appropriate for those interested in our product, and (2) we could say that if the scores go up (indicating that prospectives become increasingly knowledgeable about our product and domain over time), that our outreach efforts are proving to be successful.

**Comment by nikzei** [comment]
Waiting for feedback from [@brittag - Britta Gustafson]

**Comment by nikzei** [comment]
Learned that the best way to do this is for [@brittag - Britta Gustafson] to create an instrument in salesforce.
