### ISSUE TITLE
Comb inquiries backlog for content update prioritization

### ISSUE THREAD

**Issue by jameshupp** [18F/cg-product#696]
In order to serve content that reflects the needs of actual prospective and current cloud.gov users, update the backlog with the most recent incoming questions about cloud.gov.

Questions being tracked and backlogged here: https://docs.google.com/document/d/1nVCgwNdYO_IO_Vj-4FVeHWBlmLMrlOjXHmPghm0oObQ/edit?pli=1

**Comment by nikzei** [comment]
This will be continuous work - we'll review the inquiries listserv each sprint and we'll create cards for any work that we feel we need to take on in response.

**Comment by nikzei** [comment]
I'm doing a cursory comb through of emails from sprint 3 (1/26 - 2/8). Dropping these into the Sprint 3 section in the above linked doc. We can groom them during sprint planning.

**Comment by jameshupp** [comment]
Should this get folded into #18F-3217? (The weekly work.)
