### ISSUE TITLE
Publish PI9 sprint 1 update post

### ISSUE THREAD

**Issue by jameshupp** [18F/cg-product#699]
- [x] draft post
- [x] submit PR
- [x] publish

Criteria:
- [x] @nikzei signs off that content is ready
- [x] @nikzei signs off on PR

Will add others here requesting input as necessary; I'm sure it will be.

**Comment by jameshupp** [comment]
In progress here https://docs.google.com/document/d/1Km3z2H8aH3wN-j2RguobNUhWdV7Hngu6AxwC6SHLbW8/edit#

**Comment by nikzei** [comment]
I'll close this, @jameshupp?

**Comment by jameshupp** [comment]
I got it!
