### ISSUE TITLE
Add Favro to onboarding checklist

### ISSUE THREAD

**Issue by fureigh** [18F/cg-product#701]
If Favro continues to be A Thing, let's add joining Favro to the checklist, including:
* Who should send the new team member an invitation to Favro, and
* That the team member should authenticate with GitHub (not/just Google) in order to be able to access the necessary functionality.

**Outstanding questions:**
* Will Favro continue to be A Thing? Who will make that call and when?

(Another approach is to just add Favro, and take it out if we end up moving away from it.)

**Comment by brittag** [comment]
👍  I support just adding it to the onboarding and offboarding checklists and then removing it if we don't end up using it, since we can quickly make and approve changes to our own docs.

**Comment by rogeruiz** [comment]
Whoops. I went ahead and did this on #715. Please let me know if we want some clearer instructions there.

**Comment by fureigh** [comment]
Great! I added some suggestions over there. Thanks for addressing :)

**Comment by brittag** [comment]
We're no longer using this.
