### ISSUE TITLE
Proactive notice of new features and platform-wide incidents or changes

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#71]
What we're after: Users are regularly and centrally informed of general (non-user-specific) changes happening in cloud.gov: New features, outages, changes

Benefits/why: 
- Users can make use of new facilities, and react to events that need their attention.
- Users perceive cloud.gov velocity

Metrics:
- How many users are contacted when we have a new feature/outage/announcement?
- How consistently do we announce features/outages/changes in policy?

**Comment by brittag** [comment]
We should also figure out if users want some sort of "proactive advice/help" output from us, such as a weekly friendly newsletter of recent useful support answers and docs updates (for now, this would be a summary of answers in #cloud-gov-support + email support + any updates to docs.cloud.gov).

**Comment by brittag** [comment]
(I made a mockup of that kind of newsletter sort of accidentally while looking at synthesizing support requests - https://github.com/18F/cg-deck/issues/392#issuecomment-233101507)

**Comment by mogul** [comment]
This wasn't completed in PI8, because even though we now write `/updates` we're still not informing anyone that they exist. However we're carrying it forward into PI9 because it's still a priority.

**Comment by nikzei** [comment]
@mogul I believe that Skyporter is prepared to handle notifications that go out to prospective users via mailchimp. But this feature focuses on notifications to existing users, which I believe would be  set up with the cloudfoundry notifications api and would be more appropriately handled by Atlas folks - at least setting up the notifications to go out. Let's have an Atlas and Skyporter sync to figure out next steps - ideally we could even do this in time for our FedRAMP announcement.
