### ISSUE TITLE
Automatically manage subscriptions of users to technical updates

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#72]
In order for SkyPorter to be able to message all users without worrying about their subscription preferences, we want a list in our mailing list manager to track the set of active users in cloud.gov.

(This is about being able to notify users of changes in the service on a routine basis, with users able to opt in and out, default being in)

[Background discussion notes](https://docs.google.com/document/d/1MLYNip7TfvA5g1t5nBVrRjQNN38rcZxmXgRDF8VAbXY/edit)

**Comment by brittag** [comment]
This would include some lightweight user research (very short interviews) to learn how people *want* to get notified about various kinds of cloud.gov news (breaking changes, feature updates / new features, etc.), ideally including people at 18F, people at EPA, and a few prospective users from other agencies. (Do they read their email? Do they want an RSS feed? Would they reeeally just want a little notice in the CF CLI when they log in? Something else?)

**Comment by brittag** [comment]
This would also likely include:

* Fix the RSS feed for the updates posts (https://github.com/18F/cg-landing/issues/88)
* Make a mailing list happen

**Comment by nikzei** [comment]
**Newsletter:** 
Schedule: Quarterly - roughly the week following PI Inspect and Adapt
Length: one pager-ish
Audience: goes out to our mailing list via mailchimp
Author: Skyporter (James Hupp and others)

**Technical updates (“Platform release notes”):**
Roughly bi-weekly technical updates to cloud.gov/updates. These will focus on updates related to the functionality of the product and other items relevant to users. It will not focus on our team activity. 
Schedule: bi-weekly / as appropriate
Length: bullets
Audience: technical audience
Author: Bernd

**Blog posts (major announcements / things with opinions and editorializing)**
Schedule: occasional
Length: long-ish
Audience: 18F blog (with summary and link at /updates)
Author: Anyone, with review/oversight via the 18F blog process

See rubric by @brittag for more details

**Comment by nikzei** [comment]
Are there any other types of important notifications that aren't covered above? 
@mogul @diego?

**Comment by mogul** [comment]
This seems like it'll cover stuff for now.

**Comment by nikzei** [comment]
Nikki and Bret groomed the initial post and title of this issue to focus specifically on the case of technical updates. We will write similar issues in future for quarterly updates, outages, and pointers to blog posts.

**Comment by nikzei** [comment]
PI8 75% assessment:

SHOULD: Currently we are releasing bi-weekly technical updates but we don't give users notice of them.  Setting the notifications up as per the checklist above seems in line with PI8 if we can fit it in. I'm assuming it should be a light lift but need to check with @berndverst.

**Comment by nikzei** [comment]
Let's make separate stories for newsletter, blog posts, and technical updates.

**Comment by mogul** [comment]
We should investigate what kind of things MailChimp can do in response to feed updates to get a sense whether that automation is viable.

**Comment by cnelson** [comment]
Do we need to worry about this feed containing users from east while that's still active?

**Comment by brittag** [comment]
I'd suggest we should keep feeding data to Mailchimp from East while it's still active - for example, we may send notices about migration for East people, so all East people should get those (for example, if any new people have been added by teammates on a project that hasn't migrated yet).

**Comment by nikzei** [comment]
These Skyporter AC presuppose access to Mailchimp, which we might no longer be able to use? If we can't use mailchimp, another AC will be choosing a new tool/method to interact with customers for these purposes. I'll add that AC above.

**Comment by brittag** [comment]
Oh hm, I'd suggest rewriting this story to be not-tool-specific - for example, replacing "Mailchimp" with "our email tool" and reframing the description to include something like "a prerequisite for working on this story is having access to an email tool that we can use on an ongoing basis", since we may want to work on that choice in a different story.

**Comment by mogul** [comment]
Definitely, we don't want this story to blow up since finding a replacement tool is an endeavor in and of itself!

**Comment by mogul** [comment]
I moved this down the Atlas backlog a bit until we know more about whether we're writing this for MailChimp or for GovDelivery or some other solution.
