### ISSUE TITLE
List of changes to user permissions

### ISSUE THREAD

**Issue by hollyallen** [18F/cg-product#727]
To ensure the test-ability of SSP control narratives for systems on cloud.gov, I'm requesting the following feature.

A place in cloud.gov to see an audit list of changes to user permissions. This could be in the dashboard, in logs.cloud.gov, both, whatever works best for cloud.gov.

**Comment by brittag** [comment]
👍  As additional context for when we prioritize/groom this story: we also heard a version of this in the ["need to be able to monitor stuff" requests from the Federalist experience](https://docs.google.com/document/d/1tY56SdgNCNwOEABlhNOof_75LrZAP_OBOt6V2NJRPE4/edit#bookmark=id.d76qy9lzh7t6).

**Comment by cnelson** [comment]
The cloud controller maintains an audit log of all changes to org/space/user/quota changes, but it's stored in an internal database.  Implementing this will probably involve figuring out how to expose that data via the dashboard.

**Comment by mogul** [comment]
@hollyallen This data is in the system and you can get it out yourself today. For example:

```bash

 ~ cf set-space-role holly.allen@gsa.gov sandbox-gsa bret.mogilefsky SpaceDeveloper
Assigning role RoleSpaceDeveloper to user holly.allen@gsa.gov in org sandbox-gsa / space bret.mogilefsky as bret.mogilefsky@gsa.gov...
OK

 ~ cf unset-space-role holly.allen@gsa.gov sandbox-gsa bret.mogilefsky SpaceDeveloper
Removing role SpaceDeveloper from user holly.allen@gsa.gov in org sandbox-gsa / space bret.mogilefsky as bret.mogilefsky@gsa.gov...
OK

~ cf space --guid bret.mogilefsky
7fc37305-9421-4c8a-b7d7-addbd2a2d910

 ~ cf curl "/v2/spaces/7fc37305-9421-4c8a-b7d7-addbd2a2d910/events" -X GET
{
   "total_results": 2,
   "total_pages": 1,
   "prev_url": null,
   "next_url": null,
   "resources": [
      {
         "metadata": {
            "guid": "27198df1-13be-403e-ac76-b2828d2980a2",
            "url": "/v2/events/27198df1-13be-403e-ac76-b2828d2980a2",
            "created_at": "2017-03-16T17:15:37Z",
            "updated_at": "2017-03-16T17:15:37Z"
         },
         "entity": {
            "type": "audit.user.space_developer_add",
            "actor": "ec3aac6c-5f56-4a92-8958-a96944795b53",
            "actor_type": "user",
            "actor_name": "bret.mogilefsky@gsa.gov",
            "actor_username": "bret.mogilefsky@gsa.gov",
            "actee": "5c21d6b3-0540-408a-90df-8c55d6a0d062",
            "actee_type": "user",
            "actee_name": "holly.allen@gsa.gov",
            "timestamp": "2017-03-16T17:15:37Z",
            "metadata": {
               "request": null
            },
            "space_guid": "7fc37305-9421-4c8a-b7d7-addbd2a2d910",
            "organization_guid": "70a1c8e4-6555-44ff-9ed0-57711c90104f"
         }
      },
      {
         "metadata": {
            "guid": "2c76428c-b1d8-4356-ad48-471ea1acf314",
            "url": "/v2/events/2c76428c-b1d8-4356-ad48-471ea1acf314",
            "created_at": "2017-03-16T17:15:43Z",
            "updated_at": "2017-03-16T17:15:43Z"
         },
         "entity": {
            "type": "audit.user.space_developer_remove",
            "actor": "ec3aac6c-5f56-4a92-8958-a96944795b53",
            "actor_type": "user",
            "actor_name": "bret.mogilefsky@gsa.gov",
            "actor_username": "bret.mogilefsky@gsa.gov",
            "actee": "5c21d6b3-0540-408a-90df-8c55d6a0d062",
            "actee_type": "user",
            "actee_name": "holly.allen@gsa.gov",
            "timestamp": "2017-03-16T17:15:43Z",
            "metadata": {
               "request": null
            },
            "space_guid": "7fc37305-9421-4c8a-b7d7-addbd2a2d910",
            "organization_guid": "70a1c8e4-6555-44ff-9ed0-57711c90104f"
         }
      }
   ]
}
```

My thought is that this is sufficient to enable both manual inspection and automated testing, which is kind of ideal for compliance purposes. It also facilitates export/presentation of a log with judicious application of `jq`, like so:

```bash
~ cf curl "/v2/spaces/7fc37305-9421-4c8a-b7d7-addbd2a2d910/events?q=type+IN+audit.user.space_developer_add,audit.user.space_developer_remove,audit.user.space_auditor_add,audit.user.space_auditor_remove,audit.user.space_manager_add,audit.user.space_manager_remove" -X GET  | jq -c -r '.resources[] | [ .entity.timestamp, .entity.type, .entity.actee_name ] | @csv' | sed -e s/\"//g
2017-03-16T17:15:37Z,audit.user.space_developer_add,holly.allen@gsa.gov
2017-03-16T17:15:43Z,audit.user.space_developer_remove,holly.allen@gsa.gov
```

So: Given that, is it enough to satisfy the compliance requirement you're hearing? If not, how critical to getting an ATO is it that we do work on the platform side to expose this same data via a dashboard?

**Comment by thecapacity** [comment]
I love the idea of using the same source of "truth" (i.e. operational APIs) to support both automated and manual testing!

@mogul can you say more about where the user data is pulled from? i.e. are these "entities" / actors IAM users? And would this `cf ...` query catch users that were created via the AWS IAM console (i.e. potentially outside the CloudFoundary PaaS environment)?

**Comment by mogul** [comment]
@thecapacity This is specifically to satisfy compliance needs for applications running on cloud.gov, and the data is specifically limited to Cloud Foundry roles. The data comes from the Cloud Foundry components, not AWS, because they don't have anything to do with AWS.

Anything having to do with AWS is "below the surface" in that the compliance aspects that are handled by cloud.gov. IAM roles are involved either in how we deploy the platform or in how our brokers set up back-end services, but are never directly in control of customers.

**Comment by mogul** [comment]
(The cloud.gov operations team do have automated checks to alert us if unexpected IAM roles appear in the AWS account housing cloud.gov, and there's a quarterly manual inspection to look for anomalies there and in other areas as well.)

**Comment by mogul** [comment]
@hollyallen is this sufficient for now? If so we'll close this.

**Comment by hollyallen** [comment]
Yes, thank you Bret.
