### ISSUE TITLE
Kibana filtering for APP Unique ID

### ISSUE THREAD

**Issue by hollyallen** [18F/cg-product#728]
To ensure the test-ability of SSP control narratives for systems on cloud.gov, I'm requesting the following feature.

A kibana filtering command to show that logs exist for a particular APP Unique ID. This is needed because SSP testers are given Org Auditor roles in cloud.gov, and the kibana interface makes it hard to find the logs for a particular app.

**Comment by brittag** [comment]
As additional context for when we study this story: this sounds like it would also be helpful for the dashboard! It would allow dashboard app pages to link directly to the logs for the app you're looking at. Currently the dashboard app page links to the general logs site, so the reader has to dig a bit to find the logs they want. cc @adborden / @msecret

**Comment by cnelson** [comment]
To search by app id you can enter the following query: `@cf.app_id:":app-guid:"`

If you prefer the more human friendly org/space/app name identifiers you can query for those as well; for example: `@cf.org:"cloud-gov" AND @cf.space:"test" AND @cf.app:"wstest"`

Both of these queries are used by putting them into the search box at the top of the kibana interface:

<img width="924" alt="screen shot 2017-03-15 at 06 13 10" src="https://cloud.githubusercontent.com/assets/604163/23949957/903c2cf6-0946-11e7-9a8e-f19290de4c17.png">

**Comment by adborden** [comment]
Most apps use some form of blue/green deploy, so the app guid will actually change on every deploy. Just want to make sure that's not an issue for this use case, otherwise, I would suggest using org/space/app name to uniquely identify an app.

**Comment by hollyallen** [comment]
Good catch @adborden . app name would be lovely.

**Comment by mogul** [comment]
Going to close this one as addressed. Thanks for asking, Holly!
