### ISSUE TITLE
Updates we send to our users are visible in cloud.gov/updates

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#73]
cloud.gov/updates is fed from our Discourse topics, and clicking to comment on the update goes back to the Discourse thread.

**Comment by suprenant** [comment]
Closing this up – thinking @berndverst and team are on this already.

**Comment by mogul** [comment]
Reopening in `SkyPorter` backlog for consideration as discuss opening community. (@berndverst let me know if the intent of this one is not clear.)
