### ISSUE TITLE
We can notify users with roles on a space about specific events

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#76]
Eg you're hitting quota, your app is crashing a lot, your app is scaled too high for the traffic it's getting, etc. (This is expected to involve the [cloudfoundry notifications](https://github.com/cloudfoundry-incubator/notifications) incubation project.)

**Comment by suprenant** [comment]
We're starting to validate interest in notifications for hitting quotas during our current round of PM interviews: https://drive.google.com/drive/u/0/folders/0B_a71ksF1BfnVEQtVEc1OEktY3M

**Comment by mogul** [comment]
Did you mean to close this one, rather than just put it in the `Icebox`?

**Comment by suprenant** [comment]
Must of, or thought it was a duplicate. Thanks for the catch – opening this back up.
