### ISSUE TITLE
Streamline new user provisioning

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#77]
What we're after: Sand the rough edges off of the new-user experience and user provisioning

Benefits/why:
- Reduce team overhead due to onboarding and support on both the SkyPorter and Liberator side

**Comment by brittag** [comment]
This would be closely related to making a walkthrough - https://github.com/18F/cg-product/issues/80 - they'd be good to work on together, since we'd find issues with new user onboarding while making a walkthrough.
