### ISSUE TITLE
.gov/.mil/.fed.us users can self-provision accounts

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#78]
In order to make sign-up for cloud.gov accounts as easy as possible, users with .gov, .mil, and .fed.us addresses can generate their own invitation.

**Acceptance Criteria**

- [x] There's an unauthenticated form where entering any federal .gov, .mil, or .fed.us e-mail address will generate an invitation
- [x] If an entered address doesn't match the requirements, then the user is politely informed that cloud.gov is only available for people with federal addresses
- [x] Direct people from states to the intake form because we're interested in knowing about their use-cases to help drive the bureaucracy hacking (talk to SkyPorter about language here)
- [x] Direct others to the "[managing teammates](https://cloud.gov/docs/apps/managing-teammates/)" docs  and make sure it's clear that a legit user can invite them in.
- [ ] Any "create account" link on login.fr.cloud.gov points to this form.

**Implementation Sketch**

- See if we can leverage work done for Pulse to whitelist only federal domains, otherwise blacklist [state-abbreviation].gov

**Comment by nikzei** [comment]
cc: [@James Hupp - TEACD]

**Comment by rememberlenny** [comment]
[@Michael Kendall - TEAAB] completed the acceptance criteria. Waiting on Skyporter tasks. Moving into Awaiting Acceptance to clear up the WIP limit.

**Comment by mogul** [comment]
[@Lenny Bogdonoff] What's needed for this to be done, then? Just language from SkyPorter for what people see on screen?

**Comment by rememberlenny** [comment]
[@Bret Mogilefsky - TEABA] Yep- [@Michael Kendall - TEAAB] would be best here.

**Comment by nikzei** [comment]
I think we resolved this in Slack earlier today, no? see: https://gsa-tts.slack.com/archives/cloud-gov-atlas/p1486567358008363. I gave a quick content review and https://github.com/18F/cg-uaa-extras/pull/72 has since been merged.

**Comment by mogul** [comment]
Hi all, reports this morning are that `gpo.gov` and `blm.gov` addresses aren't being accepted. Can we figure out if those should be included in the whitelist, and how they might have missed the boat?

**Comment by brittag** [comment]
As an update - it looks like the app wasn't accepting any email address as a valid federal email address earlier today. Restarting the app seemed to resolve this issue for now. :)

**Comment by nikzei** [comment]
Seems like we have one AC left unchecked. Does anyone have an update/ any blockers to raise?

**Comment by mogul** [comment]
Hmmmm... The link to create an account was removed from the template back when we removed the vestigial login form. How hard is it to put back in the template, @rememberlenny ?

**Comment by rememberlenny** [comment]
@mogul Not hard at all. I'll add a card in Favro for this.
