### ISSUE TITLE
Give deployer credentials a longer life than user credentials

### ISSUE THREAD

**Issue by konklone** [18F/cg-product#790]
Cloud.gov credentials for users now expire after a few days. I'm also getting this with my deployer credentials as well, though, and I don't think that's as desired or useful.

I have two examples of using deployer credentials where a few days is problematic:

1. A cronjob that runs every few days that deploys at the end. Most of the time, the interval is within the expiration timeline, but sometimes it's not, and so we have to rotate creds.
2. A Travis CI builder that deploys a static site to cloud.gov in response to merged pull requests on GitHub. 

For `1.`, we can potentially use a separate cronjob that just refreshes the credentials by hitting any endpoint. But for `2.`, that wouldn't work without separate infrastructure just for that.

In any case, it seems silly to do that for deployer credentials. These are scoped, rotatable, revocable, etc., and don't pose the same risk that more unconstrained user-level credentials do.

Can we look at making those deployer credentials not expire?

**Comment by brittag** [comment]
In case others are interested in this as well, copying over a few notes from internal conversations:

Currently, service account passwords expire every 90 days (https://cloud.gov/docs/services/cloud-gov-service-account/#handling-expired-passwords). This expiration period is driven by the old NIST password standard as encoded in the FedRAMP requirements.

FedRAMP announced how we can shift to the new NIST password standards, so we'll be figuring out how the new requirements apply to deployer credentials and following this process: https://www.fedramp.gov/assets/resources/documents/CSP_Digital_Identity_Requirements.pdf
