### ISSUE TITLE
Note for curious issue observers - most of these issues are outdated

### ISSUE THREAD

**Issue by brittag** [18F/cg-product#830]
This is just a meta-note for people looking at this repository - as you can observe from the lack of new issues and updates to old issues here, we still use this repository for documentation, but no longer use these public GitHub issues as our primary issue tracker.

Please do feel free to file issues here though! We're happy to read issues filed on any open source repo that we maintain.

**Comment by mogul** [comment]
Not the case anymore... We're moving our processes back into GitHub (and ZenHub)!
