### ISSUE TITLE
Assets for cloud.gov stickers

### ISSUE THREAD

**Issue by pburkholder** [18F/cg-product#832]
![image](https://user-images.githubusercontent.com/1211146/37622201-72af1972-2b97-11e8-89cb-ee1aee8b67c6.png)

**Comment by pburkholder** [comment]
I was going to close this, but maybe keep open for new sticker orders?

**Comment by mogul** [comment]
The asset should probably just get added to the repo as a file.

**Comment by pburkholder** [comment]
Closing in favor of #1054
