### ISSUE TITLE
Improve value-proposition communication

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#85]
What we're after: People arrive in threads and meetings with our bizdev folks having a much better idea what cloud.gov is/does

Benefits/why:
-  Reduce wasted effort/time for both prospective customers and people on the team

We need compact ways to communicate what a PaaS is to people who only know the word "cloud", and what it can do for them; why they should be interested in this model for deployment/hosting rather than raw IaaS.

Examples:
- See "stack responsibility" images, eg the " [Pizza-as-a-Service](https://www.linkedin.com/pulse/20140730172610-9679881-pizza-as-a-service)" image. See also the AppFog, Pivotal Web Services, and IBM BlueMix sites.
- See also the  [list of controls that are abstracted behind cloud.gov vs left to the app](https://docs.google.com/spreadsheets/d/1EYLuavFgLUvfHDiBOuFjJsjpKQFDwXZx6J6gTffegUM/edit?ts=5733adb1#gid=0)

**Comment by brittag** [comment]
This could include:

* Revising the homepage of https://cloud.gov/ based on what we've learned so far about what people need (and getting into a habit of checking that content and iterating on it pretty frequently).
* Revising the homepage of https://docs.cloud.gov/ and the first page of the docs (https://docs.cloud.gov/intro/overview/what-is-cloudgov/).
* Making a two-page printable intro doc that answers the basics of what CIOs need to know.
* Probably a little bit of content testing - asking a few people interested in cloud.gov to screenshare with us and talk through the current site with them.

**Comment by brittag** [comment]
This also partially depends on https://github.com/18F/cg-product/issues/63 (Guidance for getting ATO with cloud.gov) - that guidance will be an important part of communicating our value proposition.

**Comment by suprenant** [comment]
This mostly seems to contain SkyPorter items, so added that label and pulled Liberator for now to make our sprint planning clearer.

**Comment by mogul** [comment]
Yeah, this predates SkyPorter taking ownership of this.

On Tue, Sep 27, 2016 at 11:36 AM, Andrew Suprenant <notifications@github.com

**Comment by nikzei** [comment]
@berndverst @dlapiduz and I have been refining our value proposition - particularly to more clearly communicate the things this ~~"Pizza as a Service"~~ Platform as a Service offers and what it doesn't.

I have a meeting with Andre from outreach on 10/19 to discuss how we want them to pitch cloud.gov. Let's have conversations beforehand - I'll schedule something for early next week.

**Comment by nikzei** [comment]
this is what we are working on in #346 so I am closing this.
