### ISSUE TITLE
Competition (closed): Customer broker example

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#876]
cloud.gov is running [a micro-purchase competition](https://github.com/18F/cg-product/tree/master/micro-purchases) via this issue to select a vendor to implement an [example of deploying a customer-operated broker](https://github.com/18F/cg-product/blob/master/helpwanted/CustomBrokerDemo.md) in Cloud Foundry. 

_Note that this is the first in a [series of competitions](https://github.com/18F/cg-product/issues/857) that cloud.gov intends to run. We are experimenting with this format as we go along, and ask for your patience with any hiccups as well as your suggestions to make this process better._

Please review the description as it stands. If you have suggestions that you think would result in the work being easier to deliver, or that would give us better results, open pull-requests that tag this issue before bidding opens and they'll be reviewed and potentially merged.

Current schedule:
- **Bidding opens** on **Friday, December 21st, at noon ET** when the words "coming soon" are replaced with "open" in this issue's title.  Any bids preceding that date will be ignored.
- **[Eligible vendors](https://github.com/18F/cg-product/tree/master/micro-purchases#eligibility-to-bid) bid** by posting to this issue. Vendors should include the amount they will charge for the work, and any evidence that will help us assess the risk of picking their bid. For example, a bidder may include a pointer to previously published work they completed which demonstrates they have the background skills and knowledge to tackle this work. **Note that bids exceeding $10000 are above the federal micro-purchase threshold, and will be ignored.**
- **Bidding closes** on **Friday, December 21st, at 6pm ET** when the word "open" is replaced with "closed" in this issue's title. The winner will be selected by the person who initiated the competition based on the best perceived combination of price and perceived risk, where evidence provided with the bid will be used to help assess risk. The bidder will be announced via a post to this issue.
- **The work is delivered.** Since this competition is being run close to the end of the year and we don't want vendors stressing out about this work through the holidays, we're setting **the delivery start date as 12AM on January 2nd, 2019**. The delivery period is one month, and **the delivery due date is 12AM on February 2nd, 2019**.

If you have any questions about the process, please post them here prior to the start of bidding!

**Comment by mogul** [comment]
First hiccup encountered: I have no idea how many people are viewing/subscribed to this issue, so have no idea how much wider I should advertise this competition before bidding opens on Friday...! 
So:

- If you're watching to see how this turns out, please add a 😆 to this post.
- If you're thinking about bidding, please add a 👍 to this post.

**Comment by spgreenberg** [comment]
@mogul is there any conflict between the upcoming RFP and responding to/delivering this micro-purchase?

**Comment by mogul** [comment]
@spgreenberg nope, there's no conflict.

**Comment by mogul** [comment]
@spgreenberg and @stevewallone, are you both [eligible bidders](https://github.com/18F/cg-product/tree/master/micro-purchases#eligibility-to-bid), or able to be? If not, I may delay the bidding window and do more publicity... I want at least two eligible bids, if possible.

**Comment by spgreenberg** [comment]
@mogul we are working together on this.  so 1 bid.  but eligible, yes.

**Comment by mogul** [comment]
Bidding is now open... Let's do this!

**Comment by spgreenberg** [comment]
@mogul You have been invited to a git repo containing our response.  Let me know if you do not see the invite.

**Comment by mogul** [comment]
The competition is now closed, and I'm reviewing the single bid from @spgreenberg and @stevewallone, which looks totally valid. This makes you the winners! I'll be in contact with the two of you via the Cloud Foundry Slack to arrange a meeting to discuss the work in more detail.

**Comment by mogul** [comment]
For everyone following this issue: How about a quick round of feedback on how this first micro-purchase competition went? Please post listing:

- What you think went well
- What you think should be improved for the next one

**Comment by spgreenberg** [comment]
I like the format and quickness with which these are executed. The notes and user stories/acceptance section were quite helpful and well written. I like that the notes are essentially suggestions, allowing for some creativity in approach.

The challenge is scope (which of course impacts price). It would help to know more about the persona you are targeting with the story and also the bounds of the deliverable. For example: are we targeting tenants familiar with CF, the open service broker concepts (perhaps API), and services already available in the marketplace? Or are we targeting a tenant that has yet to encounter these capabilities because they assume the services their portfolio requires aren't available and therefore haven't even tried CF in a meaningful way?

Given these are small by nature, it doesn't make sense to go overboard in the detail. I also wouldn't want to stifle creativity of submitters in solving the issue.  Overall, I think it went well for the first one.

**Comment by afeld** [comment]
Would love to see more bidders (no judgement on the current ones!) Wonder if it's a matter of getting the word out more broadly, or giving new gov vendors more time so they can register?

**Comment by mogul** [comment]
For anyone who was interested in the outcome of this competition: The work was delivered and is visible in https://github.com/18F/cf-byo-broker . We ended up leaving out the Azure OSBAPI example, but the repo is laid out with the expectation of that and other broker examples being added over time.

There are some nice-to-have things we didn't get to (eg automating the GCP setup with Terraform) but these can happen in future, potentially as other micropurchases. Thanks for all your work, @spgreenberg and @stevewallone !

**Comment by mogul** [comment]
Also of note: We specified that the text be generally Cloud Foundry agnostic, and we'll be moving it into the cloudfoundry-community, then forking it back into the 18F org. Note the permission CC0 license. Your pull-requests welcome, and open source ftw!
