### ISSUE TITLE
Enable functions, procedures, and triggers in AWS Labs' MySQL broker

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#892]
**Story**: In order to enable functions, procedures, and triggers for customers using MySQL backed by RDS, we want to modify [the AWS Labs broker](https://github.com/awslabs/aws-servicebroker/tree/master/templates/rdsmysql) to include an option that will [add `log_bin_trust_function_creators=1` to the DB parameter group used to provision the DB]( https://aws.amazon.com/premiumsupport/knowledge-center/rds-mysql-functions/) when users run `cf create-service` or `cf update-service`.

**Acceptance Criteria**

 * GIVEN I am logged into `cfdev` with the AWS Labs broker installed \
  AND I [create a MySQL instance](https://github.com/awslabs/aws-servicebroker/tree/master/templates/rdsmysql) using the command `cf create-service _servicename_ production my-mysql-service
-c '{"enable_functions": "true"}' ` \
  AND I [connect to that MySQL instance using the `cf-service-connect` plugin](https://github.com/18F/cf-service-connect) \
  WHEN I run `create function hello(id INT)` \
    `-> returns CHAR(50)` \
    `-> return 'foobar';` \
  THEN I see `Query OK`
* GIVEN I am logged into `cfdev` with the AWS Labs broker installed \
  AND I [create a MySQL instance](https://github.com/awslabs/aws-servicebroker/tree/master/templates/rdsmysql) using the command `cf create-service _servicename_ production my-mysql-service` \
AND I run the command `cf update-service my-mysql-service -c '{"enable_functions": "true"}' ` \
  AND I [connect to that MySQL instance using the `cf-service-connect` plugin](https://github.com/18F/cf-service-connect) \
  WHEN I run `create function hello(id INT)` \
    `-> returns CHAR(50)` \
    `-> return 'foobar';` \
  THEN I see `Query OK`

**Comment by timothy-spencer** [comment]
https://github.com/timothy-spencer/aws-broker/tree/tspencer/enablefunctions

Have one issue left to fix with this, but it is mostly done.

**Comment by timothy-spencer** [comment]
https://github.com/18F/aws-broker/pull/48

One question:  Would you like me to create another PR to enable the feature, or leave that to you?  I kind of assumed you would want to do some independent testing, so didn't enable any of the functionality by default, but I realized that if you wanted this to be a largely zero-effort thing on your part, you might want the concourse/deployment aspect addressed too.

**Comment by mogul** [comment]
For anyone following: We chose to [enable this functionality in our existing broker](https://github.com/18F/aws-broker/pull/48) instead; that was a shorter road for us, compliance-wise, even though we're still looking to move to the awslabs broker in future.
