### ISSUE TITLE
"Stratos" is an implementation detail

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#908]
## Acceptance Criteria
- [ ] WHEN I look at dashboard.fr.cloud.gov, THEN I don't see words or images that say "Stratos"

## Implementation sketch
[Customization pointers](https://gsa-tts.slack.com/archives/C4XLJ1JBV/p1550686993008500?thread_ts=1550685676.000700&cid=C4XLJ1JBV)

**Comment by hillaryj** [comment]
Duplicate of #906
