### ISSUE TITLE
Remediate out of date DB in the platform

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#921]
In order to keep up with our ConMon obligations, we need the DB instances used in cloud.gov to be upgraded to supported and secure versions.

## Acceptance Criteria
- [ ] WHEN I check the daily Nessus findings report THEN I see that there are no findings referring to an out-of-date DB.
- [ ] WHEN I check the operator docs in the cloud.gov website, THEN I see a runbook document for "Upgrading RDS instances".

**Comment by karareinsel** [comment]
@RonWilliams this appears to be compliance related. Can you take a look and advise on prioritization?

**Comment by karareinsel** [comment]
Closing - vulnerabilities are not showing up in the DB reports.
