### ISSUE TITLE
 Change remote for 18F/oauth2_proxy to something that's actually maintained

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#922]
In order to ensure our OAuth2 proxy is secure and supported, we should leverage a supported and maintained project.

In 18F/oauh2-proxy-boshrelease we're using 18F/oauth2_proxy, which is a fork of bitly/oauth2_proxy. Bitly has since archived this repo, so no further development is happening on it.

We should start using something officially supported - either by just switching remotes on 18F/oauth2_proxy, or by getting the work from 18F/oauth2_proxy integrated into a maintained repo and abandoning our fork.

**Comment by steakunderscore** [comment]
The custodian of oauth2_proxy project has been shifted from [bitly] to [pusher]. Pusher and other open source contributors are actively maintaining this fork. It even now supports [login.gov] as a provider, which I'm guessing might be of interest here.

[bitly]: https://github.com/bitly/oauth2_proxy
[pusher]: https://github.com/pusher/oauth2_proxy
[login.gov]: https://github.com/pusher/oauth2_proxy/blob/master/docs/2_auth.md#logingov-provider

**Comment by karareinsel** [comment]
Recommend time-boxing 2 hours (max) of research to determine level of effort.

**Comment by karareinsel** [comment]
Current solution works but if it stops working it'll become very urgent. Getting the research done soon is necessary.

**Comment by karareinsel** [comment]
@hillaryj will update issue to reflect that it's a time-boxed research issue to start.

**Comment by bengerman13** [comment]
We're currently ahead of the bitly repo by one commit, and behind by several.
The commits we're behind don't matter - they're all README updates about archiving the repo.
The commit we're ahead is mostly concerned with adding several security-related headers.

Looking through the forks of the bitly repo, the most-maintained seems to be OpenShift, but it's maintenance is all about making it *only* work with openshift. AFAICT, the only other maintained fork is the Pusher fork mentioned above.

Looking at the commits we are ahead of the Bitly fork, I think our best option is one of:
- fork pusher, patch to add in the functionality we'd added to bitly, and open a PR with pusher
- use pusher unpatched, and add the missing functionality via nginx or some other reverse-proxy layer

**Comment by bengerman13** [comment]
Nginx won't work very well for logsearch-platform, so I think forking pusher and adding functionality there is better
