### ISSUE TITLE
[research: X days] Figure our easiest path to making k8s stemcells updates trivial

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#923]
In order to make K8S stemcell updates sustainable and learnable, we need to learn from Jon's experiences leading the updates for the K8S stemcells that are time sensitive for 7/24 (for compliance deadline reasons).

This card is a placeholder for the work to actually figure out how to put those ideas and work into practice.

**Comment by karareinsel** [comment]
This is being replaced by the goal to replace Kubernedes but the work is TBD.
