### ISSUE TITLE
Service accounts should use client credentials instead of users

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#932]
In order to migrate from Shibboleth, existing service accounts which use user constructs need to be migrated to [client credentials](https://oauth.net/2/grant-types/client-credentials/) constructs. 

Verify client credentials can perform the same actions as users within CloudFoundry.
Research any upstream configurations that would prevent use of UAA client constructs.

### Acceptance Criteria
1. The user account constructs are migrated to client credential constructs. 
2. Ensure the service broker provisions client credentials instead of users.

**Comment by hillaryj** [comment]
These credentials exist mostly in two places:

- UAA service account broker
- Hand-created credentials - discovery work

**Comment by karareinsel** [comment]
Recommend closing this issue once new issues are created for the following.
Story 1: Verify client credentials can perform the same actions as users within CloudFoundry.
Story 2: Research any upstream configurations that would prevent use of UAA client constructs.
Story 3: Implement the behavior of the broker to provision client credentials.
Story 4: Replace/update user accounts with client credentials.
