### ISSUE TITLE
Rotate credentials using [CredHub|Vault]

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#944]
As operators we want [CredHub|Vault] to be able to regenerate any internal usernames and passwords so we don't have to generate and rotate those credentials by hand.

## Acceptance Criteria
- [ ] We can successfully rotate credentials using [CredHub|Vault]

**Comment by bengerman13** [comment]
@mxplusb can this be closed as a duplicate of your other CH work?

**Comment by mxplusb** [comment]
I'm doing the necessary requirements to make this a reality, so I would say this is the acceptance criteria for the other work I'm doing.

**Comment by mxplusb** [comment]
Okay, I think Credhub won, so closing this since a decision has been reached and we've successfully rotated credentials multiple times.
