### ISSUE TITLE
Make sure Zendesk is sending emails consistently and successfully to customers [waiting for Zendesk update]

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#948]
In order to ensure customers receive reply mail from cloud-gov-support@gsa.gov, we need to get SPF and DKIM/DMARC records in GSA's DNS system which will prevent customer SMTP agents from silently dropping our mails.

To test this:
Go to https://cloud-gov.zendesk.com/agent/admin/email
Click "SPF does not include Zendesk Support"
See if it still says "This will soon be replaced by the DNS records. During the transition period you should set up both sets of records."

---
See also: 
https://support.zendesk.com/hc/en-us/articles/203683886-SPF-Learn-More
https://support.zendesk.com/hc/en-us/articles/203663326-Digitally-signing-your-email-with-DKIM-or-DMARC

We can test that the change was made successfully here (our instance name is cloud-gov.zendesk.com):
https://support.zendesk.com/hc/en-us/articles/360000371588

**Comment by hillaryj** [comment]
There's some additional info in this 🔒[support processes flow diagram](https://docs.google.com/drawings/d/1x12SuZsyqhRutuhRpl8CN3jmIQ0bPy_IMJxsft55hZw/edit) as notes.

**Comment by hillaryj** [comment]
Got back to this and emailed GSA email folks about next steps.

**Comment by karareinsel** [comment]
@hillaryj will write up next steps (and create issues) and close out this story.

**Comment by hillaryj** [comment]
Closing in favor of #1127
