### ISSUE TITLE
Create compiled builds for plugins

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#949]
There was an issue bubbled up from David Corwin about customers struggling with the plugins. We should provide xplat builds so consumers can just install the binaries while we figure out the proper way to publish them.

---
CLI plugins that need signing:
- Service Connect: https://github.com/18F/cf-service-connect
- Multi-CUPS: https://github.com/18F/cf-multi-cups-plugin

- [CAP request](https://cap.18f.gov/proposals/7877)

Status: Still waiting on validation from digicert. The GSA case number for calling is `02256360`.
![digicert.png](https://images.zenhubusercontent.com/57045ffe6caf56c9d38f5e4c/6b697bfa-b9dc-4e1c-8bd4-072748139374)

**Comment by brittag** [comment]
Steps for Eddie:

1. [Log into GCIMS](https://insite.gsa.gov/employee-resources/information-technology/do-it-yourself-self-help/update-your-gsa-contact-information) (need to be on VPN and with PIV card) and enable the option to display your work number in the public GSA directory.
2. Schedule a call using the booking URL [in this email thread](https://groups.google.com/a/gsa.gov/forum/#!topic/cloud-gov-operations/Zi8Wo0Q0vRI) (put in the order number from our email subject line) and put in instructions that they should ask the GSA customer service representative to look you up in the GSA public directory and transfer Digicert to your number.

**Comment by mxplusb** [comment]
Eddie: bit of a detour, phone number issues still, predicts some other hurdle.

**Comment by brittag** [comment]
Certificate obtained! Next step is to try it.

**Comment by mxplusb** [comment]
![image](https://user-images.githubusercontent.com/7537841/63127815-97785980-bf70-11e9-9a8d-0fbd5d4bfe0e.png)

Still have to go through and upload signed binaries, but we're getting there.
