### ISSUE TITLE
Customer success story: FDIC 

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#954]
In order to help prospective customers understand the value of cloud.gov, we want to publish a customer case study about the customer in the subject.

## Acceptance Criteria
- [ ] The writing lab has reviewed this piece of content (context: this is a request from Outreach to get it reviewed by the writing lab before we publish it - the issue is at  https://github.com/18F/writing-lab/issues/435)
- [ ] WHEN a prospective user is browsing the site OR asks for case studies THEN they see a customer-case-study about this customer.

---

[FDIC Success Story - first draft](https://docs.google.com/document/d/1XzuxjKA0sK86OcAraV9O1t9bq6ptIrsq4800WoTqd_4/edit)

[FDIC Interview Notes](https://docs.google.com/document/d/1-lKShAMbEUfNEKZa5QcrBiIt_EIqCYS_E8iBU00jGHA/edit)

[FDIC monthly meeting notes](https://docs.google.com/document/d/1cpQrUCTMIluG0oe-w0YpqEQf9eUc3UnVUSLYZjmo2nk/edit#)

## Implementation sketch
- [x] Set up an interview
- [x] Interviewing the customer
- [x] Drafting the case-study
- [ ] Revise case-study based on customer input (plain language, less "marketing" style)
- [ ] Get #writing-lab to take a look (https://github.com/18F/writing-lab/issues/435)
- [ ] Review with customer again to get sign-off on the content (Britta can help coordinate sending it to the right stakeholders)
- [ ] Convert to PDF (based on previously-used template), publish on the site
- [ ] Publicize the availability of the new case-study
- [ ] Create a summary slide for use in BD or internal stakeholder presentations

**Comment by eddietejeda** [comment]
Is Abbey working on this or Jessyka?

**Comment by mogul** [comment]
Your guess is as good as mine! I just copied the card from the Trello board
with the title intact.

**Comment by brittag** [comment]
Context on current stage: FDIC thinks the current draft is too "marketingy". We need to revise it and review it with the customer again.

**Comment by mxplusb** [comment]
Bryant: rewriting FDIC doc as they weren't happy with it.

**Comment by Bryanthales** [comment]
Updated draft shared with @jessykacastillo. We will now choose to either wait for Britta review upon return or share directly with FDIC now for review/approval.

**Comment by brittag** [comment]
We emailed FDIC the draft.

**Comment by karareinsel** [comment]
@Bryanthales has FDIC gotten back to us with feedback? Is this done?

**Comment by Bryanthales** [comment]
@karareinsel @jessykacastillo 
I have seen no response from FDIC on this. I know that Jessyka, Eddie, and Ron are planning to meet with them on either Tuesday, Oct. 29 or Thursday Oct. 31 so I would assume that this may be covered at that time.

**Comment by karareinsel** [comment]
@eddietejeda @jessykacastillo @RonWilliams will this blog post be discussed with FDIC at your meeting with them? We're waiting on their feedback.

**Comment by jessykacastillo** [comment]
I mentioned it on the call. Put it at the top of Ramzi's inbox today. He said he will get back to us.

**Comment by karareinsel** [comment]
@jessykacastillo @eddietejeda since you're meeting with FDIC today, could you ask them about the blog post?

**Comment by karareinsel** [comment]
@jessykacastillo followed up with Ramzi today (11/7).

**Comment by karareinsel** [comment]
@karareinsel and @jessykacastillo will review and decide on next steps.

**Comment by karareinsel** [comment]
Closing this issue. A new, fresh blog post will be created leveraging the FDIC quotes.
