### ISSUE TITLE
Customer success story: EPA

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#955]
In order to help prospective customers understand the value of cloud.gov, we want to publish a customer case study about the customer in the subject.

## Acceptance Criteria
- [ ] WHEN a prospective user is browsing the site OR asks for case studies THEN they see a customer-case-study about this customer.

---
[EPA draft v2 (with EPA edits)](https://docs.google.com/document/d/1WIVGl22Oybbj46Z5EKAoA9LMz5tSMr3nTMiUH53nnaY/edit#)

[EPA case study - drafted interview notes](https://docs.google.com/document/d/1mRZX-Mf4yIH-VjGUql--KPzvX_uTtC0efgGZhBLbpR0/edit?ts=5cbdee54)

## Implementation Sketch
- [x] Interviewing the customer
- [x] Drafting the case-study
- [x] Get #writing-lab attention on it
- [ ] Get customer sign-off on the content
- [ ] Convert to PDF (based on previously-used template), publish on the site
- [ ] Publicize the availability of the new case-study
- [ ] Create a summary slide for use in BD or internal stakeholder presentations

**Comment by karareinsel** [comment]
@Bryanthales what is the latest on this? Have we heard back from EPA?

**Comment by Bryanthales** [comment]
@karareinsel At last check EPA had not reviewed it. @jessykacastillo met with EPA ~2 weeks ago but it was determined during the call that covering this success story right then was not appropriate. Plan at the time was to reengage after FY. I will defer to Jessyka on when is the appropriate time to try and get review and approval from EPA.

**Comment by karareinsel** [comment]
@jessykacastillo now that we're in the new FY, do you have a sense of when would be the best time to publish the blog post?

**Comment by karareinsel** [comment]
@jessykacastillo working to get EPA's approval to publish by Friday, 11/15.

**Comment by karareinsel** [comment]
Hoping to have EPA's approval today. cc @jessykacastillo

**Comment by karareinsel** [comment]
@karareinsel and @jessykacastillo will review and decide next steps.

**Comment by karareinsel** [comment]
@jessykacastillo and @karareinsel and Gary Hall (ELP) to finalize edits and have Gary carry it across the finish line in early January 2020.

**Comment by karareinsel** [comment]
@karareinsel and @jessykacastillo to discuss with @eddietejeda on priority - can this blog post be replaced with a list of cloud.gov that highlights how agencies are using cloud.gov (as we discussed the week of Jan. 13 when you were in DC)?

**Comment by karareinsel** [comment]
Pivoting to a list of how agencies are using cloud.gov. Will follow up with the 18F team.
