### ISSUE TITLE
Research [2 days]: Identify marketing material needs for internal GSA (CIC, ITC, CASE)

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#960]
In order to provide the right marketing materials to our internal GSA partners (Cloud Information Center, ITC, CASE), we need to understand their needs and make a plan for _what_ to provide to them and _what we need to update_ before shipping the updated materials to them.

Acceptance criteria:

- [ ] We have a brief description of what CIC needs
- [ ] We have a brief description of what ITC needs
- [ ] We have a brief description of what CASE needs

Implementation sketch:

* Meet with CASE 
* Meet with ITC

------
slick sheets, decks, etc as needed... 

---

- [cloud.gov strategic positioning](https://docs.google.com/document/d/1YwhIhMRKt3_ZDUw3lvkH61_3iKpZ8YCISE-396JlyIE/edit?usp=sharing) 
- [talking points ](https://docs.google.com/document/d/1eUqPRoFdoo8g4mH7s1KfcTgvmlmAnnctJdut9LN61YA/edit?usp=sharing)
- [briefing memo](https://docs.google.com/document/d/1tukevSXuBFlQEu8anNjJOCKXDr2T8pKNrw0byfX2mz4/edit?usp=sharing)

**Comment by brittag** [comment]
We're considering this card obsolete.
