### ISSUE TITLE
ALB/ELB logs into Logsearch

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#961]
Get ALB and ELB logs into Elasticsearch/logsearch

## Checklist
- [x] ALB and ELB instances sending logs to S3
- [ ] ALB and ELB logs from S3 into Logsearch

**Comment by mxplusb** [comment]
Left a review on 18f/cg-elb-log-ingestor#1

**Comment by bengerman13** [comment]
PRs open on:
18F/cg-elb-log-ingestor-boshrelease#1
18F/cg-elb-log-ingestor#2
