### ISSUE TITLE
Publish Carlo's blog post

### ISSUE THREAD

**Issue by eddietejeda** [18F/cg-product#979]
In order to keep cloud.gov top of mind with stakeholders, customers, and prospective customers, we want to occasionally publish blog posts with positive messaging about cloud.gov, such as a blog post by our former director Carlo about his experiences at 18F.

Carlo wrote about his time leading cloud.gov and shares valuable lessons: [draft](https://docs.google.com/document/d/1F7wNOQbaJZG8wS5w3MpWfMgik4XQY43xNUdEpygBP9Y/edit?ts=5d025d63).

Acceptance criteria:

- [ ] There's a blog post on the 18F blog
- [ ] There's a tweet on the 18F Twitter

Implementation sketch:

- [ ] Finalize draft in Google Doc
- [ ] Create issue at https://github.com/18F/blog-drafts to schedule publishing (which includes the right processes for comms/outreach review)
- [ ] Before publishing, review final content with Carlo just to make sure he's cool with it (Britta can do this with Carlo's personal email)

**Comment by karareinsel** [comment]
@eddietejeda has this been published? If so, let's close it out.

**Comment by eddietejeda** [comment]
It was never published. My suggestions were not accepted, but I am not sure how appropriate it is to publish it after so much time as passed. Thoughts?

**Comment by karareinsel** [comment]
Is the content still accurate/current? Does it still provide value? Would it be published under Carlo's name even though he has left?

**Comment by eddietejeda** [comment]
It's a goodbye and reflection about this time. Have a look and let me know what you think.

**Comment by karareinsel** [comment]
After reviewing the blog post, I agree that it's no longer appropriate to publish it since so much time has passed. Closing the issue.
