### ISSUE TITLE
Properly setup CredHub on Master BOSH to fix Tooling BOSH deployment

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#985]
Tooling BOSH is an undeployable state, because master bosh's CredHub isn't properly setup. It's missing some credentials, and we can't manually add or generate them because we don't have credentials to login the CredHub server. It was never properly setup.

## Implementation Sketch
We need to add credentials to the `master-bosh.yml` that correspond to the variables in the manifest and then add this to the `shell-pipeline.yml` in the Concourse deploy repo to be able to access things against the CLI. Once we do that we can further troubleshoot the issue and add the missing credentials that the Tooling BOSH deployment craves.

**Comment by mogul** [comment]
@bengerman13 I had a note on the original Trello card saying you'd already taken care of this... Is that right? If so go ahead and close this one!

**Comment by eddietejeda** [comment]
According to @jontours, this is done!
