### ISSUE TITLE
Merge isolation segment work

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#986]
In order to ensure our development environment is fully driven by code rather than hand-propped changes, we want to capture work in that environment that's not in the `isolation-segments` branch, then merge the branch so it's maintained.

## Acceptance criteria
- [ ] `deploy-cf-deployment` is green in `dev`
- [ ] isolation segment configuration is consistent across `dev`, `staging`, and `prod`
- [ ] Resolve smoke test failures
- [ ] Create documentation for support requests

## Next steps
- [ ] Update & resolve conflicts on PR: https://github.com/18F/cg-provision/pull/468
- [ ] Update & resolve conflicts on PR: https://github.com/18F/cg-deploy-cf/pull/366
- [ ] Check into status and details on isolation segment configuration per environment

**Comment by RonWilliams** [comment]
Consider tech talk on issue once resolved; may be relevant to other 18F, FDIC, and GSA folks.

**Comment by karareinsel** [comment]
Consult with @jontours to clarify the work that remains to be done and then prioritize.

**Comment by hillaryj** [comment]
Additional context is primarily in Github history and the checklist - Jon's leaving and doesn't have much more context.

Both of these PRs are open and need to be de-conflicted and (theoretically) merged:
- https://github.com/18F/cg-provision/pull/468
- https://github.com/18F/cg-deploy-cf/pull/366

**Comment by hillaryj** [comment]
Per @sharms:

> All of this was running successfully in `development` and would just need regex or yaml anchors for `staging` and `production`

Also somebody pointed `cf-development` back to master, that will need to be pointed back to the right branch

**Comment by mxplusb** [comment]
@eddietejeda is there an overwhelming amount of customer demand for isolation or VPN connectivity in cloud.gov? I'm asking because we as a team are not equipped to deliver this feature quickly nor sustain it over time, and the work required to do it is both time-consuming and non-trivial. I appreciate this has been an ongoing work stream for 15 months, but the cost to benefit on support this feature in the next year is egregiously high and I would much rather drop this and work on higher priority things.

**Comment by eddietejeda** [comment]
General interest for VPN connectivity has been expressed but there is no deal is currently dependent on it.

Can other folks chime in on the technical impact of this?

**Comment by karareinsel** [comment]
De-prioritizing this issue. The LOE to implement is significant and the customer demand is low.

**Comment by bengerman13** [comment]
@mxplusb do we need a ticket to track dropping the isolation segment work from dev (i.e. will it take more than two hours, and does it need to be done?)

**Comment by mxplusb** [comment]
Yes and likely.

**Comment by eddietejeda** [comment]
We need to update the website to say that this was de-prioritized for the moment: https://cloud.gov/docs/apps/private-egress/

Our primary focus at the moment is moving forward with managed services.

We've had a few customers reached out about this feature. I want to understand:

- Is there an alternative way they can solve this problem?
- If not, how many systems will they be bring online using this approach?

@karareinsel Not sure if this addendum reopens or issue or if you prefer to keep it closed. Your call.

**Comment by karareinsel** [comment]
I recommend creating a new issue (you can link to this issue from the new one for context/background).
