### ISSUE TITLE
Alert if any ALB is unable to route traffic

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#989]
This would essentially test if our main front door is working and notify us if it goes down. We currently have a hand-build CloudWatch alarm for when we have too few hosts in an ALB's target group. This card should result in a more maintainable replacement.

#### Notes
- E.g. put a test domain on each ALB and detect 503s generated
- This would also involve somehow getting metrics into Prometheus

#### Next steps
- Clarify and scope the next steps for researching and tackling this issue

**Comment by hillaryj** [comment]
CloudWatch, CloudWatch Events, and CloudWatch Logs are now FedRAMPed.

The CloudWatch hand-built alert may have been removed at some point since creation.
