### ISSUE TITLE
Prevent CDN/domain service provision from breaking on duplicate parameters

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#993]
It should be possible to create an instance with the same parameters in another space without breaking the broker state or the existing instance.

## Acceptance Criteria
- [ ] GIVEN I have a CDN/Cloudfront service instance for domain X in Space A WHEN I create a new instance with the same domain in Space B, THEN the service is cleanly created or not-created.

---
@bengerman13 previously said:
> Since this currently causes a user's service instance to break and requires someone from cloud.gov to intervene to fix it, we should either support it or prevent it, whether or not such moves are necessary.

**Comment by bengerman13** [comment]
obsoleted by new broker
