### ISSUE TITLE
Compare Vault/CredHub CA rotation process

### ISSUE THREAD

**Issue by mogul** [18F/cg-product#997]
In order to help us make an informed and shared decision about which secrets manager we should commit to for managing secrets in our platform, cloud.gov operators will spend (up to) X days to understand how CA rotation works in Vault and CredHub and write up a comparison.

## Acceptance Criteria
- [ ] We are able to have a discussion and come to an agreement about which platform-level secrets manager we're ready to commit to.

---
See 
* [background links for CredHub on the CA rotation story](https://trello.com/c/9H37qKPc/554-rotate-certificates-using-credhub) 
*  [discussion of CA rotation in the #vault channel of CF Slack](https://cloudfoundry.slack.com/archives/C22176QDP/p1558459368004200).

**Comment by mxplusb** [comment]
This has been decided, Credhub won even though Vault is arguably better software.
